"use client";
/**
 * Read-only access to admin-authored content (scenarios/quizzes/lessons)
 * published via /admin's "Generate with AI" tools.
 *
 * Replaces direct localStorage reads of published_scenarios/generated_quizzes/
 * generated_lessons in the student-facing pages. Those keys were per-browser —
 * a real student's browser never shared Tal's localStorage, so content
 * published through /admin was never actually visible to anyone but Tal on the
 * same device. This queries the durable content_* tables (migration 0019)
 * directly via the browser client; RLS restricts the read to status='published'
 * rows for any authenticated user (see 0019_admin_generated_content.sql).
 *
 * Each row's `content` column already IS the object the old localStorage array
 * held (same shape, generated by the same server-side "generate" routes) —
 * callers get back exactly what they used to get from JSON.parse(localStorage).
 */
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

async function fetchPublished<T>(table: "content_scenarios" | "content_quizzes" | "content_lessons"): Promise<T[]> {
  const supabase = getSupabaseBrowserClient();
  if (!supabase) return []; // guest/local mode — no durable store to read from
  const { data, error } = await supabase
    .from(table)
    .select("content")
    .eq("status", "published")
    .order("created_at", { ascending: false });
  if (error || !data) return [];
  return data.map(row => row.content as T);
}

export const fetchPublishedScenarios = <T,>() => fetchPublished<T>("content_scenarios");
export const fetchPublishedQuizzes   = <T,>() => fetchPublished<T>("content_quizzes");
export const fetchPublishedLessons   = <T,>() => fetchPublished<T>("content_lessons");

/** A published "College Materials" resource for the current org (migration 0038).
 *  RLS scopes the read to the caller's own org + published, so this returns only
 *  this college's materials. The file itself is fetched later via a signed URL
 *  (GET /api/org/media/[id]/url) — never a public object path. */
export interface OrgResource {
  id: string;
  kind: "pdf" | "pptx" | "video";
  title: string;
  mime: string;
  size_bytes: number;
  created_at: string;
}

export async function fetchOrgResources(): Promise<OrgResource[]> {
  const supabase = getSupabaseBrowserClient();
  if (!supabase) return [];
  const { data, error } = await supabase
    .from("org_resources")
    .select("id, kind, title, mime, size_bytes, created_at")
    .eq("status", "published")
    .order("created_at", { ascending: false });
  if (error || !data) return [];
  return data as OrgResource[];
}

/** Client-safe metadata for the current org's published authored ROOMS
 *  (migration 0043). content_rooms.content is already the answer-stripped
 *  projection, so this is safe to read in the browser under RLS (own org +
 *  published). Shaped to RoomMeta so the rooms list can merge it with the static
 *  ROOMS_META with no other change. */
export interface OrgRoomMeta {
  id: string;
  title: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  category: string;
  estimatedMinutes: number;
  xp: number;
  icon: string;
  prerequisites: string[];
  tasks: { id: string; type: string; xp: number }[];
  authored: true;
}

export async function fetchOrgRoomMetas(): Promise<OrgRoomMeta[]> {
  const supabase = getSupabaseBrowserClient();
  if (!supabase) return [];
  const { data, error } = await supabase
    .from("content_rooms")
    .select("content")
    .eq("status", "published")
    .order("created_at", { ascending: false });
  if (error || !data) return [];
  return data.map(row => {
    const c = (row.content ?? {}) as Record<string, unknown>;
    const tasks = Array.isArray(c.tasks) ? c.tasks as Record<string, unknown>[] : [];
    return {
      id: String(c.id ?? ""),
      title: String(c.title ?? "Untitled room"),
      description: String(c.description ?? ""),
      difficulty: (["beginner", "intermediate", "advanced"].includes(String(c.difficulty)) ? String(c.difficulty) : "beginner") as OrgRoomMeta["difficulty"],
      category: String(c.category ?? "Custom"),
      estimatedMinutes: Number(c.estimatedMinutes ?? 15),
      xp: Number(c.xp ?? 0),
      icon: String(c.icon ?? "🎓"),
      prerequisites: Array.isArray(c.prerequisites) ? c.prerequisites as string[] : [],
      tasks: tasks.map(t => ({ id: String(t.id ?? ""), type: String(t.type ?? "question"), xp: Number(t.xp ?? 0) })),
      authored: true as const,
    };
  }).filter(r => r.id);
}
