"use client";
/**
 * Read-only access to admin-authored content (scenarios/quizzes/lessons)
 * published via /admin's "Generate with AI" tools.
 *
 * Replaces direct localStorage reads of published_scenarios/generated_quizzes/
 * generated_lessons in the student-facing pages. Those keys were per-browser —
 * a real student's browser never shared Tal's localStorage, so content
 * published through /admin was never actually visible to anyone but Tal on the
 * same device. This queries the durable content_* tables (migration 0019)
 * directly via the browser client; RLS restricts the read to status='published'
 * rows for any authenticated user (see 0019_admin_generated_content.sql).
 *
 * Each row's `content` column already IS the object the old localStorage array
 * held (same shape, generated by the same server-side "generate" routes) —
 * callers get back exactly what they used to get from JSON.parse(localStorage).
 */
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

async function fetchPublished<T>(table: "content_scenarios" | "content_quizzes" | "content_lessons"): Promise<T[]> {
  const supabase = getSupabaseBrowserClient();
  if (!supabase) return []; // guest/local mode — no durable store to read from
  const { data, error } = await supabase
    .from(table)
    .select("content")
    .eq("status", "published")
    .order("created_at", { ascending: false });
  if (error || !data) return [];
  return data.map(row => row.content as T);
}

export const fetchPublishedScenarios = <T,>() => fetchPublished<T>("content_scenarios");
export const fetchPublishedQuizzes   = <T,>() => fetchPublished<T>("content_quizzes");
export const fetchPublishedLessons   = <T,>() => fetchPublished<T>("content_lessons");
