/**
 * Events-only half of the ./clipboardClipper.ts scenario pack.
 *
 * The dashboard's live feed runs in the browser (attackStories.ts), so what it
 * imports ships in a public /_next/static chunk. The answer key (questions,
 * answers, explanations, IOCs, killchain, narrative) stays in the builder in
 * ./clipboardClipper.ts, which composes this module on the server. Keep anything
 * answer-bearing out of this file: every visitor can read it.
 */
import type { TelemetryEvent } from "@/lib/sim/types";
import { makeSha256 } from "@/lib/sim/iocs";
import { s1Process, s1File, s1ProcessAccess, s1Detection } from "@/lib/sim/emitters/sentinelone";
import { panWeb } from "@/lib/sim/emitters/paloalto";

/** Telemetry half of `buildClipboardClipperScenario`: the events and the story title, no answer key. */
export function clipboardClipperScenarioEvents() {
  const B = new Date("2026-05-04T09:20:00Z").getTime();
  const T = (ms: number) => new Date(B + ms).toISOString();
  const MIN = 60_000;
  const HOUR = 60 * MIN;

  const host = { hostname: "LAP-5528", ip: "10.14.27.19" };
  const victim = { email: "n.peretz@nexacorp.com", name: "Noa Peretz", sam: "n.peretz" };

  const downloadSite = "cryptotracker-lite.io";
  const c2 = "wallet-cfg-sync.net";

  const installerHash = makeSha256("cryptotracker_lite_setup_bundled_clipper_2026");
  const clipperHash   = makeSha256("clipsvc_helper_exe_clipper_binary_2026");
  const cmdHash       = makeSha256("windows_system32_cmd_exe_signed_microsoft");

  // EDR↔scenario integration (Phase 4): one incident, endpoint-primary →
  // edr_scope "edr". Alert-grade rows: the SentinelOne clipboard-hijacker
  // detection that opens the ticket, plus the clipboard-hijack behavioural
  // event (the crux). The rest is pivot-only telemetry in the process tree.
  const INCIDENT = "inc:clc:1";

  // Shared emitter context — the SentinelOne endpoint chain on one NexaCorp laptop.
  // Host/user/IP pinned to the narrative's values; the emitter renders NEXACORP\n.peretz,
  // the s1.* raw and the structured process/file/registry from these.
  const cs = { companyId: "nexacorp", host: host.hostname, user: victim.email, srcIp: host.ip };

  const events: TelemetryEvent[] = [
    // ---------------------------------------------------------------------
    // 1. The download. A small utility for a real, ordinary need. (PAN emitter)
    // ---------------------------------------------------------------------
    panWeb({
      ...cs, id: "evt_clc_01_download", ts: T(0), severity: "low",
      url: `https://${downloadSite}/download/CryptoTrackerLite_Setup.exe`, domain: downloadSite,
      category: "computer-and-internet-info", action: "alert", dstIp: "104.21.87.203",
      status: 200, bytesIn: 9_842_176, userTitle: "Procurement Analyst",
      file: { name: "CryptoTrackerLite_Setup.exe", path: "/download/CryptoTrackerLite_Setup.exe", sha256: installerHash, size: 9_842_176 },
      description: "LAP-5528 downloaded CryptoTrackerLite_Setup.exe from cryptotracker-lite.io at 09:20, allowed under the category computer-and-internet-info.",
    }),

    // ---------------------------------------------------------------------
    // 2-6. The endpoint chain — SentinelOne telemetry, generated by the typed
    //      emitters (src/lib/sim/emitters/sentinelone.ts). Host, user
    //      (NEXACORP\n.peretz), PIDs and hashes thread consistently through the
    //      whole tree; each raw block uses only registry-valid s1.* / ECS fields.
    // ---------------------------------------------------------------------

    // 2. Installation. Unremarkable, user-initiated.
    s1Process({
      ...cs, id: "evt_clc_02_install", ts: T(2 * MIN + 10_000),
      processName: "CryptoTrackerLite_Setup.exe", pid: 6214,
      processPath: "C:\\Users\\n.peretz\\Downloads\\CryptoTrackerLite_Setup.exe",
      cmdline: "\"C:\\Users\\n.peretz\\Downloads\\CryptoTrackerLite_Setup.exe\"",
      parentName: "explorer.exe", parentPid: 3348, sha256: installerHash,
      mitre: "T1204.002", tactic: "Execution", severity: "low",
      description: "CryptoTrackerLite_Setup.exe ran from Downloads at 09:22, started by explorer.exe.",
    }),

    // 3. A second, unsigned binary — the real tracker installs alongside it.
    s1File({
      ...cs, id: "evt_clc_03_clipper_written", ts: T(2 * MIN + 31_000),
      path: "C:\\Users\\n.peretz\\AppData\\Roaming\\ClipSvc\\clipsvc_helper.exe", sha256: clipperHash, severity: "medium",
      description: "The installer wrote C:\\Users\\n.peretz\\AppData\\Roaming\\ClipSvc\\clipsvc_helper.exe, unsigned, 512 KB.",
    }),

    // 4. Persistence via a hidden cmd.exe `reg add` — the interpreter is the signal
    //    (T1059.003), and the same event carries the Run-key it wrote.
    s1Process({
      ...cs, id: "evt_clc_04_persistence_cmd", ts: T(2 * MIN + 36_000),
      processName: "cmd.exe", pid: 6288, processPath: "C:\\Windows\\System32\\cmd.exe",
      cmdline: "cmd.exe /c reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\" /v ClipboardService /t REG_SZ /d \"C:\\Users\\n.peretz\\AppData\\Roaming\\ClipSvc\\clipsvc_helper.exe\" /f",
      parentName: "CryptoTrackerLite_Setup.exe", parentPid: 6214, sha256: cmdHash, signed: true,
      registry: {
        keyPath: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
        valueName: "ClipboardService",
        valueData: "C:\\Users\\n.peretz\\AppData\\Roaming\\ClipSvc\\clipsvc_helper.exe",
      },
      mitre: "T1059.003", tactic: "Execution", severity: "high",
      description: "cmd.exe, spawned by the installer, ran a hidden 'reg add' command adding ClipboardService to the user's Run key, pointing at the AppData binary.",
    }),

    // 5. The background process starts, silently.
    s1Process({
      ...cs, id: "evt_clc_05_clipper_start", ts: T(2 * MIN + 44_000),
      processName: "clipsvc_helper.exe", pid: 6355,
      processPath: "C:\\Users\\n.peretz\\AppData\\Roaming\\ClipSvc\\clipsvc_helper.exe",
      cmdline: "clipsvc_helper.exe -silent", parentName: "CryptoTrackerLite_Setup.exe", parentPid: 6214,
      sha256: clipperHash, signed: false, severity: "medium",
      description: "clipsvc_helper.exe started for the first time, launched by the installer with no visible window.",
    }),

    // 6. THE EVENT THAT MATTERS — the clipboard-format-listener hijack.
    s1ProcessAccess({
      ...cs, id: "evt_clc_06_clipboard_hijack", ts: T(2 * HOUR + 15 * MIN),
      processName: "clipsvc_helper.exe", pid: 6355,
      processPath: "C:\\Users\\n.peretz\\AppData\\Roaming\\ClipSvc\\clipsvc_helper.exe",
      cmdline: "clipsvc_helper.exe -silent", parentName: "CryptoTrackerLite_Setup.exe", parentPid: 6214,
      sha256: clipperHash, signed: false,
      indicatorName: "Process Monitors and Modifies Clipboard Content",
      mitre: "T1115", tactic: "Collection", technique: "Clipboard Data",
      severity: "critical", isDetection: true, expectedVerdict: "tp",
      description: "clipsvc_helper.exe registered a clipboard format listener and repeatedly rewrote clipboard content matching cryptocurrency wallet address patterns.",
    }),

    // ---------------------------------------------------------------------
    // 7. Its periodic check-in for a fresh substitute-address list. (PAN emitter)
    // ---------------------------------------------------------------------
    panWeb({
      ...cs, id: "evt_clc_07_config_pull", ts: T(2 * HOUR + 15 * MIN + 16_000), severity: "high",
      url: `https://${c2}/w/list.json`, domain: c2, category: "newly-registered-domain",
      action: "alert", dstIp: "45.147.230.16", status: 200, bytesIn: 612,
      description: "LAP-5528 requested /w/list.json from wallet-cfg-sync.net, allowed under the category newly-registered-domain.",
    }),

    // ---------------------------------------------------------------------
    // 8. The detection that opened the ticket — two days later, after a
    //    vendor reported a misdirected payment and the SOC pulled EDR
    //    telemetry for the paying employee's laptop.
    // ---------------------------------------------------------------------
    {
      ...s1Detection({
        ...cs, id: "evt_clc_08_edr_alert", ts: T(2 * 24 * HOUR + 3 * HOUR), eventType: "edr_alert",
        processName: "clipsvc_helper.exe", pid: 6355,
        processPath: "C:\\Users\\n.peretz\\AppData\\Roaming\\ClipSvc\\clipsvc_helper.exe",
        cmdline: "clipsvc_helper.exe -silent", sha256: clipperHash,
        threatName: "Clipboard Hijacker (Generic)", action: "killed", expectedVerdict: "tp",
        mitre: "T1115", tactic: "Collection", severity: "critical",
        description: "SentinelOne raised a Critical detection on LAP-5528 for an unsigned AppData process holding a clipboard format listener, and killed it.",
      }),
      edr_scope: "edr",
    },
  ];

  // Every event belongs to the one incident.
  for (const e of events) e.incident_id = INCIDENT;

  return { title: "Wrong Wallet — Clipboard Clipper from a Trojanized Utility", events, T, MIN, HOUR, host, downloadSite, c2, installerHash, clipperHash };
}
