/**
 * Events-only half of the ./driveByBrowserMiner.ts scenario pack.
 *
 * The dashboard's live feed runs in the browser (attackStories.ts), so what it
 * imports ships in a public /_next/static chunk. The answer key (questions,
 * answers, explanations, IOCs, killchain, narrative) stays in the builder in
 * ./driveByBrowserMiner.ts, which composes this module on the server. Keep anything
 * answer-bearing out of this file: every visitor can read it.
 */
import type { TelemetryEvent } from "@/lib/sim/types";
import { csFile, csProcess, csAlert } from "@/lib/sim/emitters/crowdstrike";
import { panWeb, panConnection } from "@/lib/sim/emitters/paloalto";

/** Telemetry half of `buildDriveByBrowserMinerScenario`: the events and the story title, no answer key. */
export function driveByBrowserMinerScenarioEvents() {
  const B = new Date("2026-05-19T11:02:00Z").getTime();
  const T = (ms: number) => new Date(B + ms).toISOString();
  const SEC = 1_000;
  const MIN = 60_000;

  const host = { hostname: "LAP-6690", ip: "10.14.41.22" };
  const victim = { email: "t.ravid@nexacorp.com", name: "Tomer Ravid", sam: "t.ravid" };
  // Shared emitter context — one NexaCorp laptop, CrowdStrike + Palo Alto.
  const cs = { companyId: "nexacorp", host: host.hostname, user: victim.email, srcIp: host.ip };

  const legitSite = "quickconvert-tools.io";
  const scriptHost = "edge-metrics-cdn14.com";
  const poolRelay = "ws-relay-pool9.com";

  // EDR↔scenario integration (Phase 4): one incident, endpoint-primary →
  // edr_scope "edr". The Falcon browser-renderer detection is the single
  // alert-grade EDR row; the mining crux (the WebSocket relay tunnel) lives in
  // firewall telemetry, and the renderer/cache EDR events are pivot-only.
  const INCIDENT = "inc:dbm:1";

  const events: TelemetryEvent[] = [
    // ---------------------------------------------------------------------
    // 1-8. In-browser cryptojacking — CrowdStrike + Palo Alto, generated by the
    //      typed emitters. The renderer PID (8842) threads from the process event
    //      through the WebSocket tunnel and the Code-Cache write; every raw block
    //      uses only registry-valid vendor fields.
    // ---------------------------------------------------------------------

    // 1. Ordinary work on the (now injected) converter.
    panWeb({
      ...cs, id: "evt_dbm_01_site_visit", ts: T(0), severity: "low",
      url: `https://${legitSite}/convert/pdf-to-word`, domain: legitSite,
      category: "computer-and-internet-info", action: "alert", dstIp: "104.26.9.201", status: 200, bytesIn: 88_240,
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0 Safari/537.36",
      userTitle: "Business Analyst",
      description: "LAP-6690 loaded quickconvert-tools.io/convert/pdf-to-word at 11:02, a browser-based PDF converter Tomer uses regularly, allowed under the category computer-and-internet-info.",
    }),

    // 2. The page hands off to an unrelated host for the loader script.
    panWeb({
      ...cs, id: "evt_dbm_02_script_fetch", ts: T(8 * SEC), severity: "medium",
      url: `https://${scriptHost}/lib/wm-core.js`, domain: scriptHost, category: "content-delivery-networks",
      action: "alert", dstIp: "172.67.144.29", status: 200, bytesIn: 21_408,
      referer: `https://${legitSite}/convert/pdf-to-word`, mitre: "T1189", tactic: "Initial Access",
      description: "Eight seconds into the page load, the same browser session fetched /lib/wm-core.js from edge-metrics-cdn14.com, referred by quickconvert-tools.io.",
    }),

    // 3. That script pulls a compiled WebAssembly module from the same host.
    panWeb({
      ...cs, id: "evt_dbm_03_wasm_fetch", ts: T(9 * SEC), severity: "medium",
      url: `https://${scriptHost}/lib/wm-mod.wasm`, domain: scriptHost, category: "content-delivery-networks",
      action: "alert", dstIp: "172.67.144.29", status: 200, bytesIn: 188_416,
      referer: `https://${legitSite}/convert/pdf-to-word`, mitre: "T1189", tactic: "Initial Access",
      description: "One second later the same session fetched /lib/wm-mod.wasm, 184 KB, from edge-metrics-cdn14.com.",
    }),

    // 4. The tab's sandboxed renderer process — the one that will run the module.
    csProcess({
      ...cs, id: "evt_dbm_04_renderer", ts: T(10 * SEC),
      processName: "chrome.exe", pid: 8842, processPath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
      cmdline: '"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" --type=renderer --site-per-process --lang=en-US --renderer-client-id=14',
      parentName: "chrome.exe", parentPid: 5120, severity: "low",
      description: "chrome.exe spawned a sandboxed renderer process for the quickconvert-tools.io tab, PID 8842, running at low integrity — Chrome's normal per-site process model.",
    }),

    // 5. THE CRUX — the renderer opens a long-lived WebSocket tunnel to a mining relay.
    panConnection({
      ...cs, id: "evt_dbm_05_ws_open", ts: T(11 * SEC), severity: "critical",
      domain: poolRelay, dstIp: "45.155.204.61", remotePort: 443, app: "websocket", category: "unknown",
      url: `${poolRelay}/socket`, action: "alert", mitre: "T1496", tactic: "Impact",
      description: "At 11:02:11 the renderer opened a WebSocket connection to ws-relay-pool9.com, categorised unknown, app websocket — the tunnel a browser-based miner uses in place of a direct Stratum socket.",
    }),

    // 6. The compiled module is cached to disk (ordinary Chrome behaviour) —
    //    corroborates, by the same renderer PID, that the module actually ran.
    csFile({
      ...cs, id: "evt_dbm_06_wasm_cache", ts: T(40 * SEC), severity: "medium", sha256: null,
      path: "C:\\Users\\t.ravid\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Code Cache\\wasm\\a1f4c9_0",
      description: "The renderer process (PID 8842) wrote a compiled copy of the module to Chrome's own Code Cache, confirming wm-mod.wasm was compiled and executed rather than just downloaded.",
    }),

    // 7. The session closes 24 minutes later — the traffic-end summary for evt_dbm_05.
    panConnection({
      ...cs, id: "evt_dbm_07_ws_close", ts: T(24 * MIN + 11 * SEC), severity: "critical", end: true,
      domain: poolRelay, dstIp: "45.155.204.61", remotePort: 443, app: "websocket", category: "unknown",
      action: "allow", bytesOut: 18_400, bytesIn: 64_200, elapsedSec: 1440, mitre: "T1496", tactic: "Impact",
      description: "The WebSocket session to ws-relay-pool9.com stayed open for 24 minutes before closing, exchanging small, steady bursts consistent with mining job assignments and share submissions rather than a page's normal traffic pattern.",
    }),

    // 8. Falcon's behavioural engine ties it together — a browser-renderer resource
    //    hijack with no process to kill (the fix is to close the tab).
    {
      ...csAlert({
        ...cs, id: "evt_dbm_08_edr_alert", ts: T(24 * MIN + 26 * SEC), severity: "critical",
        threatName: "BrowserRendererResourceHijacking",
        detail: "A browser renderer process maintained a long-lived WebSocket connection to a known mining-relay pattern while consuming sustained high CPU, consistent with an in-browser cryptocurrency miner.",
        mitre: "T1496", tactic: "Impact", technique: "Resource Hijacking", malwareCategory: "cryptominer",
        action: "detected", processTree: "chrome.exe > chrome.exe (renderer, PID 8842)", confidence: 80,
        expectedVerdict: "tp",
        description: "Falcon raised a Critical detection on LAP-6690, tying renderer PID 8842 to a 24-minute WebSocket session against a mining relay and to sustained near-100% CPU usage on that single tab for the same window. No file was ever downloaded or executed outside the browser, so nothing was killed — the finding requires the tab to be closed.",
      }),
      edr_scope: "edr",
    },
  ];

  // Every event belongs to the one incident.
  for (const e of events) e.incident_id = INCIDENT;

  return { title: "Free PDF Tool, Injected — In-Browser Cryptojacking", events, T, SEC, MIN, host, legitSite, scriptHost, poolRelay };
}
