/**
 * Events-only half of the ./trojanizedInstallerKeylogger.ts scenario pack.
 *
 * The dashboard's live feed runs in the browser (attackStories.ts), so what it
 * imports ships in a public /_next/static chunk. The answer key (questions,
 * answers, explanations, IOCs, killchain, narrative) stays in the builder in
 * ./trojanizedInstallerKeylogger.ts, which composes this module on the server. Keep anything
 * answer-bearing out of this file: every visitor can read it.
 */
import type { TelemetryEvent } from "@/lib/sim/types";
import { makeSha256 } from "@/lib/sim/iocs";
import { csProcess, csFile, csRegistry, csProcessAccess, csDetection } from "@/lib/sim/emitters/crowdstrike";
import { panWeb } from "@/lib/sim/emitters/paloalto";
import { sentinelAlert } from "@/lib/sim/emitters/sentinel";

/** Telemetry half of `buildTrojanizedInstallerKeyloggerScenario`: the events and the story title, no answer key. */
export function trojanizedInstallerKeyloggerScenarioEvents() {
  const B = new Date("2026-06-25T10:05:00Z").getTime();
  const T = (ms: number) => new Date(B + ms).toISOString();
  const MIN = 60_000;

  const host = { hostname: "LAP-2290", ip: "10.14.31.44" };
  const victim = { email: "y.karni@nexacorp.com", name: "Yael Karni", sam: "y.karni" };

  const downloadSite = "pdf-tools-free.io";
  const c2 = "stat-collect-eu.com";

  const installerHash = makeSha256("swiftpdf_setup_trojanized_installer_2026");
  const keyloggerHash = makeSha256("winupd_helper_keylogger_binary_2026");
  const realToolHash  = makeSha256("swiftpdf_merge_legitimate_component_2026");

  // EDR↔scenario integration (SPEC-edr-scenario-integration, Phase 1b): one
  // incident. Endpoint-primary → edr_scope "edr" (the firewall download/exfil are
  // transport evidence, not a separate control-plane investigation). The Falcon
  // detections are alert-grade rows; the rest of the EDR process/file/registry
  // events are pivot-only telemetry surfaced inside the process tree.
  const INCIDENT = "inc:tik:1";

  // Shared emitter context: NexaCorp is a Defender shop, but this pack is authored on
  // CrowdStrike (the emitters render the correct Falcon fields either way). Host, user
  // and IP are pinned to the narrative's values; the emitter renders NEXACORP\y.karni,
  // the raw block and the structured process/file/registry from these.
  const cs = { companyId: "nexacorp", host: host.hostname, user: victim.email, srcIp: host.ip };

  const events: TelemetryEvent[] = [
    // ---------------------------------------------------------------------
    // 1. The download. Ordinary category, ordinary user, ordinary need. (PAN emitter)
    // ---------------------------------------------------------------------
    panWeb({
      ...cs, id: "evt_tik_01_download", ts: T(0), severity: "low",
      url: `https://${downloadSite}/dl/SwiftPDF_Setup.exe`, domain: downloadSite,
      category: "shareware-and-freeware", action: "alert", dstIp: "172.67.201.18",
      status: 200, bytesIn: 18_442_240, userTitle: "Contracts Administrator",
      file: { name: "SwiftPDF_Setup.exe", path: "/dl/SwiftPDF_Setup.exe", sha256: installerHash, size: 18_442_240 },
      description: "LAP-2290 downloaded SwiftPDF_Setup.exe from pdf-tools-free.io at 10:05, allowed under the category shareware-and-freeware.",
    }),

    // ---------------------------------------------------------------------
    // 2-7. The endpoint chain — CrowdStrike Falcon telemetry, generated by the
    //      typed emitters (src/lib/sim/emitters/crowdstrike.ts). Each call renders
    //      a field-correct DetectionSummary / ProcessRollup2 / PeFileWritten /
    //      AsepValueUpdate / hook raw block, with the host, user (NEXACORP\y.karni),
    //      PIDs and hashes threaded consistently through the whole tree.
    // ---------------------------------------------------------------------

    // 2. Installation. Signed, elevated, and completely normal-looking.
    csProcess({
      ...cs, id: "evt_tik_02_installer_run", ts: T(2 * MIN + 30_000),
      processName: "SwiftPDF_Setup.exe", pid: 7120,
      processPath: "C:\\Users\\y.karni\\Downloads\\SwiftPDF_Setup.exe",
      cmdline: '"C:\\Users\\y.karni\\Downloads\\SwiftPDF_Setup.exe" /S',
      parentName: "explorer.exe", parentPid: 3204, sha256: installerHash, signed: true,
      mitre: "T1204.002", tactic: "Execution", severity: "low",
      description: "SwiftPDF_Setup.exe ran from Downloads at 10:07:30, started by explorer.exe and elevated to high integrity.",
    }),

    // 3. The real product is installed. It works — not a decoy.
    csFile({
      ...cs, id: "evt_tik_03_real_component", ts: T(2 * MIN + 51_000),
      path: "C:\\Program Files\\SwiftPDF\\SwiftPDF.exe", sha256: realToolHash, signed: true, severity: "low",
      description: "The installer wrote C:\\Program Files\\SwiftPDF\\SwiftPDF.exe, the working PDF application.",
    }),

    // 4. A second binary, to AppData, with a name that borrows Windows' vocabulary.
    csFile({
      ...cs, id: "evt_tik_04_second_binary", ts: T(2 * MIN + 54_000),
      path: "C:\\Users\\y.karni\\AppData\\Roaming\\WinUpd\\winupd_helper.exe", sha256: keyloggerHash, signed: false, severity: "medium",
      description: "Three seconds later the same installer wrote C:\\Users\\y.karni\\AppData\\Roaming\\WinUpd\\winupd_helper.exe, unsigned.",
    }),

    // 5. Persistence — a Run key, in the user hive, no admin rights needed.
    csRegistry({
      ...cs, id: "evt_tik_05_run_key", ts: T(2 * MIN + 56_000),
      keyPath: "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
      valueName: "WindowsUpdateHelper",
      valueData: "C:\\Users\\y.karni\\AppData\\Roaming\\WinUpd\\winupd_helper.exe",
      writerProcess: "SwiftPDF_Setup.exe", mitre: "T1547.001", tactic: "Persistence", severity: "high",
      description: "A value named WindowsUpdateHelper was written to the user's Run key, pointing at the AppData binary.",
    }),

    // 6. THE EVENT THAT MATTERS — the helper reads another process's input.
    csProcessAccess({
      ...cs, id: "evt_tik_06_keylog_hook", ts: T(4 * MIN + 10_000),
      processName: "winupd_helper.exe", pid: 7688,
      processPath: "C:\\Users\\y.karni\\AppData\\Roaming\\WinUpd\\winupd_helper.exe",
      cmdline: "winupd_helper.exe -svc", parentName: "SwiftPDF_Setup.exe", parentPid: 7120,
      sha256: keyloggerHash, signed: false, targetProcess: "chrome.exe", targetPid: 5012,
      api: "SetWindowsHookExW", threatName: "UnsignedUserlandKeyboardHook",
      mitre: "T1056.001", tactic: "Collection", technique: "Input Capture: Keylogging",
      severity: "critical", isDetection: true, expectedVerdict: "tp",
      description: "winupd_helper.exe installed a low-level keyboard hook via SetWindowsHookExW and began reading input directed at chrome.exe.",
    }),

    // 7. A local buffer file grows in the same folder (no hash — a growing buffer).
    csFile({
      ...cs, id: "evt_tik_07_buffer_file", ts: T(38 * MIN),
      path: "C:\\Users\\y.karni\\AppData\\Roaming\\WinUpd\\cache.dat", sha256: null, action: "file_modify",
      mitre: "T1074.001", tactic: "Collection", severity: "high",
      description: "winupd_helper.exe repeatedly appended to C:\\Users\\y.karni\\AppData\\Roaming\\WinUpd\\cache.dat, which reached 61 KB over 34 minutes.",
    }),

    // ---------------------------------------------------------------------
    // 8. The buffer leaves the building — small, regular POSTs. (PAN emitter)
    // ---------------------------------------------------------------------
    panWeb({
      ...cs, id: "evt_tik_08_exfil", ts: T(40 * MIN), severity: "critical",
      method: "POST", url: `https://${c2}/v1/report`, domain: c2, category: "unknown",
      action: "allow", dstIp: "185.243.115.62", status: 200, bytesOut: 4_216, bytesIn: 118,
      repeatCount: 5, mitre: "T1041", tactic: "Exfiltration",
      description: "From 10:45 the host began POSTing roughly 4 KB every ten minutes to stat-collect-eu.com/v1/report, allowed under the category unknown.",
    }),

    // ---------------------------------------------------------------------
    // 9. The detection that opened the ticket — Falcon DetectionSummaryEvent,
    //    endpoint-primary (edr_scope "edr" → investigated in the EDR console).
    // ---------------------------------------------------------------------
    {
      ...csDetection({
        ...cs, id: "evt_tik_09_edr_alert", ts: T(41 * MIN), eventType: "edr_alert",
        processName: "winupd_helper.exe", pid: 7688, parentPid: 7120,
        processPath: "C:\\Users\\y.karni\\AppData\\Roaming\\WinUpd\\winupd_helper.exe",
        cmdline: "winupd_helper.exe -svc", sha256: keyloggerHash,
        threatName: "UnsignedUserlandKeyboardHook", action: "detected", expectedVerdict: "tp",
        mitre: "T1056.001", tactic: "Collection", technique: "Input Capture: Keylogging", severity: "critical",
        description: "Falcon raised a Critical detection on LAP-2290 for an unsigned AppData binary holding a keyboard hook, with the host's recent software-installation context attached.",
      }),
      edr_scope: "edr",
    },

    // ---------------------------------------------------------------------
    // 10. The host's software and entitlement context, from the SIEM rather
    //     than the EDR — what was installed today, what autoruns appeared, and
    //     whether this user could have needed admin rights for any of it. (Sentinel emitter)
    // ---------------------------------------------------------------------
    sentinelAlert({
      ...cs, id: "evt_tik_10_siem_context", ts: T(43 * MIN), severity: "high", eventType: "ueba_anomaly",
      alertName: "EndpointSoftwareChange_UnsignedPersistence", ruleId: "SEN-ENDPOINT-0139",
      fullName: victim.name, department: "Legal", title: "Contracts Administrator",
      extendedProperties: {
        "Software Installed Today": ["SwiftPDF 4.2 (Nordvale Software Solutions OU)"],
        "Autoruns Added Today": ["HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\WindowsUpdateHelper"],
        "Local Admin Rights": "false",
      },
      description: "Sentinel enriched the detection with the host's change history for the day and the account's local-privilege state.",
    }),
  ];

  // Every event in this pack belongs to the one keylogger incident (correlation
  // key; also lets the EDR console build a single isolated case for it).
  for (const e of events) e.incident_id = INCIDENT;

  return { title: "Free PDF Tool — Trojanized Installer with a Keylogger", events, T, MIN, host, downloadSite, c2, installerHash, keyloggerHash };
}
