// ─── Quiz Data: Foundations & Data Security ────────────────────────────────
// Closes the last two zero-quiz room categories. Same contract as ./data.ts.
// Every question here is grounded in specific room content — traced against
// intro-cybersecurity, encoding-encryption-hashing, timestamps-and-timelines,
// security-products-behaviour (Foundations), and dlp-fundamentals (Data
// Security) — not general industry trivia. See CONTENT-SPEC.md for the
// alignment discipline this is meant to uphold.

import type { Quiz } from "./data";

export const QUIZZES_FOUNDATIONS_DATASEC: Quiz[] = [

  // ── 1. Cybersecurity Foundations ──────────────────────────────────────────
  {
    slug: "cybersecurity-foundations",
    title: "Cybersecurity Foundations",
    description: "Test the core foundations every SOC analyst needs before touching a real alert: the CIA Triad and threat actors, encoding vs encryption vs hashing, timestamps and timeline discipline, and what each security product actually sees and can do.",
    difficulty: "Beginner",
    category: "Foundations",
    icon: "🧱",
    estimatedMinutes: 15,
    questions: [
      {
        id: "cf_01",
        question: "A finance team discovers that an attacker intercepted an internal expense-approval email and silently changed the approved amount from $1,000 to $10,000 before the approver read it, without stealing or blocking anything. Which CIA Triad principle was violated?",
        options: [
          "Confidentiality — the email contents were exposed to someone unauthorized",
          "Availability — the approver could not access the email when needed",
          "Integrity — the data was modified without authorization, exactly like the contract example in the reading",
          "Non-repudiation — the sender could no longer prove they sent the email",
        ],
        answer: 2,
        explanation: "The reading's contract example illustrates exactly this: data changed in transit before the recipient reads it is an Integrity violation, not Confidentiality (no exposure occurred) or Availability (the email was still accessible, just altered). Non-repudiation isn't one of the three CIA pillars covered in the reading.",
        xp: 15,
      },
      {
        id: "cf_02",
        question: "DarkSide, the ransomware group behind the Colonial Pipeline attack, gained access via a compromised VPN password, encrypted systems, and demanded a ransom payment. Based on the reading's threat actor categories, which type of threat actor does DarkSide best fit, and why?",
        options: [
          "Nation-State Actor — because the attack targeted critical infrastructure",
          "Hacktivist — because the attack disrupted a politically sensitive fuel supply",
          "Cybercriminal — an organized group running a ransomware operation for financial gain, the same category the reading uses for LockBit",
          "Script Kiddie — because they used a single stolen password rather than a sophisticated exploit",
        ],
        answer: 2,
        explanation: "The reading defines Cybercriminals as organized groups motivated by financial gain who run ransomware operations, using LockBit as its example — DarkSide's ransom demand for Colonial Pipeline fits that exact definition. Targeting critical infrastructure doesn't automatically make an actor nation-state (that requires government sponsorship, as with APT29/SolarWinds), the attack had no stated political protest motive typical of hacktivism, and using a simple compromised password reflects opportunistic access, not the low skill/pre-written-tools profile of a script kiddie.",
        xp: 20,
      },
      {
        id: "cf_03",
        question: "After Acme Corp acquires a smaller company, it inherits thousands of additional employee laptops, several new cloud applications, and old servers that were never fully documented. According to the reading, what has happened to Acme's digital attack surface, and why does it matter?",
        options: [
          "It has shrunk, because consolidating two companies into one IT department under a single security team reduces the total number of systems anyone actually has to defend",
          "It has grown, because the attack surface is everything that can be targeted — every computer, server, application, and employee inbox — and a larger, more complex environment means more potential entry points",
          "It is unaffected, because attack surface only refers to internet-facing web applications, and none of the newly acquired systems fall into that specific category",
          "It has grown, but only temporarily, and it will shrink back down automatically once the SOC finishes onboarding the new company's SIEM and closes out the migration project",
        ],
        answer: 1,
        explanation: "The reading defines the attack surface as everything that can be targeted — every computer, server, phone, application, and employee inbox — and states explicitly that the larger and more complex an organization's technology environment, the bigger its attack surface. A merger adds systems and complexity, not fewer; attack surface isn't limited to web applications; and it doesn't shrink back down just because SIEM onboarding is in progress — the systems themselves are still there, monitored or not.",
        xp: 15,
      },
      {
        id: "cf_04",
        question: "Two employees, Alice and Bob, independently choose the identical password. After a database breach, investigators find that Alice's and Bob's stored password hashes are completely different strings, sharing no visible pattern. What does this most likely indicate, and why does it matter to the investigation?",
        options: [
          "The system salts passwords with a random, unique-per-user value before hashing — as the reading explains, this is exactly why identical passwords produce different stored hashes, defeating rainbow tables and hiding the fact that Alice and Bob share a password",
          "The passwords were encrypted with two different keys, one issued per user at account creation, rather than being hashed by the authentication server at all",
          "The hash algorithm must be broken, since a correctly functioning deterministic hash should always produce identical output for identical input, hash by hash",
          "One of the two accounts is fake or duplicated in the database, since genuine accounts always produce matching hashes whenever their passwords genuinely match",
        ],
        answer: 0,
        explanation: "This is exactly the salting mechanism from the reading: a random, unique value per user is combined with the password before hashing, so identical passwords yield different stored hashes and pre-built rainbow tables become useless — the avalanche effect in action. Nothing here involves encryption or keys (passwords are hashed, not encrypted); the hash function is behaving correctly (deterministic on password+salt, not on password alone); and there's no basis to call either account fake — this is the intended, secure behavior.",
        xp: 20,
      },
      {
        id: "cf_05",
        question: "An analyst decodes a suspicious 'powershell -enc' command in under ten seconds using a free online Base64 decoder, revealing the full plaintext script with no password or key required. A colleague insists, 'Well, at least it was encrypted, so the attacker's intent was hidden from us.' What is wrong with the colleague's statement?",
        options: [
          "Nothing is wrong — Base64 is a lightweight, legacy form of weak encryption, and the analyst simply got fortunate stumbling onto the one online tool that still knows how to break it",
          "The colleague is repeating a common misconception: Base64 is encoding, not encryption — it's reversible by anyone using the same public rule, with no key or password involved; it only defeats naive string-matching detection rules, not a human analyst willing to decode it",
          "The command was never actually readable in the first place — the analyst must have accidentally opened a second, separate copy of the script that was never encoded to begin with",
          "Encoding and encryption are simply two different names that vendors and analysts use interchangeably for the identical underlying cryptographic operation, so the colleague's phrasing is technically correct",
        ],
        answer: 1,
        explanation: "The reading calls this out directly as one of the two big misconceptions: Base64 is encoding, not encryption, and it is reversible by anyone with the same public rule — no key, password, or cracking involved, which is exactly why the analyst decoded it instantly. It exists to defeat plaintext string-matching detection rules, not human analysts. Encoding and encryption are not interchangeable terms — they have fundamentally different reversibility guarantees, and there's no such thing as 'weak encryption' happening here at all.",
        xp: 15,
      },
      {
        id: "cf_06",
        question: "A SOC builds its entire malware-blocking strategy around maintaining a list of known-malicious file hashes. An attacker takes an existing piece of malware, changes a single line of code, and recompiles it. The new file sails past every hash-based control undetected. What does the reading say this demonstrates?",
        options: [
          "The SOC's threat intelligence feed must simply be stale or out of date, and refreshing the subscription more frequently would have caught the recompiled sample immediately",
          "This proves hash-based detection is entirely worthless and should be abandoned outright in favor of exclusively relying on behavioral EDR tooling instead",
          "A hash identifies one exact byte sequence, and the avalanche effect means even a single changed line produces a completely unrelated hash — this is exactly why file hashes sit at the bottom of the Pyramid of Pain, trivial and free for an attacker to invalidate with a simple recompile",
          "The recompiled file must have deliberately exploited a collision in the hashing algorithm itself, engineering a second input that reproduces the same digest to evade detection",
        ],
        answer: 2,
        explanation: "This is the reading's explicit point about hashing's limits: a hash matches one exact byte sequence, and recompiling with even one line changed produces a totally different, unrelated hash via the avalanche effect — which is precisely why hashes sit at the bottom of the Pyramid of Pain, the cheapest indicator type for an attacker to change. A hash match is still real evidence when it fires, so hash-based detection isn't worthless, just insufficient alone; and this scenario needs no collision at all — it's simply two different inputs producing two different (not colliding) hashes, working exactly as designed.",
        xp: 25,
      },
      {
        id: "cf_07",
        question: "A firewall's internal clock has drifted about 5 minutes fast because it hasn't synced with a time server in months. It logs an outbound connection at 10:15:00. A Domain Controller, correctly synced, logs a matching user logon at 10:11:00. An analyst concludes the logon happened almost 4 minutes before the connection and builds the timeline that way. What has the analyst most likely gotten wrong?",
        options: [
          "Nothing — raw timestamps pulled from two entirely different log sources can always be compared and ordered directly, with no correction needed before drawing conclusions",
          "The analyst should have checked the firewall's NTP sync status and corrected for its known ~5-minute skew first; once corrected, the actual gap between logon and connection is different from what the raw, uncorrected timestamps suggest",
          "The Domain Controller's clock must be the one that's actually wrong here, since Domain Controllers are never configured or trusted as a reliable time-sync reference point",
          "This is purely a timezone display issue rather than a clock skew issue, so simply converting both timestamps to UTC display format would fully resolve the discrepancy",
        ],
        answer: 1,
        explanation: "This is the exact trap the reading warns about: unmanaged clocks drift, and ordering events by raw, uncorrected timestamps across sources is how an analyst gets a sequence backward. NTP is the standard fix, and checking a device's sync status is a genuine diagnostic step before trusting its timeline position. Raw timestamps from different sources cannot simply be compared without checking clock health first; Domain Controllers are commonly configured as a reliable time source, not an inherently unreliable one; and this is specifically clock skew (two clocks disagreeing on the current time), not a timezone/display issue, since no offset conversion is described.",
        xp: 20,
      },
      {
        id: "cf_08",
        question: "An investigator pulls an old archived firewall log in classic syslog format that reads 'Aug 14 03:12:09 fw02 denied connection...' with no year printed anywhere in the line, and assumes it happened this year because that's the simplest reading. What mistake does this risk, and what should the investigator do instead?",
        options: [
          "No mistake at all — syslog timestamps always silently default to whatever the current calendar year is, unless a full ISO 8601 date happens to be present in the line",
          "Classic syslog format carries no year at all; assuming 'this year' can silently shift the entire timeline by exactly a year or more with no obvious error, so the year should be corroborated from file metadata, ingestion records, or a neighboring log entry with a full date",
          "The mistake is essentially irrelevant here, since syslog entries lacking a year are automatically filtered out and excluded from any investigation timeline by well-built SIEM tooling",
          "This is actually a Windows FILETIME formatting issue rather than a syslog issue, and the investigator should instead convert the value from 100-nanosecond intervals counted since the year 1601",
        ],
        answer: 1,
        explanation: "The reading is explicit about this exact trap: classic syslog predates any expectation of being read years later, so it carries no year field, and assuming 'this year' can silently shift a whole timeline by 365 days or more with no visible error. The year must be corroborated externally — file modification metadata, ingestion timestamps, or a neighboring entry with a fuller date. Syslog entries aren't auto-excluded from timelines, and this format has nothing to do with Windows FILETIME, which is a completely different, much larger numeric format counting from 1601.",
        xp: 15,
      },
      {
        id: "cf_09",
        question: "An investigation timeline shows the attacker's first malicious login at 2026-01-02 03:00 UTC and the SOC's first detection alert firing at 2026-01-09 03:00 UTC — a 7-day gap. Containment was completed two hours after the alert fired. Which of these numbers is 'dwell time' as the reading defines it, and what is it specifically meant to measure?",
        options: [
          "The 7-day gap between first compromise and first detection — dwell time measures how long an attacker operated undetected, which is a different number from how quickly the SOC responded once it noticed",
          "The 2-hour gap between detection and containment, since dwell time measures how fast the SOC reacted once an alert fired",
          "The combined 7-day-and-2-hour total, since dwell time measures the entire incident from compromise through containment as one figure",
          "There is no way to calculate dwell time without knowing the exact clock-sync status of every device involved",
        ],
        answer: 0,
        explanation: "The reading defines dwell time precisely as the gap between when an attacker first gained access and when that activity was first detected — here, the 7-day gap — and explicitly separates it from containment/response speed, which is a different measurement of how fast the SOC acted after noticing. The 2-hour figure is response time, not dwell time, and dwell time isn't a combined total of both phases. While clock-sync accuracy matters generally for building a trustworthy timeline, dwell time itself is still a defined, calculable concept once timestamps are normalized — it doesn't require perfect NTP sync to have a meaning.",
        xp: 20,
      },
      {
        id: "cf_10",
        question: "A user uploads a spreadsheet full of customer credit card numbers to a personal cloud-storage app that was never added to the company's DLP monitored-channel list. DLP generates zero alerts for the transfer. What does this best illustrate about DLP's blind spot, per the reading?",
        options: [
          "DLP is structurally and permanently incapable of ever inspecting any cloud storage upload whatsoever, no matter how the platform or its policies are configured",
          "DLP's blind spot is entirely a configuration question — it only watches the channels it has been explicitly told to watch, so a channel nobody configured is invisible to it, not because the data wasn't sensitive but because nothing was inspecting that path",
          "The credit card numbers in this specific export must simply not have matched DLP's built-in sensitive-data pattern for that regulated data type, which is the actual reason nothing fired here",
          "DLP only ever inspects the corporate email channel by design, so literally any non-email transfer path is permanently and inherently outside its detection scope",
        ],
        answer: 1,
        explanation: "This is exactly how the reading frames DLP's blind spot: it's a configuration gap, not a structural one — DLP can inspect cloud uploads when that channel is configured, and this specific app simply wasn't on the monitored list. There's no indication the data pattern failed to match; the problem is that nothing was ever watching that channel at all. DLP is explicitly described as covering multiple channels — email, USB, cloud uploads, web forms, print — not only email.",
        xp: 15,
      },
      {
        id: "cf_11",
        question: "An EDR alert flags a process tree showing PsExec launching a remote script with elevated privileges on a server. Investigation reveals it was the sysadmin's routine patch-deployment tool, not an attacker. Why does this kind of activity trip up EDR specifically, according to the reading?",
        options: [
          "Because EDR cannot actually see process command lines or arguments at all, so it can only ever guess at malicious intent based on static file hashes alone",
          "Because legitimate remote administration (PsExec, WMI, or PowerShell used by sysadmins) looks, on the process tree alone, almost identical to an attacker's lateral movement — this is named as EDR's characteristic false positive",
          "Because PsExec is inherently and always malicious wherever it appears, so any EDR alert that mentions it should be escalated automatically without further investigation",
          "Because EDR products only ever monitor east-west network traffic rather than process activity, meaning this particular alert must actually have originated from the NGFW instead",
        ],
        answer: 1,
        explanation: "The reading names this directly as EDR's characteristic false positive: legitimate sysadmin tooling using PsExec, WMI, or PowerShell for routine remote administration is structurally hard to distinguish from lateral movement using process-tree data alone. EDR's whole value is watching process behavior and command lines in detail (the opposite of option A); PsExec itself is a legitimate Microsoft tool with many benign uses, not inherently malicious; and EDR is explicitly a host-based, process-level product, not a network-traffic product.",
        xp: 20,
      },
      {
        id: "cf_12",
        question: "An NGFW without TLS inspection enabled logs an HTTPS session to an unfamiliar destination: unusually large byte counts, and an App-ID classification of 'unknown-tcp.' Based on the reading, what can the analyst reasonably conclude from this log entry alone, and what remains completely out of reach?",
        options: [
          "The analyst can see the fully decrypted request and response bodies directly inside the log, since every modern NGFW decrypts all TLS sessions by default purely for logging purposes",
          "The analyst can see connection metadata — destination, byte volume, and App-ID's best-effort classification — which is enough to flag the session as worth investigating, but not the actual encrypted content, unless TLS inspection is specifically configured",
          "Nothing at all can be meaningfully concluded here, since an NGFW without TLS inspection enabled provides absolutely zero visibility into any session that happens to be encrypted",
          "The App-ID label 'unknown-tcp' by itself definitively proves the traffic is malicious, since legitimate, well-behaved applications are always correctly fingerprinted by App-ID's pattern matching",
        ],
        answer: 1,
        explanation: "This matches the reading's description precisely: without TLS inspection, an NGFW sees that a connection happened, its destination, byte counts, and App-ID's pattern-based guess — enough to flag an anomalous-looking session as worth investigating — but never the actual bytes inside it. NGFWs don't decrypt by default (that requires specifically configuring TLS inspection); the metadata alone is still meaningful, so 'nothing at all' is wrong; and an 'unknown-tcp' classification is the reading's named characteristic false-positive pattern (App-ID misclassifying unusual-but-legitimate traffic), not proof of malice by itself.",
        xp: 25,
      },
    ],
  },

  // ── 2. Data Loss Prevention (DLP) Triage ─────────────────────────────────
  {
    slug: "data-loss-prevention",
    title: "Data Loss Prevention (DLP) Triage",
    description: "Read a DLP alert like an analyst: which channel caught it, what the confidence score and match count actually mean, what each action (Audit, Warn, Block, Encrypt) tells you, and whether it's a false positive, a well-meaning mistake, or a real insider-threat escalation.",
    difficulty: "Intermediate",
    category: "Data Security",
    icon: "📤",
    estimatedMinutes: 14,
    questions: [
      {
        id: "dlp_01",
        question: "A DLP alert fires on a file that turns out to have been sent by a well-meaning employee who attached the wrong document by mistake. Why did DLP flag this the exact same way it would flag a malicious insider deliberately stealing the same file?",
        options: [
          "DLP is a content-inspection control — it judges the content pattern, not the sender's intent, so the same content triggers the same technical detection regardless of who sent it or why",
          "DLP always assumes malicious intent by default until an analyst proves otherwise",
          "DLP scores users by a reputation rating, and this employee happened to have a low score that day",
          "Accidental attachments are technically routed through a separate 'mistake' classifier that mimics the malicious one",
        ],
        answer: 0,
        explanation: "Like the airport bag scanner analogy the room opens with, DLP looks at what is inside the outbound content and compares it to a rule set — it does not primarily judge intent. A careless mistake and a deliberate theft of the same file produce an identical content match; distinguishing intent is explicitly described as the analyst's job downstream, not something the DLP engine itself does. There is no reputation score or separate 'mistake' classifier in how the room describes DLP.",
        xp: 15,
      },
      {
        id: "dlp_02",
        question: "A user pastes a large block of customer PII copied from a corporate spreadsheet into the input box of an unauthorized AI chatbot website. Which DLP channel is capable of catching this, and why?",
        options: [
          "Network DLP, because it inspects all HTTPS traffic to any website without needing further setup",
          "Cloud/Email DLP, because it covers every SaaS platform an employee might visit, including unsanctioned websites",
          "Endpoint DLP, because it runs as an agent directly on the device and can see clipboard paste activity even when the destination is outside any monitored network or cloud workload",
          "None of the three channels can see clipboard paste, since it never touches a file",
        ],
        answer: 2,
        explanation: "The room lists clipboard paste into an unauthorized application as one of the local, on-device actions that only Endpoint DLP sees, alongside USB copy, printing, and screenshots — none of which touch the network or a managed SaaS workload. Network DLP would need the traffic to cross the network boundary, and even then only sees it if paired with SSL inspection; an unsanctioned chatbot site is not a managed Cloud/Email workload Purview integrates with natively.",
        xp: 20,
      },
      {
        id: "dlp_03",
        question: "Your organization's Network DLP appliance sits inline but is not paired with a TLS/SSL-inspecting proxy. An employee uploads a sensitive file to a cloud SaaS app over HTTPS. What does the room say about Network DLP's ability to catch this?",
        options: [
          "Network DLP has become less dominant for exactly this scenario, because it cannot decrypt or see inside encrypted HTTPS traffic without an SSL-inspecting proxy in the path",
          "Network DLP inspects HTTPS traffic identically to unencrypted HTTP, so this upload is caught the same way an FTP transfer would be",
          "Network DLP relies on the Workload field to catch cloud uploads, so it would flag this the same way Purview's cloud DLP does",
          "This activity would go completely undetected by any DLP channel, since only Network DLP monitors uploads",
        ],
        answer: 0,
        explanation: "The room explicitly says Network DLP has become less dominant as traffic moved to encrypted HTTPS and cloud SaaS apps the appliance cannot decrypt without a TLS-inspecting proxy in the path. The Workload field belongs to Purview's unified cloud/email schema, not to a network appliance. And the scenario doesn't rule out other channels (Endpoint or Cloud DLP) catching the same upload — the question is specifically about Network DLP's limitation here.",
        xp: 20,
      },
      {
        id: "dlp_04",
        question: "A DLP alert shows Workload = SharePoint, indicating an external sharing link was created for a folder containing PHI. Per the room's guidance on triaging cloud-channel alerts, what should you check first?",
        options: [
          "The RemovableMedia.SerialNumber field, to identify the physical device involved",
          "Who the share was granted to, and whether the link is anonymous / 'anyone with the link'",
          "Whether ActionTaken is Warn/Justify, since SharePoint alerts can never result in a Block",
          "The EventTimeLocal field only, since SharePoint alerts are exclusively about timing",
        ],
        answer: 1,
        explanation: "The room states that a SharePoint or Teams event usually means an external share link was created, and directs the analyst to check who the share was granted to and whether the link is anonymous/anyone-with-the-link. RemovableMedia fields belong to Endpoint DLP's USB events, not SharePoint sharing. Nothing in the room claims SharePoint policies are restricted to Warn/Justify only.",
        xp: 20,
      },
      {
        id: "dlp_05",
        question: "A DLP alert matches a 5-digit diagnosis code appearing in a document, with no patient name, ID, or other identifier anywhere nearby. How should this be interpreted based on how the room describes PHI classifiers?",
        options: [
          "A diagnosis code alone is not sufficient for a reliable PHI match — PHI classifiers typically require compound evidence such as a patient identifier plus a medical term, since a diagnosis code or a name alone is not enough to constitute PHI",
          "Any diagnosis code automatically constitutes a confirmed PHI match regardless of surrounding context",
          "Diagnosis codes have a fixed numeric format, so this match is exactly as reliable as an SSN regex hit",
          "PHI is detected exclusively through document fingerprinting, so a regex-style diagnosis-code match like this cannot legitimately be labeled PHI at all",
        ],
        answer: 0,
        explanation: "The room states PHI classifiers often look for a combination of a patient identifier plus a medical term or diagnosis code, since a diagnosis code alone (or a name alone) is not enough — this 'compound evidence' requirement is exactly what raises confidence for compound types. It does not say PHI can only be caught via fingerprinting; that describes source code/IP detection instead.",
        xp: 25,
      },
      {
        id: "dlp_06",
        question: "An outbound message is flagged for containing what appears to be an AWS access key, matched via a regex pattern beginning with the prefix AKIA. Regardless of whether the sender's intent turns out to be malicious or accidental, what does the room say should happen to that credential?",
        options: [
          "Nothing further is needed once the DLP alert is simply logged for the record — secrets matches require no meaningful analyst follow-up action beyond documentation",
          "The credential should be rotated immediately, since a leaked secret can be immediately weaponized by whoever finds it, unlike a leaked PII record which usually requires further exploitation first",
          "Escalation and any remediation should wait until the employee is reached and confirms one way or another whether they acted with malicious intent",
          "AKIA-prefixed strings flagged in outbound mail are near-certain false positives, since genuine, currently-valid AWS keys essentially never appear inside outbound email traffic",
        ],
        answer: 1,
        explanation: "The room specifically calls out secrets and credentials as a category where a leaked value can be immediately weaponized by anyone who finds it, unlike PII which usually needs further exploitation — and lists rotating the exposed credential immediately, regardless of intent, as the correct response. Waiting on the employee's explanation before acting would leave a live credential exposed in the meantime.",
        xp: 20,
      },
      {
        id: "dlp_07",
        question: "A DLP alert shows Confidence = 95 and Count = 1, generated by a match against a fingerprinted reference dataset (document fingerprinting / EDM) rather than a generic regex pattern. Should this be dismissed as low priority purely because the count is only 1?",
        options: [
          "No — the room notes a high-confidence single match, such as a fingerprinted secret, is still worth checking, because EDM confidence reflects recognition of the organization's actual protected content rather than a generic pattern that merely happens to fit",
          "Yes — a match count of exactly 1 always and unconditionally signals a false positive, regardless of which detection method or classifier actually produced it",
          "Yes — only regex-based matches paired with a high count are ever genuinely worth an analyst spending investigative time on",
          "No, but only because every EDM match is automatically hard-coded to Critical severity across every DLP platform, independent of the underlying content",
        ],
        answer: 0,
        explanation: "The room's confidence-plus-count reference explicitly lists 'Confidence: 95, Count: 1' as a high-confidence single match, e.g. a fingerprinted secret, that is still worth checking — distinguishing it from a low-confidence single match (Confidence: 55, Count: 1), which is the likely-false-positive shape. EDM recognizes the organization's real registered content rather than guessing at a pattern, which is why a single hit still carries weight here. The room never claims a fixed severity is auto-assigned to EDM matches.",
        xp: 25,
      },
      {
        id: "dlp_08",
        question: "A finance employee needs to send a signed contract containing customer PII to an external partner as a normal part of business. The policy for this data type is configured to apply Microsoft Purview Message Encryption rather than Block. Why would an organization choose Encrypt over Block here?",
        options: [
          "Encrypt lets the legitimate business communication proceed while ensuring only the intended, authenticated recipient can open it — appropriate for regulated data that must legitimately go out, unlike Block, which would stop the workflow entirely",
          "Encrypt and Block ultimately produce identical outcomes for the sender and recipient; only the internal log label written to the ActionTaken field actually differs between them",
          "Encrypt is a capability only available on the Endpoint DLP channel, and it structurally cannot be applied to an Exchange email policy at all",
          "Choosing Encrypt as the policy action causes the DLP engine to skip content inspection entirely for that particular outbound message before it is sent",
        ],
        answer: 0,
        explanation: "The room describes Encrypt as a distinct fourth action, common for legitimate regulated data that MUST be sent externally as part of business, where the policy adds protection instead of stopping the workflow — contrasted directly with Block, which stops the action outright (email bounces, USB write fails, upload rejected). The room gives email/Exchange as the example channel for Encrypt, not Endpoint, and content is still inspected — Encrypt is the action taken after a match, not a bypass of matching.",
        xp: 20,
      },
      {
        id: "dlp_09",
        question: "A DLP alert shows ActionTaken = 'Allowed - Overridden.' What does this specific value tell you that 'Allowed - Alert Only' would not, and what should you check first?",
        options: [
          "It means the outbound transfer was initially blocked by policy and then the system automatically retried and re-evaluated the exact same message a second time",
          "It carries the exact same underlying meaning as 'Allowed - Alert Only,' with no operationally distinguishable next step for the investigating analyst to take",
          "It means the user was shown a Warn/Justify policy tip and actively chose to proceed anyway — check the JustificationText field first, since it captures what they typed to explain the override",
          "It means the policy governing this particular content type is currently running in audit mode and therefore never actually evaluated the message's content at all",
        ],
        answer: 2,
        explanation: "The room's ActionTaken reference lists 'Allowed - Overridden' as meaning the user saw the warning and chose to proceed anyway, directing the analyst to check JustificationText immediately — distinct from 'Allowed - Alert Only,' which means the data left with no user interruption at all. There is no automatic retry behavior described, and audit-mode policies are associated with the Audit action, not Overridden.",
        xp: 25,
      },
      {
        id: "dlp_10",
        question: "A DLP alert shows a high-confidence, high-count match on regulated data, sent from one internal corporate mailbox to another internal corporate mailbox. Per the room's triage framework, how should the internal-to-internal destination affect your assessment relative to the content match itself?",
        options: [
          "Internal-to-internal transfers should be treated as exactly as high-risk as movement to an external destination, since regardless of destination the data still technically left the originating source mailbox",
          "The content match quality still matters on its own, but internal-to-internal movement is inherently lower risk than movement to an external domain, personal webmail, or unsanctioned cloud app — destination narrows the risk after content is assessed",
          "Destination is essentially irrelevant to DLP triage altogether; only the raw classifier confidence score should ever determine an alert's investigative priority",
          "Internal-to-internal transfers matching a policy should be auto-closed as routine false positives without an analyst ever reviewing the underlying content match quality at all",
        ],
        answer: 1,
        explanation: "The room's triage framework treats content-match quality and destination risk as separate, sequential steps: a strong content match still matters, but the framework explicitly ranks internal-to-internal movement as lower risk than external, personal-webmail, or unsanctioned-cloud destinations. Neither extreme — treating destination as irrelevant, or auto-closing based on destination alone without checking content — matches the step-by-step framework described.",
        xp: 20,
      },
      {
        id: "dlp_11",
        question: "A DLP alert (Allowed - Alert Only) shows a sales employee uploading a large customer export to a personal cloud storage account at 11 PM. Unlike the departing-employee case covered in the room, there is no resignation or other HR flag on file for this user. Does the absence of an HR flag mean this alert should be treated as routine?",
        options: [
          "No — off-hours timing and an unsanctioned personal-cloud destination are still independently meaningful risk signals in the triage framework; the case for escalation is weaker without an HR flag reinforcing it, but the analyst should still assess whether this volume and timing is normal for this user before closing it",
          "Yes — an HR flag such as a resignation, PIP, or role change is the only signal the room's triage framework treats as genuinely meaningful when assessing insider-threat risk on a DLP event",
          "Yes — an ActionTaken value of 'Allowed - Alert Only' means the policy engine itself already evaluated the underlying activity and judged it to be low risk before logging it",
          "No — this alert should be escalated with the exact same urgency and priority as the confirmed departing-employee case, since the content type and destination pattern involved are broadly similar",
        ],
        answer: 0,
        explanation: "The room's framework lists off-hours timing, unusual volume, and an unsanctioned personal-cloud destination as behavioral risk signals in their own right — HR context (resignation, PIP, role change) is described as raising suspicion further when present, not as the sole qualifying signal. The room also explicitly warns that Audit/Alert-Only means zero prevention, not low priority — it says nothing about the policy having 'judged' the content as safe. But it also emphasizes that a single DLP event in isolation rarely proves malicious intent, so treating this identically to the departing-employee case (which had a confirmed HR flag) overstates the certainty here.",
        xp: 30,
      },
      {
        id: "dlp_12",
        question: "What makes document fingerprinting (Exact Data Match / EDM) more precise than a plain regex classifier for detecting a leaked customer database, according to the room?",
        options: [
          "EDM matches outgoing content against a cryptographic fingerprint of an actual registered reference dataset, so it recognizes the organization's real protected content rather than merely a pattern that looks similar",
          "EDM works purely by checking the outgoing file's extension, such as .csv or .xlsx, without inspecting anything about the actual file content itself",
          "EDM is fundamentally a machine-learning model trained on hundreds of confirmed sensitive and non-sensitive sample documents, similar to a trainable classifier",
          "EDM and plain regex classifiers ultimately produce identical confidence scores in Purview logs, because both methods rely on exactly the same underlying pattern-matching engine",
        ],
        answer: 0,
        explanation: "The room describes EDM as letting DLP say 'this file contains OUR customer records' rather than merely 'this file contains something that looks like a customer record,' because it fingerprints an actual uploaded reference dataset rather than guessing at a generic pattern. File-extension checking is described as a weaker signal used for source-code detection, and the trained-on-samples description belongs to the separate 'trainable classifier / ML' method, not EDM.",
        xp: 15,
      },
    ],
  },
];
