// ─── Quiz Data: Detection Engineering, Vulnerability Management, AppSec, Ops ──
// Four quizzes closing measured coverage gaps. Same contract as ./data.ts.

import type { Quiz } from "./data";

export const QUIZZES_DETECTION_APPSEC: Quiz[] = [

  // ── 1. Detection Engineering & Rule Writing ───────────────────────────────
  {
    slug: "detection-engineering",
    title: "Detection Engineering & Rule Writing",
    description: "Write rules that survive contact with a real SOC — precision versus recall, behavioural logic over brittle IOCs, honest tuning, and ATT&CK coverage you can prove.",
    difficulty: "Advanced",
    category: "SIEM",
    icon: "🎯",
    estimatedMinutes: 15,
    questions: [
      {
        id: "de_01",
        question: "A detection rule catches 9 of the 10 real intrusions in a test window, but 92% of the alerts it raises turn out to be benign. In detection terms, what is the problem?",
        options: [
          "Low recall — the rule misses most of the real intrusions it sees",
          "Low precision — most alerts it raises are not intrusions",
          "Low fidelity in the log source that feeds the rule",
          "Low coverage of the ATT&CK techniques in scope",
        ],
        answer: 1,
        explanation: "Precision = true positives ÷ all alerts raised. At 8% precision the rule is drowning analysts. Recall is fine here — it caught 9 of 10, so 'low recall' describes the opposite failure. Log fidelity is not implicated: the rule is matching exactly what it was told to match, the logic is just too broad. Coverage describes how many techniques you can detect at all, not how noisy one rule is.",
        xp: 15,
      },
      {
        id: "de_02",
        question: "Which statement best describes the real cost difference between a false negative and a false positive in a SOC?",
        options: [
          "A false positive costs analyst hours; a false negative costs a breach",
          "A false negative costs analyst hours; a false positive costs a breach",
          "Both cost the same, since every alert consumes one full triage cycle",
          "Neither carries real cost once the rule is documented and approved",
        ],
        answer: 0,
        explanation: "A false positive is a real alert that was not a threat — it burns triage time. A false negative is an intrusion nobody saw — it costs an incident. Option two simply reverses the two definitions, which is the single most common mix-up. Option three is wrong because a false negative generates no alert and therefore no triage cycle at all; its cost is invisible until much later. Option four is wrong because documentation changes nothing about either error rate.",
        xp: 10,
      },
      {
        id: "de_03",
        question: "Rule A alerts on a specific malware file hash. Rule B alerts on winword.exe spawning a child process that immediately makes an outbound connection. Why does Rule B survive longer against the same actor?",
        options: [
          "It watches attacker behaviour, not one disposable artefact",
          "It queries more log sources, so it has more chances to fire",
          "Hash lookups are expensive and get disabled under load first",
          "Behavioural rules are exempt from the tuning process entirely",
        ],
        answer: 0,
        explanation: "Rule B describes a step the actor must take to achieve their objective — a document spawning a networked child. Changing that costs them tooling redesign. Rule A dies the moment they recompile. Option two is wrong because the number of sources a rule touches has no bearing on durability; a hash rule spanning ten sources is still dead after one recompile. Option three is a performance myth — hash equality is trivially cheap. Option four is false: behavioural rules need *more* tuning, not less, because they match on generic activity.",
        xp: 15,
      },
      {
        id: "de_04",
        question: "An EDR rule for 'unusual child process' fires dozens of times a day on a build server where msbuild.exe legitimately spawns compilers. Which tuning is the safer choice?",
        options: [
          "Suppress the rule when the parent is the known build binary",
          "Suppress the rule for that host entirely, since it is a build server",
          "Lower the rule severity to informational and stop reviewing those alerts",
          "Delete the rule and rely on the endpoint's default prevention policy",
        ],
        answer: 0,
        explanation: "Scoping the exception to the specific parent process keeps the rule alive for everything else on that host — if an attacker lands a web shell or a scheduled task there, you still see it. Option two blinds you on an entire machine, and build servers are high-value targets holding signing keys and credentials. Option three is the same blindness dressed as tuning: an alert nobody reads is a suppressed alert. Option four gives up the detection altogether and assumes prevention catches what detection was written for.",
        xp: 20,
      },
      {
        id: "de_05",
        question: "On the Pyramid of Pain, why is a file hash the weakest indicator to build detections on?",
        options: [
          "An attacker changes it by recompiling or padding a single byte",
          "Hashes cannot be collected by most endpoint agents in real time",
          "Hash values are too long to index efficiently in a SIEM backend",
          "Hashes are only produced for executables, never scripts or documents",
        ],
        answer: 0,
        explanation: "Hashes sit at the base of the pyramid because they are trivially and automatically variable — one byte of padding produces a completely new value at zero cost to the adversary. TTPs sit at the apex because changing them means changing how the actor operates. Option two is false: hashing on execution is a standard EDR capability. Option three is false: hashes are fixed-length and index well. Option four is false: any file can be hashed, including scripts, documents and archives.",
        xp: 10,
      },
      {
        id: "de_06",
        question: "What is the main reason a mature team keeps detection content in version control with automated tests?",
        options: [
          "Every rule change is reviewable, revertible and regression-tested",
          "It lets the SIEM compress rule storage and run searches faster",
          "It removes the need to tune rules once they reach production",
          "It converts vendor rules into a format auditors are required to accept",
        ],
        answer: 0,
        explanation: "Detection-as-code treats rules as software: peer review before merge, a diff explaining why logic changed, and unit tests firing sample events so a 'small' edit cannot silently break a working detection. Option two confuses rule management with storage engineering — version control lives outside the SIEM and affects nothing about query speed. Option three is backwards: version control makes tuning safer and more frequent, not unnecessary. Option four invents an audit requirement that does not exist.",
        xp: 10,
      },
      {
        id: "de_07",
        question: "Before writing a rule on anomalous service-account logons, you are told to build a baseline. What are you actually building?",
        options: [
          "A record of where, when and how often those accounts normally log on",
          "A list of every alert the SIEM has raised on those accounts in the last year",
          "A copy of the AD group memberships held by each service account",
          "A threshold copied from the vendor's recommended default settings",
        ],
        answer: 0,
        explanation: "A baseline is an empirical description of normal, gathered over enough time to include month-end and quarter-end behaviour — which hosts each account touches, at which hours, at what frequency. Only then can 'anomalous' mean anything. Option two baselines your *alerting*, not the environment, so it inherits every blind spot the current rules already have. Option three is useful context but static configuration, not observed behaviour. Option four is a vendor guess about someone else's estate.",
        xp: 15,
      },
      {
        id: "de_08",
        question: "Why can a rule that fires 400 times a day be worse than having no rule at all?",
        options: [
          "Analysts learn to close it unread — including the one real hit",
          "The SIEM licence cost per event makes the rule financially unviable",
          "High-volume rules are automatically disabled by most SIEM platforms",
          "It overwrites older detections held in the correlation engine's memory",
        ],
        answer: 0,
        explanation: "With no rule you at least know you have a gap. With a 400-a-day rule you have a false sense of coverage plus a trained reflex to bulk-close, so the genuine detection is closed alongside the noise — and the coverage report still shows a green tick. Option two is a real budget concern but the rule fires on events already ingested, so it adds no licence cost. Option three does not happen: SIEMs run whatever you deploy. Option four describes no real correlation engine behaviour.",
        xp: 15,
      },
      {
        id: "de_09",
        question: "Which metric most directly exposes alert fatigue across a detection portfolio?",
        options: [
          "The share of alerts closed as benign, tracked per rule",
          "The total number of detection rules deployed in the SIEM",
          "The average size in bytes of the events matching each rule",
          "The number of ATT&CK techniques the rule set claims to cover",
        ],
        answer: 0,
        explanation: "Benign-close rate per rule turns fatigue from a feeling into a number, and it names the specific rules to fix. Option two counts activity, not quality — 900 rules can be far worse than 90. Option three measures event volume and says nothing about whether analysts trust the output. Option four measures breadth of coverage; a portfolio can map to 200 techniques and still be unusable if every rule is 95% noise.",
        xp: 10,
      },
      {
        id: "de_10",
        question: "Why do detection engineers map each deployed rule to an ATT&CK technique?",
        options: [
          "It shows which techniques currently have no detection at all",
          "It guarantees the rule will fire on every variant of that technique",
          "It allows the SIEM to auto-generate rules for adjacent techniques",
          "It replaces the need for a baseline, since ATT&CK defines what is normal",
        ],
        answer: 0,
        explanation: "Mapping produces a coverage matrix, and the value is in the empty cells — the techniques your adversaries use that nothing currently detects. Option two is the dangerous misreading: a label is a claim about intent, not a guarantee of completeness, and one rule rarely covers a whole technique. Option three describes a capability no SIEM has. Option four inverts the purpose — ATT&CK catalogues adversary behaviour, it says nothing about what is normal in your estate.",
        xp: 10,
      },
      {
        id: "de_11",
        question: "A rule reads: process_name = 'powershell.exe' AND command_line CONTAINS '-enc'. What is its biggest weakness as written?",
        options: [
          "Admin tooling also uses encoded commands, so precision is poor",
          "PowerShell logging cannot record the command line of a process",
          "The -enc flag is deprecated and no longer accepted by PowerShell",
          "Encoded commands are decoded by the SIEM before rules are evaluated",
        ],
        answer: 0,
        explanation: "Encoded commands are a legitimate way to pass quoting-hostile strings, so management agents, installers and scheduled jobs use them daily. Without a parent-process or user context filter the rule alerts on all of it. Option two is false — Event ID 4688 with command-line auditing, and Sysmon Event ID 1, both carry the full command line. Option three is false: -EncodedCommand and its -enc abbreviation are current. Option four is false: the SIEM stores the raw string, and decoding is a step you must add yourself.",
        xp: 20,
      },
      {
        id: "de_12",
        question: "You have two candidate rules for the same technique: a broad one with 30% precision, and a narrow one with 95% precision that catches roughly half as many cases. What is the sound design decision?",
        options: [
          "Ship both, routing each to the queue its precision justifies",
          "Ship only the narrow rule, because Tier 1 must never see noise",
          "Ship only the broad rule, because recall always beats precision",
          "Ship neither until a single rule reaches both 95% precision and full recall",
        ],
        answer: 0,
        explanation: "Precision determines destination, not existence. The 95% rule earns a Tier 1 page; the 30% rule is valuable hunting input and belongs in a hunt or enrichment queue where volume is expected. Option two throws away real recall to protect a queue that the broad rule was never going to enter. Option three routes 70% noise at Tier 1 and manufactures the fatigue that makes the other rule useless too. Option four is paralysis — that rule does not exist for any non-trivial technique.",
        xp: 20,
      },
    ],
  },

  // ── 2. Vulnerability Management for SOC ───────────────────────────────────
  {
    slug: "vulnerability-management",
    title: "Vulnerability Management for SOC",
    description: "CVE, CWE, CVSS, EPSS and KEV — what each one actually tells you, how to prioritise when everything is 'critical', and where the SOC's job ends and IT's begins.",
    difficulty: "Intermediate",
    category: "Vulnerability Management",
    icon: "🩹",
    estimatedMinutes: 14,
    questions: [
      {
        id: "vm_01",
        question: "Log4Shell is described by CVE-2021-44228, by CWE-917, and by a CVSS score of 10.0. What does the CVE identifier itself provide?",
        options: [
          "A unique reference to that one specific flaw in that product",
          "A numeric score expressing how severe the flaw is judged to be",
          "A category naming the class of coding weakness behind the flaw",
          "A probability that the flaw will be exploited in the next 30 days",
        ],
        answer: 0,
        explanation: "A CVE ID is a catalogue number — its only job is to let two tools mean the same flaw. Option two is the CVSS score's job (10.0 here). Option three is what the CWE gives you: CWE-917 is expression-language injection, the weakness class, which applies to many unrelated CVEs. Option four is EPSS. All four describe Log4Shell, but only one of them is the identifier.",
        xp: 10,
      },
      {
        id: "vm_02",
        question: "An analyst writes in a ticket: 'the CVE of this vulnerability is 9.8'. What is wrong with that sentence?",
        options: [
          "9.8 is a CVSS score; a CVE is an identifier, not a number",
          "9.8 is an EPSS score; CVE values only ever run from 1 to 5",
          "Nothing — CVE and CVSS are two names for the same rating",
          "CVEs are scored 0-10 but only NIST may assign the value",
        ],
        answer: 0,
        explanation: "CVE and CVSS are different things that both appear on the same finding: CVE-2021-44228 names the flaw, 9.8 or 10.0 rates it. Option two is wrong twice — EPSS is a 0-to-1 probability, and CVEs are not scored on any scale. Option three is the exact confusion the sentence exposes. Option four keeps the false premise that a CVE carries a number, and misstates the process: CVE IDs come from CNAs, and CVSS scores are published by multiple parties who sometimes disagree.",
        xp: 15,
      },
      {
        id: "vm_03",
        question: "Which CVSS metric group adjusts a score for your own asset's exposure and business impact?",
        options: [
          "Environmental",
          "Temporal",
          "Base",
          "Exploitability",
        ],
        answer: 0,
        explanation: "Environmental metrics let you re-score for your estate — security requirements for confidentiality, integrity and availability, plus modified base metrics reflecting your actual deployment. Temporal reflects the flaw's changing state over time, such as exploit maturity and patch availability, and is the same for everyone. Base is the intrinsic, context-free score published with the CVE. Exploitability is a sub-group inside Base (attack vector, complexity, privileges required), not a group of its own.",
        xp: 10,
      },
      {
        id: "vm_04",
        question: "Under CVSS v3.1, a base score of 7.5 falls into which severity band?",
        options: [
          "High (7.0-8.9)",
          "Critical (9.0-10.0)",
          "Medium (4.0-6.9)",
          "Low (0.1-3.9)",
        ],
        answer: 0,
        explanation: "The v3.1 qualitative bands are None 0.0, Low 0.1-3.9, Medium 4.0-6.9, High 7.0-8.9, and Critical 9.0-10.0, so 7.5 is High. The other three options give the correct ranges for their own labels — the trap is the habit of calling anything above 7 'critical' in a ticket, which quietly inflates every report and destroys the meaning of the top band.",
        xp: 10,
      },
      {
        id: "vm_05",
        question: "Why is the CVSS base score a poor sole input for deciding what to patch first?",
        options: [
          "It ignores whether the flaw is actually being exploited anywhere",
          "It is recalculated weekly, so the number is never stable enough",
          "It applies only to network flaws and not to local or physical ones",
          "It is vendor-supplied, so two vendors never agree on the same flaw",
        ],
        answer: 0,
        explanation: "Base is a static description of worst-case technical impact. It knows nothing about exploit availability, your asset's exposure, or compensating controls — which is why estates full of 9.8s cannot rank them. Option two is wrong: the base score is deliberately stable, and it is the temporal group that moves. Option three is wrong — attack vector explicitly includes local and physical. Option four is wrong: scoring disagreement happens, but the deeper problem is what the score omits, not who published it.",
        xp: 15,
      },
      {
        id: "vm_06",
        question: "A finding appears on the CISA Known Exploited Vulnerabilities (KEV) catalogue. What does that tell you?",
        options: [
          "It has been seen exploited in the wild — patch it first",
          "It scored above 9.0 on CVSS and was reclassified as critical",
          "It affects software that CISA has designated as federal-only",
          "Its exploit code was published but never seen used in attacks",
        ],
        answer: 0,
        explanation: "KEV listing is evidence of confirmed in-the-wild exploitation, which makes it one of the strongest prioritisation signals available. Option two is wrong: KEV entries are not selected by CVSS, and plenty of listed flaws score in the sevens. Option three is wrong — the catalogue is public and applies to commodity software everyone runs, even though the remediation deadlines are binding only on US federal agencies. Option four describes the opposite of the KEV criterion — published-but-unused code is exactly what does not qualify.",
        xp: 10,
      },
      {
        id: "vm_07",
        question: "A vulnerability has an EPSS score of 0.94. What does that number mean?",
        options: [
          "A 94% chance of exploitation activity in the next 30 days",
          "A severity of 9.4 out of 10 on the standard CVSS scale",
          "94% of scanned hosts in your estate carry this vulnerability",
          "The patch has been available for 94 days without being applied",
        ],
        answer: 0,
        explanation: "EPSS is a probability from 0 to 1 that a flaw will see exploitation activity in the next 30 days, derived from observed attack telemetry and vulnerability characteristics. Option two rescales it into a CVSS-looking number, which is the usual mistake — the two scales measure different things and are not interchangeable. Option three describes scan prevalence, which comes from your own scanner. Option four describes patch age, an internal SLA metric.",
        xp: 15,
      },
      {
        id: "vm_08",
        question: "An unauthenticated scan of a server reports 12 findings. An authenticated scan of the same server, run the same day, reports 340. Why the difference?",
        options: [
          "Credentialed scans see installed patch levels, not just open ports",
          "Unauthenticated scans can only run against Windows hosts, never Linux",
          "The credentialed scan counts each affected file as a separate finding",
          "Authenticated scans include findings from every other host in the subnet",
        ],
        answer: 0,
        explanation: "Without credentials the scanner infers from the outside — banners, open ports, service responses — so it sees only network-reachable surface and guesses at versions. With credentials it reads the installed package and patch inventory directly, exposing every unpatched local component. Option two is false: unauthenticated scanning is OS-agnostic. Option three invents a counting rule scanners do not use. Option four is false — a scan reports on its target, and subnet results are a different scan job.",
        xp: 15,
      },
      {
        id: "vm_09",
        question: "A scanner flags Log4Shell (CVE-2021-44228) on a Windows application server, and the app team insists it is a false positive. What is the sound way to settle it?",
        options: [
          "Check the actual log4j-core jar version present on the host",
          "Re-run the identical scan and see whether the finding appears again",
          "Compare the CVSS score against the vendor's published advisory",
          "Ask the asset owner whether the application has ever been patched",
        ],
        answer: 0,
        explanation: "Confirmation means going to ground truth: locate the library on disk, read its version, and check whether it falls in the affected range. Option two just repeats the same inference and will reproduce the same false positive with equal confidence. Option three tells you how bad the flaw would be if present, which is not the question in dispute. Option four substitutes recollection for evidence — the same recollection that produced the disagreement.",
        xp: 20,
      },
      {
        id: "vm_10",
        question: "A critical, KEV-listed flaw affects a clinical device whose vendor will not ship a fix for nine months. What is the correct next step?",
        options: [
          "Segment and monitor the device, and record the risk decision",
          "Accept the risk silently, since no patch exists to apply anyway",
          "Take the device offline until the vendor ships fixed firmware",
          "Downgrade the finding to low because it cannot be remediated",
        ],
        answer: 0,
        explanation: "When patching is unavailable you apply compensating controls — network segmentation, restricted inbound access, targeted detection on the device's traffic — and you write the residual risk down with an owner and a review date. Option two skips the documentation, which is the part that makes acceptance a decision rather than an oversight. Option three trades a security risk for a patient-safety risk and is rarely the SOC's call. Option four is the worst outcome: the risk is unchanged, and now nobody is tracking it.",
        xp: 20,
      },
      {
        id: "vm_11",
        question: "In most organisations, what is the SOC's role in vulnerability remediation?",
        options: [
          "Prioritise and verify, while IT owns the patching itself",
          "Deploy the patches directly to every affected production host",
          "Approve change windows and sign off on downtime with the business",
          "Own the entire lifecycle from discovery through to patch rollout",
        ],
        answer: 0,
        explanation: "The SOC brings threat context — what is exploited, what is exposed, what matters — and then verifies remediation by re-scanning and by watching for exploitation of what remains open. IT or platform teams hold the change process and the deployment tooling. Option two puts operational change in the hands of a monitoring function with neither the tooling nor the rollback authority. Option three belongs to change management and the service owner. Option four blurs the separation that keeps the verifier independent of the remediator.",
        xp: 10,
      },
    ],
  },

  // ── 3. Web Application Attacks & WAF ──────────────────────────────────────
  {
    slug: "web-application-security",
    title: "Web Application Attacks & WAF",
    description: "Read a web attack from the access log up — injection, XSS, traversal, SSRF and web shells — and learn what a WAF verdict does and does not tell you.",
    difficulty: "Advanced",
    category: "Application Security",
    icon: "🕸️",
    estimatedMinutes: 15,
    questions: [
      {
        id: "wa_01",
        question: "What is the OWASP Top 10?",
        options: [
          "A ranked list of the most critical web application risk categories",
          "A certification standard that a web application must pass before deploying",
          "A catalogue of the ten most exploited CVEs published each quarter",
          "A set of ten WAF rules every commercial vendor ships by default",
        ],
        answer: 0,
        explanation: "The Top 10 is an awareness document listing broad risk categories — broken access control, injection, security misconfiguration and so on — derived from contributed application data. Option two is wrong: it certifies nothing and confers no pass or fail; the OWASP ASVS is the verification standard. Option three confuses risk categories with individual vulnerabilities — a single Top 10 entry covers thousands of CVEs. Option four is wrong: it is vendor-neutral and defines no rules.",
        xp: 10,
      },
      {
        id: "wa_02",
        question: "A web access log shows: GET /product?id=7%20UNION%20SELECT%20null,version()-- HTTP/1.1. What is this?",
        options: [
          "Union-based SQL injection probing the column count and DB version",
          "Blind SQL injection inferring data one boolean condition at a time",
          "Reflected XSS attempting to run script in the responding page",
          "Path traversal trying to reach a file outside the web root",
        ],
        answer: 0,
        explanation: "UNION SELECT appends a second result set to the original query so the output appears in the page — the null placeholder is the attacker matching column counts, and version() is the classic first thing to read back. Option two is wrong because blind injection extracts nothing directly; it asks true/false questions and reads the difference in response. Option three needs script or an event handler, not SQL keywords. Option four needs directory sequences such as ../ in a file parameter.",
        xp: 15,
      },
      {
        id: "wa_03",
        question: "Which request signature points to time-based blind SQL injection?",
        options: [
          "A parameter containing SLEEP(5) with a response ~5 seconds slow",
          "A parameter containing <img src=x onerror=alert(1)> in the query",
          "A request with ../../../../etc/passwd appended to the file path",
          "A request whose User-Agent string is longer than 4096 characters",
        ],
        answer: 0,
        explanation: "When the app returns no data and no distinguishable error, the attacker makes the database itself the output channel: if the injected condition is true, sleep — and response latency carries one bit per request. Option two is an XSS payload. Option three is path traversal. Option four suggests a buffer or header-injection probe. The tell for time-based blind is always latency correlated with a delay function, not content in the response.",
        xp: 15,
      },
      {
        id: "wa_04",
        question: "Why is DOM-based XSS often completely invisible in web server access logs?",
        options: [
          "The payload can sit in the fragment, which is never sent to the server",
          "The payload is encrypted by TLS and cannot be recorded by the web server",
          "The browser strips all script tags before the request leaves the client",
          "The server records only POST bodies, and DOM XSS always uses GET",
        ],
        answer: 0,
        explanation: "DOM XSS happens entirely in client-side JavaScript, and the payload frequently rides in the URL fragment after the # — which browsers never transmit. The server logs a normal page request. Option two is wrong: TLS terminates at the server, which logs the decrypted request line. Option three is wrong — browsers do not sanitise outbound requests. Option four is wrong twice: access logs record the request line, not POST bodies, and DOM XSS is not restricted to GET.",
        xp: 15,
      },
      {
        id: "wa_05",
        question: "What distinguishes stored XSS from reflected XSS?",
        options: [
          "The payload is stored server-side and served to later visitors",
          "The payload runs only in the browser of the user who submitted it",
          "The payload is written into the URL fragment after the hash mark",
          "The payload targets the database engine rather than the browser",
        ],
        answer: 0,
        explanation: "Stored XSS persists in the application — a comment, a profile field, a support ticket — and fires for everyone who views it later, which is why it needs no social engineering and often hits administrators. Option one describes reflected XSS, which requires the victim to follow a crafted link. Option two describes DOM-based XSS. Option three describes SQL injection: XSS executes in the browser, and the database is only the transport for the stored variant.",
        xp: 10,
      },
      {
        id: "wa_06",
        question: "GET /view.php?file=....//....//etc/passwd returns HTTP 200 with a 4 KB body, where that page normally returns about 800 bytes. What is the best read?",
        options: [
          "Path traversal likely succeeded and returned the passwd file",
          "Path traversal was blocked, since a 200 means the WAF allowed it",
          "This is SSRF, because the app fetched a file on the user's behalf",
          "This is stored XSS, since a payload persisted in the file parameter",
        ],
        answer: 0,
        explanation: "The ....// sequence defeats naive filters that strip ../ once — removing the inner ../ from ....// leaves ../ behind. A 200 with a response five times the normal size is the strongest available signal that different content came back; confirm by retrieving the response body. Option one confuses the WAF verdict with the application outcome. Option two is wrong because SSRF means the server requests a remote URL, not a local path. Option three is wrong: nothing here is stored or rendered to another user.",
        xp: 20,
      },
      {
        id: "wa_07",
        question: "Why is 169.254.169.254 the classic SSRF target in a cloud environment?",
        options: [
          "It is the metadata service that can hand out instance credentials",
          "It is the default gateway address for every virtual private cloud subnet",
          "It is the internal DNS resolver that maps all private hostnames",
          "It is the load balancer health-check endpoint exposed to the VPC",
        ],
        answer: 0,
        explanation: "The link-local instance metadata endpoint answers only from the instance itself, so an SSRF that makes the server fetch it can retrieve the role's temporary credentials — turning a web bug into cloud API access. That is why IMDSv2's session-token requirement exists. The other three options name real infrastructure roles, but none of them return credentials, which is the specific reason this address is the prize rather than merely reachable.",
        xp: 15,
      },
      {
        id: "wa_08",
        question: "On an IIS server, w3wp.exe (the application pool worker process) spawns cmd.exe running whoami. Which ATT&CK technique best explains why a web server process has a shell child at all?",
        options: [
          "T1505.003 – Server Software Component: Web Shell",
          "T1059.003 – Command and Scripting Interpreter: Windows Command Shell",
          "T1190 – Exploit Public-Facing Application",
          "T1078 – Valid Accounts",
        ],
        answer: 0,
        explanation: "A web shell is a script planted in the web root that the worker process executes on request, so commands appear as children of w3wp.exe — that parent-child edge is the detection. Option one names the shell that ran, which is the execution mechanism rather than the reason a web server is running it. Option two is likely how the shell was planted, but it describes the initial access, not this artefact. Option three would apply to authenticated abuse, and nothing here shows a logon.",
        xp: 20,
      },
      {
        id: "wa_09",
        question: "An attacker lands a web shell on an IIS server. Why is the attacker not automatically SYSTEM?",
        options: [
          "The worker runs as the app pool identity, not a privileged one",
          "IIS strips all tokens from any process it spawns as a child",
          "Web shells always execute inside a sandboxed browser context",
          "The shell inherits the privileges of the user browsing the site",
        ],
        answer: 0,
        explanation: "Commands from a web shell inherit the worker process token, and modern IIS defaults that to a low-privilege ApplicationPoolIdentity or a dedicated service account. Expect the next step to be privilege escalation — token abuse, an unquoted service path, or a local exploit. Option one invents behaviour IIS does not have: children inherit the parent token normally. Option two is wrong because the shell executes server-side with no browser sandbox involved. Option three is wrong: the remote visitor's identity confers nothing on the server.",
        xp: 15,
      },
      {
        id: "wa_10",
        question: "A single source IP sent 300 injection attempts against /login. 297 returned HTTP 500 and 3 returned HTTP 200. Where do you look first?",
        options: [
          "The three 200s — a working payload stops throwing errors",
          "The 500s, since a server error proves code execution occurred",
          "Neither, because a 200 only means the web server stayed alive",
          "The 500s first, as they show the database was reachable at all",
        ],
        answer: 0,
        explanation: "Errors are the sound of payloads failing to parse. The moment a payload is syntactically valid the query succeeds and the app returns a normal page, so the small cluster of 200s is where the successful syntax lives. Option one overreads a 500: it usually means an unhandled exception, often a syntax error, not execution of the attacker's intent. Option two abandons the strongest signal in the set. Option three is true of the volume but wrong about priority — the 500s are the noise here.",
        xp: 20,
      },
      {
        id: "wa_11",
        question: "A WAF log records action=ALLOW on a POST to /upload.aspx with a 240 KB request body from an external IP. Why does this deserve a look?",
        options: [
          "Nothing matched a rule, yet a large upload reached the app itself",
          "ALLOW means the request was logged but never forwarded upstream",
          "A 240 KB body always exceeds the maximum HTTP POST size allowed",
          "ALLOW entries are informational and are never correlated to a host",
        ],
        answer: 0,
        explanation: "ALLOW means no signature matched — it is not a verdict that the request was safe. An unmatched large POST to an upload endpoint is exactly how a web shell gets planted, so the next step is to correlate against file-creation events in the web root and any process spawned by the worker. Option one is wrong: ALLOW forwards the request, which is the whole point. Option two invents a universal size limit that does not exist. Option three is wrong — ALLOW records carry the backend target and are correlated routinely.",
        xp: 20,
      },
      {
        id: "wa_12",
        question: "Overnight your WAF blocked 4,000 SQL injection attempts from one IP address. Why is that not the end of the investigation?",
        options: [
          "You still do not know whether any request slipped past the WAF",
          "Blocked requests are never written to the WAF's own audit log",
          "A WAF block automatically rolls back any database write it caused",
          "Four thousand attempts always indicates an authenticated insider",
        ],
        answer: 0,
        explanation: "Block counts tell you what the rules matched, and say nothing about what they did not. Check the same source for ALLOW verdicts, look for an encoding or endpoint that evaded the signature, and confirm at the application and database layer. Option one is backwards: blocks are the entries you always have. Option two is wrong because a blocked request never reaches the database, so there is nothing to roll back. Option three is wrong — high volume from a single external IP usually means an automated scanner.",
        xp: 15,
      },
    ],
  },

  // ── 4. SOC Operations & Alert Triage ──────────────────────────────────────
  {
    slug: "soc-operations-triage",
    title: "SOC Operations & Alert Triage",
    description: "How a SOC actually runs a shift — tiering, the order you ask triage questions, the verdict everyone forgets, and handovers that survive the person who wrote them.",
    difficulty: "Beginner",
    category: "SOC Fundamentals",
    icon: "🎧",
    estimatedMinutes: 12,
    questions: [
      {
        id: "so_01",
        question: "Which task belongs to Tier 1 rather than Tier 2 or Tier 3?",
        options: [
          "Triaging incoming alerts and escalating the ones that qualify",
          "Building new detection rules from a fresh threat intelligence report",
          "Leading the forensic timeline of a confirmed domain compromise",
          "Deciding whether the organisation notifies a data regulator",
        ],
        answer: 0,
        explanation: "Tier 1 works the queue: validate, gather context, close what is clearly benign, escalate what is not. Option one is detection engineering, typically Tier 3 or a dedicated function. Option two is deep investigation and forensics, which is Tier 2 or 3 with a defined incident lead. Option three is not a SOC decision at all — regulatory notification sits with legal and privacy, informed by what the SOC establishes.",
        xp: 10,
      },
      {
        id: "so_02",
        question: "You are Tier 1 with four open alerts. Which one should you close rather than escalate?",
        options: [
          "A blocked EICAR test file detected on the AV team's own laptop",
          "A blocked ransomware sample found on a domain controller share",
          "A password spray of 400 accounts from one external IP address",
          "A successful admin logon from a country with no staff or offices",
        ],
        answer: 0,
        explanation: "EICAR is a harmless standard test string, and finding it on the AV team's own machine is a control being verified — document the reasoning and close it. Option one is different: a real sample on a domain controller means something reached your most sensitive host, and 'blocked' does not explain how it got there. Option two is an active credential attack. Option three is a successful authentication that the geography cannot account for. Blocked is not the same as harmless.",
        xp: 15,
      },
      {
        id: "so_03",
        question: "An alert lands in your queue. What is the first question to ask?",
        options: [
          "Is this real, or is it a known benign pattern?",
          "Which regulator must be notified about this event?",
          "Who wrote the rule and when was it last tuned?",
          "What is the CVSS score of the affected software?",
        ],
        answer: 0,
        explanation: "Triage runs in order: is it real, what is the scope, how bad is it, what do I do now. Validity comes first because every later question wastes time if the answer is no. Option one is a late-stage legal question that depends on confirmed impact. Option two is a tuning question worth asking after the verdict, not before it. Option three matters for vulnerability work but tells you nothing about whether this specific alert reflects real activity.",
        xp: 10,
      },
      {
        id: "so_04",
        question: "An alert fires on PsExec execution. You confirm it really ran — a named sysadmin ran it during an approved change window. How do you classify it?",
        options: [
          "A benign true positive — real activity, but authorised",
          "A false positive — the rule matched something that never ran",
          "A true positive — any PsExec use is an incident by definition",
          "A false negative — the rule failed to catch the real intrusion",
        ],
        answer: 0,
        explanation: "The rule detected exactly what it was built to detect, and the activity genuinely happened — the only thing that makes it non-malicious is authorisation. That is a benign true positive. Option one is wrong because nothing misfired: the tool did run. Option two overreaches — PsExec is a legitimate admin utility, and treating every use as an incident guarantees you stop reading the alert. Option three is impossible here, since a false negative is an event that produced no alert at all.",
        xp: 15,
      },
      {
        id: "so_05",
        question: "Why does labelling an alert a benign true positive matter more than just calling it a false positive?",
        options: [
          "The rule worked, so tuning should add context, not rewrite it",
          "It lets the SOC delete the rule without any approval process",
          "It moves the ticket straight into the incident queue for legal review",
          "It marks the detection as failed so the vendor can be billed",
        ],
        answer: 0,
        explanation: "The distinction routes the fix. Calling it a false positive sends an engineer to repair logic that is not broken, and the usual outcome is a narrower rule with a new blind spot. The honest label points at the real fix: enrich with change-ticket or asset-owner context so authorised activity is recognisable. Option one is a governance failure, not a benefit. Option two escalates something already resolved. Option three misstates the verdict entirely — the detection worked.",
        xp: 10,
      },
      {
        id: "so_06",
        question: "What does MTTD measure in a SOC?",
        options: [
          "Average time from compromise to the SOC noticing it",
          "Average time from alert creation to ticket closure",
          "Average number of alerts each analyst handles daily",
          "Average time an attacker dwells after containment",
        ],
        answer: 0,
        explanation: "Mean time to detect spans the gap between the intrusion starting and anyone realising, which is why it is driven by detection coverage and log visibility rather than analyst speed. Option one is closer to mean time to respond or resolve, measured after the alert exists. Option two is analyst throughput, a workload metric. Option three is not a standard measure — dwell time by definition ends at detection and containment, not after.",
        xp: 10,
      },
      {
        id: "so_07",
        question: "Which change most directly reduces MTTR?",
        options: [
          "Playbooks with pre-approved containment steps",
          "Adding more detection rules to the SIEM stack",
          "Increasing the log retention window to two years",
          "Raising the severity of every existing rule",
        ],
        answer: 0,
        explanation: "Most response time is spent waiting for a decision, not performing the action. Pre-approved steps — isolate this device class, disable this account type — remove the approval round trip, which is the largest block of dead time in most incidents. Option one may improve detection but adds triage volume, often worsening response time. Option two helps investigation depth, not speed of action. Option three floods the queue with false urgency and slows everything.",
        xp: 10,
      },
      {
        id: "so_08",
        question: "You are handing over an open investigation at shift end. Which handover note is most useful to the incoming analyst?",
        options: [
          "What is confirmed, what is ruled out, and the next action",
          "A copy of every raw log line collected during the shift",
          "The alert ID and a note saying investigation is ongoing",
          "A list of all the tools you opened while working the case",
        ],
        answer: 0,
        explanation: "A good handover transfers state and intent, so the next analyst resumes instead of restarting. The classic failure modes are all in the other options: option one dumps evidence with no interpretation, forcing a re-read of everything. Option two is 'ongoing' with no state at all, which is the most common and most costly handover note there is. Option three records your activity rather than your findings. Verbal-only handovers fail the same way — nothing survives the shift.",
        xp: 15,
      },
      {
        id: "so_09",
        question: "A single host is beaconing to a known command-and-control domain. Under what condition would you watch rather than contain immediately?",
        options: [
          "When scope is unknown and IR has authorised watching",
          "When the host belongs to an executive who dislikes interruptions",
          "Whenever the EDR has already blocked the outbound connection",
          "When the alert severity is medium rather than high or critical",
        ],
        answer: 0,
        explanation: "Containing one host tips the attacker off and can cost you the other twelve. Deliberately watching to establish scope is legitimate — but only as a decision made and recorded by the incident lead, with monitoring in place and a trigger defined for when to pull the plug. Option one is convenience overriding risk. Option two is not watching but assuming the tool already handled it, and beaconing means the implant is still resident. Option three treats a severity label as an authorisation.",
        xp: 20,
      },
      {
        id: "so_10",
        question: "Why is it worth recording what you ruled out during triage?",
        options: [
          "It stops the next analyst repeating dead ends",
          "It is required before any ticket can be marked closed",
          "It replaces the need to record what you actually found",
          "It lets the SIEM automatically suppress the same alert",
        ],
        answer: 0,
        explanation: "Negative findings are evidence. 'No persistence in Run keys, no scheduled tasks created, no lateral SMB' tells the next person exactly where not to spend an hour, and it is what makes a reopened case resumable months later. Option one states a rule most ticketing systems do not enforce. Option two is a false trade — exclusions supplement your findings, they never substitute for them. Option three describes suppression, which is a tuning action you configure deliberately, not a side effect of a ticket note.",
        xp: 10,
      },
      {
        id: "so_11",
        question: "The EDR blocked a malware execution on a workstation. Why does that not close the ticket?",
        options: [
          "You still do not know how the file reached the host",
          "Blocks are reversed automatically after 24 hours pass",
          "The EDR cannot log which user account was logged on",
          "A block always means other hosts were already infected",
        ],
        answer: 0,
        explanation: "A block is one round won, not the match. The delivery path is still open — a phishing message, a shared drive, a USB device, a compromised update — and whatever delivered this can deliver something the EDR does not recognise. Close the ticket once you have the delivery vector and have checked whether other hosts received it. Option one invents behaviour EDRs do not have. Option two is false: the process and user context are in the detection record. Option three overstates a possibility as a certainty.",
        xp: 15,
      },
    ],
  },
];
