// ─── Quiz Data: Threat Hunting & SOC Decision Making ───────────────────────
// Two quizzes: an advanced deep-dive into proactive threat hunting (hypothesis
// design, IOC vs TTP, Pyramid of Pain, frequency/long-tail/stacking analysis,
// and turning hunts into lasting detections), and an intermediate,
// scenario-driven quiz on the professional judgement calls a SOC analyst makes
// every shift — escalate, close, isolate, block, or ask for more evidence.
// Options are length-balanced so the answer can't be guessed by shape. Same
// contract as ./data.ts.

import type { Quiz } from "./data";

export const QUIZZES_HUNTING_DECISIONS: Quiz[] = [
  {
    slug: "threat-hunting-fundamentals",
    title: "Threat Hunting — Hypothesis, Baseline, and the Hunt Loop",
    description: "Proactive hunting versus reactive triage — hypotheses, TTPs over IOCs, the Pyramid of Pain, baselining, and turning a hunt finding into a lasting detection.",
    difficulty: "Advanced",
    category: "Threat Detection",
    icon: "🎯",
    estimatedMinutes: 16,
    questions: [
      {
        id: "th_01",
        question: "What distinguishes threat hunting from alert triage?",
        options: [
          "Threat hunting is proactive and hypothesis-driven, searching for threats that haven't triggered any alert; triage is reactive, working alerts already generated.",
          "Threat hunting only investigates confirmed incidents, while triage searches for undiscovered threats without any alert.",
          "Threat hunting is performed exclusively by Tier 1 analysts, while triage is reserved for senior threat hunters.",
          "Threat hunting relies solely on automated tools, while triage requires manual human judgment for every alert.",
        ],
        answer: 0,
        explanation: "Threat hunting is proactive: hunters start from a hypothesis and search for adversary activity that hasn't triggered any alert yet. Triage is reactive: it works alerts a detection has already fired. Option B reverses the definitions. Option C conflates hunting and triage with seniority — both can be performed at multiple tiers depending on the program. Option D is false — both hunting and triage combine tooling with analyst judgement; neither is purely automated or purely manual.",
        xp: 10,
      },
      {
        id: "th_02",
        question: "What makes a well-formed threat hunting hypothesis?",
        options: [
          "A specific, testable statement — e.g., 'an adversary may be using WMI for lateral movement on finance servers' — that guides the data pulled and analysed.",
          "A broad statement such as 'something bad might be happening somewhere in the environment' that leaves the search scope open.",
          "A list of every IOC published in the last threat intelligence feed, checked one at a time against the SIEM.",
          "A ticket raised by a user reporting slow performance, which the hunter then investigates for malware.",
        ],
        answer: 0,
        explanation: "A strong hypothesis is specific and testable, naming a technique, an asset class, or a behaviour so the hunter knows exactly what data to pull and what would confirm or refute it. Option B is too vague to test — it doesn't tell the hunter where to look or what would count as a finding. Option C describes IOC matching, not hypothesis-driven hunting, and skips the reasoning step entirely. Option D describes a routine user-reported ticket, which is triage, not a hunt.",
        xp: 10,
      },
      {
        id: "th_03",
        question: "What is the core difference between IOC-based and TTP-based hunting?",
        options: [
          "IOC-based hunting searches for known indicators like hashes or IPs; TTP-based hunting searches for behaviours an adversary must exhibit regardless of tooling.",
          "IOC-based hunting searches for behavioural patterns, while TTP-based hunting only matches file hashes against a blocklist.",
          "IOC-based hunting is performed by Tier 3 only, while TTP-based hunting is reserved for automated SOAR playbooks.",
          "IOC-based hunting requires no threat intelligence, while TTP-based hunting depends entirely on a paid intel feed.",
        ],
        answer: 0,
        explanation: "IOC-based hunting matches known artefacts — hashes, IPs, domains — that an attacker can change trivially. TTP-based hunting looks for behaviours (e.g. living-off-the-land execution, specific lateral movement patterns) that are much harder for an adversary to avoid entirely, because they're tied to how the attack must function, not what tool happens to implement it. Option B swaps the two definitions. Option C invents a tiering restriction that doesn't exist — either style can be run by any trained hunter. Option D is false — TTP hunting can, and often does, draw on threat intelligence too.",
        xp: 10,
      },
      {
        id: "th_04",
        question: "A coverage assessment shows your organisation has no visibility into technique T1055 (Process Injection) on its endpoints. What's the best use of this finding?",
        options: [
          "Build a hunting hypothesis around process injection behaviours to test detection coverage and close the gap.",
          "Ignore the gap until an alert for process injection actually fires, since hunting cannot address coverage gaps.",
          "Escalate the finding directly to legal as a compliance violation requiring immediate regulator notification.",
          "Purchase a new EDR product, since ATT&CK coverage gaps can only be resolved by replacing existing tools.",
        ],
        answer: 0,
        explanation: "A documented ATT&CK coverage gap is exactly the kind of thing a hunter turns into a hypothesis: search manually for the technique the environment can't yet detect, and use the results to validate or build coverage. Option B wastes the gap — waiting for an alert that, by definition, the environment isn't yet equipped to generate defeats the purpose of finding the gap. Option C treats a coverage question as a legal matter it isn't. Option D assumes tooling alone closes visibility gaps, when hunting and tuning existing telemetry is usually the first and cheaper step.",
        xp: 15,
      },
      {
        id: "th_05",
        question: "Why does the Pyramid of Pain place TTPs above hashes — why do TTPs hurt an attacker more?",
        options: [
          "Changing a TTP means rebuilding tradecraft and tools, while changing a hash takes an attacker seconds — so detecting TTPs forces costlier adaptation.",
          "Hashes are harder for defenders to collect than TTPs, so detections built on hashes require far more engineering effort.",
          "TTPs expire automatically after 90 days, while hash-based detections remain valid indefinitely without maintenance.",
          "Attackers cannot see which indicator type a defender is using, so the pyramid has no real effect on their behaviour.",
        ],
        answer: 0,
        explanation: "The Pyramid of Pain ranks indicators by how much cost changing them imposes on an attacker. A hash or IP can be swapped in seconds with no real effort; a TTP is tied to tradecraft, tooling, and training that takes real time and resources to rebuild. That's why detections anchored on TTPs are more durable. Option B has the collection difficulty backwards — hashes are typically easier to collect than behavioural TTP data. Option C invents an expiry rule that doesn't exist in the model. Option D is false — the pyramid's entire premise is about the cost imposed on attacker behaviour, which very much affects them.",
        xp: 15,
      },
      {
        id: "th_06",
        question: "In threat hunting, what is a 'baseline' used for anomaly detection?",
        options: [
          "A documented picture of what normal looks like for a host or user, against which deviations can be measured and investigated.",
          "A fixed list of every IOC an organisation has ever observed, refreshed once per year during audit season.",
          "A single alert threshold configured once in the SIEM and never revisited regardless of environment changes.",
          "A snapshot of the network taken immediately after a confirmed breach, used only for post-incident reporting.",
        ],
        answer: 0,
        explanation: "A baseline is a working definition of 'normal' — typical logon times, typical process lineage, typical data volumes — against which deviations become detectable anomalies. Option B describes a static IOC list, not a behavioural baseline, and IOC lists go stale in days, not years. Option C describes a single alert rule, which is a detection, not a baseline of normal behaviour. Option D describes a post-incident snapshot, which reflects an abnormal state, not the normal one a baseline is meant to capture.",
        xp: 10,
      },
      {
        id: "th_07",
        question: "Stacking process execution across 5,000 endpoints, you find powershell.exe running with an unusual argument set on exactly one host, while a broadly deployed backup agent runs identically on all 5,000. Which is more hunt-worthy?",
        options: [
          "The single-host PowerShell execution, because rarity across a large population is itself a strong anomaly signal worth investigating.",
          "The backup agent, because software present on every single endpoint always indicates the widest possible compromise.",
          "Neither is worth investigating, since frequency analysis only applies to network traffic, not process execution.",
          "Both are equally suspicious, because rarity and ubiquity carry exactly the same weight in frequency analysis.",
        ],
        answer: 0,
        explanation: "Rarity across a large, mostly-uniform population is a core hunting signal: something running on one host out of five thousand stands out precisely because almost nothing else in the environment does it. The broadly deployed backup agent is the opposite case — ubiquity across the fleet is what you'd expect from sanctioned software, not evidence of compromise. Option C wrongly limits frequency analysis to network data; it applies just as well to process, parent-child, and command-line data. Option D flattens rarity and ubiquity into equal risk, which defeats the entire point of stacking analysis.",
        xp: 15,
      },
      {
        id: "th_08",
        question: "What makes rare domain analysis in DNS logs a useful hunting technique?",
        options: [
          "A newly-registered or rarely-queried domain contacted by only a handful of hosts stands out against the bulk of DNS traffic to common, long-established domains.",
          "Domains queried by every host in the environment are the most suspicious, since malware always targets the entire fleet at once.",
          "DNS traffic cannot be baselined for rarity, because domain names change too frequently for frequency analysis to work.",
          "Only domains with no resolvable IP address deserve investigation; domains that resolve successfully are inherently safe.",
        ],
        answer: 0,
        explanation: "Most legitimate DNS traffic clusters around a small set of well-established domains queried by many hosts; a domain that's brand-new or contacted by only a few machines breaks that pattern and warrants a closer look. Option B inverts the logic — domains queried fleet-wide are usually common infrastructure or advertising, not malware, which typically touches a small number of infected hosts. Option C is false; DNS is one of the most commonly baselined and stacked data sources in hunting. Option D ignores that malicious domains resolve successfully all the time — successful resolution says nothing about intent.",
        xp: 15,
      },
      {
        id: "th_09",
        question: "What does 'stacking' (frequency analysis) mean in a threat hunt?",
        options: [
          "Counting how often a value — a process, domain, or parent-child pair — occurs across a population, then examining the outliers at either end.",
          "Comparing the file size of every binary on disk against a hash reputation database updated hourly by the vendor.",
          "Correlating timestamps across three different log sources to reconstruct the precise order of an attacker's actions.",
          "Reviewing a single host in isolation without reference to how the rest of the environment behaves, host by host.",
        ],
        answer: 0,
        explanation: "Stacking counts occurrences of a value across a population and surfaces the outliers — both the rare ones and, sometimes, unexpectedly common ones — for closer review. Option B describes hash reputation lookups, a different technique entirely. Option C describes timeline correlation, useful in investigation but not what stacking measures. Option D describes single-host review with no population comparison, which is the opposite of what stacking does — stacking's value comes from comparing across many hosts.",
        xp: 10,
      },
      {
        id: "th_10",
        question: "What is 'long-tail analysis' in threat hunting?",
        options: [
          "Focusing on the least-frequent values in a dataset — the 'tail' of the distribution — where rare and potentially malicious activity often hides.",
          "Focusing on the most-frequent values in a dataset, since common activity is statistically more likely to be malicious.",
          "Analysing only the most recent 24 hours of logs, discarding anything older as no longer operationally relevant.",
          "Reviewing logs in strict chronological order from oldest to newest without any statistical filtering applied.",
        ],
        answer: 0,
        explanation: "Long-tail analysis deliberately looks at the sparse, infrequent end of a distribution, because malicious activity is usually rare relative to the bulk of routine, common behaviour. Option B inverts this — focusing on the most common values would surface routine software and normal user behaviour, not anomalies. Option C describes a time-window filter, unrelated to distribution shape. Option D describes plain chronological log review with no statistical reasoning applied at all.",
        xp: 10,
      },
      {
        id: "th_11",
        question: "A hunter spends a week testing a hypothesis and finds no matching activity anywhere in the environment. Was the hunt worth doing?",
        options: [
          "Yes — a documented negative result confirms detection coverage for that hypothesis and closes a gap in visibility.",
          "No — a hunt that finds no threat should not be documented or reported to anyone.",
          "No — it proves the hypothesis was wrong and should never be tested again by any hunter.",
          "No — it means the data source used was faulty and must be replaced before any further hunting.",
        ],
        answer: 0,
        explanation: "A hunt that finds nothing is not wasted — documenting that a hypothesis was tested and no matching activity was found confirms detection coverage for that scenario and can be cited later as evidence the environment was checked. Option B discards that value and treats a negative result as unworthy of record, which undermines the whole point of tracking coverage. Option C overstates the conclusion — a negative result for one time window doesn't mean the hypothesis is permanently invalid; conditions change. Option D wrongly assumes a negative result always implies a data problem, when it may simply mean the activity genuinely wasn't present.",
        xp: 15,
      },
      {
        id: "th_12",
        question: "A hunter manually uncovers a novel lateral movement technique using a legitimate admin tool. What should happen next to get lasting value from this?",
        options: [
          "Translate the manual query into an automated detection rule so future occurrences trigger an alert without repeating the manual hunt.",
          "Delete the hunting notes once the report is filed, since a one-time finding has no further operational use.",
          "Keep the finding as a manual quarterly check performed by the same hunter, without ever automating it.",
          "Forward the finding only to the vendor's support team and take no internal action within the SOC.",
        ],
        answer: 0,
        explanation: "The whole value of a hunting program compounds when a manual finding becomes an automated detection — the SOC gets ongoing coverage instead of a one-time discovery that only exists in someone's memory or a report. Option B throws away the institutional knowledge the hunt produced. Option C keeps the coverage manual and analyst-dependent indefinitely, which doesn't scale and depends on one person remembering to repeat it. Option D routes internal findings externally instead of using them to strengthen the SOC's own detection stack.",
        xp: 15,
      },
      {
        id: "th_13",
        question: "How does a threat hunting maturity model generally describe progression?",
        options: [
          "Maturity progresses from ad-hoc, manual searches with minimal data, toward repeatable, largely automated hunting fed by rich, well-instrumented telemetry.",
          "Maturity is measured only by the number of external threat intelligence feeds an organisation subscribes to and pays for.",
          "Maturity means every hunt must be performed entirely by hand, since automation is considered a sign of low sophistication.",
          "Maturity has a single fixed level; an organisation either has a hunting program or does not, with nothing in between.",
        ],
        answer: 0,
        explanation: "Hunting maturity models (like the well-known HMM) track a progression: from minimal, ad-hoc, mostly manual hunting with limited data, up through repeatable processes, to advanced programs with rich, automated telemetry supporting frequent, structured hunts. Option B reduces maturity to a single input (intel feed count), ignoring process and telemetry entirely. Option C gets the direction backwards — mature programs automate what they can precisely so hunters spend their time on judgement, not repetitive manual queries. Option D flattens a genuine spectrum into a binary that doesn't reflect how real programs actually develop.",
        xp: 15,
      },
      {
        id: "th_14",
        question: "Which set of metrics best reflects a mature threat hunting program?",
        options: [
          "Coverage gaps closed, hypotheses tested, findings converted into detections, and dwell time reduced by hunts.",
          "Total number of alerts generated by the SIEM in a month, regardless of whether any alert relates to a hunt.",
          "Number of hunters employed by the team, independent of any hypothesis tested or finding produced.",
          "Total storage consumed by log retention, since larger log volumes are assumed to reflect hunting maturity.",
        ],
        answer: 0,
        explanation: "Useful hunting metrics track outcomes that matter: gaps in detection coverage that were closed, how many hypotheses were actually tested, how many findings became lasting detections, and any measurable reduction in dwell time. Option B counts alert volume, which reflects the SIEM's tuning, not the hunting program's output. Option C counts headcount, which says nothing about whether any hunting actually happened or produced value. Option D conflates storage spend with maturity, when a program could retain huge volumes of data and still never hunt through it effectively.",
        xp: 20,
      },
    ],
  },
  {
    slug: "soc-decision-making",
    title: "SOC Decision Making — Escalate, Close, or Dig Deeper",
    description: "The professional judgement calls of a SOC shift — when to escalate, close, isolate, or block, what counts as enough evidence, and how severity is actually determined.",
    difficulty: "Intermediate",
    category: "SOC Operations",
    icon: "🚦",
    estimatedMinutes: 15,
    questions: [
      {
        id: "dm_01",
        question: "You are a Tier 1 analyst. An alert shows a domain admin account authenticating successfully from a country where the organisation has no staff, offices, or VPN egress point. What should you do?",
        options: [
          "Escalate to Tier 2 — a privileged account authenticating from an impossible location needs deeper investigation than Tier 1 can complete alone.",
          "Close the alert as a false positive, since successful authentication proves the credentials were entered correctly.",
          "Wait for the account to perform a second suspicious action before taking any investigative steps at all.",
          "Reset the account password yourself without informing anyone, then close the ticket as resolved.",
        ],
        answer: 0,
        explanation: "A privileged account authenticating successfully from a location with no legitimate business reason is exactly the kind of finding Tier 1 should hand up — the investigation likely needs deeper access, tooling, or authority than Tier 1 holds. Option B wrongly treats 'successful' as synonymous with 'legitimate' — attackers authenticate successfully too, that's the point of using valid credentials. Option C delays action while a privileged account may already be active in the environment, which trades away valuable response time. Option D takes containment action unilaterally and without documentation or handover, bypassing the process that makes incidents defensible and traceable.",
        xp: 15,
      },
      {
        id: "dm_02",
        question: "A vulnerability scanner triggers an IDS alert for 'SQL injection attempt' against a web server, at the exact time your change log shows the internal vulnerability management team ran an authorised scan against that server. How should you close this?",
        options: [
          "Close as a false positive, and document the scanner's source IP, the scan window, and the change ticket that authorised it.",
          "Close as a true positive, since any SQL injection payload observed on the wire is malicious regardless of its source.",
          "Escalate to Tier 3 without documentation, since scanner traffic always requires senior analyst review.",
          "Leave the alert open indefinitely, since a scan and an attack cannot be told apart from network traffic alone.",
        ],
        answer: 0,
        explanation: "This is a textbook false positive with a verifiable, documented cause — closing it with the source IP, time window, and change ticket referenced means anyone reviewing later can see exactly why it was closed. Option B ignores the authorised context entirely and treats sanctioned scanning as an attack. Option C escalates without adding any documentation, which pushes an already-explained alert onto someone else instead of resolving it. Option D leaves a fully explainable alert open indefinitely, which clutters the queue and provides no closure reasoning for the next analyst who sees it.",
        xp: 10,
      },
      {
        id: "dm_03",
        question: "An alert fires for 'mass file access' on a file server. You see the user account and file count, but not which files were accessed, whether they were copied elsewhere, or the account's normal access pattern. What should you do before deciding?",
        options: [
          "Pull the missing context — file paths, destination of any copy or transfer, and the account's baseline — before making a verdict.",
          "Close the alert immediately, since file access by an authenticated account is expected behaviour by default.",
          "Escalate to the CISO directly, since any alert lacking full context always qualifies as a confirmed breach.",
          "Guess the most likely explanation and record it as the verdict, since gathering more data takes too long.",
        ],
        answer: 0,
        explanation: "Before rendering a verdict, the analyst needs to close the gaps that actually determine impact — what was touched, whether anything left the environment, and whether the volume is normal for that account. Option B closes prematurely on an assumption that hasn't been checked. Option C escalates as a confirmed breach without evidence, which is just as unjustified as closing without evidence — missing context isn't proof of anything. Option D substitutes a guess for the missing data, which produces a verdict that can't be defended if questioned later.",
        xp: 15,
      },
      {
        id: "dm_04",
        question: "A new alert lands in your queue. Before anything else, what should you check first?",
        options: [
          "What the alert actually detected and which asset, user, and rule triggered it — the raw facts before any interpretation.",
          "Whether the analyst who wrote the detection rule is currently on shift and available to consult.",
          "How many other unrelated alerts are currently open across the entire SOC queue at that moment.",
          "Whether the affected asset appears anywhere in the company's public-facing marketing materials.",
        ],
        answer: 0,
        explanation: "The starting point of any triage is establishing the raw facts — what the alert says was detected, which rule fired, and which asset and user are involved — because every subsequent decision depends on getting that baseline right. Option B makes the investigation depend on a specific person's availability rather than the alert's own facts. Option C is queue management, not analysis of this particular alert. Option D has no bearing on whether the underlying activity is malicious.",
        xp: 10,
      },
      {
        id: "dm_05",
        question: "An EDR alert shows a suspicious PowerShell command on a workstation, but you don't yet know whether it succeeded, what it connected to, or whether other hosts show the same command. What is the best next step?",
        options: [
          "Pivot to the process tree and network connections for that host, then search the same command across the wider fleet.",
          "Immediately notify the regulator, since any PowerShell execution alert is defined as a reportable breach.",
          "Close the alert, since PowerShell is a legitimate administrative tool present on every managed workstation.",
          "Wait for a second, unrelated alert to fire before taking any further investigative action on this host.",
        ],
        answer: 0,
        explanation: "The next logical step is to pull more context that's directly relevant to what's still unknown — what the process actually touched and whether the same pattern shows up elsewhere — before deciding severity or scope. Option B jumps to a regulatory conclusion far ahead of the evidence; not every suspicious command execution is a reportable breach. Option C closes based on PowerShell's legitimate uses in general, ignoring the specific suspicious command observed. Option D makes this alert's investigation depend on an unrelated one, which isn't a valid reason to pause.",
        xp: 15,
      },
      {
        id: "dm_06",
        question: "EDR confirms a workstation executed a known ransomware binary and is actively encrypting files on a mapped network share. What should you do regarding the host?",
        options: [
          "Isolate the host from the network immediately to stop the encryption from spreading, then continue investigating.",
          "Leave the host connected so you can keep watching its behaviour before taking any containment action at all.",
          "Power the host off completely, since isolation only works for network-based threats, not for ransomware.",
          "Wait for written approval from the asset owner before isolating, even while the encryption continues to spread.",
        ],
        answer: 0,
        explanation: "Active, confirmed ransomware encryption is a rare case where the cost of continued spread clearly outweighs the value of more observation — isolating the host stops the bleeding while the investigation continues in parallel. Option B keeps the host connected while files keep encrypting, trading containment for observation it doesn't need. Option C conflates isolation with power-off; isolation (network containment) is usually preferred because it preserves volatile evidence that powering off can destroy. Option D adds an approval delay that isn't appropriate for an active, confirmed, spreading threat — this is the scenario isolation authority exists for.",
        xp: 15,
      },
      {
        id: "dm_07",
        question: "You want to block an external IP that appeared in a brute-force alert. Before adding the block, what should you check first?",
        options: [
          "Whether the IP belongs to a shared resource like a CDN, cloud load balancer, or corporate NAT gateway that would also block legitimate traffic.",
          "Whether the IP address has an easy-to-remember hostname, since memorable hostnames are more likely to belong to attackers.",
          "Whether the IP is located in the same country as company headquarters, since local IPs are always safe to leave open.",
          "Whether blocking the IP will improve the SOC's monthly ticket-closure metrics, since metrics guide containment decisions.",
        ],
        answer: 0,
        explanation: "Blocking an IP that actually serves as a CDN edge, a cloud load balancer, or a NAT gateway can silently cut off large numbers of unrelated, legitimate users who happen to share that address — so verifying what the IP actually is comes before adding the block. Option B judges risk by how memorable the hostname is, which has no bearing on whether the IP is malicious or shared. Option C assumes geography determines safety, which ignores that attackers routinely operate from, or route through, any country including the target's own. Option D lets an internal metric drive a containment decision instead of the actual risk of collateral impact.",
        xp: 15,
      },
      {
        id: "dm_08",
        question: "You block an IP tied to a brute-force alert. Within minutes, dozens of legitimate customers report they can no longer reach the company's website. What most likely happened?",
        options: [
          "The blocked IP belonged to a shared CDN or NAT gateway, so the block also cut off unrelated legitimate traffic passing through it.",
          "The brute-force attacker retaliated by launching a denial-of-service attack against the company's own customers.",
          "The website's certificate expired at the same moment, which is an unrelated coincidence with no connection to the block.",
          "The customers' own internet service providers experienced an outage that happened to align with the block.",
        ],
        answer: 0,
        explanation: "This is the classic collateral-damage failure mode of IP blocking: many customers reaching the site through the same shared CDN or NAT egress point means blocking that one IP silently blocks all of them, not just the attacker. Option B invents a retaliation scenario with no evidence connecting the attacker to a new attack. Option C introduces an unrelated technical failure that coincidentally lines up with the block, which is a much less likely explanation than the block itself. Option D blames an external, unrelated outage instead of the action the analyst just took, when the timing points directly at the block.",
        xp: 15,
      },
      {
        id: "dm_09",
        question: "You find a server's configuration was changed outside the documented change window, but the logs alone can't tell you whether it was an authorised emergency change or unauthorised tampering. What should you do?",
        options: [
          "Contact the system owner directly to confirm whether the change was authorised, since only they can close that gap in the evidence.",
          "Assume the change was authorised, since unexplained configuration changes are rarely worth confirming with anyone.",
          "Assume the change was malicious, and immediately wipe and reimage the server without any further confirmation.",
          "Ignore the change entirely, since configuration changes fall outside the scope of any SOC investigation.",
        ],
        answer: 0,
        explanation: "When logs alone can't distinguish an authorised emergency change from tampering, the system owner is the only source who can close that specific gap, so contacting them is the correct next step before acting further. Option B assumes the best case without confirming it, which risks missing real unauthorised activity. Option C assumes the worst case and takes a costly, disruptive action before confirming anything, which risks unnecessary downtime if the change was legitimate. Option D drops a real anomaly instead of resolving the uncertainty around it.",
        xp: 15,
      },
      {
        id: "dm_10",
        question: "What generally counts as sufficient evidence to escalate an alert as a confirmed incident, rather than closing it?",
        options: [
          "Corroborating evidence from at least one independent source — such as EDR plus authentication logs — that supports the same conclusion.",
          "A single alert from one tool, since modern detection products are tuned to never produce a false positive.",
          "A gut feeling that something looks unusual, even when every log source reviewed shows normal activity.",
          "The seniority of the analyst reviewing the alert, since more experienced analysts require less supporting evidence.",
        ],
        answer: 0,
        explanation: "Sufficient evidence generally means independent corroboration — two or more unrelated sources telling the same story make a false positive far less likely than any single source alone. Option B treats one tool's output as infallible, which ignores that every detection product produces false positives. Option C substitutes intuition for evidence when every log actually reviewed points the other way. Option D makes the verdict depend on who's reviewing rather than what the evidence shows, which isn't a repeatable or defensible standard.",
        xp: 10,
      },
      {
        id: "dm_11",
        question: "How should severity for a confirmed incident be determined?",
        options: [
          "By combining asset criticality, scope of impact, confidence in the detection, and sensitivity of the data involved.",
          "By whatever number the SIEM's built-in alert severity field displays, without any additional analyst judgement.",
          "By how many people are currently on shift, since a fuller SOC roster justifies rating incidents more severely.",
          "By the order alerts arrived in the queue, since the first alert of the day is always treated as most severe.",
        ],
        answer: 0,
        explanation: "Severity should reflect how critical the affected asset is, how far the impact has spread, how confident the analyst is in the detection, and how sensitive the data involved is — combining these gives a reasoned, defensible rating. Option B outsources judgement entirely to a vendor-assigned default, which often doesn't reflect the specific asset or context involved. Option C ties severity to staffing levels, which has nothing to do with the actual risk of the incident. Option D ties severity to queue order, which is an artefact of timing, not a measure of impact.",
        xp: 15,
      },
      {
        id: "dm_12",
        question: "Compare two confirmed incidents: (1) a phishing email opened but not clicked, on a receptionist's low-privilege workstation, and (2) a successful login with a stolen credential to a domain controller holding the company's identity data. Which is higher severity, and why?",
        options: [
          "Incident 2 — the asset is more critical, the potential blast radius is far larger, and the data exposed is more sensitive.",
          "Incident 1 — phishing emails are always rated higher severity than credential-based logons, regardless of the target.",
          "Both are equal severity, since every confirmed incident is assigned the same default rating until closed.",
          "Incident 1 — the receptionist's workstation is a more visible target, so it always carries higher business risk.",
        ],
        answer: 0,
        explanation: "Incident 2 scores higher on every factor that matters: the domain controller is far more critical, a successful logon with valid-looking credentials has a much larger potential blast radius, and identity data is highly sensitive — while incident 1 involves a low-privilege asset and no evidence the payload executed. Option B applies a fixed rule based on alert type alone, ignoring the actual assets and impact involved in each case. Option C treats severity as a formality assigned identically to everything, which defeats the purpose of triage. Option D reasons from visibility rather than actual business risk, and a receptionist's workstation is not inherently higher risk than a domain controller.",
        xp: 20,
      },
      {
        id: "dm_13",
        question: "A junior analyst closes an alert with the note 'looks fine.' What is the problem with this closure?",
        options: [
          "It gives no reasoning or evidence — a proper closure should state what was checked and why it's benign, so it can be reviewed later.",
          "There is no problem, since a short note saves time and every analyst is trusted to be right by default.",
          "The problem is only that the note is too short in character count, not that it lacks investigative reasoning.",
          "The problem is that 'looks fine' should have been written in uppercase to signal a confirmed false positive.",
        ],
        answer: 0,
        explanation: "A defensible closure states what was checked and why the evidence supports a benign verdict, so another analyst — or an auditor — can follow the reasoning later without re-doing the work. Option B accepts unsupported trust as a substitute for documented reasoning, which breaks down the moment a closure needs to be reviewed. Option C treats the issue as one of length rather than substance — a longer note with the same lack of reasoning would have exactly the same problem. Option D focuses on formatting instead of the actual missing content, which doesn't address the underlying issue at all.",
        xp: 10,
      },
      {
        id: "dm_14",
        question: "You've gathered context on an alert and it looks suspicious, but you lack the access or tooling to pull memory forensics from the host yourself. What should you do?",
        options: [
          "Escalate to a tier or team with the right access and tooling, and hand over everything you've already gathered.",
          "Keep investigating alone until you personally acquire the missing access, however long that takes to arrange.",
          "Close the alert as inconclusive, since a lack of personal access means no further investigation is possible.",
          "Guess the outcome from the context alone and record it as fact, since memory forensics rarely changes a verdict.",
        ],
        answer: 0,
        explanation: "Recognising the limits of your own access and tooling, then escalating with the context already gathered, keeps the investigation moving without duplicating work or losing time arranging access that another tier already has. Option B delays the investigation indefinitely while access is arranged, when handing off is faster and just as effective. Option C treats a personal access limitation as an investigative dead end, when it's actually just a handoff point. Option D substitutes a guess for the missing forensic evidence, which is exactly the kind of unsupported verdict proper escalation is meant to avoid.",
        xp: 15,
      },
    ],
  },
];
