// ─── Quiz Data: Detection Engineering, Vulnerability Management, AppSec, Ops ──
// Four quizzes closing measured coverage gaps. Same contract as ./data.ts.

import type { Quiz } from "./data";

export const QUIZZES_DETECTION_APPSEC: Quiz[] = [

  // ── 1. Detection Engineering & Rule Writing ───────────────────────────────
  {
    slug: "detection-engineering",
    title: "Detection Engineering & Rule Writing",
    description: "Write rules that survive contact with a real SOC — precision versus recall, behavioural logic over brittle IOCs, honest tuning, and ATT&CK coverage you can prove.",
    difficulty: "Advanced",
    category: "SIEM",
    icon: "🎯",
    estimatedMinutes: 15,
    questions: [
      {
        id: "de_01",
        question: "A detection rule catches 9 of the 10 real intrusions in a test window, but 92% of the alerts it raises turn out to be benign. In detection terms, what is the problem?",
        options: [
          "Low recall — the rule misses most of the real intrusions it sees",
          "Low precision — most alerts it raises are not intrusions",
          "Low fidelity in the log source that feeds the rule",
          "Low coverage of the ATT&CK techniques in scope",
        ],
        answer: 1,
        explanation: "Precision = true positives ÷ all alerts raised. At 8% precision the rule is drowning analysts. Recall describes the opposite failure and is actually fine here — it caught 9 of 10. Log fidelity is not implicated: the rule matches exactly what it was told to match, the logic is just too broad. Coverage describes how many techniques you can detect at all, not how noisy one rule is.",
        xp: 15,
      },
      {
        id: "de_02",
        question: "Which statement best describes the real cost difference between a false negative and a false positive in a SOC?",
        options: [
          "A false negative costs analyst hours, while a false positive costs a breach",
          "Both cost the same, since every alert consumes one full triage cycle",
          "A false positive costs analyst hours; a false negative costs a breach",
          "Neither carries real cost once the rule is documented and approved",
        ],
        answer: 2,
        explanation: "A false positive is a real alert that was not a threat — it burns triage time. A false negative is an intrusion nobody saw — it costs an incident. Swapping the two around, so the negative burns hours and the positive causes the breach, is the most common mix-up in this topic. Claiming equal cost fails because a false negative generates no alert and therefore no triage cycle at all; its cost stays invisible until much later. And documentation changes nothing about either error rate.",
        xp: 10,
      },
      {
        id: "de_03",
        question: "Rule A alerts on a specific malware file hash. Rule B alerts on winword.exe spawning a child process that immediately makes an outbound connection. Why does Rule B survive longer against the same actor?",
        options: [
          "It queries more log sources, so it has more chances to fire",
          "Hash lookups are expensive and get disabled under load first",
          "Behavioural rules are exempt from the tuning process entirely",
          "It watches attacker behaviour, not one disposable artefact",
        ],
        answer: 3,
        explanation: "Rule B describes a step the actor must take to reach their objective — a document spawning a networked child. Changing that costs them tooling redesign, while Rule A dies the moment they recompile. The number of log sources a rule touches has no bearing on durability: a hash rule spanning ten sources is still dead after one recompile. The cost argument is a myth, since hash equality is trivially cheap to evaluate. And behavioural rules need more tuning, not less, precisely because they match on generic activity.",
        xp: 15,
      },
      {
        id: "de_04",
        question: "An EDR rule for 'unusual child process' fires dozens of times a day on a build server where msbuild.exe legitimately spawns compilers. Which tuning is the safer choice?",
        options: [
          "Suppress the rule for that host entirely, since it is a build server",
          "Suppress the rule when the parent is the known build binary",
          "Lower the rule severity to informational and stop reviewing those alerts",
          "Delete the rule and rely on the endpoint's default prevention policy",
        ],
        answer: 1,
        explanation: "Scoping the exception to the specific parent process keeps the rule alive for everything else on that host — if an attacker lands a web shell or a scheduled task there, you still see it. Excluding the whole host blinds you on an entire machine, and build servers are high-value targets holding signing keys and credentials. Dropping severity to informational is the same blindness dressed as tuning: an alert nobody reads is a suppressed alert. Deleting the rule gives up the detection and assumes prevention catches what detection was written for.",
        xp: 20,
      },
      {
        id: "de_05",
        question: "On the Pyramid of Pain, why is a file hash the weakest indicator to build detections on?",
        options: [
          "Hashes cannot be collected by most endpoint agents in real time",
          "Hash values are too long to index efficiently in a SIEM backend",
          "An attacker changes it by recompiling or padding a single byte",
          "Hashes are only produced for executables, never scripts or documents",
        ],
        answer: 2,
        explanation: "Hashes sit at the base of the pyramid because they are trivially and automatically variable — one byte of padding produces a new value at zero cost to the adversary. TTPs sit at the apex because changing those means changing how the actor operates. Hashing on execution is a standard EDR capability, so collection is not the barrier. Hashes are fixed-length and index perfectly well. And any file can be hashed, including scripts, documents and archives.",
        xp: 10,
      },
      {
        id: "de_06",
        question: "What is the main reason a mature team keeps detection content in version control with automated tests?",
        options: [
          "It lets the SIEM compress rule storage and run searches faster",
          "It removes the need to tune rules once they reach production",
          "It converts vendor rules into a format auditors are required to accept",
          "Every rule change is reviewable, revertible and regression-tested",
        ],
        answer: 3,
        explanation: "Detection-as-code treats rules as software: peer review before merge, a diff explaining why logic changed, and tests firing sample events so a 'small' edit cannot silently break a working detection. The storage answer confuses rule management with query engineering — the repository lives outside the SIEM and affects nothing about search speed. Version control makes tuning safer and more frequent rather than unnecessary. And no audit standard mandates a rule format, so the auditor claim is invented.",
        xp: 10,
      },
      {
        id: "de_07",
        question: "Before writing a rule on anomalous service-account logons, you are told to build a baseline. What are you actually building?",
        options: [
          "A list of every alert the SIEM has raised on those accounts in the last year",
          "A record of where, when and how often those accounts normally log on",
          "A copy of the AD group memberships held by each service account",
          "A threshold copied from the vendor's recommended default settings",
        ],
        answer: 1,
        explanation: "A baseline is an empirical description of normal, gathered over long enough to include month-end and quarter-end behaviour — which hosts each account touches, at which hours, at what frequency. Only then does 'anomalous' mean anything. Baselining past alerts measures your alerting rather than the environment, so it inherits every blind spot the current rules already have. Group memberships are useful context but static configuration, not observed behaviour. A vendor default is a guess about someone else's estate.",
        xp: 15,
      },
      {
        id: "de_08",
        question: "Why can a rule that fires 400 times a day be worse than having no rule at all?",
        options: [
          "The SIEM licence cost per event makes the rule financially unviable",
          "High-volume rules are automatically disabled by most SIEM platforms",
          "Analysts learn to close it unread — including the one real hit",
          "It overwrites older detections held in the correlation engine's memory",
        ],
        answer: 2,
        explanation: "With no rule you at least know you have a gap. With a 400-a-day rule you get a false sense of coverage plus a trained reflex to bulk-close, so the genuine detection is closed alongside the noise while the coverage report still shows a green tick. Licence cost is a real budget concern but not the issue: the rule fires on events already ingested. SIEMs do not disable rules for volume — they run whatever you deploy. And no correlation engine evicts old detections this way.",
        xp: 15,
      },
      {
        id: "de_09",
        question: "Which metric most directly exposes alert fatigue across a detection portfolio?",
        options: [
          "The total number of detection rules deployed in the SIEM",
          "The average size in bytes of the events matching each rule",
          "The number of ATT&CK techniques the rule set claims to cover",
          "The share of alerts closed as benign, tracked per rule",
        ],
        answer: 3,
        explanation: "Benign-close rate per rule turns fatigue from a feeling into a number, and it names the specific rules to fix. Rule count measures activity rather than quality — 900 rules can be far worse than 90. Event size measures volume and says nothing about whether analysts trust the output. Technique count measures breadth: a portfolio can map to 200 techniques and still be unusable if every rule is 95% noise.",
        xp: 10,
      },
      {
        id: "de_10",
        question: "Why do detection engineers map each deployed rule to an ATT&CK technique?",
        options: [
          "It shows which techniques currently have no detection at all",
          "It guarantees the rule will fire on every variant of that technique",
          "It allows the SIEM to auto-generate rules for adjacent techniques",
          "It replaces the need for a baseline, since ATT&CK defines what is normal",
        ],
        answer: 0,
        explanation: "Mapping produces a coverage matrix, and the value is in the empty cells — the techniques your adversaries use that nothing currently detects. Treating the label as a guarantee is the dangerous misreading: a mapping states intent, not completeness, and one rule rarely covers a whole technique. No SIEM auto-generates rules for adjacent techniques. And ATT&CK catalogues adversary behaviour, so it can never tell you what is normal in your estate — that still requires a baseline.",
        xp: 10,
      },
      {
        id: "de_11",
        question: "A rule reads: process_name = 'powershell.exe' AND command_line CONTAINS '-enc'. What is its biggest weakness as written?",
        options: [
          "PowerShell logging cannot record the command line of a process",
          "Admin tooling also uses encoded commands, so precision is poor",
          "The -enc flag is deprecated and no longer accepted by PowerShell",
          "Encoded commands are decoded by the SIEM before rules are evaluated",
        ],
        answer: 1,
        explanation: "Encoding is a legitimate way to pass quoting-hostile strings, so management agents, installers and scheduled jobs use it daily. Without a parent-process or user filter the rule alerts on all of it. Command-line capture is not the problem: Event ID 4688 with command-line auditing enabled, and Sysmon Event ID 1, both carry the full string. The -EncodedCommand parameter and its -enc abbreviation are current, not deprecated. And the SIEM stores the raw string — decoding is a step you have to add yourself.",
        xp: 20,
      },
      {
        id: "de_12",
        question: "You have two candidate rules for the same technique: a broad one with 30% precision, and a narrow one with 95% precision that catches roughly half as many cases. What is the sound design decision?",
        options: [
          "Ship only the narrow rule, because Tier 1 must never see noise",
          "Ship only the broad rule, because recall always beats precision",
          "Ship both, routing each to the queue its precision justifies",
          "Ship neither until a single rule reaches both 95% precision and full recall",
        ],
        answer: 2,
        explanation: "Precision determines destination, not existence. The 95% rule earns a Tier 1 page; the 30% rule is valuable hunting input and belongs in a hunt or enrichment queue where volume is expected. Shipping only the narrow rule throws away real recall to protect a queue the broad rule was never going to enter. Shipping only the broad rule puts 70% noise in front of Tier 1 and manufactures the fatigue that makes the other rule useless too. Waiting for a perfect rule is paralysis — it does not exist for any non-trivial technique.",
        xp: 20,
      },
    ],
  },

  // ── 2. Vulnerability Management for SOC ───────────────────────────────────
  {
    slug: "vulnerability-management",
    title: "Vulnerability Management for SOC",
    description: "CVE, CWE, CVSS, EPSS and KEV — what each one actually tells you, how to prioritise when everything is 'critical', and where the SOC's job ends and IT's begins.",
    difficulty: "Intermediate",
    category: "Vulnerability Management",
    icon: "🩹",
    estimatedMinutes: 14,
    questions: [
      {
        id: "vm_01",
        question: "Log4Shell is described by CVE-2021-44228, by CWE-917, and by a CVSS score of 10.0. What does the CVE identifier itself provide?",
        options: [
          "A numeric score expressing how severe the flaw is judged to be",
          "A category naming the class of coding weakness behind the flaw",
          "A unique reference to that one specific flaw in that product",
          "A probability that the flaw will be exploited in the next 30 days",
        ],
        answer: 2,
        explanation: "A CVE ID is a catalogue number — its only job is to let two tools mean the same flaw. The severity number is what CVSS supplies, 10.0 in this case. The weakness class is what the CWE supplies: CWE-917 is expression-language injection, a category shared by many unrelated CVEs. The 30-day exploitation probability is EPSS. All four describe Log4Shell, but only one of them is the identifier.",
        xp: 10,
      },
      {
        id: "vm_02",
        question: "An analyst writes in a ticket: 'the CVE of this vulnerability is 9.8'. What is wrong with that sentence?",
        options: [
          "9.8 is an EPSS score; CVE values only ever run from 1 to 5",
          "9.8 is a CVSS score; a CVE is an identifier, not a number",
          "Nothing — CVE and CVSS are two names for the same rating",
          "CVEs are scored 0-10 but only NIST may assign the value",
        ],
        answer: 1,
        explanation: "CVE and CVSS are different things that appear on the same finding: CVE-2021-44228 names the flaw, 9.8 or 10.0 rates it. The EPSS option is wrong twice, because EPSS is a probability between 0 and 1 and CVEs carry no score on any scale. Saying nothing is wrong is exactly the confusion the sentence exposes. The NIST option keeps the false premise that a CVE holds a number and misstates the process too — CVE IDs are issued by CNAs, and CVSS scores are published by several parties who sometimes disagree.",
        xp: 15,
      },
      {
        id: "vm_03",
        question: "Which CVSS metric group adjusts a score for your own asset's exposure and business impact?",
        options: [
          "Temporal",
          "Base",
          "Exploitability",
          "Environmental",
        ],
        answer: 3,
        explanation: "Environmental metrics let you re-score for your estate — confidentiality, integrity and availability requirements, plus modified base metrics reflecting your actual deployment. Temporal reflects the flaw's changing state over time, such as exploit maturity and remediation level, and is identical for everyone. Base is the intrinsic, context-free score published alongside the CVE. Exploitability is a sub-group inside Base covering attack vector, complexity and privileges required — not a group of its own.",
        xp: 10,
      },
      {
        id: "vm_04",
        question: "Under CVSS v3.1, a base score of 7.5 falls into which severity band?",
        options: [
          "Critical (9.0-10.0)",
          "Medium (4.0-6.9)",
          "High (7.0-8.9)",
          "Low (0.1-3.9)",
        ],
        answer: 2,
        explanation: "The v3.1 qualitative bands are None at 0.0, Low 0.1-3.9, Medium 4.0-6.9, High 7.0-8.9 and Critical 9.0-10.0, so 7.5 is High. Every option here states the correct range for its own label — the trap is the habit of calling anything above 7 'critical' in a ticket, which inflates reports and destroys the meaning of the top band when a genuine 9.8 arrives.",
        xp: 10,
      },
      {
        id: "vm_05",
        question: "Why is the CVSS base score a poor sole input for deciding what to patch first?",
        options: [
          "It is recalculated weekly, so the number is never stable enough",
          "It applies only to network flaws and not to local or physical ones",
          "It is vendor-supplied, so two vendors never agree on the same flaw",
          "It ignores whether the flaw is actually being exploited anywhere",
        ],
        answer: 3,
        explanation: "Base is a static description of worst-case technical impact. It knows nothing about exploit availability, your asset's exposure or your compensating controls, which is why an estate full of 9.8s cannot be ranked by it. The base score is deliberately stable — it is the temporal group that moves over time. Attack vector explicitly includes local and physical, so it is not network-only. Scoring disagreements do happen, but the real problem is what the score omits rather than who published it.",
        xp: 15,
      },
      {
        id: "vm_06",
        question: "A finding appears on the CISA Known Exploited Vulnerabilities (KEV) catalogue. What does that tell you?",
        options: [
          "It scored above 9.0 on CVSS and was reclassified as critical",
          "It has been seen exploited in the wild — patch it first",
          "It affects software that CISA has designated as federal-only",
          "Its exploit code was published but never seen used in attacks",
        ],
        answer: 1,
        explanation: "KEV listing is evidence of confirmed in-the-wild exploitation, which makes it one of the strongest prioritisation signals available. Entries are not selected by CVSS, and plenty of listed flaws score in the sevens. The catalogue is public and covers commodity software everyone runs, even though the remediation deadlines bind only US federal agencies. And published-but-unused exploit code is precisely what does not qualify for KEV — observed use is the entry criterion.",
        xp: 10,
      },
      {
        id: "vm_07",
        question: "A vulnerability has an EPSS score of 0.94. What does that number mean?",
        options: [
          "A severity of 9.4 out of 10 on the standard CVSS scale",
          "94% of scanned hosts in your estate carry this vulnerability",
          "A 94% chance of exploitation activity in the next 30 days",
          "The patch has been available for 94 days without being applied",
        ],
        answer: 2,
        explanation: "EPSS is a probability from 0 to 1 that a flaw will see exploitation activity in the next 30 days, derived from observed attack telemetry and vulnerability characteristics. Rescaling it into a CVSS-looking 9.4 is the usual mistake: the two scales measure different things and are not interchangeable. Host prevalence comes from your own scanner, not from EPSS. Patch age is an internal SLA metric that no external feed can know.",
        xp: 15,
      },
      {
        id: "vm_08",
        question: "An unauthenticated scan of a server reports 12 findings. An authenticated scan of the same server, run the same day, reports 340. Why the difference?",
        options: [
          "Unauthenticated scans can only run against Windows hosts, never Linux",
          "The credentialed scan counts each affected file as a separate finding",
          "Authenticated scans include findings from every other host in the subnet",
          "Credentialed scans see installed patch levels, not just open ports",
        ],
        answer: 3,
        explanation: "Without credentials the scanner infers from outside — banners, open ports, service responses — so it sees only network-reachable surface and guesses at versions. With credentials it reads the installed package and patch inventory directly, exposing every unpatched local component. Unauthenticated scanning is OS-agnostic and works fine against Linux. Scanners report one finding per vulnerable component, not per file. And a scan reports on its target host; subnet-wide results come from a different scan job.",
        xp: 15,
      },
      {
        id: "vm_09",
        question: "A scanner flags Log4Shell (CVE-2021-44228) on a Windows application server, and the app team insists it is a false positive. What is the sound way to settle it?",
        options: [
          "Re-run the identical scan and see whether the finding appears again",
          "Check the actual log4j-core jar version present on the host",
          "Compare the CVSS score against the vendor's published advisory",
          "Ask the asset owner whether the application has ever been patched",
        ],
        answer: 1,
        explanation: "Confirmation means going to ground truth: locate the library on disk, read its version, and check whether it falls inside the affected range. Re-running the same scan repeats the same inference and reproduces the same false positive with equal confidence. Comparing CVSS tells you how bad the flaw would be if present, which is not the point in dispute. Asking the owner substitutes recollection for evidence — and it is the same recollection that produced the disagreement.",
        xp: 20,
      },
      {
        id: "vm_10",
        question: "A critical, KEV-listed flaw affects a clinical device whose vendor will not ship a fix for nine months. What is the correct next step?",
        options: [
          "Accept the risk silently, since no patch exists to apply anyway",
          "Take the device offline until the vendor ships fixed firmware",
          "Segment and monitor the device, and record the risk decision",
          "Downgrade the finding to low because it cannot be remediated",
        ],
        answer: 2,
        explanation: "When patching is unavailable you apply compensating controls — network segmentation, restricted inbound access, targeted detection on that device's traffic — and you write the residual risk down with an owner and a review date. Accepting silently skips the documentation, which is the part that makes acceptance a decision rather than an oversight. Pulling a clinical device offline trades a security risk for a patient-safety risk and is rarely the SOC's call. Downgrading is the worst outcome: the risk is unchanged and now nobody tracks it.",
        xp: 20,
      },
      {
        id: "vm_11",
        question: "In most organisations, what is the SOC's role in vulnerability remediation?",
        options: [
          "Prioritise and verify, while IT owns the patching itself",
          "Deploy the patches directly to every affected production host",
          "Approve change windows and sign off on downtime with the business",
          "Own the entire lifecycle from discovery through to patch rollout",
        ],
        answer: 0,
        explanation: "The SOC supplies threat context — what is exploited, what is exposed, what matters — then verifies remediation by re-scanning and by watching for exploitation of whatever remains open. Deploying patches puts operational change in the hands of a monitoring function with neither the tooling nor the rollback authority. Approving change windows and downtime belongs to change management and the service owner. Owning the whole lifecycle collapses the separation that keeps the verifier independent of the remediator.",
        xp: 10,
      },
    ],
  },

  // ── 3. Web Application Attacks & WAF ──────────────────────────────────────
  {
    slug: "web-application-security",
    title: "Web Application Attacks & WAF",
    description: "Read a web attack from the access log up — injection, XSS, traversal, SSRF and web shells — and learn what a WAF verdict does and does not tell you.",
    difficulty: "Advanced",
    category: "Application Security",
    icon: "🕸️",
    estimatedMinutes: 15,
    questions: [
      {
        id: "wa_01",
        question: "What is the OWASP Top 10?",
        options: [
          "A ranked list of the most critical web application risk categories",
          "A certification standard that a web application must pass before deploying",
          "A catalogue of the ten most exploited CVEs published each quarter",
          "A set of ten WAF rules every commercial vendor ships by default",
        ],
        answer: 0,
        explanation: "The Top 10 is an awareness document listing broad risk categories — broken access control, injection, security misconfiguration and so on — derived from contributed application data. It certifies nothing and confers no pass or fail; the OWASP ASVS is the verification standard people are reaching for there. Calling it a CVE list confuses risk categories with individual vulnerabilities, since a single entry covers thousands of CVEs. And it is vendor-neutral, defining no rules of its own.",
        xp: 10,
      },
      {
        id: "wa_02",
        question: "A web access log shows: GET /product?id=7%20UNION%20SELECT%20null,version()-- HTTP/1.1. What is this?",
        options: [
          "Blind SQL injection inferring data one boolean condition at a time",
          "Reflected XSS attempting to run script in the responding page",
          "Path traversal trying to reach a file outside the web root",
          "Union-based SQL injection probing the column count and DB version",
        ],
        answer: 3,
        explanation: "UNION SELECT appends a second result set to the original query so the output appears in the page — the null is the attacker matching column counts, and version() is the classic first thing to read back. Blind injection is excluded precisely because nothing is returned directly there: it asks true/false questions and reads the difference in the response. Reflected XSS needs script or an event handler, not SQL keywords. Path traversal needs directory sequences such as ../ in a file parameter.",
        xp: 15,
      },
      {
        id: "wa_03",
        question: "Which request signature points to time-based blind SQL injection?",
        options: [
          "A parameter containing <img src=x onerror=alert(1)> in the query",
          "A request with ../../../../etc/passwd appended to the file path",
          "A parameter containing SLEEP(5) with a response ~5 seconds slow",
          "A request whose User-Agent string is longer than 4096 characters",
        ],
        answer: 2,
        explanation: "When the app returns no data and no distinguishable error, the attacker makes the database itself the output channel: if the injected condition is true, sleep — and response latency carries one bit per request. The onerror handler is an XSS payload. The traversal sequence targets the filesystem, not the database. An oversized User-Agent suggests a buffer or header-injection probe. The tell for time-based blind is always latency correlated with a delay function, never content in the response.",
        xp: 15,
      },
      {
        id: "wa_04",
        question: "Why is DOM-based XSS often completely invisible in web server access logs?",
        options: [
          "The payload is encrypted by TLS and cannot be recorded by the web server",
          "The payload can sit in the fragment, which is never sent to the server",
          "The browser strips all script tags before the request leaves the client",
          "The server records only POST bodies, and DOM XSS always uses GET",
        ],
        answer: 1,
        explanation: "DOM XSS executes entirely in client-side JavaScript, and the payload frequently rides in the URL fragment after the # — which browsers never transmit. The server logs an ordinary page request. TLS terminates at the server, which logs the decrypted request line, so encryption is not the reason. Browsers do not sanitise outbound requests. And access logs record the request line rather than POST bodies, while DOM XSS is not restricted to GET in the first place.",
        xp: 15,
      },
      {
        id: "wa_05",
        question: "What distinguishes stored XSS from reflected XSS?",
        options: [
          "The payload runs only in the browser of the user who submitted it",
          "The payload is written into the URL fragment after the hash mark",
          "The payload targets the database engine rather than the browser",
          "The payload is stored server-side and served to later visitors",
        ],
        answer: 3,
        explanation: "Stored XSS persists in the application — a comment, a profile field, a support ticket — and fires for everyone who views it later, which is why it needs no social engineering and often reaches administrators. Running only for the submitter describes reflected XSS, which requires the victim to follow a crafted link. The fragment answer describes the DOM-based variant. Targeting the database engine describes SQL injection: XSS always executes in the browser, and storage is only the transport.",
        xp: 10,
      },
      {
        id: "wa_06",
        question: "GET /view.php?file=....//....//etc/passwd returns HTTP 200 with a 4 KB body, where that page normally returns about 800 bytes. What is the best read?",
        options: [
          "Path traversal was blocked, since a 200 means the WAF allowed it",
          "Path traversal likely succeeded and returned the passwd file",
          "This is SSRF, because the app fetched a file on the user's behalf",
          "This is stored XSS, since a payload persisted in the file parameter",
        ],
        answer: 1,
        explanation: "The ....// sequence defeats naive filters that strip ../ exactly once — remove the inner ../ from ....// and you are left with ../ again. A 200 carrying five times the normal body size is the strongest available signal that different content came back; confirm by retrieving the response. Reading a 200 as evidence of a block confuses the WAF verdict with the application outcome. SSRF would mean the server fetching a remote URL, not a local path. And nothing here is stored or rendered to another user.",
        xp: 20,
      },
      {
        id: "wa_07",
        question: "Why is 169.254.169.254 the classic SSRF target in a cloud environment?",
        options: [
          "It is the default gateway address for every virtual private cloud subnet",
          "It is the internal DNS resolver that maps all private hostnames",
          "It is the metadata service that can hand out instance credentials",
          "It is the load balancer health-check endpoint exposed to the VPC",
        ],
        answer: 2,
        explanation: "The link-local instance metadata endpoint answers only from the instance itself, so an SSRF that makes the server fetch it can retrieve the attached role's temporary credentials — turning a web bug into cloud API access. That is exactly why IMDSv2 requires a session token obtained by PUT. The gateway, resolver and health-check answers all name real infrastructure roles, but none of them return credentials, which is the specific reason this address is the prize rather than merely reachable.",
        xp: 15,
      },
      {
        id: "wa_08",
        question: "On an IIS server, w3wp.exe (the application pool worker process) spawns cmd.exe running whoami. Which ATT&CK technique best explains why a web server process has a shell child at all?",
        options: [
          "T1059.003 – Command and Scripting Interpreter: Windows Command Shell",
          "T1190 – Exploit Public-Facing Application",
          "T1078 – Valid Accounts",
          "T1505.003 – Server Software Component: Web Shell",
        ],
        answer: 3,
        explanation: "A web shell is a script planted in the web root that the worker process executes on request, so commands appear as children of w3wp.exe — that parent-child edge is the detection. T1059.003 correctly names the shell that ran, but it is the execution mechanism, not the reason a web server is running one. T1190 is very likely how the shell was planted, so it describes initial access rather than this artefact. T1078 would require an authenticated logon, and none is shown here.",
        xp: 20,
      },
      {
        id: "wa_09",
        question: "An attacker lands a web shell on an IIS server. Why is the attacker not automatically SYSTEM?",
        options: [
          "IIS strips all tokens from any process it spawns as a child",
          "Web shells always execute inside a sandboxed browser context",
          "The worker runs as the app pool identity, not a privileged one",
          "The shell inherits the privileges of the user browsing the site",
        ],
        answer: 2,
        explanation: "Commands from a web shell inherit the worker process token, and modern IIS defaults that to a low-privilege ApplicationPoolIdentity or a dedicated service account — so expect privilege escalation next, via token abuse, an unquoted service path or a local exploit. IIS does not strip tokens; children inherit the parent token normally. There is no browser sandbox involved, because the shell executes server-side. And the remote visitor's identity confers nothing at all on the server.",
        xp: 15,
      },
      {
        id: "wa_10",
        question: "A single source IP sent 300 injection attempts against /login. 297 returned HTTP 500 and 3 returned HTTP 200. Where do you look first?",
        options: [
          "The 500s, since a server error proves code execution occurred",
          "The three 200s — a working payload stops throwing errors",
          "Neither, because a 200 only means the web server stayed alive",
          "The 500s first, as they show the database was reachable at all",
        ],
        answer: 1,
        explanation: "Errors are the sound of payloads failing to parse. The moment a payload is syntactically valid the query succeeds and the app returns a normal page, so the small cluster of 200s is where the working syntax lives. Reading a 500 as proof of code execution overreads it — it usually means an unhandled exception, most often a syntax error. Dismissing the 200s abandons the strongest signal in the set. And prioritising the 500s for reachability spends your time on the noise.",
        xp: 20,
      },
      {
        id: "wa_11",
        question: "A WAF log records action=ALLOW on a POST to /upload.aspx with a 240 KB request body from an external IP. Why does this deserve a look?",
        options: [
          "ALLOW means the request was logged but never forwarded upstream",
          "A 240 KB body always exceeds the maximum HTTP POST size allowed",
          "ALLOW entries are informational and are never correlated to a host",
          "Nothing matched a rule, yet a large upload reached the app itself",
        ],
        answer: 3,
        explanation: "ALLOW means no signature matched — it is not a verdict that the request was safe. An unmatched large POST to an upload endpoint is exactly how a web shell gets planted, so the next step is correlating against file-creation events in the web root and any process spawned by the worker. ALLOW forwards the request, which is the whole point of the verdict. There is no universal HTTP body-size limit at 240 KB. And ALLOW records carry the backend target, so they are correlated routinely.",
        xp: 20,
      },
      {
        id: "wa_12",
        question: "Overnight your WAF blocked 4,000 SQL injection attempts from one IP address. Why is that not the end of the investigation?",
        options: [
          "Blocked requests are never written to the WAF's own audit log",
          "A WAF block automatically rolls back any database write it caused",
          "You still do not know whether any request slipped past the WAF",
          "Four thousand attempts always indicates an authenticated insider",
        ],
        answer: 2,
        explanation: "Block counts tell you what the rules matched and say nothing about what they missed. Check the same source for ALLOW verdicts, look for an encoding or endpoint that evaded the signature, and confirm at the application and database layer. Blocks are in fact the entries you always have, which is why they are the visible half. A blocked request never reaches the database, so there is nothing to roll back. And high volume from a single external IP normally means an automated scanner, not an insider.",
        xp: 15,
      },
    ],
  },

  // ── 4. SOC Operations & Alert Triage ──────────────────────────────────────
  {
    slug: "soc-operations-triage",
    title: "SOC Operations & Alert Triage",
    description: "How a SOC actually runs a shift — tiering, the order you ask triage questions, the verdict everyone forgets, and handovers that survive the person who wrote them.",
    difficulty: "Beginner",
    category: "SOC Fundamentals",
    icon: "🎧",
    estimatedMinutes: 12,
    questions: [
      {
        id: "so_01",
        question: "Which task belongs to Tier 1 rather than Tier 2 or Tier 3?",
        options: [
          "Triaging incoming alerts and escalating the ones that qualify",
          "Building new detection rules from a fresh threat intelligence report",
          "Leading the forensic timeline of a confirmed domain compromise",
          "Deciding whether the organisation notifies a data regulator",
        ],
        answer: 0,
        explanation: "Tier 1 works the queue: validate, gather context, close what is clearly benign, escalate what is not. Writing detections from intel is detection engineering, typically Tier 3 or a dedicated function. Leading a forensic timeline is deep investigation, owned by Tier 2 or 3 with a named incident lead. Regulator notification is not a SOC decision at all — it sits with legal and privacy, informed by what the SOC establishes.",
        xp: 10,
      },
      {
        id: "so_02",
        question: "You are Tier 1 with four open alerts. Which one should you close rather than escalate?",
        options: [
          "A blocked ransomware sample found on a domain controller share",
          "A password spray of 400 accounts from one external IP address",
          "A successful admin logon from a country with no staff or offices",
          "A blocked EICAR test file detected on the AV team's own laptop",
        ],
        answer: 3,
        explanation: "EICAR is a harmless standard test string, and finding it on the AV team's own machine is a control being verified — document the reasoning and close it. The ransomware sample is different: something reached your most sensitive host, and 'blocked' never explains how it got there. The spray is an active credential attack in progress. The foreign admin logon is a successful authentication that geography cannot account for. Blocked is not a synonym for harmless.",
        xp: 15,
      },
      {
        id: "so_03",
        question: "An alert lands in your queue. What is the first question to ask?",
        options: [
          "Which regulator must be notified about this event?",
          "Who wrote the rule and when was it last tuned?",
          "Is this real, or is it a known benign pattern?",
          "What is the CVSS score of the affected software?",
        ],
        answer: 2,
        explanation: "Triage runs in a fixed order: is it real, what is the scope, how bad is it, what do I do now. Validity comes first because every later question wastes time if the answer turns out to be no. Regulator notification is a late-stage legal question that depends on confirmed impact. Rule authorship is a tuning question worth asking after the verdict, not before it. And a CVSS score describes software risk, telling you nothing about whether this specific alert reflects real activity.",
        xp: 10,
      },
      {
        id: "so_04",
        question: "An alert fires on PsExec execution. You confirm it really ran — a named sysadmin ran it during an approved change window. How do you classify it?",
        options: [
          "A false positive — the rule matched something that never ran",
          "A benign true positive — real activity, but authorised",
          "A true positive — any PsExec use is an incident by definition",
          "A false negative — the rule failed to catch the real intrusion",
        ],
        answer: 1,
        explanation: "The rule detected exactly what it was built to detect and the activity genuinely happened; the only thing making it non-malicious is authorisation. Calling it a false positive is wrong because nothing misfired — the tool really did run. Calling every PsExec use an incident overreaches, since it is a legitimate admin utility, and that stance guarantees analysts stop reading the alert. A false negative is impossible here by definition: that is an event which produced no alert at all.",
        xp: 15,
      },
      {
        id: "so_05",
        question: "Why does labelling an alert a benign true positive matter more than just calling it a false positive?",
        options: [
          "It lets the SOC delete the rule without any approval process",
          "It moves the ticket straight into the incident queue for legal review",
          "The rule worked, so tuning should add context, not rewrite it",
          "It marks the detection as failed so the vendor can be billed",
        ],
        answer: 2,
        explanation: "The distinction routes the fix. Calling it a false positive sends an engineer to repair logic that is not broken, and the usual result is a narrower rule with a fresh blind spot. The honest label points at the real fix: enrich with change-ticket or asset-owner context so authorised activity becomes recognisable. Deleting a rule without approval is a governance failure rather than a benefit. Escalating to legal re-opens something already resolved. And nothing failed, so no vendor claim exists.",
        xp: 10,
      },
      {
        id: "so_06",
        question: "What does MTTD measure in a SOC?",
        options: [
          "Average time from alert creation to ticket closure",
          "Average number of alerts each analyst handles per day",
          "Average time an attacker dwells after containment",
          "Average time from compromise to the SOC noticing it",
        ],
        answer: 3,
        explanation: "Mean time to detect spans the gap between the intrusion starting and anyone realising, which is why it is driven by detection coverage and log visibility rather than analyst speed. Alert-to-closure is closer to mean time to respond or resolve, measured only after the alert exists. Alerts per analyst is workload throughput. And dwell after containment is not a standard measure at all — dwell time ends at detection and containment by definition.",
        xp: 10,
      },
      {
        id: "so_07",
        question: "Which change most directly reduces MTTR?",
        options: [
          "Adding more detection rules to the SIEM stack",
          "Playbooks with pre-approved containment steps",
          "Increasing the log retention window to two years",
          "Raising the severity of every existing rule",
        ],
        answer: 1,
        explanation: "Most response time is spent waiting for a decision, not performing the action. Pre-approved steps — isolate this device class, disable this account type — remove the approval round trip, which is the largest block of dead time in most incidents. More rules may improve detection but add triage volume, often worsening response time. Longer retention helps investigation depth, not speed of action. Raising every severity floods the queue with false urgency and slows everything down.",
        xp: 10,
      },
      {
        id: "so_08",
        question: "You are handing over an open investigation at shift end. Which handover note is most useful to the incoming analyst?",
        options: [
          "A copy of every raw log line collected during the shift",
          "The alert ID and a note saying investigation is ongoing",
          "What is confirmed, what is ruled out, and the next action",
          "A list of every tool you opened while working the case today",
        ],
        answer: 2,
        explanation: "A good handover transfers state and intent so the next analyst resumes instead of restarting. The other three are the classic failure modes: a raw log dump hands over evidence with no interpretation, forcing a full re-read. 'Ongoing' with no state is the most common and most costly handover note in any SOC. A tool list records your activity rather than your findings. Verbal-only handovers fail the same way — nothing survives the shift.",
        xp: 15,
      },
      {
        id: "so_09",
        question: "A single host is beaconing to a known command-and-control domain. Under what condition would you watch rather than contain immediately?",
        options: [
          "When the host belongs to an executive who dislikes interruptions",
          "Whenever the EDR has already blocked the outbound connection",
          "When the alert severity is medium rather than high or critical",
          "When scope is unknown and IR has authorised watching",
        ],
        answer: 3,
        explanation: "Containing one host tips the attacker off and can cost you the other twelve, so deliberately watching to establish scope is legitimate — but only as a decision made and recorded by the incident lead, with monitoring in place and a trigger defined for when to pull the plug. Deferring to an executive's convenience is convenience overriding risk. Trusting an EDR block is not watching but assuming the tool handled it, and beaconing means the implant is still resident. A severity label is not an authorisation.",
        xp: 20,
      },
      {
        id: "so_10",
        question: "Why is it worth recording what you ruled out during triage?",
        options: [
          "It is required before any ticket can be marked closed",
          "It stops the next analyst repeating dead ends",
          "It replaces the need to record what you actually found",
          "It lets the SIEM automatically suppress the same alert",
        ],
        answer: 1,
        explanation: "Negative findings are evidence. 'No persistence in Run keys, no scheduled tasks created, no lateral SMB' tells the next person exactly where not to spend an hour, and it is what makes a reopened case resumable months later. Most ticketing systems do not enforce this as a closure requirement, so that is a rule people assume rather than one that exists. Exclusions supplement findings and never substitute for them. And suppression is a tuning action you configure deliberately, not a side effect of a note.",
        xp: 10,
      },
      {
        id: "so_11",
        question: "The EDR blocked a malware execution on a workstation. Why does that not close the ticket?",
        options: [
          "Blocks are reversed automatically after 24 hours pass",
          "The EDR cannot log which user account was logged on",
          "You still do not know how the file reached the host",
          "A block always means other hosts were already infected",
        ],
        answer: 2,
        explanation: "A block is one round won, not the match. The delivery path is still open — a phishing message, a shared drive, a USB device, a compromised update — and whatever delivered this can deliver something the EDR does not recognise. Close it once you have the delivery vector and have checked whether other hosts received the same thing. Blocks are not time-limited and do not reverse themselves. The detection record carries the process and user context. And other infections are a possibility to check, never a certainty.",
        xp: 15,
      },
    ],
  },
];
