// ─── Quiz Data: Linux Security & Cloud Security ─────────────────────────────
// Two intermediate quizzes: Linux Security covers filesystem structure,
// permissions, SUID/SGID, sudo, core log sources, auditd, and the common
// Linux persistence techniques and investigation commands an analyst needs.
// Cloud Security Fundamentals covers AWS/Azure platform basics, the shared
// responsibility model, storage and network exposure, CloudTrail/Activity
// Log, and cloud-native attack patterns — deliberately scoped to platform
// and infrastructure, not identity (see data.ts: cloud-identity-security for
// the identity-focused quiz). Same contract as ./data.ts.

import type { Quiz } from "./data";

export const QUIZZES_LINUX_CLOUD: Quiz[] = [
  // ── Linux Security ──────────────────────────────────────────────────────
  {
    slug: "linux-security-for-analysts",
    title: "Linux Security — Logs, Permissions, and Persistence",
    description: "Filesystem layout, permissions and SUID/SGID, sudo, core log sources, auditd, and the persistence and investigation techniques every analyst needs on a Linux host.",
    difficulty: "Intermediate",
    category: "Linux",
    icon: "🐧",
    estimatedMinutes: 16,
    questions: [
      {
        id: "lx_01",
        question: "Which directory holds Linux system-wide configuration files, including passwd, shadow, and the sudoers file?",
        options: [
          "/var/log, which stores runtime log files written by the kernel and services.",
          "/tmp, a world-writable directory for temporary files cleared on reboot.",
          "/etc, which holds system-wide configuration files for the OS and daemons.",
          "/home, which stores each local user's personal files and profile.",
        ],
        answer: 2,
        explanation: "/etc is the standard location for Linux configuration: /etc/passwd (user accounts), /etc/shadow (password hashes), /etc/sudoers (privilege rules), and per-service config files. /var/log holds logs, /tmp is a volatile scratch space attackers often use to stage tools, and /home holds user data — not configuration.",
        xp: 10,
      },
      {
        id: "lx_02",
        question: "An analyst wants live information about currently running processes, open file descriptors, and kernel parameters on a compromised host. Which filesystem exposes this?",
        options: [
          "/var, a static directory that only updates when a service is restarted.",
          "/proc, a virtual filesystem exposing live kernel and process information.",
          "/etc, which reflects the live configuration state of every running process.",
          "/opt, where third-party applications store their live runtime state.",
        ],
        answer: 1,
        explanation: "/proc is a pseudo-filesystem generated in memory by the kernel; reading /proc/[pid]/ shows a process's command line, open files, and environment in real time. It's a go-to source for live triage — /etc holds static configuration, /var holds logs and variable data, and /opt just holds installed software.",
        xp: 10,
      },
      {
        id: "lx_03",
        question: "A file shows permissions -rwxr-x---. What access does this grant?",
        options: [
          "Owner can read, write, and execute; group can read and execute; others have no access.",
          "Owner can only read; group can read and write; others can execute only.",
          "Owner and group both have full read, write, and execute; others can read only.",
          "Owner can read and write; group has no access; others can execute only.",
        ],
        answer: 0,
        explanation: "Each permission triplet reads owner/group/others. rwx (owner: read+write+execute), r-x (group: read+execute), --- (others: nothing). This is a common pattern for admin scripts — the owner can edit and run it, a trusted group can only run it, and everyone else is locked out entirely.",
        xp: 10,
      },
      {
        id: "lx_04",
        question: "Running chmod 4755 on a binary sets which special permission in addition to standard rwx?",
        options: [
          "The sticky bit, which restricts who can delete files inside a directory.",
          "SUID, which lets the binary run with the privileges of its file owner.",
          "SGID, which makes new files inherit the group of the parent directory.",
          "The immutable attribute, which blocks the file from being changed or deleted.",
        ],
        answer: 1,
        explanation: "The leading 4 in chmod 4755 sets SUID (SetUID) — when the binary runs, it executes with the privileges of its owner rather than the invoking user. A leading 2 sets SGID (group inheritance), and a leading 1 sets the sticky bit (used on directories like /tmp). The immutable attribute isn't set by chmod at all — that's chattr +i.",
        xp: 15,
      },
      {
        id: "lx_05",
        question: "During a host review, an analyst finds that /usr/bin/find is owned by root and has the SUID bit set — not a default Linux configuration. Why is this a serious finding?",
        options: [
          "It means find will silently run as a scheduled task at every system boot.",
          "It logs every search query to /var/log/faillog for compliance auditing purposes.",
          "Any user who runs it inherits root privileges, and find's -exec option can spawn a root shell.",
          "It forces the binary to execute inside a restricted, root-owned chroot jail.",
        ],
        answer: 2,
        explanation: "find with SUID root is a textbook privilege escalation path: any local user can run find with its -exec option to launch a shell, and that shell executes with the file owner's (root's) privileges rather than the calling user's. SUID has nothing to do with boot scheduling, audit logging, or chroot confinement — those are separate mechanisms entirely.",
        xp: 15,
      },
      {
        id: "lx_06",
        question: "An analyst reviewing /etc/sudoers finds the line: deploy ALL=(ALL) NOPASSWD: ALL. What risk does this create?",
        options: [
          "The deploy account can run any command as root without ever entering a password.",
          "The deploy account is blocked from using sudo entirely until a password is set.",
          "Only the specific 'ALL' binary can be run by the deploy account as root.",
          "The rule only applies during the deploy account's very first login session.",
        ],
        answer: 0,
        explanation: "NOPASSWD: ALL on 'ALL=(ALL)' means the deploy account can execute any command as any user, including root, without authenticating each time. If that account — often used by CI/CD pipelines — is ever compromised through a leaked SSH key or a poisoned deploy script, the attacker gets instant, frictionless root.",
        xp: 15,
      },
      {
        id: "lx_07",
        question: "A SOC analyst reviewing /var/log/auth.log (or /var/log/secure on RHEL) sees hundreds of 'Failed password for root' entries from one external IP within a few minutes. What does this indicate?",
        options: [
          "A misconfigured cron job that repeatedly restarts the SSH daemon.",
          "An SSH brute-force attempt against the root account from that IP.",
          "A normal pattern generated by automated vulnerability scanning tools.",
          "An expired SSL certificate causing repeated failed handshake attempts.",
        ],
        answer: 1,
        explanation: "auth.log/secure records every SSH authentication attempt. A burst of 'Failed password' lines for the same account from one source, at high frequency, is the classic signature of brute forcing — worth blocking the source IP and checking whether any attempt eventually succeeded, since an 'Accepted password' line right after the burst would mean compromise.",
        xp: 10,
      },
      {
        id: "lx_08",
        question: "What does the Linux auditd service add that syslog alone does not provide?",
        options: [
          "Automatic encryption of every log file at rest using AES-256, transparently.",
          "Fine-grained rules that log specific syscalls, like every execve, with full arguments.",
          "Scheduled email alerts sent out whenever any new user account is created.",
          "A built-in host firewall that blocks traffic matching suspicious signatures.",
        ],
        answer: 1,
        explanation: "auditd lets you define rules, typically in /etc/audit/rules.d/, that watch specific syscalls — commonly execve, to capture every command executed on the box with its full arguments, written to /var/log/audit/audit.log. Plain syslog only sees what applications choose to log; auditd sees at the kernel level. It doesn't encrypt logs, send email, or filter network traffic.",
        xp: 15,
      },
      {
        id: "lx_09",
        question: "An analyst finds a new public key appended to ~/.ssh/authorized_keys for a service account, added outside any change window. Why is this a persistence concern?",
        options: [
          "It forces every future SSH login on the box to require a password change.",
          "It lets the key's holder log in as that account without knowing its password.",
          "It automatically disables SSH access for every other account on the host.",
          "It schedules the account to be deleted after the next reboot.",
        ],
        answer: 1,
        explanation: "authorized_keys lists public keys allowed to authenticate as that user, no password needed. An attacker who briefly gained access can append their own key and retain login access indefinitely — even after the original foothold, like a stolen password or an exploited service, is patched or rotated. It's one of the quietest, most durable Linux persistence techniques.",
        xp: 15,
      },
      {
        id: "lx_10",
        question: "A file appears under /etc/cron.d/ that runs a script as root every five minutes, and it was not created by any known deployment process. What is the likely purpose?",
        options: [
          "Persistence — the attacker re-establishes access even if their original foothold is removed.",
          "Log rotation — the entry is a routine housekeeping job for /var/log.",
          "A kernel update — the entry triggers scheduled patch installation.",
          "Disk cleanup — the entry clears temporary files from /tmp periodically.",
        ],
        answer: 0,
        explanation: "cron.d entries, like user crontabs, run automatically on a schedule with the privileges of whichever user owns them — root, in this case. Attackers plant them as a low-effort persistence mechanism: even if their initial shell is killed or the compromised account is disabled, the cron job re-executes their payload on schedule. It has nothing inherently to do with log rotation, patching, or cleanup.",
        xp: 15,
      },
      {
        id: "lx_11",
        question: "An unfamiliar systemd unit file is found in /etc/systemd/system/, enabled to start at boot, with an ExecStart line pointing to a script in /tmp. Why does this matter?",
        options: [
          "systemd units can only run scripts that are digitally signed by the vendor.",
          "It guarantees the script will be scanned by the system's antivirus before running.",
          "It gives the attacker a payload that restarts automatically at every boot.",
          "It permanently disables all other services from starting on the host.",
        ],
        answer: 2,
        explanation: "A custom systemd service that is enabled to start at boot is a durable persistence mechanism — the attacker's payload survives reboots and can even be configured to restart if killed. Pointing ExecStart at a script in /tmp is a red flag, since legitimate services rarely run from a world-writable, volatile directory. systemd enforces no signing requirement by default and doesn't touch antivirus or other services.",
        xp: 15,
      },
      {
        id: "lx_12",
        question: "A user's ~/.bashrc file has an extra line appended that downloads and executes a script every time the user opens a new shell. What persistence technique is this?",
        options: [
          "Shell profile persistence — the payload re-runs on every interactive login.",
          "SUID abuse — the shell itself gains root privileges permanently.",
          "Cron-based persistence — the shell schedules the payload for a fixed time.",
          "Kernel module persistence — the payload loads directly into kernel space.",
        ],
        answer: 0,
        explanation: "Files like .bashrc, .bash_profile, and .profile execute automatically whenever a matching shell starts. An attacker who can write to one of them gets code execution every time that user opens a terminal or logs in — no scheduled task, no SUID bit, and no kernel involvement required. It's simple, and easy to miss during a quick review.",
        xp: 15,
      },
      {
        id: "lx_13",
        question: "An analyst suspects a process is exfiltrating data over an unusual outbound port. Which command would best show which running process owns that specific network connection?",
        options: [
          "ss -tulpn (or netstat -tulpn), which lists listening and active sockets with their owning process.",
          "last, which lists recent login sessions and their terminal, but not network sockets.",
          "top, which shows live CPU and memory usage, not per-connection ownership.",
          "who, which shows currently logged-in users, not process-to-socket mappings.",
        ],
        answer: 0,
        explanation: "ss -tulpn, the modern replacement for netstat -tulpn, maps sockets to the PID and process name that owns them — exactly what's needed to tie a suspicious connection back to a process, which can then be inspected further with lsof -p or ps. last, top, and who all give useful context but none map a specific network connection to its owning process.",
        xp: 15,
      },
      {
        id: "lx_14",
        question: "A compromised web server shows a process tree where the web server spawned bash, which opened a connection to an external IP on an unusual port. Soon after, the account's shell history file is empty. What happened?",
        options: [
          "The attacker piped an interactive shell over TCP to get remote access, then cleared history to hide their commands.",
          "The web server process restarted and regenerated a fresh, empty history file automatically.",
          "A routine cron job rotated the log files, which coincidentally reset the history file too.",
          "The account hit its disk quota, which silently truncated its shell history file.",
        ],
        answer: 0,
        explanation: "A web server process spawning bash, which then opens a raw TCP connection, is the classic signature of a web shell chaining into a reverse shell — commonly launched with a one-liner that redirects an interactive shell over /dev/tcp. Attackers then commonly clear or redirect their history file, for example by unsetting HISTFILE, to erase evidence of the commands they ran. Log rotation, restarts, and disk quotas don't clear a user's shell history.",
        xp: 15,
      },
      {
        id: "lx_15",
        question: "A security review finds a Docker container running with --privileged and the host's /var/run/docker.sock mounted inside it. Why is this a serious risk?",
        options: [
          "It only affects the container's own filesystem and cannot reach the host.",
          "It automatically encrypts all traffic leaving the container's network interface.",
          "A process inside the container can effectively gain root access to the host.",
          "It permanently disables the container from starting any additional processes.",
        ],
        answer: 2,
        explanation: "--privileged removes most container isolation, including device access and Linux capabilities, and mounting docker.sock inside a container hands it control of the host's Docker daemon — from there, an attacker can launch a new container that mounts the host's root filesystem, achieving full host compromise. This is a well-known container escape pattern and a strong reason to avoid both settings unless truly necessary.",
        xp: 15,
      },
    ],
  },

  // ── Cloud Security Fundamentals ─────────────────────────────────────────
  {
    slug: "cloud-security-fundamentals",
    title: "Cloud Security — AWS and Azure Through an Analyst's Eyes",
    description: "Platform and infrastructure fundamentals for AWS and Azure: the shared responsibility model, storage and network exposure, CloudTrail/Activity Log, and cloud-native attack patterns like cryptomining and IMDS abuse.",
    difficulty: "Intermediate",
    category: "Cloud Security",
    icon: "🌩️",
    estimatedMinutes: 16,
    questions: [
      {
        id: "cl_01",
        question: "An Azure subscription defines a billing and access boundary for a set of resources. Which AWS concept plays the closest equivalent role?",
        options: [
          "An AWS account, since it isolates billing, resources, and IAM identities.",
          "An AWS region, since it isolates resources by geographic location only.",
          "An AWS VPC, since it isolates network traffic between resource groups.",
          "An AWS bucket, since it isolates stored objects from other accounts.",
        ],
        answer: 0,
        explanation: "An AWS account is the closest equivalent to an Azure subscription — both are billing and administrative boundaries containing their own resources and identities. A region is just a geographic location, present separately in both clouds, a VPC is a network construct within an account, and a bucket only stores objects — neither is a billing or account boundary.",
        xp: 10,
      },
      {
        id: "cl_02",
        question: "Under the Shared Responsibility Model for an IaaS virtual machine, such as an AWS EC2 instance or an Azure VM, which task is the customer's responsibility, not the provider's?",
        options: [
          "Patching the physical hardware and maintaining the data center's power supply.",
          "Patching the guest operating system and configuring security groups for the VM.",
          "Guaranteeing the physical security of the data center where the VM runs.",
          "Maintaining the hypervisor layer that isolates one customer's VM from another.",
        ],
        answer: 1,
        explanation: "In IaaS, the provider secures 'of the cloud' — physical hardware, data center security, and the hypervisor. The customer secures 'in the cloud' — guest OS patching, network rules like security groups or NSGs, IAM, and data. Confusing this split is a top cause of cloud breaches, since many public-cloud incidents trace back to a customer assuming the provider handled something it never did.",
        xp: 15,
      },
      {
        id: "cl_03",
        question: "In cloud IAM, what is the key difference between an IAM role and an IAM policy?",
        options: [
          "A role is an identity that can be assumed; a policy is a document that defines what actions are allowed.",
          "A role always belongs to a human user; a policy always belongs to a service account only.",
          "A role restricts network traffic; a policy restricts which regions resources can run in.",
          "A role and a policy are interchangeable terms for the exact same IAM object.",
        ],
        answer: 0,
        explanation: "An IAM role is an identity — something a user, service, or application can assume — while a policy is a document that defines exactly which actions are allowed on which resources, and gets attached to a user, group, or role. Roles aren't tied only to humans or only to services, and neither construct governs network traffic or regions — that's handled by security groups and NSGs.",
        xp: 15,
      },
      {
        id: "cl_04",
        question: "A developer accidentally commits an AWS access key and secret key to a public GitHub repository. What is the most urgent first response?",
        options: [
          "Rotate and deactivate the exposed access key immediately, then investigate for any usage.",
          "Wait for the next scheduled key rotation cycle before taking any action.",
          "Ask the developer to delete the commit from their local repository only.",
          "Change the account's console password, since access keys are unrelated to it.",
        ],
        answer: 0,
        explanation: "Public GitHub repos are scanned by bots within minutes, and a leaked access key can be used for API calls almost immediately. The urgent response is to deactivate and rotate the key through IAM, then review CloudTrail for any activity performed with it before deactivation. Deleting a local commit doesn't remove it from GitHub's history or forks, waiting for scheduled rotation leaves the window open, and access keys are entirely separate credentials from the console password.",
        xp: 15,
      },
      {
        id: "cl_05",
        question: "A cloud security review finds an S3 bucket policy with Principal: '*' and Action: 's3:GetObject', with no other restricting condition. What does this configuration allow?",
        options: [
          "Anyone on the internet can read every object in that bucket, without authenticating.",
          "Only IAM users within the same AWS account can read objects in the bucket.",
          "Only AWS support engineers can read objects in the bucket for troubleshooting.",
          "No one can read the bucket until an explicit allow condition is added.",
        ],
        answer: 0,
        explanation: "Principal: '*' means the policy applies to anyone, authenticated or not, and s3:GetObject with no conditions — no IP restriction, no VPC endpoint requirement — grants public read access to every object. This is one of the most common and damaging cloud misconfigurations, and countless breaches trace back to an S3 bucket left open like this. It doesn't restrict to the account, to AWS support, or default-deny anything.",
        xp: 15,
      },
      {
        id: "cl_06",
        question: "In Azure Blob Storage, what does setting a container's public access level to 'Container' allow, compared to 'Private'?",
        options: [
          "Anonymous users can list and read every blob in that container over the internet.",
          "Only users with an Azure AD account in the same tenant can read blobs.",
          "Only the storage account owner can read or list blobs in the container.",
          "Blobs become readable solely by other Azure services within the same region.",
        ],
        answer: 0,
        explanation: "Azure Blob container access levels: 'Private' by default requires authentication for every request, 'Blob' allows anonymous read of individual blobs if the exact URL is known, and 'Container' allows anonymous read and listing of every blob inside — the most exposed setting. Misconfigured public containers are Azure's equivalent of an open S3 bucket, and are a frequent source of accidental data exposure.",
        xp: 15,
      },
      {
        id: "cl_07",
        question: "A Security Group (AWS) or NSG (Azure) inbound rule allows source 0.0.0.0/0 on port 3389. What risk does this create?",
        options: [
          "Any host on the internet can attempt to reach RDP on that resource.",
          "Only hosts inside the same virtual network can reach RDP on that resource.",
          "The rule blocks all inbound RDP traffic from every source by default.",
          "The rule only applies to outbound traffic leaving the resource, not inbound.",
        ],
        answer: 0,
        explanation: "0.0.0.0/0 means 'any IPv4 address', and port 3389 is RDP, so this rule exposes Remote Desktop to the entire internet, a magnet for brute-force and credential-stuffing bots. The same logic applies to port 22 for SSH. Best practice restricts management ports to a VPN, bastion host, or specific known IP ranges — never 0.0.0.0/0. This is an inbound allow rule, not a block, and it isn't scoped to the internal network or to outbound traffic.",
        xp: 15,
      },
      {
        id: "cl_08",
        question: "What does AWS CloudTrail primarily record?",
        options: [
          "API calls and management-plane actions across the account, with the identity behind each.",
          "The full byte-level content of every file stored in S3 buckets, continuously.",
          "Network packet captures collected for every EC2 instance's network interface.",
          "CPU and memory performance metrics collected for running compute resources.",
        ],
        answer: 0,
        explanation: "CloudTrail logs API activity — who called what action, on which resource, from which IP, and whether it succeeded — covering both the console and programmatic access. It's the AWS equivalent of an audit trail for account activity, not a file-content inspector, a packet capture tool like VPC Flow Logs, or a performance monitor like CloudWatch metrics.",
        xp: 10,
      },
      {
        id: "cl_09",
        question: "An analyst notices a CloudTrail event showing StopLogging was called on a trail, shortly after a new IAM user was created with administrator access. What does this pattern suggest?",
        options: [
          "An attacker with a compromised account is disabling audit logging to hide further actions.",
          "A scheduled maintenance job is rotating CloudTrail's storage bucket for cost savings.",
          "AWS Support temporarily paused logging while investigating a billing dispute.",
          "The account reached its CloudTrail event quota and logging paused automatically.",
        ],
        answer: 0,
        explanation: "StopLogging disables a CloudTrail trail, and pairing it with a freshly created admin user is a strong compromise indicator — a classic attacker move is to create a persistent privileged identity, then blind the audit trail so their subsequent actions go unrecorded. CloudTrail doesn't auto-pause on a quota, AWS Support doesn't silently disable customer logging, and there's no 'bucket rotation' maintenance job that calls StopLogging.",
        xp: 15,
      },
      {
        id: "cl_10",
        question: "What is the Azure equivalent of AWS CloudTrail — the service that records management-plane operations like resource creation, deletion, and role assignment changes?",
        options: [
          "Azure Activity Log, which records subscription-level control-plane operations.",
          "Azure Monitor Metrics, which tracks CPU and memory usage of resources.",
          "Azure Blob Storage, which stores backups of virtual machine disks.",
          "Azure Key Vault, which stores and manages encryption keys and secrets.",
        ],
        answer: 0,
        explanation: "Azure Activity Log records control-plane, or management, operations on a subscription — who created, modified, or deleted a resource, and when. It's the direct equivalent of CloudTrail. Metrics track performance data, Blob Storage is for object storage, and Key Vault manages secrets — none of them log administrative activity.",
        xp: 10,
      },
      {
        id: "cl_11",
        question: "What is the primary function of AWS GuardDuty or Microsoft Defender for Cloud?",
        options: [
          "Continuous threat detection that analyzes logs and signals to flag suspicious cloud activity.",
          "A firewall service that filters inbound and outbound network traffic by rule.",
          "A backup service that snapshots virtual machines and databases on a schedule.",
          "An identity provider that issues single sign-on tokens for cloud applications.",
        ],
        answer: 0,
        explanation: "GuardDuty and Defender for Cloud are managed threat-detection services — they continuously analyze signals like CloudTrail or Activity Log events, DNS queries, and network flow data using threat intelligence and anomaly detection to surface findings such as compromised credentials, cryptomining, or reconnaissance. They don't filter traffic, take backups, or issue SSO tokens.",
        xp: 10,
      },
      {
        id: "cl_12",
        question: "GuardDuty raises a finding named CryptoCurrency:EC2/BitcoinTool.B for an EC2 instance that suddenly started making DNS queries to known mining pool domains. What is the most likely cause?",
        options: [
          "The instance, or the credentials used to launch it, has been compromised and is now mining cryptocurrency.",
          "The instance is running a routine AWS health check that queries external DNS servers.",
          "A misconfigured NTP client is querying the wrong time-synchronization servers.",
          "The finding is a known false positive that GuardDuty generates for all new instances.",
        ],
        answer: 0,
        explanation: "DNS queries to known mining pool domains from an EC2 instance are a strong, specific signal of cryptomining malware, usually the result of stolen access keys or credentials being used to launch compute resources for the attacker's own profit. It's not a health check, a misconfigured NTP client, or a blanket false positive; GuardDuty's crypto-mining detections rely on known malicious domain and IP intelligence.",
        xp: 15,
      },
      {
        id: "cl_13",
        question: "An IAM user lacks admin rights directly, but their attached policy allows both iam:PassRole and iam:CreatePolicyVersion on any resource. What risk does this combination create?",
        options: [
          "The user can create a new policy version granting themselves administrator access, then act as admin.",
          "The user gains temporary read-only access to CloudWatch logs for thirty days.",
          "The user can only pass an existing role to a Lambda function they already own.",
          "The combination has no practical effect unless MFA is disabled account-wide.",
        ],
        answer: 0,
        explanation: "This is a classic IAM privilege escalation path: iam:CreatePolicyVersion lets the user rewrite the permissions on a policy they can access, including their own, and iam:PassRole lets them attach powerful roles to services they control — together, these let a user with limited starting access escalate to full administrator. It grants nothing related to CloudWatch, and it isn't neutralized simply by MFA being enabled.",
        xp: 15,
      },
      {
        id: "cl_14",
        question: "A vulnerable web application on an EC2 instance is exploited with a Server-Side Request Forgery flaw that fetches the instance metadata endpoint's IAM security-credentials path for the instance's role. What has the attacker just obtained?",
        options: [
          "The temporary IAM role credentials assigned to that EC2 instance, usable to call AWS APIs.",
          "A list of every file stored in the instance's local /tmp directory.",
          "The root SSH private key used to originally launch the instance.",
          "A copy of the instance's full disk image for offline analysis.",
        ],
        answer: 0,
        explanation: "The link-local address 169.254.169.254 is the Instance Metadata Service, or IMDS — every EC2 instance can query it without authentication under IMDSv1 to retrieve its own metadata, including temporary IAM credentials for its attached role. An SSRF flaw that reaches this endpoint lets an attacker steal those credentials and call AWS APIs as the instance's role, a major reason AWS now pushes IMDSv2, which requires a session token. This has nothing to do with local files, SSH keys, or disk images.",
        xp: 15,
      },
      {
        id: "cl_15",
        question: "Within a ten-minute window, CloudTrail shows: a new access key created for a dormant IAM user, followed by API calls from an unfamiliar IP launching several large compute instances in a region the organization has never used. How should the analyst interpret this?",
        options: [
          "Likely credential compromise being used to spin up compute for cryptomining or other abuse.",
          "A routine automated key-rotation script performing scheduled account maintenance.",
          "A disaster-recovery drill validating failover into a secondary AWS region.",
          "A billing team member testing new instance types before a purchase decision.",
        ],
        answer: 0,
        explanation: "The combination — a dormant account suddenly getting a new key, an unfamiliar source IP, and compute launched in a region the organization has no history using — is a strong composite indicator of stolen credentials being monetized, most often through cryptomining since large instances run up compute cost fast. Legitimate key rotation doesn't come from unfamiliar IPs, DR drills use known regions and are scheduled and communicated, and billing tests wouldn't launch instances via a dormant account's freshly minted key.",
        xp: 15,
      },
    ],
  },
];
