// ─── Quiz Data ────────────────────────────────────────────────────────────────
// Each quiz has 10-12 multiple-choice questions with one correct answer.

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  answer: number;        // index into options[]
  explanation: string;
  xp: number;
}

export interface Quiz {
  slug: string;
  title: string;
  description: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  category: string;
  icon: string;        // emoji
  estimatedMinutes: number;
  questions: QuizQuestion[];
}

// ─────────────────────────────────────────────────────────────────────────────

export const QUIZZES: Quiz[] = [

  // ── 1. MITRE ATT&CK ───────────────────────────────────────────────────────
  {
    slug: "mitre-attack",
    title: "MITRE ATT&CK Framework",
    description: "Test your knowledge of tactics, techniques, and sub-techniques used by real adversaries across the full attack lifecycle.",
    difficulty: "Intermediate",
    category: "Threat Framework",
    icon: "🗺️",
    estimatedMinutes: 15,
    questions: [
      {
        id: "ma_01",
        question: "Which MITRE ATT&CK tactic describes an adversary attempting to steal credentials such as account names and passwords?",
        options: [
          "Defense Evasion",
          "Credential Access",
          "Privilege Escalation",
          "Lateral Movement",
        ],
        answer: 1,
        explanation: "Credential Access (TA0006) covers techniques used to steal credentials like usernames, passwords, and tokens — including keylogging, credential dumping (T1003), and brute force (T1110).",
        xp: 10,
      },
      {
        id: "ma_02",
        question: "An attacker uses 'reg save HKLM\\SAM C:\\Windows\\Temp\\sam.hiv' on a compromised host. Which technique best describes this?",
        options: [
          "T1547 – Boot or Logon Autostart Execution",
          "T1003.002 – OS Credential Dumping: Security Account Manager",
          "T1059.001 – PowerShell",
          "T1112 – Modify Registry",
        ],
        answer: 1,
        explanation: "T1003.002 covers dumping the SAM hive, which stores NTLM password hashes for local accounts. The 'reg save' command copies the SAM registry hive to disk for offline cracking.",
        xp: 15,
      },
      {
        id: "ma_03",
        question: "What does the 'Discovery' tactic (TA0007) primarily involve?",
        options: [
          "Moving laterally to other systems using stolen credentials",
          "Encrypting data to hold for ransom",
          "Gathering information about the environment — users, hosts, network topology",
          "Establishing a command-and-control channel",
        ],
        answer: 2,
        explanation: "Discovery techniques let adversaries understand the target environment — who's in Active Directory (T1087), what hosts exist (T1018), what processes run (T1057), and what security tools are present (T1518.001).",
        xp: 10,
      },
      {
        id: "ma_04",
        question: "An adversary uses PsExec to run a payload on a remote host using domain admin credentials. Which ATT&CK technique applies?",
        options: [
          "T1021.002 – Remote Services: SMB/Windows Admin Shares",
          "T1055 – Process Injection",
          "T1070 – Indicator Removal",
          "T1078 – Valid Accounts",
        ],
        answer: 0,
        explanation: "PsExec connects over SMB (port 445) and uses admin shares (ADMIN$, C$) to copy and execute the payload remotely. This maps to T1021.002 under Lateral Movement.",
        xp: 15,
      },
      {
        id: "ma_05",
        question: "What is a 'sub-technique' in the ATT&CK framework?",
        options: [
          "A technique used only by nation-state actors",
          "A more specific implementation of a parent technique",
          "A technique that evades signature-based detection",
          "A technique requiring elevated privileges",
        ],
        answer: 1,
        explanation: "Sub-techniques (denoted T1xxx.00x) provide more specific detail under a parent technique. For example, T1059.001 (PowerShell) is a sub-technique of T1059 (Command and Scripting Interpreter).",
        xp: 10,
      },
      {
        id: "ma_06",
        question: "Which technique involves an attacker abusing legitimate scheduled tasks to run malicious code persistently?",
        options: [
          "T1548 – Abuse Elevation Control Mechanism",
          "T1053.005 – Scheduled Task/Job: Scheduled Task",
          "T1543.003 – Create or Modify System Process: Windows Service",
          "T1574 – Hijack Execution Flow",
        ],
        answer: 1,
        explanation: "T1053.005 covers attackers using the Windows Task Scheduler to run code at a specified time or trigger, achieving persistence or privilege escalation. Common tools: schtasks.exe, at.exe.",
        xp: 10,
      },
      {
        id: "ma_07",
        question: "An adversary uses DNS TXT record queries with long subdomains to tunnel data out of the network. This maps to which ATT&CK technique?",
        options: [
          "T1048 – Exfiltration Over Alternative Protocol",
          "T1071.004 – Application Layer Protocol: DNS",
          "T1572 – Protocol Tunneling",
          "T1041 – Exfiltration Over C2 Channel",
        ],
        answer: 1,
        explanation: "T1071.004 covers using DNS as a communication channel for C2 or data exfiltration, exploiting the fact that DNS traffic is rarely blocked. TXT queries with encoded subdomains are the classic pattern.",
        xp: 15,
      },
      {
        id: "ma_08",
        question: "Which ATT&CK tactic contains the 'Phishing' technique (T1566)?",
        options: [
          "Execution",
          "Persistence",
          "Initial Access",
          "Collection",
        ],
        answer: 2,
        explanation: "T1566 (Phishing) lives under Initial Access (TA0001) — it covers spearphishing attachments, links, and service-based phishing as ways to gain a foothold in the target environment.",
        xp: 10,
      },
      {
        id: "ma_09",
        question: "An attacker injects malicious code into the memory of a running svchost.exe process. Which technique does this describe?",
        options: [
          "T1055 – Process Injection",
          "T1569.002 – System Services: Service Execution",
          "T1134 – Access Token Manipulation",
          "T1036 – Masquerading",
        ],
        answer: 0,
        explanation: "T1055 (Process Injection) involves inserting code into running processes to evade defenses and elevate privileges. svchost.exe is a common target because it's legitimate and always running. Sub-techniques include DLL injection, process hollowing, and reflective injection.",
        xp: 15,
      },
      {
        id: "ma_10",
        question: "What does the Impact tactic (TA0040) cover?",
        options: [
          "Techniques to maintain access after initial compromise",
          "Techniques that manipulate, interrupt, or destroy systems and data",
          "Techniques to move laterally between systems",
          "Techniques to bypass security controls",
        ],
        answer: 1,
        explanation: "Impact (TA0040) covers the end-goal techniques — ransomware encryption (T1486), data destruction (T1485), disk wipe (T1561), service stop (T1489), and defacement (T1491). These represent the adversary achieving their objective.",
        xp: 10,
      },
      {
        id: "ma_11",
        question: "Which tool is most associated with T1003 (OS Credential Dumping)?",
        options: [
          "Cobalt Strike",
          "Mimikatz",
          "BloodHound",
          "Metasploit",
        ],
        answer: 1,
        explanation: "Mimikatz is the most commonly used tool for credential dumping — it can extract NTLM hashes, Kerberos tickets, and plaintext passwords from LSASS memory. It's referenced in hundreds of threat intelligence reports.",
        xp: 10,
      },
      {
        id: "ma_12",
        question: "An adversary adds a new local administrator account and enables RDP on a compromised server. Which tactic does this primarily represent?",
        options: [
          "Initial Access",
          "Execution",
          "Persistence",
          "Exfiltration",
        ],
        answer: 2,
        explanation: "Creating backdoor accounts and enabling remote access services are classic persistence (TA0003) techniques. The attacker ensures they can return even if the initial foothold is discovered. Relevant techniques: T1136 (Create Account), T1021.001 (RDP).",
        xp: 10,
      },
    ],
  },

  // ── 2. Incident Response ──────────────────────────────────────────────────
  {
    slug: "incident-response",
    title: "Incident Response",
    description: "Master the IR lifecycle — preparation, detection, containment, eradication, and lessons learned. Based on NIST SP 800-61 and PICERL.",
    difficulty: "Intermediate",
    category: "SOC Fundamentals",
    icon: "🚨",
    estimatedMinutes: 14,
    questions: [
      {
        id: "ir_01",
        question: "According to NIST SP 800-61, what are the four phases of the incident response lifecycle (in order)?",
        options: [
          "Detect → Respond → Remediate → Report",
          "Preparation → Detection & Analysis → Containment, Eradication & Recovery → Post-Incident Activity",
          "Identify → Protect → Detect → Respond",
          "Triage → Investigate → Contain → Close",
        ],
        answer: 1,
        explanation: "NIST SP 800-61 defines the IR lifecycle as: Preparation → Detection & Analysis → Containment, Eradication & Recovery → Post-Incident Activity (lessons learned). This is the standard model used in most enterprise IR programs.",
        xp: 10,
      },
      {
        id: "ir_02",
        question: "During containment of an active ransomware incident, what is typically the FIRST action?",
        options: [
          "Wipe and rebuild all affected systems",
          "Notify law enforcement",
          "Isolate affected endpoints from the network",
          "Preserve forensic evidence",
        ],
        answer: 2,
        explanation: "Network isolation is the first priority in ransomware containment — it stops lateral movement and prevents additional encryption. After isolation, forensic preservation and eradication follow. Rebuilding comes later in Recovery.",
        xp: 15,
      },
      {
        id: "ir_03",
        question: "What is the purpose of a 'lessons learned' meeting after an incident?",
        options: [
          "To assign blame to the team that missed the alert",
          "To document what happened and improve processes for future incidents",
          "To verify that all malware has been removed from the network",
          "To calculate the financial cost of the incident",
        ],
        answer: 1,
        explanation: "The post-incident lessons learned (or post-mortem) meeting is blameless and forward-looking — it identifies what worked, what didn't, and what changes to procedures, detection rules, or tools can prevent recurrence.",
        xp: 10,
      },
      {
        id: "ir_04",
        question: "A user reports that their screen shows a ransom note and files have the extension '.locked'. What is the correct triage severity?",
        options: [
          "Low — a single workstation is not critical",
          "Medium — monitor and investigate",
          "Critical — initiate major incident response immediately",
          "High — open a ticket and investigate within 4 hours",
        ],
        answer: 2,
        explanation: "Active ransomware is a Critical/P1 incident. Encryption can spread across shared drives and network hosts within minutes. Immediate isolation and escalation to IR commander are required — every minute of delay increases the blast radius.",
        xp: 15,
      },
      {
        id: "ir_05",
        question: "What does 'dwell time' refer to in incident response?",
        options: [
          "Time taken to eradicate the threat after detection",
          "Time from initial compromise to detection",
          "Time the attacker spends in the exfiltration phase",
          "Time required to restore systems after an incident",
        ],
        answer: 1,
        explanation: "Dwell time (or mean time to detect, MTTD) is the gap between initial compromise and discovery. Industry average is ~21 days. Reducing dwell time is a core SOC objective — shorter dwell time means less damage.",
        xp: 10,
      },
      {
        id: "ir_06",
        question: "Which document defines the roles, responsibilities, and communication plan for a security incident?",
        options: [
          "Business Continuity Plan (BCP)",
          "Incident Response Plan (IRP)",
          "System Security Plan (SSP)",
          "Disaster Recovery Plan (DRP)",
        ],
        answer: 1,
        explanation: "The Incident Response Plan (IRP) documents who does what during an incident — escalation paths, communication trees, evidence handling procedures, and decision authorities. It should be tested regularly with tabletop exercises.",
        xp: 10,
      },
      {
        id: "ir_07",
        question: "An analyst receives an alert for unusual PowerShell activity on a workstation. What is the FIRST step they should take?",
        options: [
          "Immediately isolate the workstation from the network",
          "Check the alert context — review the process tree, parent process, and command line",
          "Open a P1 incident and page the CISO",
          "Run an AV scan on the affected machine",
        ],
        answer: 1,
        explanation: "Before taking action, triage means gathering context: Is the PowerShell encoded? Who ran it? What was the parent process? Is this a known admin script? Analysis first prevents false-positive escalations and ensures the right response.",
        xp: 15,
      },
      {
        id: "ir_08",
        question: "What is 'chain of custody' important for during an incident?",
        options: [
          "Ensuring all analysts are working on the same timeline",
          "Maintaining the integrity and admissibility of digital evidence",
          "Tracking the attacker's lateral movement path",
          "Documenting the communication chain during escalation",
        ],
        answer: 1,
        explanation: "Chain of custody documents who handled evidence, when, and how — ensuring it hasn't been tampered with. This is critical if the incident leads to legal proceedings or law enforcement involvement. Break the chain and evidence may be inadmissible.",
        xp: 10,
      },
      {
        id: "ir_09",
        question: "During eradication, which action should be performed BEFORE rebuilding a compromised system?",
        options: [
          "Notify affected users",
          "Take a forensic image of the system",
          "Reset the domain admin password",
          "Deploy endpoint detection tools",
        ],
        answer: 1,
        explanation: "A forensic image (disk image) must be captured before wiping or rebuilding — it preserves evidence of attacker tools, persistence mechanisms, and malware for analysis. Rebuilding without imaging destroys evidence permanently.",
        xp: 10,
      },
      {
        id: "ir_10",
        question: "What is a 'playbook' in the context of SOC operations?",
        options: [
          "A compliance framework checklist",
          "A step-by-step procedure for responding to a specific type of alert or incident",
          "The attacker's documented plan of action",
          "A list of approved security tools",
        ],
        answer: 1,
        explanation: "A SOC playbook is a documented, repeatable workflow for a specific alert type — e.g., 'Phishing Email Playbook', 'Ransomware Playbook'. Playbooks reduce response time, ensure consistency, and help junior analysts handle complex scenarios.",
        xp: 10,
      },
      {
        id: "ir_11",
        question: "An attacker has been evicted from the network. Before closing the incident, what critical step is often missed?",
        options: [
          "Rebooting all servers",
          "Scanning all endpoints with antivirus",
          "Checking for additional persistence mechanisms across all systems",
          "Rotating all service account passwords",
        ],
        answer: 2,
        explanation: "Sophisticated attackers plant multiple persistence mechanisms — scheduled tasks, registry run keys, new user accounts, malicious DLLs. Missing any one means re-compromise. A thorough hunt for persistence is essential before declaring eradication complete.",
        xp: 15,
      },
    ],
  },

  // ── 3. Log Analysis & SIEM ────────────────────────────────────────────────
  {
    slug: "log-analysis-siem",
    title: "Log Analysis & SIEM",
    description: "Identify attack patterns from Windows Event Logs, Sysmon, Office 365, firewall logs, and DNS — the core skill of any SOC analyst.",
    difficulty: "Intermediate",
    category: "SOC Fundamentals",
    icon: "📋",
    estimatedMinutes: 15,
    questions: [
      {
        id: "la_01",
        question: "Windows Event ID 4624 indicates a successful logon. Which Event ID indicates a FAILED logon attempt?",
        options: [
          "4625",
          "4648",
          "4720",
          "4776",
        ],
        answer: 0,
        explanation: "Event ID 4625 is a failed logon attempt. Seeing many 4625 events from a single source IP or against a single account in a short period is a strong indicator of brute force or password spraying.",
        xp: 10,
      },
      {
        id: "la_02",
        question: "A Sysmon Event ID 1 (Process Create) log shows: ParentImage: WINWORD.EXE, Image: cmd.exe, CommandLine: 'cmd /c whoami > C:\\Users\\Public\\out.txt'. What is the most likely explanation?",
        options: [
          "A legitimate Office macro running a system command",
          "A malicious macro executing a discovery command — a strong indicator of compromise",
          "A Windows update process spawned by Office",
          "A user running cmd.exe from within Word for scripting purposes",
        ],
        answer: 1,
        explanation: "Office applications (WINWORD.EXE) should never spawn cmd.exe or powershell.exe in normal usage. This pattern — Office as parent, shell as child — is one of the most reliable indicators of a malicious macro executing a command.",
        xp: 15,
      },
      {
        id: "la_03",
        question: "In a SIEM, what does a 'correlation rule' do?",
        options: [
          "It normalizes log formats from different sources into a standard schema",
          "It combines multiple events across sources or time to detect attack patterns",
          "It routes alerts to the correct analyst based on severity",
          "It encrypts log data for compliance",
        ],
        answer: 1,
        explanation: "Correlation rules analyze events across time, users, hosts, and log sources to identify attack sequences that no single event would reveal — e.g., 'failed logins followed by success from the same IP' detects brute force success.",
        xp: 10,
      },
      {
        id: "la_04",
        question: "You observe thousands of DNS queries per minute to subdomains like 'a3f2b1.evil.com', 'd9e7c6.evil.com', each with different long random subdomains. What does this suggest?",
        options: [
          "A misconfigured DNS forwarder",
          "A CDN using DNS-based load balancing",
          "DNS tunneling — data exfiltration or C2 communication encoded in DNS queries",
          "A DDoS attack against the DNS server",
        ],
        answer: 2,
        explanation: "High-entropy subdomains in DNS queries are the hallmark of DNS tunneling. Tools like iodine, dnscat2, and custom C2 frameworks encode data into subdomain labels and TXT record responses. Legitimate DNS traffic does not have thousands of unique high-entropy subdomains.",
        xp: 15,
      },
      {
        id: "la_05",
        question: "What does Windows Event ID 4768 indicate?",
        options: [
          "A Kerberos TGT (Ticket Granting Ticket) was requested",
          "An account was created in Active Directory",
          "A user logged on with explicit credentials",
          "A logon session was terminated",
        ],
        answer: 0,
        explanation: "Event ID 4768 is a Kerberos Authentication Service (AS) Request — someone requested a TGT. This is the first step in Kerberos authentication. Multiple 4768 events for non-existent accounts can indicate Kerberoasting or AS-REP Roasting reconnaissance.",
        xp: 15,
      },
      {
        id: "la_06",
        question: "An Office 365 audit log shows 'Operation: New-InboxRule' with parameters that forward all email to an external address. What attack is this?",
        options: [
          "Business Email Compromise (BEC) — attacker creating a mail forwarding rule for persistent access",
          "Spam campaign from a compromised account",
          "Phishing link sent from the account",
          "Account lockout evasion technique",
        ],
        answer: 0,
        explanation: "New-InboxRule with external forwarding is a classic BEC indicator. After compromising an account, attackers create forwarding rules to silently copy all email — monitoring financial conversations and impersonating the victim. This is a critical alert that requires immediate response.",
        xp: 15,
      },
      {
        id: "la_07",
        question: "What is log normalization in a SIEM context?",
        options: [
          "Deleting logs older than the retention period",
          "Converting logs from different sources into a common data model/schema",
          "Applying statistical analysis to find anomalies",
          "Encrypting logs before storage",
        ],
        answer: 1,
        explanation: "Log normalization (parsing) extracts structured fields from raw log text and maps them to a common schema (like ECS or CEF). This allows a single query to search across Windows, Linux, firewall, and cloud logs using the same field names.",
        xp: 10,
      },
      {
        id: "la_08",
        question: "A firewall log shows 10,000 connection attempts from a single IP to sequential destination ports (22, 23, 25, 80, 443, 445...). What is happening?",
        options: [
          "A legitimate network scanner performing asset inventory",
          "Port scanning — reconnaissance activity mapping open services",
          "A DDoS attack from a botnet",
          "A misconfigured application retrying connections",
        ],
        answer: 1,
        explanation: "Sequential port connections from a single source are a textbook port scan (nmap default behavior). While this could be a legitimate internal scanner, from an external IP or unexpected internal host, it indicates reconnaissance — the first step of many attacks.",
        xp: 10,
      },
      {
        id: "la_09",
        question: "What does 'log retention' policy determine?",
        options: [
          "How many analysts can access logs simultaneously",
          "How long logs are stored before deletion",
          "Which log sources are sent to the SIEM",
          "The maximum size of a single log entry",
        ],
        answer: 1,
        explanation: "Log retention defines how long logs are kept. Compliance frameworks (PCI-DSS: 1 year, GDPR: varies) and forensic needs (average attacker dwell time ~21 days) drive retention requirements. Too short and you can't investigate historical incidents.",
        xp: 10,
      },
      {
        id: "la_10",
        question: "Sysmon Event ID 3 (Network Connection) shows lsass.exe making an outbound connection to 185.220.101.42 on port 443. Why is this suspicious?",
        options: [
          "lsass.exe should not make outbound network connections — this indicates possible credential theft or process injection",
          "lsass.exe regularly communicates with domain controllers over port 443",
          "Port 443 traffic from system processes is normal for Windows Update",
          "This is expected behavior when a user logs on",
        ],
        answer: 0,
        explanation: "lsass.exe (Local Security Authority Subsystem) handles authentication and should NEVER make outbound internet connections. An outbound connection from lsass.exe suggests process injection (e.g., Cobalt Strike beacon injected into lsass) or a credential-stealing tool communicating with C2.",
        xp: 15,
      },
      {
        id: "la_11",
        question: "What is a 'false positive' in SIEM alerting?",
        options: [
          "An alert that correctly identifies a real attack",
          "An alert for a legitimate activity that is incorrectly flagged as malicious",
          "A critical vulnerability that is not detected by any rule",
          "A rule that fires too slowly to be actionable",
        ],
        answer: 1,
        explanation: "A false positive is a SIEM alert that fires on benign activity. High false positive rates cause 'alert fatigue' — analysts start ignoring alerts. Tuning rules to reduce false positives (e.g., whitelisting known admin tools) while maintaining detection coverage is a key SIEM engineering challenge.",
        xp: 10,
      },
      {
        id: "la_12",
        question: "You see Windows Event 4698 (A scheduled task was created) immediately followed by 4702 (A scheduled task was updated) and 4700 (A scheduled task was enabled). What attack pattern does this suggest?",
        options: [
          "Windows Update managing system tasks",
          "A legitimate application installing its update scheduler",
          "Persistence via scheduled task — attacker creating and immediately enabling a task for execution",
          "A Group Policy Object pushing scheduled tasks to endpoints",
        ],
        answer: 2,
        explanation: "The sequence Create → Update → Enable for a scheduled task in a short time window (especially outside change windows or for non-system processes) is a persistence mechanism. Attackers use schtasks.exe to schedule malicious payloads that survive reboots.",
        xp: 15,
      },
    ],
  },

  // ── 4. Threat Intelligence ────────────────────────────────────────────────
  {
    slug: "threat-intelligence",
    title: "Threat Intelligence",
    description: "Understand IOC enrichment, threat actor profiling, intelligence sources, and how to operationalize TI in a SOC environment.",
    difficulty: "Advanced",
    category: "Threat Intelligence",
    icon: "🧠",
    estimatedMinutes: 13,
    questions: [
      {
        id: "ti_01",
        question: "What is the difference between 'strategic' and 'tactical' threat intelligence?",
        options: [
          "Strategic is for technical teams; tactical is for executives",
          "Strategic is high-level trend information for decision-makers; tactical is technical IOCs and TTPs for analysts",
          "Strategic covers nation-state threats; tactical covers cybercriminal groups",
          "Strategic intelligence has a longer shelf life; tactical changes daily",
        ],
        answer: 1,
        explanation: "Strategic TI (industry trends, geopolitical threat landscape) informs executive and board-level decisions. Tactical TI (IPs, hashes, YARA rules, TTPs) is operationalized by analysts in SIEMs, EDR, and firewalls. Both are needed in a mature TI program.",
        xp: 10,
      },
      {
        id: "ti_02",
        question: "Which framework describes the relationship between attacker capabilities, infrastructure, and victims using a diamond shape?",
        options: [
          "Cyber Kill Chain",
          "MITRE ATT&CK",
          "Diamond Model of Intrusion Analysis",
          "PASTA (Process for Attack Simulation and Threat Analysis)",
        ],
        answer: 2,
        explanation: "The Diamond Model has four vertices: Adversary, Capability, Infrastructure, Victim — connected in a diamond shape. It's used to analyze intrusions and understand how changing one vertex affects the others, enabling effective attribution and detection pivoting.",
        xp: 15,
      },
      {
        id: "ti_03",
        question: "What does 'TTPs' stand for in threat intelligence, and why are they more valuable than IOCs?",
        options: [
          "Tactics, Techniques, Procedures — they describe behavior that changes slowly and is harder to evade detection of",
          "Threats, Tools, Processes — they are unique to each threat actor",
          "Targets, Telemetry, Profiles — they describe the victim profile",
          "Tactics, Tools, Payloads — they cover the entire kill chain",
        ],
        answer: 0,
        explanation: "IOCs (IPs, hashes) can be changed cheaply by attackers in minutes. TTPs — the behaviors and methods attackers use — change slowly because they require effort to retool. Detecting TTPs (e.g., 'Office spawning PowerShell') provides durable detection that survives IOC rotation.",
        xp: 15,
      },
      {
        id: "ti_04",
        question: "What is STIX/TAXII used for?",
        options: [
          "Encrypting logs before transmission to a SIEM",
          "Standardized formats for sharing threat intelligence between organizations",
          "Scanning endpoints for known malware signatures",
          "Correlating alerts across different security tools",
        ],
        answer: 1,
        explanation: "STIX (Structured Threat Information eXpression) is the data format for describing threat intelligence objects (indicators, campaigns, threat actors). TAXII (Trusted Automated eXchange of Intelligence Information) is the transport protocol. Together they enable automated TI sharing between organizations and threat feeds.",
        xp: 10,
      },
      {
        id: "ti_05",
        question: "What is the 'Pyramid of Pain' and what does it demonstrate?",
        options: [
          "A severity rating model for vulnerability management",
          "A model showing how difficult it is for attackers to change different types of indicators — from trivial (hashes) to very hard (TTPs)",
          "A risk assessment framework based on attacker impact",
          "A visual showing the cost of a data breach at each stage",
        ],
        answer: 1,
        explanation: "David Bianco's Pyramid of Pain ranks IOC types by how much it 'hurts' the attacker to have them blocked: Hash (trivial) → IP (easy) → Domain (simple) → Network Artifacts (annoying) → Host Artifacts (challenging) → TTPs (tough). The higher you detect, the more resilient your detection.",
        xp: 15,
      },
      {
        id: "ti_06",
        question: "Which free threat intelligence platform provides SHA256 hash lookup, IP reputation, and domain analysis?",
        options: [
          "MISP",
          "VirusTotal",
          "OpenCTI",
          "TAXII Server",
        ],
        answer: 1,
        explanation: "VirusTotal aggregates results from 70+ antivirus engines and provides reputation data for hashes, IPs, domains, and URLs. It's the most widely used free lookup tool in SOC operations. MISP and OpenCTI are TI platforms for managing and sharing intelligence internally.",
        xp: 10,
      },
      {
        id: "ti_07",
        question: "What is a 'threat actor group' in the context of threat intelligence?",
        options: [
          "A group of security analysts tracking a threat",
          "A named cluster of malicious activity attributed to a specific adversary or organization",
          "A collection of malware samples with similar code",
          "A vendor-defined severity tier for vulnerability prioritization",
        ],
        answer: 1,
        explanation: "Threat actor groups (APT28, Lazarus Group, FIN7) are named clusters of attack activity believed to originate from the same adversary. Attribution is based on TTPs, infrastructure, malware, and victimology. Names differ by vendor (Mandiant vs Microsoft vs CrowdStrike).",
        xp: 10,
      },
      {
        id: "ti_08",
        question: "What is 'indicator enrichment' in a SOC workflow?",
        options: [
          "Adding context to a raw IOC — geolocation, WHOIS, reputation score, related campaigns",
          "Encrypting IOCs before sharing with external partners",
          "Removing duplicate indicators from a threat feed",
          "Converting indicators from one format (STIX) to another (CSV)",
        ],
        answer: 0,
        explanation: "Enrichment adds context to raw IOCs: an IP address becomes 'ASN: AS202425, Country: RU, Reputation: malicious, Related campaigns: APT29 SVR'. Enriched IOCs help analysts quickly assess severity and relevance without manual research.",
        xp: 10,
      },
      {
        id: "ti_09",
        question: "APT29 (Cozy Bear) is attributed to which nation-state?",
        options: [
          "China (People's Liberation Army)",
          "North Korea (Lazarus Group)",
          "Russia (SVR Foreign Intelligence Service)",
          "Iran (IRGC)",
        ],
        answer: 2,
        explanation: "APT29 (also called Cozy Bear, Midnight Blizzard, or NOBELIUM) is attributed to Russia's SVR (Foreign Intelligence Service). They are known for the SolarWinds supply chain attack, Microsoft Exchange compromise, and sophisticated long-term espionage campaigns.",
        xp: 10,
      },
      {
        id: "ti_10",
        question: "What does 'confidence level' mean when applied to threat intelligence?",
        options: [
          "How severe the threat is rated on a 1-10 scale",
          "The probability that the intelligence is accurate and the indicator is truly malicious",
          "How quickly the indicator was discovered after the attack",
          "The number of threat feeds that have reported the same IOC",
        ],
        answer: 1,
        explanation: "Confidence level (often High/Medium/Low) expresses how certain analysts are that an IOC or attribution is correct. Low-confidence indicators may have false positive risk. Acting on low-confidence intelligence without verification can waste resources or cause disruption.",
        xp: 10,
      },
    ],
  },

  // ── 5. Network Security ───────────────────────────────────────────────────
  {
    slug: "network-security",
    title: "Network Security & Firewalls",
    description: "Understand firewall rules, network-based attack detection, protocol analysis, and common network attack patterns seen in enterprise environments.",
    difficulty: "Beginner",
    category: "Network",
    icon: "🌐",
    estimatedMinutes: 12,
    questions: [
      {
        id: "ns_01",
        question: "What is the purpose of a DMZ (Demilitarized Zone) in network architecture?",
        options: [
          "To store backup data away from the main network",
          "To isolate publicly accessible servers from the internal network, limiting breach impact",
          "To provide a high-speed network segment for servers",
          "To segment internal users by department",
        ],
        answer: 1,
        explanation: "A DMZ places internet-facing servers (web servers, mail servers, VPN gateways) in a segment separated from the internal LAN by firewalls. If a public server is compromised, the attacker cannot directly reach internal systems — they must breach another firewall.",
        xp: 10,
      },
      {
        id: "ns_02",
        question: "What does a stateful firewall track that a stateless (packet filter) firewall does not?",
        options: [
          "Application layer protocols like HTTP and DNS",
          "The state of network connections — allowing return traffic automatically",
          "User identities and group memberships",
          "Deep packet content for malware signatures",
        ],
        answer: 1,
        explanation: "A stateful firewall maintains a connection table — it tracks TCP sessions (SYN, SYN-ACK, established) and allows return traffic automatically. A stateless firewall evaluates each packet independently, making it easy to bypass with crafted ACK packets.",
        xp: 10,
      },
      {
        id: "ns_03",
        question: "Port 445 is commonly targeted by attackers. Which protocol runs on port 445 and why is it high-value?",
        options: [
          "DNS — it's used for name resolution",
          "RDP — it allows remote desktop access",
          "SMB — it allows file sharing and is targeted for lateral movement and ransomware",
          "LDAP — it provides Active Directory authentication",
        ],
        answer: 2,
        explanation: "Port 445 is SMB (Server Message Block), used for Windows file sharing. Attackers exploit SMB for lateral movement (PsExec, WannaCry, EternalBlue/MS17-010), credential relay attacks (NTLM relay), and ransomware deployment. SMB from workstation-to-workstation should always be blocked.",
        xp: 15,
      },
      {
        id: "ns_04",
        question: "What is a 'beaconing' pattern in network traffic, and why is it significant?",
        options: [
          "A broadcast packet used for device discovery on the local network",
          "Regular, periodic outbound connections to a C2 server indicating malware 'calling home'",
          "An ICMP ping sweep used for network reconnaissance",
          "A legitimate keepalive mechanism used by VPN clients",
        ],
        answer: 1,
        explanation: "Beaconing is when malware makes regular outbound connections to a C2 server (e.g., every 60 seconds ± jitter). The regular interval is the key detection signal. Tools like Cobalt Strike beacon default to 60-second intervals. Network flow analysis can detect this pattern even if the payload is encrypted.",
        xp: 15,
      },
      {
        id: "ns_05",
        question: "What is NTLM relay attack, and which network condition enables it?",
        options: [
          "Capturing Kerberos tickets in transit — enabled by unpatched AD domain controllers",
          "Intercepting NTLM authentication and forwarding it to another server — enabled by NTLM being allowed over the network",
          "Brute-forcing NTLM hashes offline — enabled by weak passwords",
          "Injecting malicious DNS responses — enabled by unsecured DNS servers",
        ],
        answer: 1,
        explanation: "NTLM relay (Responder + ntlmrelayx) intercepts NTLM authentication challenges and relays them to another host to authenticate as the victim. Mitigations: enable SMB signing, disable NTLM where possible, enforce Kerberos. Responder listens on LLMNR/NBT-NS to capture challenges.",
        xp: 15,
      },
      {
        id: "ns_06",
        question: "Which firewall log field helps identify whether a connection was allowed or blocked?",
        options: [
          "source.port",
          "network.protocol",
          "action / disposition",
          "session.duration",
        ],
        answer: 2,
        explanation: "The action field (allow, deny, drop, reject) tells you what the firewall did with the packet. 'allow' means traffic passed; 'deny/drop' means it was blocked. In Palo Alto logs, this is 'action'; in Fortinet, it's 'action'; in Cisco ASA, it's 'Built/Teardown' or 'Deny'.",
        xp: 10,
      },
      {
        id: "ns_07",
        question: "What is a 'split-tunnel VPN' and what security risk does it introduce?",
        options: [
          "A VPN that encrypts only half of the traffic — making it vulnerable to interception",
          "A VPN where only corporate traffic routes through the VPN, while internet traffic goes direct — reducing visibility into user internet activity",
          "A VPN that uses two encrypted tunnels for redundancy",
          "A VPN that splits access between admin and standard user privileges",
        ],
        answer: 1,
        explanation: "Split-tunnel VPN routes corporate traffic through the VPN but allows personal/internet traffic to bypass it. This reduces VPN load but means the organization has no visibility or control over the user's internet activity — a risk if the endpoint is compromised (e.g., C2 traffic bypasses VPN monitoring).",
        xp: 10,
      },
      {
        id: "ns_08",
        question: "What does a high volume of outbound HTTPS traffic to a newly registered domain with a self-signed certificate suggest?",
        options: [
          "A user streaming video from a new streaming service",
          "Legitimate software update traffic",
          "Possible C2 communication — attackers often use new domains and self-signed certs to avoid reputation blocks",
          "A misconfigured proxy server",
        ],
        answer: 2,
        explanation: "New/recently registered domains (< 30 days old) combined with self-signed TLS certificates are a classic C2 pattern. Legitimate services use CA-signed certificates and have established domain age. These are high-fidelity indicators worth investigating, especially with unusual traffic volumes.",
        xp: 15,
      },
      {
        id: "ns_09",
        question: "What is the purpose of Network Access Control (NAC)?",
        options: [
          "To filter web content for users accessing the internet",
          "To enforce policy-based access — only compliant, authenticated devices can connect to the network",
          "To block DDoS attacks at the network perimeter",
          "To log all network traffic for forensic analysis",
        ],
        answer: 1,
        explanation: "NAC checks device compliance (patch level, AV installed, certificate) before granting network access. Non-compliant devices are quarantined. It prevents rogue or unmanaged devices from accessing the corporate network — critical for zero-trust enforcement.",
        xp: 10,
      },
      {
        id: "ns_10",
        question: "Which port and protocol does Kerberos use?",
        options: [
          "TCP/UDP 389 — LDAP",
          "TCP/UDP 88 — Kerberos",
          "TCP 445 — SMB",
          "UDP 123 — NTP",
        ],
        answer: 1,
        explanation: "Kerberos uses TCP and UDP port 88 for ticket requests and responses. Port 88 traffic to domain controllers is normal; excessive AS-REQ (4768) or TGS-REQ (4769) volume, especially for service accounts, may indicate Kerberoasting or AS-REP Roasting.",
        xp: 10,
      },
      {
        id: "ns_11",
        question: "An IDS alert fires for 'ET SCAN Nmap SYN Scan'. What does this mean and should it be treated as a critical incident?",
        options: [
          "Yes — Nmap scans always indicate an active attack and require immediate containment",
          "No — this is a rule for detecting port scans; triage is needed to determine if it's authorized scanning or malicious reconnaissance",
          "No — Nmap is a legitimate tool only used by system administrators",
          "Yes — Nmap always precedes ransomware deployment",
        ],
        answer: 1,
        explanation: "An Nmap SYN scan alert requires triage: Is the source IP an authorized scanner (vulnerability scanner, asset management tool)? Is it external or internal? External Nmap scans are suspicious; internal scans may be authorized. Context determines severity — not the alert alone.",
        xp: 15,
      },
    ],
  },

  // ── 6. Cloud & Identity Security ──────────────────────────────────────────
  {
    slug: "cloud-identity-security",
    title: "Cloud & Identity Security",
    description: "Azure AD, Entra ID, OAuth, MFA bypass techniques, and cloud-specific attack patterns — essential knowledge for modern enterprise SOC analysts.",
    difficulty: "Advanced",
    category: "Cloud Security",
    icon: "☁️",
    estimatedMinutes: 15,
    questions: [
      {
        id: "ci_01",
        question: "What is 'MFA Fatigue' (also called MFA Bombing)?",
        options: [
          "A technique where the attacker steals MFA tokens from the authenticator app",
          "Spamming a victim with MFA push notifications until they approve one out of frustration or confusion",
          "Disabling MFA policies in Azure AD to bypass authentication",
          "Phishing the victim's MFA backup codes via email",
        ],
        answer: 1,
        explanation: "MFA Fatigue involves sending repeated push notifications to the victim's authenticator app. Attackers (like Lapsus$) used this to compromise Uber, Cisco, and others. Mitigations: number matching, additional context in MFA prompts, push notification limits.",
        xp: 15,
      },
      {
        id: "ci_02",
        question: "What is OAuth consent phishing and how does it differ from credential phishing?",
        options: [
          "It steals credentials via a fake login page, bypassing MFA",
          "It tricks users into granting a malicious app OAuth permissions to their account, giving the attacker API-level access without needing the password",
          "It intercepts OAuth tokens in transit using a man-in-the-middle attack",
          "It exploits a vulnerability in the OAuth 2.0 protocol",
        ],
        answer: 1,
        explanation: "OAuth consent phishing bypasses MFA entirely — the attacker creates a malicious app and sends a legitimate-looking OAuth consent URL. If the user approves, the attacker gets an API token. No password is stolen and MFA is irrelevant. Detected via 'Consent to application' events in Azure AD logs.",
        xp: 15,
      },
      {
        id: "ci_03",
        question: "In Azure AD logs, what does the Office 365 operation 'Add service principal' indicate?",
        options: [
          "A new user account was created",
          "An application was registered and given an identity in the tenant — can be used for persistent access",
          "A service account password was reset",
          "A conditional access policy was modified",
        ],
        answer: 1,
        explanation: "Adding a service principal creates an application identity in the tenant. Attackers who compromise privileged accounts may register malicious apps with persistent delegated or application permissions — allowing API access that survives password resets. Monitor for unexpected app registrations.",
        xp: 15,
      },
      {
        id: "ci_04",
        question: "What is 'Conditional Access' in Azure AD and why is it important for security?",
        options: [
          "A firewall rule system for Azure virtual networks",
          "Policy-based access control that enforces conditions (device compliance, location, risk level) before granting access",
          "Multi-factor authentication configuration for all users",
          "A feature that automatically blocks suspicious sign-ins",
        ],
        answer: 1,
        explanation: "Conditional Access is Azure AD's zero-trust enforcement engine. Policies define who can access what, from where, under what conditions — e.g., 'Require MFA for all cloud app access from non-compliant devices'. It can block sign-ins from risky locations or require device compliance.",
        xp: 10,
      },
      {
        id: "ci_05",
        question: "An Azure AD sign-in log shows RiskLevel: 'high' and RiskState: 'atRisk' for an admin account signing in from an anonymous IP. What should the SOC do?",
        options: [
          "Ignore it — Azure AD risk scores have a high false positive rate",
          "Immediately suspend the account and investigate for compromise indicators",
          "Send an email to the admin asking if the sign-in was legitimate",
          "Enable MFA for the account before taking further action",
        ],
        answer: 1,
        explanation: "High-risk admin sign-in from anonymous IP (Tor, VPN) is a critical signal. Admin accounts are the keys to the kingdom — immediate suspension prevents an attacker with these credentials from causing further damage. Investigate in parallel. Don't wait for the user to respond — the account may be compromised.",
        xp: 15,
      },
      {
        id: "ci_06",
        question: "What is the difference between 'delegated permissions' and 'application permissions' in Microsoft Graph API?",
        options: [
          "Delegated permissions require a user to be signed in; application permissions allow the app to access data without a user context",
          "Delegated permissions are for admins; application permissions are for regular users",
          "Application permissions require MFA; delegated permissions bypass it",
          "There is no security difference — both grant the same access level",
        ],
        answer: 0,
        explanation: "Delegated permissions act on behalf of a signed-in user (limited to what that user can access). Application permissions allow the app to access all tenant data regardless of which user is signed in — making them extremely powerful and attractive to attackers (e.g., Mail.ReadAll without impersonating any user).",
        xp: 15,
      },
      {
        id: "ci_07",
        question: "What is 'Pass-the-Cookie' attack in cloud environments?",
        options: [
          "Stealing browser cookies containing authenticated session tokens to bypass MFA and access cloud services",
          "Passing NTLM hashes between systems using Kerberos tickets",
          "Injecting malicious cookies into a web application",
          "Stealing OAuth refresh tokens from mobile applications",
        ],
        answer: 0,
        explanation: "Pass-the-Cookie (or token theft) extracts browser session cookies that prove authentication has already occurred — including MFA. Attackers steal these cookies (via malware like Evilginx, AiTM phishing, or browser stealers) and import them to authenticate as the victim without needing credentials or MFA.",
        xp: 15,
      },
      {
        id: "ci_08",
        question: "Azure AD Privileged Identity Management (PIM) provides which security capability?",
        options: [
          "Continuous monitoring of all Azure resource configurations",
          "Just-in-time privileged access — requiring approval and providing time-limited admin roles",
          "Automated threat response for identity-based attacks",
          "Certificate-based authentication for service accounts",
        ],
        answer: 1,
        explanation: "PIM implements just-in-time (JIT) access — users don't permanently hold privileged roles. They activate them when needed (with approval and justification), for a limited time window. This dramatically reduces standing privilege exposure and forces audit trails for privileged actions.",
        xp: 10,
      },
      {
        id: "ci_09",
        question: "What does a 'Global Administrator' role in Azure AD/Entra ID allow?",
        options: [
          "Read access to all Azure resources across the tenant",
          "Administrative control over all Microsoft 365 services and the ability to reset passwords for any user including other Global Admins",
          "Management of Azure virtual machines and subscriptions",
          "Access to billing and subscription management only",
        ],
        answer: 1,
        explanation: "Global Administrator is the highest privilege in Azure AD — it can reset any user's password, grant any role, access any service, and modify security policies. Compromise of a Global Admin account gives the attacker full tenant control. Best practice: use PIM, require Phishing-Resistant MFA (FIDO2), break-glass accounts only.",
        xp: 10,
      },
      {
        id: "ci_10",
        question: "What is 'Password Spray' and how does it differ from brute force?",
        options: [
          "Password spray tries many passwords against one account; brute force tries one password against many accounts",
          "Password spray tries one common password against many accounts to avoid account lockouts; brute force tries many passwords against one account",
          "Password spray only works against cloud accounts; brute force only works against on-premises AD",
          "There is no difference — both are the same attack",
        ],
        answer: 1,
        explanation: "Password spray avoids account lockout by trying one or a few common passwords (Password1!, Summer2024) across thousands of accounts. Each account only sees 1-2 failed attempts — below the lockout threshold. Detected in logs as many 4625/UserLoginFailed events spread across accounts from a single IP.",
        xp: 10,
      },
      {
        id: "ci_11",
        question: "Which Azure AD log source would show evidence of a successful Pass-the-Cookie attack?",
        options: [
          "Azure Activity Log",
          "Azure AD Audit Log showing 'Update user' operations",
          "Azure AD Sign-in Log showing token-based authentication without MFA in an unexpected location",
          "Microsoft 365 Message Trace",
        ],
        answer: 2,
        explanation: "Pass-the-Cookie uses a stolen session token — so the sign-in log will show a successful authentication (no MFA required since the cookie already has a valid session) from an unexpected location or device. Key signals: different country than usual, unfamiliar device, sign-in method shows 'Previously satisfied'.",
        xp: 15,
      },
      {
        id: "ci_12",
        question: "What is the 'principle of least privilege' in cloud IAM and why is it critical?",
        options: [
          "Users should have the minimum permissions needed for their job — no more",
          "All users should start with no permissions and request access only when needed",
          "Privileged accounts should be limited to administrators only",
          "Cloud resources should only be accessible from the corporate network",
        ],
        answer: 0,
        explanation: "Least privilege limits the blast radius of any single compromised account. If a developer only has read access to their project's S3 bucket, a breach of that account can't access other buckets or services. Over-privileged identities are the #1 cloud security risk — attackers hunt for them specifically.",
        xp: 10,
      },
    ],
  },
];

// Quiz packs live in their own files so the catalogue can grow without this one
// becoming unreviewable. Everything that reads QUIZZES — the index, the admin
// content manager, getQuiz — picks them up from here automatically.
import { QUIZZES_ENDPOINT_IDENTITY } from "./data-endpoint-identity";
import { QUIZZES_DETECTION_APPSEC } from "./data-detection-appsec";

export const ALL_QUIZZES: Quiz[] = [
  ...QUIZZES,
  ...QUIZZES_ENDPOINT_IDENTITY,
  ...QUIZZES_DETECTION_APPSEC,
];

export function getQuiz(slug: string): Quiz | undefined {
  return ALL_QUIZZES.find(q => q.slug === slug);
}
