// AUTO-GENERATED by scripts/generate-scenarios-meta.mjs — do not hand-edit.
// Client-safe list of built-in scenarios: NO answers, explanations, IOCs,
// events, attack_kind or threat_actor. Client components import this instead of
// "@/lib/sim/scenarios" (which bundles every scenario pack and its answer key).
// Regenerate: npx tsx scripts/generate-scenarios-meta.mjs

export interface ScenarioMeta {
  slug: string;
  title: string;
  difficulty: string;
  summary: string;
}

export const SCENARIOS_META: ScenarioMeta[] = [
  {
    "slug": "phishing-malware-basic",
    "title": "Phishing Attachment → Malware Execution → Workstation Compromise",
    "difficulty": "beginner",
    "summary": "An everyday phishing email leads to a disguised .pdf.exe running on one workstation — the simplest attack in the platform, single host, no lateral movement."
  },
  {
    "slug": "usb-malware-basic",
    "title": "Malicious USB Drive → Trojan Persistence → Workstation Compromise",
    "difficulty": "beginner",
    "summary": "An untagged USB drive delivers a trojan that sets up Registry Run key persistence on one workstation before EDR catches it."
  },
  {
    "slug": "phishing-to-cloud-exfil",
    "title": "Phishing Macro → AWS Key Theft → S3 Download",
    "difficulty": "intermediate",
    "summary": "A finance analyst opens a macro-laced invoice. Trace the chain from Word → PowerShell → the AWS key on the workstation → a 184 MB S3 download, and contain both the host and the key."
  },
  {
    "slug": "bec-mailbox-rule",
    "title": "Password Spray → BEC Mailbox Rule",
    "difficulty": "beginner",
    "summary": "Spot the spray, the off-hours MFA acceptance, and the hidden inbox rule before a $247K wire fraud lands."
  },
  {
    "slug": "ransomware-lockbit",
    "title": "Ransomware Outbreak — LockBit 3.0",
    "difficulty": "advanced",
    "summary": "Trace LockBit from a late-night phishing email through LSASS dump, PsExec lateral movement, shadow copy deletion, and 18GB of file encryption."
  },
  {
    "slug": "oauth-app-persistence",
    "title": "OAuth App Persistence — Cloud APT",
    "difficulty": "advanced",
    "summary": "A rogue OAuth app survives a password reset — silently exfiltrating 340MB of product roadmaps via Microsoft Graph API."
  },
  {
    "slug": "insider-threat-finance",
    "title": "Bulk Finance Downloads and Removable Media — WS-FIN-4421",
    "difficulty": "intermediate",
    "summary": "DLP flagged a burst of downloads from a finance share, and removable media was mounted on the same workstation minutes later. Establish what happened and whether it was authorised."
  },
  {
    "slug": "kerberoasting",
    "title": "Kerberoasting → Service Account Compromise",
    "difficulty": "advanced",
    "summary": "A developer's account enumerates SPNs via LDAP, requests 12 TGS tickets using weak RC4 encryption, cracks svc-mssql offline, and executes code via xp_cmdshell."
  },
  {
    "slug": "dns-tunneling",
    "title": "DNS Tunneling — C2 via DNS",
    "difficulty": "advanced",
    "summary": "An attacker uses dnscat2 to exfiltrate data via DNS — 847 queries/minute with base32-encoded subdomains carrying stolen credentials to an attacker-controlled domain."
  },
  {
    "slug": "lolbins",
    "title": "Living-off-the-Land (LOLBins)",
    "difficulty": "advanced",
    "summary": "A 7-step LOLBin chain: certutil download → regsvr32 Squiblydoo → mshta VBScript → wmic recon → bitsadmin persistence → rundll32 DLL → schtasks SYSTEM task."
  },
  {
    "slug": "aws-key-leak-s3-exfil",
    "title": "Leaked AWS Key → IAM Backdoor → S3 Data Theft",
    "difficulty": "advanced",
    "summary": "A CI access key pushed to a public GitHub repo is used from a VPS within minutes: recon, a new IAM user with its own key and AdministratorAccess, then a GetObject run on the customer-data bucket. Follow the key ids from the leak to the bucket and contain both credentials."
  },
  {
    "slug": "dcsync-golden-ticket",
    "title": "DCSync → Golden Ticket (Domain Dominance)",
    "difficulty": "advanced",
    "summary": "APT uses stolen IT admin credentials to DCSync the domain controller, extract the krbtgt hash, forge a 10-year Golden Ticket, create a shadow admin, and wipe Security logs — full domain compromise in 25 minutes."
  },
  {
    "slug": "supply-chain-vendor-update",
    "title": "Supply Chain Attack — Malicious Vendor Update",
    "difficulty": "advanced",
    "summary": "A trojanized vendor update installs a malicious shared object disguised as telemetry, establishes C2, steals AWS credentials, and exfiltrates 2.3GB of production data — all via a legitimately-signed package."
  },
  {
    "slug": "mfa-fatigue-ato",
    "title": "MFA Fatigue → Okta Account Takeover",
    "difficulty": "beginner",
    "summary": "UNC3944 bombards Jennifer Chen with 60 MFA push notifications until she approves at 1:32 AM. Within minutes the attacker enrolls a new device, bulk-downloads 847 SharePoint files, creates a persistent API token, and modifies Conditional Access policies — all from a Moscow IP."
  },
  {
    "slug": "asrep-roasting",
    "title": "AS-REP Roasting → Offline Hash Crack",
    "difficulty": "intermediate",
    "summary": "APT28 foothold on WS-DEV-09 discovers 3 service accounts with Kerberos pre-auth disabled. Impacket GetNPUsers.py captures RC4-encrypted TGT hashes offline. Six hours later the cracked svc-backup password enables lateral movement to NTDS.dit."
  },
  {
    "slug": "ntlm-relay-responder",
    "title": "NTLM Relay — Internal Credential Hijacking",
    "difficulty": "advanced",
    "summary": "An LLMNR poisoner on WS-DEV-09 intercepts l.nguyen's NTLM authentication and relays it to SRV-FILE01. Remote SYSTEM execution via PsExec, LSASS dump with 0x1FFFFF access, and SMB pivot to 3 internal servers — no external C2."
  },
  {
    "slug": "k8s-pod-escape-imds",
    "title": "Kubernetes Pod Escape → Cloud Metadata Theft",
    "difficulty": "advanced",
    "summary": "Compromised CI/CD token gives APT40 kubectl exec into production. nsenter escapes to EC2 host, curl to 169.254.169.254 steals IAM credentials. Attacker enumerates S3 buckets from Tor IP, downloads db-passwords.json, and backdoors both the cluster and IAM."
  },
  {
    "slug": "oauth-consent-grant-phishing",
    "title": "OAuth Consent Grant Phishing — Silent BEC",
    "difficulty": "expert",
    "summary": "j.chen clicks a phishing link and grants 'Productivity Suite Pro' (48h-old unverified app on typosquat domain) Mail.ReadWrite + Files.ReadWrite.All. The app silently reads 1,247 emails, copies 312 SharePoint files, creates an inbox forwarding rule, and maps the org via Calendar — no malware, no suspicious IPs, 100% Microsoft Graph API."
  },
  {
    "slug": "backup-agent-false-positive",
    "title": "Mass File Encryption Alert — Enterprise Backup Agent",
    "difficulty": "beginner",
    "summary": "A CRITICAL ransomware-behaviour alert on a production file server. Every scenario before this one was a real attack — this one is not, and the job is to prove it."
  },
  {
    "slug": "brute-force-single-account",
    "title": "Logon Failure Burst — Published Remote Desktop Server",
    "difficulty": "beginner",
    "summary": "Hundreds of failed logons against one account, and then one that succeeds. The failures are the noise; finding the success — and what the session did next — is the job."
  },
  {
    "slug": "rogue-admin-account",
    "title": "Out-of-Hours Account Creation — Service Desk Credentials",
    "difficulty": "beginner",
    "summary": "A privileged account is created at 22:47 by an admin who is allowed to create accounts. Nothing here is technically forbidden — the question is whether it was authorised."
  },
  {
    "slug": "impossible-travel-basic",
    "title": "Sign-In From Two Countries — Accounts Payable Clerk",
    "difficulty": "beginner",
    "summary": "The same account signs in from Tel Aviv and then Amsterdam hours apart. Impossible travel is a hypothesis, not a verdict — the telemetry decides whether it is a VPN artefact or a real takeover."
  },
  {
    "slug": "software-install-false-positive",
    "title": "Unsigned Binary Writes to Program Files — Engineering Workstation",
    "difficulty": "beginner",
    "summary": "An EDR rule fires HIGH on behaviour that genuinely overlaps with a dropper. Closing an alert correctly needs evidence just as rigorous as opening one."
  },
  {
    "slug": "web-shell-sqli",
    "title": "SQL Injection → Web Shell → Server Compromise",
    "difficulty": "advanced",
    "summary": "The WAF blocked the obvious payloads and missed the one that worked. Pivot between WAF, IIS, SQL audit and EDR to find how a web shell reached the server."
  },
  {
    "slug": "linux-ssh-persistence",
    "title": "Exposed SSH → Cron-Persisted Backdoor",
    "difficulty": "intermediate",
    "summary": "A Linux server intrusion read through sshd, auditd, Falcon and the firewall rather than Windows telemetry — the login that worked comes from an address that never failed, and the flagged process checks in every five minutes."
  },
  {
    "slug": "aitm-token-theft",
    "title": "Adversary-in-the-Middle Phishing — Session Token Theft",
    "difficulty": "advanced",
    "summary": "MFA was satisfied correctly and the account still fell. One session id, two browsers, 365 km apart, six minutes apart."
  },
  {
    "slug": "esxi-ransomware",
    "title": "Hypervisor Ransomware — ESXi Datastore Encryption",
    "difficulty": "expert",
    "summary": "Ninety-six VMs go dark at once and the endpoint EDR sees nothing, because there is no agent on the hypervisor. Reason from the telemetry that stopped arriving."
  },
  {
    "slug": "okta-password-burst",
    "title": "Sign-In Failure Burst — Okta Tenant, One Account",
    "difficulty": "beginner",
    "summary": "The attacker never got in — and the password is still compromised. One field on one sign-in event separates 'blocked, no impact' from a credential you have to reset."
  },
  {
    "slug": "fake-browser-update",
    "title": "Fake Browser Update — Drive-by on a Trusted Site",
    "difficulty": "beginner",
    "summary": "The site that started this is real, categorised business-and-economy, and read by half the department. Nothing in the first four minutes looks like an attack if you are hunting bad domains."
  },
  {
    "slug": "trojanized-installer-keylogger",
    "title": "Free PDF Tool — Trojanized Installer with a Keylogger",
    "difficulty": "beginner",
    "summary": "The installer is signed and the PDF tool genuinely works. It also drops a second binary that reads what she types into her browser."
  },
  {
    "slug": "multi-host-intrusion",
    "title": "Multi-Host Intrusion — Foothold, Lateral Move, Staging",
    "difficulty": "advanced",
    "summary": "One operator, three hosts, three separate EDR incidents in forty minutes — foothold, an LSASS dump on the file server, and gigabytes staged and pushed out. Investigate each host as its own case, then tie them into one campaign."
  },
  {
    "slug": "ai-llmjacking-bedrock",
    "title": "LLMjacking — Stolen CI Key Used for Bedrock Inference",
    "difficulty": "advanced",
    "summary": "A cost alert and a GuardDuty finding land on QuantumBank's AWS account overnight. Work out from CloudTrail and the Bedrock logs what the CI service identity was used for, by whom, and what the logs no longer show."
  },
  {
    "slug": "gws-phishing-attachment",
    "title": "Shared Invoice — Malicious Attachment via Google Workspace",
    "difficulty": "beginner",
    "summary": "SPF, DKIM and DMARC all passed, because the supplier's domain really did send it. The mailbox belongs to someone else now."
  },
  {
    "slug": "seo-poisoned-installer",
    "title": "Sponsored Result — SEO-Poisoned PuTTY Download",
    "difficulty": "beginner",
    "summary": "An admin searched for a tool she installs all the time and clicked the top result. The domain was registered last week — and by the time Defender flagged it, the browser-saved credentials were already gone."
  },
  {
    "slug": "iso-container-smuggling",
    "title": "Invoice.iso — Container-Delivered LNK and LOLBin Chain",
    "difficulty": "beginner",
    "summary": "The firewall only logged the .iso because it is not on the block list. Windows tags the files inside it (the Nov-2022 fix) and warns — but the user clicks Run anyway, and the shortcut runs rundll32 against a bundled data file, so SmartScreen never re-gates it."
  },
  {
    "slug": "clickfix-fake-captcha",
    "title": "Fake CAPTCHA — 'Paste This to Verify You're Human'",
    "difficulty": "beginner",
    "summary": "The 'verification' step told her to press Win+R and paste — and she did. The command she never saw was already on her clipboard, put there by the page."
  },
  {
    "slug": "scheduled-task-persistence",
    "title": "Speed-Boost Script — Persistence via a Scheduled Task",
    "difficulty": "beginner",
    "summary": "One PowerShell script promising a faster VPN. Its real job was a single schtasks command — so that even after a reboot and an AV sweep, it runs again every logon."
  },
  {
    "slug": "infostealer-session-theft",
    "title": "Free Converter, Stolen Session — Infostealer Cookie Theft & Replay",
    "difficulty": "intermediate",
    "summary": "A free PDF converter that never installs anything, but copies Chrome's saved-password and cookie databases and ships them out. Five minutes later her session is replayed from Moscow — no password, no MFA prompt, because the stolen cookie already satisfied it."
  },
  {
    "slug": "helpdesk-mfa-reset",
    "title": "Help Desk MFA Reset — Social Engineering Account Takeover",
    "difficulty": "intermediate",
    "summary": "A phone call to the service desk, a reset MFA, and a new authenticator enrolled from an IP the employee has never used — while her real session is still active elsewhere. The ticket that 'fixed' an access problem is the breach."
  },
  {
    "slug": "edge-vpn-cve-exploit",
    "title": "Edge Appliance Exploitation — FortiOS SSL-VPN Auth Bypass to Internal Foothold",
    "difficulty": "advanced",
    "summary": "The FortiGate SSL-VPN appliance's own IPS fires CVE-2022-40684 and its event log records admin access as Local_Process_Access, then a new rogue admin. An hour later a 'valid' VPN login's tunnel IP turns up as a 4624 on an internal jump host, then a SAM dump and SMB reach. The initial access is the appliance itself."
  },
  {
    "slug": "exfil-first-extortion",
    "title": "Exfiltration-First Extortion — Ransomware Without an Encryptor",
    "difficulty": "advanced",
    "summary": "Mass file reads, a 7-Zip archive, and a sustained upload to a cloud-storage host — then a demand. Nothing is encrypted and no ransom note lands on disk, which is exactly why grading this by 'what did they break' misses that it is a ransomware-class incident."
  },
  {
    "slug": "windows-privesc-token",
    "title": "SYSTEM in Twelve Seconds — Token Impersonation on an IIS Host",
    "difficulty": "intermediate",
    "summary": "A non-admin IIS service account holds SeImpersonatePrivilege — and turns it into a SYSTEM shell via a named-pipe potato attack, then dumps the local SAM. The loud SAM export is downstream; the quiet 4672 is where it began."
  },
  {
    "slug": "linux-privesc-suid",
    "title": "www-data to Root — SUID find on an Ubuntu App Server",
    "difficulty": "intermediate",
    "summary": "A www-data foothold escalates to root by abusing a setuid /usr/bin/find (GTFOBins), reads /etc/shadow, and plants a uid-0 backdoor account — proven from auditd uid/euid/auid and a Falcon privilege-escalation detection."
  },
  {
    "slug": "lateral-movement-pth",
    "title": "Pass-the-Hash to the File Server, Second Hop to the DC",
    "difficulty": "intermediate",
    "summary": "An operator replays a stolen NTLM hash to log into a file server without a password, installs a remote service PsExec-style, and hops to a Domain Controller — learn to tell a pass-the-hash 4624 from a legitimate network logon."
  },
  {
    "slug": "insider-dlp-usb-cloud",
    "title": "Last Week on the Job — Insider Exfil via USB and Personal Cloud",
    "difficulty": "intermediate",
    "summary": "A departing Senior Financial Analyst copies labeled client data to a personal USB stick and uploads it to consumer Dropbox — every action allowed under his own account because Purview DLP is in Audit mode. Reach the verdict from audit-only DLP + HR context, not from any control that blocked."
  },
  {
    "slug": "nac-rogue-device",
    "title": "The Printer That Wasn't — Rogue Device Caught by NAC",
    "difficulty": "beginner",
    "summary": "A rogue Windows laptop spoofs an HP printer's MAC to bypass MAB onto the corporate LAN; Cisco ISE profiling catches the OUI/fingerprint mismatch, posture fails, and NAC quarantines the port."
  },
  {
    "slug": "macos-stealer-dmg",
    "title": "macOS Stealer — a 'Cracked' App DMG Harvests Keychain, Cookies and Wallets",
    "difficulty": "intermediate",
    "summary": "A pirated-app DMG carries an Atomic/AMOS-family stealer: it mounts, phishes the user's macOS password through a fake osascript dialog, then reads the login Keychain, browser cookies and a crypto wallet before zipping it all to an external host. A signed, notarized install of the same shape is the benign control — the malice is the source, not the file type."
  },
  {
    "slug": "sqli-db-exfil",
    "title": "SQL Injection to Database Exfiltration — Following the Attack Past the WAF",
    "difficulty": "advanced",
    "summary": "The WAF blocks the obvious ' OR 1=1 probe but the UNION and error-based payloads sail through a detection-mode rule — and the database audit shows what the WAF alert alone cannot: schema enumeration, a 248k-row PII dump, and xp_cmdshell OS execution. Learn to follow the injection past the perimeter into the DB where the data actually left."
  },
  {
    "slug": "azure-managed-identity-abuse",
    "title": "Azure App-Registration Credential Abuse — the Quiet Secret-Add Behind a Cloud Data-Access Alert",
    "difficulty": "advanced",
    "summary": "An attacker appends a new client secret to an over-permissioned Entra app registration, then authenticates non-interactively to Graph and ARM to enumerate the subscription, grant itself a role, and read Key Vault secrets and Storage keys. The loud data-access alert traces back to one quiet 'Add service principal credentials' audit line — a legitimate Terraform rotation is the benign look-alike."
  },
  {
    "slug": "cicd-supply-chain",
    "title": "Poisoned Pipeline — CI/CD Supply-Chain Compromise into the Cloud",
    "difficulty": "advanced",
    "summary": "A compromised maintainer mints a PAT, registers an attacker-controlled self-hosted runner, and pushes a workflow change through a branch-protection override — then the run trades its GitHub OIDC token for an AWS deploy role and reads S3 and Secrets Manager from outside AWS, which is what GuardDuty finally catches. An approved PR editing the same workflow is the benign control."
  },
  {
    "slug": "ueba-compromised-account",
    "title": "Behavioral Risk First — a UEBA-led Account-Compromise Hunt",
    "difficulty": "intermediate",
    "summary": "The investigation starts not from a signature alert but from a Sentinel UEBA risk score: impossible travel, a mass SharePoint download, and a new inbox-forwarding rule on one entity. Pivot from the anomaly into the Entra sign-in and O365 audit to confirm a real token-replay compromise — and contrast it with a benign impossible-travel anomaly (corporate VPN, approved travel) that scores high but is not an attack."
  },
  {
    "slug": "vishing-rmm",
    "title": "Callback Vishing — RMM Install to Hands-on-Keyboard Discovery",
    "difficulty": "intermediate",
    "summary": "A caller posing as IT security talks a payments clerk into installing signed, legitimate AnyDesk, then runs AD discovery hands-on-keyboard. The binary is trusted and the signature is valid — the signal is the context: an unsolicited install right after an inbound call, an RMM the bank does not deploy. A sanctioned ScreenConnect support session is the benign control of the identical shape."
  },
  {
    "slug": "pam-vault-abuse",
    "title": "PAM Vault Abuse — an Off-Hours Domain-Admin Checkout Used Outside PSM",
    "difficulty": "advanced",
    "summary": "A CyberArk-vaulted domain-admin credential is retrieved off-hours with no dual-control and no change record, then replayed straight into servers — bypassing the monitored PSM proxy that policy requires. A privileged logon alone looks normal; the tell is the checkout record plus the credential used outside PSM. An approved break-glass checkout of the same account is the benign control."
  },
  {
    "slug": "destructive-wiper",
    "title": "Destructive Wiper — an Endpoint Bricked, and No Way to Pay for It Back",
    "difficulty": "advanced",
    "summary": "It looks ransomware-adjacent — mass file overwrites, shadow copies deleted, recovery disabled, event logs cleared — but there is no ransom note, no key, and no decryptor C2, because the goal is destruction, not extortion. Learn to tell a wiper from ransomware by the absence of any recovery path, and why the response is rebuild-from-backup rather than negotiate. A change-ticketed IT secure-wipe is the benign control."
  },
  {
    "slug": "s3-exfil-exposure",
    "title": "Exposed Bucket — S3 Made Public, Then Emptied",
    "difficulty": "intermediate",
    "summary": "A leaked IAM key disables Block Public Access and rewrites the bucket policy to public, then bulk-downloads tens of thousands of objects — and GuardDuty raises anonymous-access and exfiltration findings. The config-change management events are the origin; the GetObject burst from an internet address is the blast radius. A backup service role reading the same bucket from inside AWS is the benign control."
  },
  {
    "slug": "golden-saml",
    "title": "Golden SAML — a Federation Token With No Matching AD FS Issuance",
    "difficulty": "expert",
    "summary": "An attacker who owns the AD FS server steals the token-signing key and mints SAML assertions for privileged users straight to the cloud — no real logon at the identity provider. The defining tell is an absence: a federated sign-in accepted by Entra with no matching AD FS token-issuance event on-prem, and MFA satisfied by a claim already inside the token. A legitimate federated sign-in that does have its issuance record is the benign control."
  },
  {
    "slug": "gws-oauth-marketplace",
    "title": "Consent, Not Credentials — a Malicious OAuth App in Google Workspace",
    "difficulty": "intermediate",
    "summary": "A user is phished into authorizing a broad-scope OAuth app; the consent issues an offline refresh token that reads their mailbox and exfiltrates Drive over the API — no password, MFA irrelevant, and it survives the password reset the help desk tries. The consent grant is the persistence; the API access is the impact. A narrow-scope, admin-allowlisted app the user consents to normally is the benign control."
  },
  {
    "slug": "threat-intel-hunt",
    "title": "Threat-Intel Hunt — From a Recorded Future IOC Set to a Live Beacon",
    "difficulty": "intermediate",
    "summary": "This case opens with intelligence, not an alert: a Recorded Future risk-list update names a C2 domain, an IP and a malware hash tied to an active campaign. Sweep the estate and one workstation lights up — DNS to the C2, periodic proxy beacons, and the exact hash running on the host. Learn intel→sweep→confirm, and why a second host that matched a now-sinkholed indicator is a false hit, not a compromise."
  },
  {
    "slug": "mobile-mdm-compromise",
    "title": "Mobile in the Blind Spot — an Intune-Managed Phone Goes Rogue",
    "difficulty": "intermediate",
    "summary": "A smishing link leads to a sideloaded app and a rooted device; Intune's mobile-threat signal fires and the device flips non-compliant, yet corporate mail and files are still reached because the Entra sign-in shows a Conditional-Access gap — a non-compliant device getting success. The analyst reaches the verdict from Intune compliance + Entra sign-ins, not a host process tree. A phone that briefly went non-compliant for a pending OS update is the benign control."
  },
  {
    "slug": "gcp-sa-key-theft",
    "title": "Minted Key — Service-Account Key Theft on GCP",
    "difficulty": "advanced",
    "summary": "A compromised developer identity mints a long-lived user-managed key on an over-permissioned service account, then the acting principal switches to that SA to read the datalake and Secret Manager — all from an external IP. The quiet CreateServiceAccountKey admin-activity line is the pivot; the data reads are the blast radius. A Terraform CI service account creating a key from inside the pipeline is the benign control."
  },
  {
    "slug": "macos-tcc-pkg",
    "title": "macOS TCC Bypass — a Fake .pkg Rewrites the Privacy Database and Persists as a LaunchDaemon",
    "difficulty": "intermediate",
    "summary": "A fake meeting-app installer package runs a root postinstall script that rewrites the TCC privacy database to grant itself Full Disk Access and Screen Recording, then installs a LaunchDaemon for boot persistence and reads protected user data. The tells are the root install-script, the TCC.db manipulation and the daemon that survives reboot. A notarized, validly-signed .pkg with a normal per-user LaunchAgent is the benign control."
  },
  {
    "slug": "email-bomb-helpdesk",
    "title": "Email Bomb to Fake Help Desk — Quick Assist Takeover",
    "difficulty": "intermediate",
    "summary": "Hundreds of individually-clean newsletter confirmations flood a mailbox in minutes; then a caller posing as IT offers to 'help stop the spam' and talks the overwhelmed user into launching Microsoft's own signed Quick Assist, and hands-on-keyboard discovery follows. The flood is the opening move, not the attack — a signed remote tool is not the signal, the unsolicited context is. A sanctioned Quick Assist session on a real ticket is the benign control. (Black Basta TTP.)"
  },
  {
    "slug": "ot-network-anomaly",
    "title": "OT/ICS Intrusion — A Corporate Host Writes to a PLC (Network-Only Visibility)",
    "difficulty": "advanced",
    "summary": "Seen only through passive network sensors (Zeek + Suricata) at the IT/OT boundary: a corporate-VLAN host starts speaking Modbus to production PLCs it never contacts, sweeps the controller range, and issues write function codes to a line controller. The discriminator is source identity + a Modbus WRITE from an unauthorized host versus the engineering station's normal read polling — the benign control on the same protocol, port and PLCs."
  },
  {
    "slug": "bec-wire-fraud",
    "title": "The CFO Who Never Called — a BEC Wire-Fraud Impersonation",
    "difficulty": "intermediate",
    "summary": "An urgent wire request appears to come from the CFO — a lookalike-domain email with a display-name spoof that fails SPF/DKIM/DMARC, reinforced by a deepfake voice-clone phone call. The teaching point is that this is impersonation, not a mailbox takeover: the real CFO account is untouched. The verdict comes from email authentication + the lookalike domain, not from any compromised internal account. A genuine CFO payment email that passes auth is the benign control."
  }
];
