-- HACK THE SOC :: 0056 — continuous live feed — Phase 0.9
-- ===========================================================================
-- The feed must keep streaming for a whole shift like the single-player Live SOC
-- dashboard, not stop once the seeded timeline is exhausted. buildTimeline seeds
-- the REAL telemetry (company benign pool + one attack story). This adds a
-- server-side "replenisher": whenever a running session is about to run dry, it
-- recycles already-fired BENIGN events (never attack ones) back into the queue at
-- fresh offsets with a fresh id + current timestamp — so benign noise flows
-- endlessly while the attack still happens exactly once. Pure SQL (no JS needed
-- in the DB); the benign bodies were generated by the real engine at start.
-- Idempotent.
-- ===========================================================================

create or replace function public.replenish_feed()
  returns int language plpgsql security definer set search_path = public as $$
declare s record; r record; v_off bigint; v_count int := 0;
begin
  for s in select id, started_at from public.team_sessions where status = 'running' loop
    -- Keep a small buffer of upcoming events; only top up when it's nearly empty.
    if (select count(*) from public.session_injects where session_id = s.id and status = 'pending') >= 4 then
      continue;
    end if;
    -- Resume scheduling from "now" relative to the session start.
    v_off := greatest(0, floor(extract(epoch from (now() - s.started_at)) * 1000))::bigint;
    -- Recycle a handful of benign, already-fired events (skip anything that was
    -- part of the attack story, i.e. tp/escalate verdicts).
    for r in
      select body from public.session_injects
      where session_id = s.id and status = 'fired'
        and coalesce(body->>'expected_verdict', '') not in ('tp', 'escalate')
      order by random() limit 6
    loop
      v_off := v_off + 3000 + floor(random() * 4000)::bigint;
      insert into public.session_injects(session_id, due_offset_ms, trigger, channel, body, status)
      values (
        s.id, v_off, jsonb_build_object('kind', 'at_time'), 'feed',
        r.body || jsonb_build_object(
          'id', coalesce(r.body->>'id', 'ev') || '_r' || floor(random() * 1000000)::text,
          'ts', to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
        ),
        'pending'
      );
      v_count := v_count + 1;
    end loop;
  end loop;
  return v_count;
end $$;
grant execute on function public.replenish_feed() to authenticated;

-- Schedule the replenisher every 10s (pg_cron 1.6 supports sub-minute).
do $$ begin perform cron.unschedule('team-replenish-feed'); exception when others then null; end $$;
select cron.schedule('team-replenish-feed', '10 seconds', $$ select public.replenish_feed(); $$);

-- Verification:
--   select jobname, schedule, active from cron.job where jobname='team-replenish-feed';
--   select public.replenish_feed();  -- returns rows queued for running sessions low on pending injects
