// AUTO-GENERATED by scripts/generate-catalog-meta.mjs. Do not hand-edit.
// The id/title/grouping fields of every built-in quiz and scenario, in corpus
// order, for the learning-plan catalogue. No questions, answers or builders.
// Regenerate: npx tsx scripts/generate-catalog-meta.mjs
// Staleness is checked by scripts/validate-content.mjs.

export interface QuizMeta { slug: string; title: string; category: string; difficulty: string }
export interface ScenarioMeta { slug: string; title: string; difficulty: string }

export const QUIZZES_META: QuizMeta[] = [
  {
    "slug": "mitre-attack",
    "title": "MITRE ATT&CK Framework",
    "category": "Threat Framework",
    "difficulty": "Intermediate"
  },
  {
    "slug": "incident-response",
    "title": "Incident Response",
    "category": "SOC Fundamentals",
    "difficulty": "Intermediate"
  },
  {
    "slug": "log-analysis-siem",
    "title": "Log Analysis & SIEM",
    "category": "SOC Fundamentals",
    "difficulty": "Intermediate"
  },
  {
    "slug": "threat-intelligence",
    "title": "Threat Intelligence",
    "category": "Threat Intelligence",
    "difficulty": "Advanced"
  },
  {
    "slug": "network-security",
    "title": "Network Security & Firewalls",
    "category": "Network",
    "difficulty": "Beginner"
  },
  {
    "slug": "cloud-identity-security",
    "title": "Cloud & Identity Security",
    "category": "Cloud Security",
    "difficulty": "Advanced"
  },
  {
    "slug": "active-directory-kerberos",
    "title": "Active Directory & Kerberos Security",
    "category": "Identity",
    "difficulty": "Advanced"
  },
  {
    "slug": "endpoint-security-edr",
    "title": "Endpoint Security & EDR",
    "category": "Endpoint Security",
    "difficulty": "Intermediate"
  },
  {
    "slug": "email-security-phishing",
    "title": "Email Security & Phishing Analysis",
    "category": "Threat Detection",
    "difficulty": "Intermediate"
  },
  {
    "slug": "digital-forensics-evidence",
    "title": "Digital Forensics & Evidence Handling",
    "category": "Forensics",
    "difficulty": "Advanced"
  },
  {
    "slug": "detection-engineering",
    "title": "Detection Engineering & Rule Writing",
    "category": "SIEM",
    "difficulty": "Advanced"
  },
  {
    "slug": "vulnerability-management",
    "title": "Vulnerability Management for SOC",
    "category": "Vulnerability Management",
    "difficulty": "Intermediate"
  },
  {
    "slug": "web-application-security",
    "title": "Web Application Attacks & WAF",
    "category": "Application Security",
    "difficulty": "Advanced"
  },
  {
    "slug": "soc-operations-triage",
    "title": "SOC Operations & Alert Triage",
    "category": "SOC Fundamentals",
    "difficulty": "Beginner"
  },
  {
    "slug": "cybersecurity-foundations",
    "title": "Cybersecurity Foundations",
    "category": "Foundations",
    "difficulty": "Beginner"
  },
  {
    "slug": "data-loss-prevention",
    "title": "Data Loss Prevention (DLP) Triage",
    "category": "Data Security",
    "difficulty": "Intermediate"
  },
  {
    "slug": "security-tools-defensive-stack",
    "title": "Security Tools & the Defensive Stack",
    "category": "SOC Fundamentals",
    "difficulty": "Beginner"
  },
  {
    "slug": "protocols-and-ports",
    "title": "Protocols & Ports for Analysts",
    "category": "Network",
    "difficulty": "Beginner"
  },
  {
    "slug": "security-models-principles",
    "title": "Security Models & Core Principles",
    "category": "Foundations",
    "difficulty": "Beginner"
  },
  {
    "slug": "attack-types-threat-actors",
    "title": "Attack Types & Threat Actors",
    "category": "Threat Framework",
    "difficulty": "Beginner"
  },
  {
    "slug": "threat-hunting-fundamentals",
    "title": "Threat Hunting — Hypothesis, Baseline, and the Hunt Loop",
    "category": "Threat Detection",
    "difficulty": "Advanced"
  },
  {
    "slug": "soc-decision-making",
    "title": "SOC Decision Making — Escalate, Close, or Dig Deeper",
    "category": "SOC Operations",
    "difficulty": "Intermediate"
  },
  {
    "slug": "malware-analysis-triage",
    "title": "Malware — Families, Behaviour, and Analyst Triage",
    "category": "Malware Analysis",
    "difficulty": "Intermediate"
  },
  {
    "slug": "windows-security-event-ids",
    "title": "Windows Security — Event IDs an Analyst Must Know Cold",
    "category": "Windows Security",
    "difficulty": "Intermediate"
  },
  {
    "slug": "linux-security-for-analysts",
    "title": "Linux Security — Logs, Permissions, and Persistence",
    "category": "Linux",
    "difficulty": "Intermediate"
  },
  {
    "slug": "cloud-security-fundamentals",
    "title": "Cloud Security — AWS and Azure Through an Analyst's Eyes",
    "category": "Cloud Security",
    "difficulty": "Intermediate"
  },
  {
    "slug": "vendor-edr-in-practice",
    "title": "CrowdStrike, SentinelOne & Defender — Vendor EDR in Practice",
    "category": "Endpoint Security",
    "difficulty": "Advanced"
  },
  {
    "slug": "microsoft-security-stack",
    "title": "The Microsoft Security Stack — Defender XDR, Sentinel, Entra",
    "category": "Microsoft Security",
    "difficulty": "Intermediate"
  }
];

export const SCENARIOS_META: ScenarioMeta[] = [
  {
    "slug": "phishing-malware-basic",
    "title": "Phishing Attachment → Malware Execution → Workstation Compromise",
    "difficulty": "beginner"
  },
  {
    "slug": "usb-malware-basic",
    "title": "Malicious USB Drive → Trojan Persistence → Workstation Compromise",
    "difficulty": "beginner"
  },
  {
    "slug": "phishing-to-cloud-exfil",
    "title": "Phishing Macro → AWS Key Theft → S3 Download",
    "difficulty": "intermediate"
  },
  {
    "slug": "bec-mailbox-rule",
    "title": "Password Spray → BEC Mailbox Rule",
    "difficulty": "beginner"
  },
  {
    "slug": "ransomware-lockbit",
    "title": "Ransomware Outbreak — LockBit 3.0",
    "difficulty": "advanced"
  },
  {
    "slug": "oauth-app-persistence",
    "title": "OAuth App Persistence — Cloud APT",
    "difficulty": "advanced"
  },
  {
    "slug": "insider-threat-finance",
    "title": "Bulk Finance Downloads and Removable Media — WS-FIN-4421",
    "difficulty": "intermediate"
  },
  {
    "slug": "kerberoasting",
    "title": "Kerberoasting → Service Account Compromise",
    "difficulty": "advanced"
  },
  {
    "slug": "dns-tunneling",
    "title": "DNS Tunneling — C2 via DNS",
    "difficulty": "advanced"
  },
  {
    "slug": "lolbins",
    "title": "Living-off-the-Land (LOLBins)",
    "difficulty": "advanced"
  },
  {
    "slug": "aws-key-leak-s3-exfil",
    "title": "Leaked AWS Key → IAM Backdoor → S3 Data Theft",
    "difficulty": "advanced"
  },
  {
    "slug": "dcsync-golden-ticket",
    "title": "DCSync → Golden Ticket (Domain Dominance)",
    "difficulty": "advanced"
  },
  {
    "slug": "supply-chain-vendor-update",
    "title": "Supply Chain Attack — Malicious Vendor Update",
    "difficulty": "advanced"
  },
  {
    "slug": "mfa-fatigue-ato",
    "title": "MFA Fatigue → Okta Account Takeover",
    "difficulty": "beginner"
  },
  {
    "slug": "asrep-roasting",
    "title": "AS-REP Roasting → Offline Hash Crack",
    "difficulty": "intermediate"
  },
  {
    "slug": "ntlm-relay-responder",
    "title": "NTLM Relay — Internal Credential Hijacking",
    "difficulty": "advanced"
  },
  {
    "slug": "k8s-pod-escape-imds",
    "title": "Kubernetes Pod Escape → Cloud Metadata Theft",
    "difficulty": "advanced"
  },
  {
    "slug": "oauth-consent-grant-phishing",
    "title": "OAuth Consent Grant Phishing — Silent BEC",
    "difficulty": "expert"
  },
  {
    "slug": "backup-agent-false-positive",
    "title": "Mass File Encryption Alert — Enterprise Backup Agent",
    "difficulty": "beginner"
  },
  {
    "slug": "brute-force-single-account",
    "title": "Logon Failure Burst — Published Remote Desktop Server",
    "difficulty": "beginner"
  },
  {
    "slug": "rogue-admin-account",
    "title": "Out-of-Hours Account Creation — Service Desk Credentials",
    "difficulty": "beginner"
  },
  {
    "slug": "impossible-travel-basic",
    "title": "Sign-In From Two Countries — Accounts Payable Clerk",
    "difficulty": "beginner"
  },
  {
    "slug": "software-install-false-positive",
    "title": "Unsigned Binary Writes to Program Files — Engineering Workstation",
    "difficulty": "beginner"
  },
  {
    "slug": "web-shell-sqli",
    "title": "SQL Injection → Web Shell → Server Compromise",
    "difficulty": "advanced"
  },
  {
    "slug": "linux-ssh-persistence",
    "title": "Exposed SSH → Cron-Persisted Backdoor",
    "difficulty": "intermediate"
  },
  {
    "slug": "aitm-token-theft",
    "title": "Adversary-in-the-Middle Phishing — Session Token Theft",
    "difficulty": "advanced"
  },
  {
    "slug": "esxi-ransomware",
    "title": "Hypervisor Ransomware — ESXi Datastore Encryption",
    "difficulty": "expert"
  },
  {
    "slug": "okta-password-burst",
    "title": "Sign-In Failure Burst — Okta Tenant, One Account",
    "difficulty": "beginner"
  },
  {
    "slug": "fake-browser-update",
    "title": "Fake Browser Update — Drive-by on a Trusted Site",
    "difficulty": "beginner"
  },
  {
    "slug": "trojanized-installer-keylogger",
    "title": "Free PDF Tool — Trojanized Installer with a Keylogger",
    "difficulty": "beginner"
  },
  {
    "slug": "multi-host-intrusion",
    "title": "Multi-Host Intrusion — Foothold, Lateral Move, Staging",
    "difficulty": "advanced"
  },
  {
    "slug": "ai-llmjacking-bedrock",
    "title": "LLMjacking — Stolen CI Key Used for Bedrock Inference",
    "difficulty": "advanced"
  },
  {
    "slug": "gws-phishing-attachment",
    "title": "Shared Invoice — Malicious Attachment via Google Workspace",
    "difficulty": "beginner"
  },
  {
    "slug": "seo-poisoned-installer",
    "title": "Sponsored Result — SEO-Poisoned PuTTY Download",
    "difficulty": "beginner"
  },
  {
    "slug": "iso-container-smuggling",
    "title": "Invoice.iso — Container-Delivered LNK and LOLBin Chain",
    "difficulty": "beginner"
  },
  {
    "slug": "clickfix-fake-captcha",
    "title": "Fake CAPTCHA — 'Paste This to Verify You're Human'",
    "difficulty": "beginner"
  },
  {
    "slug": "scheduled-task-persistence",
    "title": "Speed-Boost Script — Persistence via a Scheduled Task",
    "difficulty": "beginner"
  },
  {
    "slug": "infostealer-session-theft",
    "title": "Free Converter, Stolen Session — Infostealer Cookie Theft & Replay",
    "difficulty": "intermediate"
  },
  {
    "slug": "helpdesk-mfa-reset",
    "title": "Help Desk MFA Reset — Social Engineering Account Takeover",
    "difficulty": "intermediate"
  },
  {
    "slug": "edge-vpn-cve-exploit",
    "title": "Edge Appliance Exploitation — FortiOS SSL-VPN Auth Bypass to Internal Foothold",
    "difficulty": "advanced"
  },
  {
    "slug": "exfil-first-extortion",
    "title": "Exfiltration-First Extortion — Ransomware Without an Encryptor",
    "difficulty": "advanced"
  },
  {
    "slug": "windows-privesc-token",
    "title": "SYSTEM in Twelve Seconds — Token Impersonation on an IIS Host",
    "difficulty": "intermediate"
  },
  {
    "slug": "linux-privesc-suid",
    "title": "www-data to Root — SUID find on an Ubuntu App Server",
    "difficulty": "intermediate"
  },
  {
    "slug": "lateral-movement-pth",
    "title": "Pass-the-Hash to the File Server, Second Hop to the DC",
    "difficulty": "intermediate"
  },
  {
    "slug": "insider-dlp-usb-cloud",
    "title": "Last Week on the Job — Insider Exfil via USB and Personal Cloud",
    "difficulty": "intermediate"
  },
  {
    "slug": "nac-rogue-device",
    "title": "The Printer That Wasn't — Rogue Device Caught by NAC",
    "difficulty": "beginner"
  },
  {
    "slug": "macos-stealer-dmg",
    "title": "macOS Stealer — a 'Cracked' App DMG Harvests Keychain, Cookies and Wallets",
    "difficulty": "intermediate"
  },
  {
    "slug": "sqli-db-exfil",
    "title": "SQL Injection to Database Exfiltration — Following the Attack Past the WAF",
    "difficulty": "advanced"
  },
  {
    "slug": "azure-managed-identity-abuse",
    "title": "Azure App-Registration Credential Abuse — the Quiet Secret-Add Behind a Cloud Data-Access Alert",
    "difficulty": "advanced"
  },
  {
    "slug": "cicd-supply-chain",
    "title": "Poisoned Pipeline — CI/CD Supply-Chain Compromise into the Cloud",
    "difficulty": "advanced"
  },
  {
    "slug": "ueba-compromised-account",
    "title": "Behavioral Risk First — a UEBA-led Account-Compromise Hunt",
    "difficulty": "intermediate"
  },
  {
    "slug": "vishing-rmm",
    "title": "Callback Vishing — RMM Install to Hands-on-Keyboard Discovery",
    "difficulty": "intermediate"
  },
  {
    "slug": "pam-vault-abuse",
    "title": "PAM Vault Abuse — an Off-Hours Domain-Admin Checkout Used Outside PSM",
    "difficulty": "advanced"
  },
  {
    "slug": "destructive-wiper",
    "title": "Destructive Wiper — an Endpoint Bricked, and No Way to Pay for It Back",
    "difficulty": "advanced"
  },
  {
    "slug": "s3-exfil-exposure",
    "title": "Exposed Bucket — S3 Made Public, Then Emptied",
    "difficulty": "intermediate"
  },
  {
    "slug": "golden-saml",
    "title": "Golden SAML — a Federation Token With No Matching AD FS Issuance",
    "difficulty": "expert"
  },
  {
    "slug": "gws-oauth-marketplace",
    "title": "Consent, Not Credentials — a Malicious OAuth App in Google Workspace",
    "difficulty": "intermediate"
  },
  {
    "slug": "threat-intel-hunt",
    "title": "Threat-Intel Hunt — From a Recorded Future IOC Set to a Live Beacon",
    "difficulty": "intermediate"
  },
  {
    "slug": "mobile-mdm-compromise",
    "title": "Mobile in the Blind Spot — an Intune-Managed Phone Goes Rogue",
    "difficulty": "intermediate"
  },
  {
    "slug": "gcp-sa-key-theft",
    "title": "Minted Key — Service-Account Key Theft on GCP",
    "difficulty": "advanced"
  },
  {
    "slug": "macos-tcc-pkg",
    "title": "macOS TCC Bypass — a Fake .pkg Rewrites the Privacy Database and Persists as a LaunchDaemon",
    "difficulty": "intermediate"
  },
  {
    "slug": "email-bomb-helpdesk",
    "title": "Email Bomb to Fake Help Desk — Quick Assist Takeover",
    "difficulty": "intermediate"
  },
  {
    "slug": "ot-network-anomaly",
    "title": "OT/ICS Intrusion — A Corporate Host Writes to a PLC (Network-Only Visibility)",
    "difficulty": "advanced"
  },
  {
    "slug": "bec-wire-fraud",
    "title": "The CFO Who Never Called — a BEC Wire-Fraud Impersonation",
    "difficulty": "intermediate"
  }
];
