/**
 * Learning Rooms — Batch 43
 *
 * Companion practice room to the theory lesson "Where Credentials Hide:
 * Unsecured Credentials & Credential Stores" (newTopicLessons.ts). Closes a
 * verified gap: the platform already teaches active credential DUMPING
 * (LSASS/SAM/NTDS via the sibling lesson) and login-endpoint attacks (the
 * credential-attacks-practice room), but never taught credentials that are
 * simply left exposed — in files, private keys, OS/browser password stores,
 * and cloud-native secrets managers — nor the file-access telemetry angle on
 * NTDS.dit. Every reading and task here is self-contained; deep extraction
 * mechanics for NTDS.dit (ntdsutil/vssadmin commands) are deliberately NOT
 * re-taught — students are pointed to the sibling lesson for that.
 *
 * Rooms in this batch:
 *  1. unsecured-credentials-practice
 */

import type { TelemetryEvent } from "@/lib/sim/types";

// ===========================================================================
// ROOM — Unsecured Credentials & Credential Stores
// ===========================================================================

// Log-analysis 1: a compromised Lambda execution-role identity calling AWS
// Secrets Manager GetSecretValue against secrets it has never touched before,
// from an IP outside AWS's own network — T1555.006, with the T1552.005
// (instance metadata theft) precondition narrated in the context rather than
// as its own event, since IMDS theft is never logged as a CloudTrail entry.
const secretsManagerAbuseEvent: TelemetryEvent = {
  id: "evt-cred2-la1-001",
  ts: "2026-07-14T03:41:07.000Z",
  source: "cloudtrail",
  vendor: "AWS CloudTrail",
  event_type: "cloud_api_call",
  severity: "critical",
  src_ip: "154.16.88.203",
  mitre_technique: "T1555.006",
  mitre_tactic: "Credential Access",
  description:
    "An AssumedRole identity belonging to a Lambda execution role called Secrets Manager GetSecretValue against a secret ARN it has no prior access history with, from a source IP address outside AWS's own network ranges.",
  raw: {
    "aws.cloudtrail.eventName": "GetSecretValue",
    "aws.cloudtrail.eventSource": "secretsmanager.amazonaws.com",
    "aws.cloudtrail.awsRegion": "eu-west-1",
    "aws.cloudtrail.userIdentity.type": "AssumedRole",
    "aws.cloudtrail.userIdentity.arn": "arn:aws:sts::719044852201:assumed-role/lambda-report-generator/i-0d2f9a7c1b3e4f501",
    "aws.cloudtrail.userIdentity.accountId": "719044852201",
    "aws.cloudtrail.userIdentity.principalId": "AROAEXAMPLE123:i-0d2f9a7c1b3e4f501",
    "aws.cloudtrail.sourceIPAddress": "154.16.88.203",
    "aws.cloudtrail.userAgent": "aws-cli/2.15.10 Python/3.11.6 Linux/6.1.0",
    "aws.cloudtrail.requestParameters.secretId": "arn:aws:secretsmanager:eu-west-1:719044852201:secret:prod/finance-db/creds-Ab3xQ9",
    "aws.cloudtrail.responseElements": null,
    "aws.cloudtrail.errorCode": "",
    "aws.cloudtrail.errorMessage": "",
    "aws.cloudtrail.requestID": "3a9c7f21-4b6e-4d02-9a11-7c5e2f8d0b44",
    "aws.cloudtrail.eventType": "AwsApiCall",
    "aws.cloudtrail.managementEvent": true,
    "aws.cloudtrail.readOnly": true,
    "cloud.account.id": "719044852201",
    "cloud.region": "eu-west-1",
    "action_result": "allowed",
  },
};

// Log-analysis 2: NTDS.dit read via a Volume Shadow Copy device path, by
// ntdsutil.exe, run by a domain-admin account off-hours with no matching
// change ticket — T1003.003, the file-access-telemetry angle the sibling
// dumping lesson does not teach.
const ntdsShadowCopyReadEvent: TelemetryEvent = {
  id: "evt-cred2-la2-001",
  ts: "2026-07-02T02:14:51.000Z",
  source: "windows_security",
  vendor: "Windows Security",
  event_type: "file_access",
  severity: "critical",
  hostname: "DC02.brightloop.local",
  mitre_technique: "T1003.003",
  mitre_tactic: "Credential Access",
  description:
    "An object-access event was recorded on DC02 against a file inside the Windows NTDS directory tree, generated by ntdsutil.exe rather than the Active Directory Domain Services process itself.",
  raw: {
    "event.code": "4663",
    "winlog.channel": "Security",
    "winlog.computer_name": "DC02.brightloop.local",
    "winlog.event_data.SubjectUserSid": "S-1-5-21-2839104458-1789233981-3402271847-1147",
    "winlog.event_data.SubjectUserName": "t.okafor-adm",
    "winlog.event_data.SubjectDomainName": "BRIGHTLOOP",
    "winlog.event_data.SubjectLogonId": "0x3E29A7C1",
    "winlog.event_data.ObjectServer": "Security",
    "winlog.event_data.ObjectType": "File",
    "winlog.event_data.ObjectName": "\\Device\\HarddiskVolumeShadowCopy3\\Windows\\NTDS\\ntds.dit",
    "winlog.event_data.HandleId": "0x2f18",
    "winlog.event_data.AccessList": "%%4416",
    "winlog.event_data.AccessMask": "0x1",
    "winlog.event_data.ProcessId": "0x1a94",
    "winlog.event_data.ProcessName": "C:\\Windows\\System32\\ntdsutil.exe",
    "winlog.event_id": 4663,
  },
};

// Analyst-choice: a legitimate, scheduled secrets-rotation Lambda calling
// BatchGetSecretValue against many secrets at once — looks like the same
// "many new secrets, unusual burst" shape as the la1 attack, but is a
// confirmed rotation job under a change ticket, same identity every night.
const rotationJobEvent: TelemetryEvent = {
  id: "evt-cred2-ac1-001",
  ts: "2026-07-09T03:00:12.000Z",
  source: "cloudtrail",
  vendor: "AWS CloudTrail",
  event_type: "cloud_api_call",
  severity: "medium",
  mitre_tactic: "Credential Access",
  description:
    "The secrets-rotation-lambda role called Secrets Manager BatchGetSecretValue against 42 secret ARNs in a single request during its nightly scheduled run.",
  raw: {
    "aws.cloudtrail.eventName": "BatchGetSecretValue",
    "aws.cloudtrail.eventSource": "secretsmanager.amazonaws.com",
    "aws.cloudtrail.awsRegion": "eu-west-1",
    "aws.cloudtrail.userIdentity.type": "AssumedRole",
    "aws.cloudtrail.userIdentity.arn": "arn:aws:sts::719044852201:assumed-role/secrets-rotation-lambda/rotation-run-20260709",
    "aws.cloudtrail.userIdentity.accountId": "719044852201",
    "aws.cloudtrail.sourceIPAddress": "10.44.2.17",
    "aws.cloudtrail.userAgent": "Boto3/1.34.0 Python/3.12.1 Linux/6.1.0 exec-env/AWS_Lambda_python3.12",
    "aws.cloudtrail.requestParameters.filters": "[{\"Key\":\"tag-key\",\"Values\":[\"auto-rotate\"]}]",
    "aws.cloudtrail.responseElements": null,
    "aws.cloudtrail.errorCode": "",
    "aws.cloudtrail.errorMessage": "",
    "aws.cloudtrail.requestID": "9b1e4a03-2c88-4f5d-8e10-6a3f7d9c2b51",
    "aws.cloudtrail.eventType": "AwsApiCall",
    "aws.cloudtrail.managementEvent": true,
    "aws.cloudtrail.readOnly": true,
    "cloud.account.id": "719044852201",
    "cloud.region": "eu-west-1",
    "action_result": "allowed",
  },
};

export const roomsBatch43 = [
  {
    id: "unsecured-credentials-practice",
    title: "Unsecured Credentials & Credential Stores",
    description:
      "The theory lesson 'Where Credentials Hide' taught you where secrets end up exposed without anyone actively dumping them — files, private keys, OS password stores, cloud secrets managers, and NTDS.dit's file-access telemetry. This room makes you find and interpret them from real artifacts: a GPP cpassword decrypt, a CloudTrail GetSecretValue burst, a Windows Event 4663 record with a Volume Shadow Copy device path, and the hardest professional skill in this whole domain — telling a compromised identity's secrets-manager sweep apart from a legitimate rotation job's own scheduled burst.",
    difficulty: "advanced",
    category: "Threat Detection",
    estimatedMinutes: 65,
    xp: 385,
    icon: "🗝️",
    prerequisites: ["credential-attacks-practice", "aws-security", "identity-basics"],
    tasks: [
      {
        type: "reading",
        id: "uc-r1",
        heading: "A Different Family: Finding a Secret, Not Dumping One",
        content:
          `The credential-attacks-practice room taught you to tell brute forcing, spraying, stuffing, and dumping apart from failed-logon telemetry. This room covers a related but distinct family of MITRE ATT&CK techniques, all still filed under the Credential Access tactic: **T1552 (Unsecured Credentials)** and **T1555 (Credentials from Password Stores)**. Neither one actively breaks into a protected store the way OS Credential Dumping (T1003) does — instead, the attacker finds a secret that was already reachable, or reaches a vault through its own legitimate access path.\n\n` +
          `**Why this distinction changes what you look for**\n\n` +
          `Dumping LSASS or NTDS.dit produces a distinctive access pattern against something the OS actively locks down — a process opening a handle to lsass.exe, a shadow copy appearing on a domain controller. This room's techniques leave much thinner traces, because reading a file, unlocking a vault with a captured password, or calling a documented API are all unremarkable actions by design. The whole discipline here is telling a NORMAL instance of that action apart from an ABNORMAL one — which account, which process, which pattern of access, not the action itself.\n\n` +
          `**The seven techniques this room covers**\n\n` +
          `All seven map to the same ATT&CK tactic, Credential Access (TA0006):\n\n` +
          `- T1552.001 — Credentials In Files (plaintext secrets in configs/scripts)\n` +
          `- T1552.006 — Group Policy Preferences (SYSVOL cpassword)\n` +
          `- T1552.004 — Private Keys (unprotected SSH/TLS/GPG key files)\n` +
          `- T1552.005 — Cloud Instance Metadata API (IMDS credential theft)\n` +
          `- T1555.001 — Credentials from Password Stores: Keychain\n` +
          `- T1555.006 — Credentials from Password Stores: Cloud Secrets Management Stores\n` +
          `- T1003.003 — OS Credential Dumping: NTDS, revisited ONLY for its file-access telemetry (the extraction commands themselves were already taught in the sibling dumping lesson — this room does not repeat them)\n\n` +
          `If you have not yet completed the theory lesson 'Where Credentials Hide: Unsecured Credentials & Credential Stores,' read it before continuing — every task in this room assumes that reading, not outside knowledge.`,
        checkpoint: {
          question: "What is the key structural difference between T1003 (OS Credential Dumping) and the T1552/T1555 techniques this room covers?",
          options: [
            "T1003 only ever targets cloud environments and never appears on-premises, while T1552/T1555 only ever target on-premises Windows hosts and never appear in any cloud environment",
            "T1003 actively reads a store the OS locks down; T1552/T1555 find a secret already reachable, or reach a vault through its own legitimate access path, leaving much thinner access traces",
            "T1552/T1555 always require domain administrator privileges to succeed, unlike T1003, which can be performed by any unprivileged domain user with no special access needed at all",
            "There is no real difference between the three technique families -- MITRE ATT&CK simply assigns them different ID numbers for organizational convenience within the same tactic",
          ],
          answer: 1,
          explanation:
            "T1003 breaks into a genuinely protected store (LSASS memory, a locked NTDS.dit) and leaves a distinctive pattern; T1552/T1555 reach something already exposed or use a documented, legitimate access path, which is exactly why this room is built around telling normal access apart from abnormal access rather than spotting the access itself.",
        },
      },
      {
        type: "reading",
        id: "uc-r2",
        heading: "T1552.001 / T1552.006 — Credentials in Files and Group Policy Preferences",
        content:
          `**Credentials In Files (T1552.001)** covers plaintext secrets left in application configs (.env, appsettings.json, web.config), automation definitions (Ansible vars, Jenkinsfiles, .gitlab-ci.yml), shell history (.bash_history), and source code itself. An attacker with any foothold searches for these the same way you would:\n\n` +
          "```\ngrep -RIl \"password\" --include=*.{env,yml,json,conf,ps1,sh} /home /var/www\nfindstr /S /I /M \"password\" *.txt *.xml *.ini *.config\n```\n\n" +
          `**Group Policy Preferences (T1552.006)** is a specific, historically devastating case of this same family. Windows once let administrators push local-account passwords to many machines via GPP settings (Groups.xml, ScheduledTasks.xml), 'encrypting' the password with AES-256. The catch: Microsoft published that AES key in its own documentation. Any domain user — SYSVOL is readable domain-wide by design — can decrypt a cpassword value with tools like Get-GPPPassword or gpp-decrypt:\n\n` +
          "```\nfindstr /S /I cpassword \\\\corp.local\\SYSVOL\\corp.local\\Policies\\*.xml\ngpp-decrypt <captured-cpassword-ciphertext>\n```\n\n" +
          `Microsoft's 2014 fix (MS14-025) stopped administrators from CREATING new cpassword values through the GPP interface — it did nothing to purge old XML files already sitting in SYSVOL from before the patch, which is why this remains a real, findable weakness years later in unaudited environments.\n\n` +
          `**Detection for both**: source-control secret-scanning (GitHub secret scanning, gitleaks, TruffleHog) catching a credential-shaped string the moment it's committed; DLP/CASB regex rules watching for password=, api_key=, or cpassword= patterns in content leaving the organization; and, for GPP specifically, a proactive SYSVOL sweep for any surviving cpassword attribute regardless of patch status. The remediation for a confirmed exposure is always rotation of the actual credential — never just deleting the file that exposed it, since there is no way to know how many times it was already read.`,
        codeExample:
          "SEARCH PATTERNS (T1552.001)\n" +
          "grep -RIl \"password\" --include=*.{env,yml,json,conf,ps1,sh} .\n" +
          "findstr /S /I /M \"password\" *.txt *.xml *.ini *.config\n\n" +
          "GPP cpassword (T1552.006)\n" +
          "findstr /S /I cpassword \\\\corp.local\\SYSVOL\\corp.local\\Policies\\*.xml\n" +
          "gpp-decrypt <ciphertext>   # works because the AES key is PUBLIC",
      },
      {
        type: "question",
        id: "uc-q1",
        question:
          "An analyst finds a Groups.xml file in SYSVOL with a cpassword attribute, on a domain that applied MS14-025 eighteen months ago. Is the value still decryptable, and why?",
        options: [
          "No — the patch retroactively re-encrypted every existing cpassword value across the entire domain with a brand new, non-public key the moment it was installed on the domain controller",
          "Yes — MS14-025 only stops NEW cpassword values from being created through the GPP UI; it never purges or re-encrypts old XML files already in SYSVOL, so a surviving pre-patch file stays fully decryptable with the same public AES key",
          "No — SYSVOL access itself was fully and permanently disabled for all domain users the moment the patch was applied, so the file can no longer be read by anyone at all",
          "Yes, but only for domain administrators — regular domain users lost all SYSVOL read access entirely as part of that very same security patch rollout",
        ],
        answer: 1,
        explanation:
          "MS14-025 prevents creating new cpassword values through the GPP interface going forward; it does not touch files that already existed in SYSVOL, and the AES key itself was never changed or made secret. SYSVOL remains readable by any domain user by design (that is the whole point of Group Policy distribution), both before and after the patch.",
        xp: 25,
      },
      {
        type: "reading",
        id: "uc-r3",
        heading: "T1552.004 — Private Keys: Immediate Access, No Guessing Required",
        content:
          `A private key is the secret half of a key pair: whoever holds it authenticates as its owner, no password guessing needed. That is exactly what makes **Unsecured Credentials: Private Keys (T1552.004)** so consequential compared to a plaintext password sitting in a file.\n\n` +
          `**Recognizable extensions**: .key, .pem (generic PEM key), .ppk (PuTTY), .p12/.pfx (PKCS#12 bundle, often password-protected), .pgp/.gpg/.asc (GPG/PGP). SSH keys live at ~/.ssh/id_rsa or id_ed25519 by convention on Linux/macOS, and the equivalent path on Windows once OpenSSH tooling is installed. Cloud CLI credential files (~/.aws/credentials) are a close cousin — plaintext long-lived access keys, functionally identical in impact to a stolen private key.\n\n` +
          "```\nfind / -type f \\( -name \"*.pem\" -o -name \"id_rsa\" -o -name \"*.ppk\" \\) 2>/dev/null\nGet-ChildItem C:\\Users -Recurse -Include *.pem,*.ppk,*.key -ErrorAction SilentlyContinue\n```\n\n" +
          `**The one real mitigation**: a passphrase-protected key still requires the attacker to succeed at an offline crack (ssh2john + Hashcat/John) before it becomes usable — exactly the same offline-cracking workflow covered in the credential-attacks-practice room, just applied to a key file instead of a password hash. This converts an instantly-usable stolen credential into one requiring successful cracking first, buying real time for detection and rotation.\n\n` +
          `**The single highest-fidelity detection signature in this entire room**: the literal string -----BEGIN RSA PRIVATE KEY----- (or its EC/OPENSSH/PGP equivalents) appearing anywhere it should not — in a Git commit, an outbound upload, or an email. On the host itself, a process other than ssh, scp, or a recognized backup tool reading id_rsa or a .pem file is a strong behavioral tell.`,
        checkpoint: {
          question: "Why does a passphrase on a stolen private key matter, if the attacker already has the file itself?",
          options: [
            "It doesn't matter at all — SSH authenticates purely on file possession alone, regardless of whether any passphrase was ever set on that particular key file to begin with",
            "The passphrase encrypts the key material itself, so the attacker must still recover it (typically via ssh2john plus offline cracking) before the key becomes usable — turning an instant credential into one requiring successful cracking first",
            "The passphrase is only ever checked by the destination SSH server during the handshake, never by the client application holding the key file locally on disk",
            "A passphrase prevents the key file from ever being copied off the original machine in the first place, regardless of what access level an attacker might otherwise have",
          ],
          answer: 1,
          explanation:
            "A passphrase-protected private key file is still encrypted at rest -- the client must decrypt it locally with the correct passphrase before it can be used to authenticate anywhere, which is why a stolen protected key still requires an offline cracking step, unlike an unprotected key which is instantly usable the moment it is stolen.",
        },
      },
      {
        type: "question",
        id: "uc-q2",
        question:
          "A DLP rule flags an outbound file upload containing the literal string '-----BEGIN OPENSSH PRIVATE KEY-----'. Why is this specific string such a high-fidelity detection signature?",
        options: [
          "It is not actually reliable at all — that exact header string appears constantly in ordinary business text documents and email templates, producing overwhelming false positives in practice",
          "It is a fixed, unambiguous marker that only ever appears at the start of genuine unencrypted private-key material — almost nothing else produces that exact string, making it a rare, near-certain positive rather than a probabilistic heuristic",
          "It only ever appears in files that were deliberately created by malware authors, so any single match automatically and conclusively proves a compromise has already occurred",
          "It indicates the key has already been successfully used to authenticate somewhere on the network, not merely that key material happens to exist in the uploaded content",
        ],
        answer: 1,
        explanation:
          "The PEM header format is a fixed, standardized marker specific to key material -- it is not common ordinary-document text, so a match is a rare, high-confidence signal rather than noise. It says nothing about who created the file (legitimate developers write real keys constantly) and nothing about whether the key was ever actually used to authenticate -- it only confirms key material is present in the outbound content.",
        xp: 25,
      },
      {
        type: "reading",
        id: "uc-r4",
        heading: "T1555.001 — Raiding the macOS Keychain and Other Password Stores",
        content:
          `Rather than memorize many passwords, operating systems and browsers offer a **password store**: one encrypted vault, unlocked with a single master secret. Steal or unlock the vault and every credential inside arrives at once.\n\n` +
          `**macOS Keychain (T1555.001)**: three keychains exist — the per-user login keychain (most saved passwords, Wi-Fi credentials, app tokens, at ~/Library/Keychains/login.keychain-db), the System keychain, and Local Items/iCloud Keychain. By default, the login keychain unlocks automatically because its own unlock password matches the account's login password. The built-in security command-line tool is the primary interface:\n\n` +
          "```\nsecurity dump-keychain -d\nsecurity find-generic-password -ga \"Slack\"\n```\n\n" +
          `Extracting most items' actual secret still needs the keychain already unlocked (an active session) or the login password supplied when prompted — which is why real Keychain-theft chains usually capture that login password FIRST through some other means (a spoofed system dialog, for instance), and only then run dump-keychain -d as the second stage. An attacker with root or full-disk access can skip the tool entirely and copy the raw login.keychain-db file, parsing it offline with a tool like Chainbreaker.\n\n` +
          `**Windows equivalent, briefly**: Credential Manager and DPAPI-protected secrets play the same role, already covered in the sibling credential-dumping lesson's LSA Secrets material.\n\n` +
          `**Browser password stores (T1555.003)**: Chrome/Edge keep a 'Login Data' SQLite database encrypted with an OS-level key (DPAPI on Windows, the Keychain on macOS); Firefox uses its own NSS-based encryption. Tools like LaZagne and SharpChrome automate decrypting these given the same local access level the OS-level key requires.\n\n` +
          `**Detection**: the security binary (or a Keychain API call) invoked by an unusual parent process — a downloaded script or unnotarized binary rather than a normal user-initiated action — especially right after an earlier password-capture event in the same process tree.`,
      },
      {
        type: "question",
        id: "uc-q3",
        question:
          "Why is macOS Keychain theft (T1555.001) usually the SECOND step in a real attack chain, rather than the first?",
        options: [
          "Because extracting most Keychain items' actual secret values requires the keychain to already be unlocked or the account's login password supplied — so an earlier step (often a spoofed password prompt) must capture that password first",
          "Because the security command-line tool does not ship with macOS by default at all and must be manually installed separately through the full Xcode developer tools package",
          "Because Apple requires a separate two-factor authentication challenge to complete before any Keychain API call can succeed on the device, regardless of local access level",
          "Because dump-keychain -d only ever works on keychains that have already been synced to iCloud Keychain across a user's other Apple devices beforehand",
        ],
        answer: 0,
        explanation:
          "The keychain's own protection (needing it unlocked or the login password) is exactly why theft is normally staged in two steps: capture the login password some other way, then use it to unlock and dump the keychain. The security tool ships with the OS, no macOS-wide 2FA gate exists on local Keychain API calls, and dump-keychain -d works on the local login keychain regardless of iCloud sync status.",
        xp: 25,
      },
      {
        type: "reading",
        id: "uc-r5",
        heading: "T1555.006 and T1552.005 — When the Vault Is a Cloud API Call",
        content:
          `Cloud platforms offer a purpose-built alternative to plaintext config files: a **secrets management store** (AWS Secrets Manager, Azure Key Vault, GCP Secret Manager, HashiCorp Vault). It is a genuine improvement over T1552.001 — but it shifts the whole problem onto one question: who is allowed to call the retrieval API, and how tightly is that permission scoped?\n\n` +
          "```\naws secretsmanager get-secret-value --secret-id prod/db/creds\naws secretsmanager batch-get-secret-value --secret-id-list prod/db/creds prod/api/key\naz keyvault secret show --name ExamplePassword --vault-name prod-vault --query value\ngcloud secrets versions access latest --secret=my-db-password\n```\n\n" +
          `**T1555.006** is simply using one of these calls with a compromised or over-permissioned identity — MITRE ATT&CK documents the state-sponsored group HAFNIUM moving laterally from on-premises systems specifically to reach Azure Key Vault secrets this way. None of these calls work without an identity already permitted to make them, which leads to a closely related, distinct technique: **Unsecured Credentials: Cloud Instance Metadata API (T1552.005)**. A process running on a cloud compute instance can query a link-local endpoint (169.254.169.254 on AWS) and receive that instance's own temporary IAM role credentials directly — no GetSecretValue call, no CloudTrail Secrets Manager entry at all, because the metadata service is not a logged AWS management-plane API. This exact mechanism drove the 2019 Capital One breach: an SSRF flaw in a misconfigured WAF let an attacker make the WAF's own EC2 instance query its metadata endpoint on the attacker's behalf, handing over its IAM role's credentials and, from there, over 100 million customers' records in S3 — the incident that led directly to AWS building IMDSv2.\n\n` +
          `**Detection**: for T1555.006, CloudTrail (eventSource secretsmanager.amazonaws.com), Azure Key Vault diagnostic logs (operationName SecretGet), or GCP Secret Manager audit logs, watching for an identity requesting secrets it has never touched before, from an atypical source. For T1552.005, the tell is the ABSENCE of a matching secrets-manager trail despite a credential clearly in active use elsewhere.\n\n` +
          `**Why naive volume thresholds fail here**: CI/CD pipelines, autoscaling fleets, and rotation jobs all legitimately call these APIs in bursts. The professional approach baselines by identity-and-secretId PAIR — a given role normally reads the same one or two secrets repeatedly for months; a request for a secret it has never touched before is the real signal, not raw call count.`,
        codeExample:
          "T1552.005 LEAVES NO SECRETS-MANAGER TRAIL AT ALL:\n" +
          "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>\n" +
          "-> the 2019 Capital One breach mechanism (SSRF -> IMDSv1 -> IAM creds)\n" +
          "-> fixed industry-wide by AWS IMDSv2 (session-token required)",
      },
      {
        type: "log_analysis",
        id: "uc-la1",
        heading: "A Secrets Manager Call From Outside AWS",
        context:
          "BrightLoop's lambda-report-generator role has, for its entire 8-month history, called GetSecretValue exactly once per invocation against a single secret, prod/reports-db/creds, always from AWS's own internal Lambda service network, always during business hours. In the 10 minutes before this event, CloudTrail recorded the same role's temporary credentials calling GetSecretValue against SEVEN different secret ARNs it has never accessed before — this record is one of them.",
        event: secretsManagerAbuseEvent,
        questions: [
          {
            question:
              "The event shows userAgent 'aws-cli/2.15.10 Python/3.11.6 Linux/6.1.0' calling from sourceIPAddress 154.16.88.203, which is not an AWS-owned IP range. Why does this combination matter, given the identity is a Lambda execution role?",
            options: [
              "It doesn't matter at all — AWS Lambda functions routinely install and invoke the aws-cli binary directly as part of their normal runtime environment, and a Lambda function's outbound source IP address is inherently unpredictable and constantly changing by design",
              "A Lambda function's own AWS SDK calls originate from AWS's internal network with an SDK-specific user agent — a locally-installed aws-cli binary calling from an external, non-AWS IP means the role's temporary credentials were exported and are being used directly from attacker infrastructure, not from the Lambda function itself",
              "The userAgent field is purely cosmetic metadata that CloudTrail automatically appends for display and reporting purposes only, and it carries no real investigative meaning about how or where the call actually originated",
              "This proves the event itself is a logging artifact or parsing error, since CloudTrail is fundamentally incapable of recording API events made by AssumedRole identities under any circumstances whatsoever, regardless of account",
            ],
            answer: 1,
            explanation:
              "Lambda's managed runtime calls AWS APIs through its own SDK from AWS's internal network, not a hand-installed aws-cli binary from a residential/hosting IP. That mismatch is the direct evidence that this role's temporary credentials were exfiltrated (commonly via T1552.005 IMDS theft against the underlying compute, or a leaked build log) and are now being replayed from outside AWS entirely. The field is genuinely informative, not decorative, and CloudTrail logs AssumedRole activity identically to any other identity type.",
            xp: 25,
          },
          {
            question:
              "This role has never touched the 7 secret ARNs it requested in this 10-minute window, versus its normal single-secret pattern. Applying the identity-and-secretId baseline principle from the reading, how should this be scored?",
            options: [
              "As low priority — seven calls in a ten-minute window is a small, genuinely unremarkable volume compared to what a real, large-scale attacker sweep would typically be expected to generate",
              "As a high-confidence indicator — the NEW pairing (this identity touching secrets it has never read before) is the actual signal the baseline approach is built to catch, independent of whether the raw call count looks large or small",
              "As a false positive by default, since any AssumedRole identity is inherently trusted for whatever it subsequently requests once it has successfully authenticated to AWS in the first place",
              "As entirely unscoreable without first knowing the exact literal secret values that were actually returned by each call, information CloudTrail deliberately does not record",
            ],
            answer: 1,
            explanation:
              "The reading's core detection principle is exactly this: baseline which identity normally reads which secret, and treat a new pairing as the signal, not the raw volume. Seven calls is a small number in absolute terms, but seven NEW secrets for a role that has read exactly one for 8 months is a severe deviation. AssumedRole identities are not inherently trusted just for authenticating successfully, and the verdict does not require knowing the secret's literal value -- the anomalous access pattern is enough on its own.",
            xp: 25,
          },
          {
            question:
              "responseElements is null and errorCode is empty in this record. What does that combination tell the analyst, and what does it NOT tell them?",
            options: [
              "It tells the analyst the call must have failed, since AWS CloudTrail would always be expected to populate the errorCode field with specific failure details whenever any Secrets Manager call is unsuccessful",
              "It confirms the call succeeded (empty errorCode = no failure), but AWS deliberately never logs the actual secret VALUE in responseElements for GetSecretValue — so the analyst can confirm the credential was successfully retrieved, but cannot see the literal secret string from the log alone",
              "It tells the analyst the request is still pending evaluation somewhere in AWS's backend and has not yet fully completed processing, meaning the outcome cannot be determined from this record",
              "It proves the secret itself was invalid or had already been rotated out from under the caller, since a genuinely valid, current secret would always populate responseElements with its actual value",
            ],
            answer: 1,
            explanation:
              "An empty errorCode in CloudTrail means the call succeeded, not failed or pending -- CloudTrail records events only after AWS has evaluated them. AWS deliberately excludes the actual secret value from CloudTrail's GetSecretValue log entries as a design choice, so the analyst can confirm ACCESS succeeded (and must treat the secret as compromised) without ever seeing which literal value left the vault. Nothing here indicates the secret was invalid or rotated -- that would require checking Secrets Manager's own state, not this log entry.",
            xp: 25,
          },
        ],
      },
      {
        type: "reading",
        id: "uc-r6",
        heading: "Building a Detection Program That Survives Contact With Real Traffic",
        content:
          `Every technique in this room shares one hard problem: each store has a completely legitimate access path, and the whole discipline is telling that apart from an attacker's. Five practices make this workable in production rather than a wall of noisy alerts.\n\n` +
          `**1. Continuous secret-scanning.** Run source-control scanning (GitHub secret scanning, gitleaks, TruffleHog) on every commit and periodic sweeps of endpoints/shares for T1552.001/.004/.006-shaped content, so exposures are caught before an attacker ever needs to search for them.\n\n` +
          `**2. Prefer short-lived credentials over static ones.** Cloud IAM roles and managed identities that auto-rotate directly shrink the T1552.004/.005 attack surface — there is no long-lived key file or access-key pair sitting around waiting to be found.\n\n` +
          `**3. Honeytoken / canary secrets.** Seed a file, a private key, and a cloud secret that no legitimate process should EVER read into every store type this room covers. Any access to one is an unambiguous, high-confidence alert — not a probabilistic heuristic.\n\n` +
          `**4. Baseline WHO reads WHAT before writing any volume threshold.** As Reading 5 and the log-analysis task demonstrated, legitimate automation (CI/CD, autoscaling, rotation jobs) generates bursts that a naive count-based rule cannot distinguish from an attacker. Identity-and-resource PAIR baselining is the professional answer.\n\n` +
          `**5. Rotate on ANY confirmed exposure.** Never just delete the file, revoke the one session, or remove the one copy found — you can never be certain how many times a credential was already read before discovery. Rotation is the only remediation that actually closes the exposure.\n\n` +
          `The next task puts practice 4 directly to the test: a real cloud event that LOOKS exactly like the attack you just investigated, but is actually a confirmed, scheduled, legitimate job.`,
      },
      {
        type: "analyst_choice",
        id: "uc-ac1",
        heading: "Verdict: A Nightly Secrets-Rotation Job",
        scenario:
          "BrightLoop's change management system shows an open, approved change ticket for 'automated secrets rotation — nightly run' scheduled for 03:00 UTC. Review the CloudTrail record below, generated at 03:00:12 UTC by the identity that change ticket names.",
        event: rotationJobEvent,
        correct_verdict: "false_positive",
        explanation:
          "This event superficially resembles the earlier attack (a burst against many secret ARNs), but every distinguishing detail is different: the identity is secrets-rotation-lambda, not lambda-report-generator; the sourceIPAddress 10.44.2.17 is an internal VPC address, not an external IP; the userAgent (Boto3/Python running inside an AWS_Lambda exec-env) is exactly what a real Lambda function's own SDK call looks like; the call is BatchGetSecretValue (the bulk operation, matching a filter for tag-key=auto-rotate) rather than repeated single-secret GetSecretValue calls against ARNs with no logical relationship; and there is a matching, pre-approved change ticket naming this exact identity and time. Applying the identity-and-secretId baseline principle correctly means recognizing that THIS identity's normal pattern is a large, tag-filtered batch every night — the anomaly in the earlier attack was a DIFFERENT identity touching secrets outside its own established pattern, not merely 'a burst against multiple secrets' in isolation.",
        fp_trap:
          "An analyst who over-applies 'many secrets in one burst = suspicious' without checking WHICH identity, WHAT source IP, and WHETHER a change ticket exists would escalate a routine, months-old scheduled job — exactly the alert fatigue that makes analysts start ignoring real Secrets Manager alerts altogether.",
        xp: 35,
      },
      {
        type: "reading",
        id: "uc-r7",
        heading: "T1003.003 Revisited: NTDS.dit's File-Access Telemetry",
        content:
          `NTDS.dit is different in scale from everything else in this room: it is the Active Directory database on every Domain Controller, holding the password hash of every account in the domain. The extraction commands (ntdsutil, vssadmin, secretsdump.py) were already taught in the sibling lesson 'Credential Dumping: LSASS, SAM, and NTDS.dit' — if you have not completed that lesson, do so before this task; it is not repeated here. This room instead teaches the file-access telemetry angle that lesson does not cover.\n\n` +
          `**Why an extraction always leaves a specific tell.** C:\\Windows\\NTDS\\ntds.dit is locked for exclusive use by the AD DS process while a domain controller is running — nothing can simply open and copy the live file. Every extraction method therefore routes through a **Volume Shadow Copy (VSS)**, either taken directly (vssadmin create shadow) or internally by ntdsutil's Install-From-Media feature, exposing the locked file as a readable copy at a shadow-copy DEVICE path rather than the live path.\n\n` +
          `**Event ID 4663 ('An attempt was made to access an object')** fires for every read of the file — but only where an administrator has proactively enabled object-access (SACL) auditing on ntds.dit, a real hardening step that is often skipped, worth calling out honestly as a limitation of this whole detection path.\n\n` +
          `| 4663 field | What it holds | The tell |\n` +
          `| --- | --- | --- |\n` +
          `| ObjectName | Full accessed path | A shadow-copy DEVICE path (\\Device\\HarddiskVolumeShadowCopyN\\...) rather than the live C:\\Windows\\NTDS\\ntds.dit path |\n` +
          `| AccessList | The access right exercised, as an untranslated %%code | %%4416 = ReadData (or ListDirectory) — a plain file read |\n` +
          `| ProcessName | The process that opened the object | ntdsutil.exe or a scripted copy, rather than the expected NTDS/LSASS service processes |\n` +
          `| SubjectUserName | The account performing the access | Routine AD replication never reads ntds.dit at the file level at all — any account doing this is worth scrutiny |\n\n` +
          `A device-path ObjectName is not a coincidence or a logging artifact — it is the specific, unavoidable byproduct of the VSS workaround every real extraction method must use.`,
      },
      {
        type: "question",
        id: "uc-q4",
        question:
          "Why does routine, legitimate Active Directory replication between two Domain Controllers never generate a Windows Event 4663 record against ntds.dit?",
        options: [
          "Because replication is a protocol-level exchange between the AD DS processes on each Domain Controller (DRSUAPI) — it never reads the ntds.dit FILE directly at the file-access level, so there is no file object-access event to generate at all",
          "Because replication traffic is always encrypted, and encrypted traffic is automatically exempt from Windows object-access auditing regardless of what it accesses",
          "Because replication only ever happens through Volume Shadow Copy snapshots, which Windows explicitly excludes from all object-access auditing",
          "Because 4663 auditing is only ever enabled on member servers, never on Domain Controllers, by Windows' own default security baseline",
        ],
        answer: 0,
        explanation:
          "AD replication operates through the DRSUAPI protocol between the AD DS processes themselves -- it is a service-to-service data exchange, not a file-system-level read of ntds.dit, so it produces no 4663 record regardless of whether SACL auditing is enabled. Encryption has no bearing on whether object-access auditing fires, replication does not route through VSS snapshots, and 4663 auditing can be enabled on any system including Domain Controllers -- it simply is not on by default anywhere.",
        xp: 25,
      },
      {
        type: "matching",
        id: "uc-m1",
        heading: "Match Each Technique to What It Actually Exposes",
        instructions: "Match each ATT&CK technique ID to the credential-store artifact and mechanism it describes.",
        pairs: [
          { id: "t1552001", left: "T1552.001 — Unsecured Credentials: Credentials In Files", right: "Plaintext secrets in .env/config files, source code, or shell history, found with grep/findstr searches" },
          { id: "t1552006", left: "T1552.006 — Unsecured Credentials: Group Policy Preferences", right: "A cpassword value in a SYSVOL XML file, 'encrypted' with an AES key Microsoft made public" },
          { id: "t1552004", left: "T1552.004 — Unsecured Credentials: Private Keys", right: "An unprotected SSH/TLS/GPG key file granting immediate access with no further guessing needed" },
          { id: "t1552005", left: "T1552.005 — Unsecured Credentials: Cloud Instance Metadata API", right: "Temporary IAM role credentials from a link-local endpoint on the instance itself, never logged as a CloudTrail API call" },
          { id: "t1555001", left: "T1555.001 — Credentials from Password Stores: Keychain", right: "macOS's login-keychain vault, unlocked with the account's own login password by default" },
          { id: "t1555006", left: "T1555.006 — Credentials from Password Stores: Cloud Secrets Management Stores", right: "A direct API call such as GetSecretValue or az keyvault secret show against a cloud-native secrets vault" },
        ],
        explanation:
          "Each pairing comes straight from this room's readings: T1552.001/.006 are variations on files holding plaintext or trivially-decryptable secrets; T1552.004/.005 both hand over immediately-usable credentials with no guessing needed, one from a stolen file and one from an unlogged local API; T1555.001/.006 both reach a purpose-built vault, one via a local OS mechanism and one via a cloud-native service API.",
        xp: 40,
      },
      {
        type: "ordering",
        id: "uc-o1",
        heading: "Order the Chain: From One Leaked Key to a Full Cloud Secrets Sweep",
        instructions: "Arrange these events in the order a real intrusion chains this room's techniques together, from initial exposure to full impact.",
        items: [
          { id: "commit", text: "A developer accidentally commits a .pem private key to a public GitHub repository (T1552.004)" },
          { id: "scrape", text: "An automated credential-scraping bot clones the repository and extracts the key within minutes of the commit" },
          { id: "ssh", text: "The attacker uses the stolen key to SSH directly into the production host it was provisioned to access" },
          { id: "hunt", text: "Once on the host, the attacker searches the local filesystem for further unsecured credentials, finding a plaintext ~/.aws/credentials file (T1552.001)" },
          { id: "sweep", text: "The attacker uses those newly found AWS credentials to call GetSecretValue against the organization's Secrets Manager, sweeping additional production secrets (T1555.006)" },
        ],
        correct_order: ["commit", "scrape", "ssh", "hunt", "sweep"],
        explanation:
          "This is the realistic shape of how this room's techniques chain together in a real intrusion: a single leaked private key (T1552.004) grants direct host access, which then exposes a second unsecured credential on that host (T1552.001, here a cloud credentials file), which in turn grants an identity capable of reaching the cloud-native secrets vault (T1555.006) — each stage's compromise is what makes the next stage possible, illustrating why any ONE exposure in this family should be treated as a potential foothold for the next.",
        xp: 40,
      },
      {
        type: "log_analysis",
        id: "uc-la2",
        heading: "A 2 AM Read of ntds.dit Through a Shadow Copy",
        context:
          "DC02 has object-access (SACL) auditing enabled on ntds.dit as part of BrightLoop's hardening baseline. There is no scheduled AD backup job configured on DC02 (backups run from DC01 only, under service account svc-adbackup, always against the live C:\\Windows\\NTDS\\ntds.dit path, always at 01:00 UTC), and no open change ticket covers any activity on DC02 tonight. Review the event below, recorded at 02:14 AM.",
        event: ntdsShadowCopyReadEvent,
        questions: [
          {
            question:
              "ObjectName here is \\Device\\HarddiskVolumeShadowCopy3\\Windows\\NTDS\\ntds.dit rather than the live C:\\Windows\\NTDS\\ntds.dit path. What does that specific path format indicate?",
            options: [
              "Nothing significant at all — both paths ultimately refer to the exact same underlying physical file on disk and therefore carry completely identical meaning for any investigation",
              "That the file was reached through a Volume Shadow Copy snapshot — exactly the workaround every real NTDS.dit extraction method (vssadmin, ntdsutil's IFM feature, secretsdump.py) must use, since the live file is locked while AD DS is running",
              "That the Domain Controller's primary disk hardware has failed entirely and Windows automatically and silently rerouted this specific read request to a backup volume instead",
              "That this must be a logging error, since ntds.dit can never legitimately be accessed via a shadow-copy device path under any circumstance",
            ],
            answer: 1,
            explanation:
              "The live ntds.dit is locked for exclusive AD DS use, so any extraction method must route through a VSS snapshot to get a readable copy — this device-path ObjectName is the specific, unavoidable artifact that workaround leaves behind, not a coincidence, a disk failure symptom, or a logging error.",
            xp: 25,
          },
          {
            question:
              "ProcessName is ntdsutil.exe and AccessList shows %%4416. What does %%4416 mean, and what does the combination suggest?",
            options: [
              "%%4416 specifically means the access attempt was denied and blocked by Windows before it could complete, meaning no actual file data was ever read, which would make ntdsutil.exe's presence here inconsequential",
              "%%4416 is the untranslated code for ReadData (or ListDirectory) — a plain file read. Combined with ntdsutil.exe (whose Install-From-Media feature is a documented method for exporting NTDS.dit) reading the file via a shadow-copy path, this is consistent with an extraction attempt, not routine replication",
              "%%4416 indicates the file was being written to rather than read, which would mean this event actually represents a legitimate, routine AD DS database maintenance operation instead",
              "%%4416 is simply a benign, extremely common code that appears on nearly every ordinary file access across the entire domain controller all day long and therefore carries no real investigative weight",
            ],
            answer: 1,
            explanation:
              "AccessList records the RIGHT EXERCISED, and 4663 only logs successful uses of a right (there is no failure variant of 4663) — so %%4416/ReadData confirms a completed read, not a denial. Combined with ntdsutil.exe (a documented NTDS.dit export tool) reading via a shadow-copy path, this matches an extraction pattern, not a write operation or routine, contentless background noise.",
            xp: 25,
          },
          {
            question:
              "The account performing this access, t.okafor-adm, is a domain admin rather than an unprivileged user. Does that change how this event should be triaged?",
            options: [
              "Yes — domain admin accounts should be considered implicitly and permanently trusted for absolutely any action taken on a Domain Controller, so this event should simply be closed as benign without any further review at all",
              "No — a legitimate privilege level does not make an action legitimate; domain admin rights are exactly what NTDS.dit extraction requires, and with no scheduled backup job or change ticket to explain ntdsutil running against a shadow copy at 2 AM, a compromised admin account raises the stakes rather than lowering suspicion",
              "Yes, but only because domain admin accounts are technically and fundamentally incapable of ever triggering Event ID 4663 under any configuration, so this record must represent a different account somehow spoofing that exact name",
              "No, because domain admin status is entirely irrelevant to how Windows security auditing works, and this exact event would look completely identical in every field regardless of which account performed the access",
            ],
            answer: 1,
            explanation:
              "Privilege is a precondition for this attack, not evidence against it -- NTDS.dit extraction requires exactly the level of access a domain admin has, so finding this pattern under a privileged account is more consequential if that account is compromised, not reassuring. There is no scheduled job or ticket to explain it, domain admin accounts can absolutely generate 4663 events like any other account, and SubjectUserName is a genuine, meaningful field regardless of privilege level.",
            xp: 25,
          },
        ],
      },
      {
        type: "flag",
        id: "uc-f1",
        prompt:
          "This room's cloud reading names the exact AWS Secrets Manager API operation that retrieves MULTIPLE different secrets in a single request, rather than one secret at a time. What is that exact operation name?",
        answer: "BatchGetSecretValue",
        hint: "Covered in Reading 5 ('T1555.006 and T1552.005') and used directly in the analyst_choice task's rotation-job event — it's the bulk counterpart to GetSecretValue.",
        xp: 20,
      },
    ],
  },
];

export default roomsBatch43;
